### ISSUE TITLE
Extened screen function

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1005]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:cait_sidhe@ukr.net<br><br>Hello. Is there an extended screen function in EasyCanvas? I installed the trial version, connected my Ipad pro to my laptop pc but there is no second screen option.<br><br>[EL_Display_d96c0374-f95f-4938-b7da-2c8cc5d7658d.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_d96c0374-f95f-4938-b7da-2c8cc5d7658d.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello. We are an Easy & Light support team.

I'm sending this email for your inquiry.


EasyCanvas not only Duplicate the display, but also provides Extension.

If you cannot use the "Extension" function, please take the following actions.

1. Reboot after deleting EL Display Hub (If a third-party monitor app PC program is installed, delete it together and reboot)
2. Install the latest version of EL Display Hub 
3. Press Win+P to select "Extend"
 

4. Select "Extension"" in EL Display Hub [Options] - [Select Display](If it is already extended, the "Extension" menu is not displayed.) 
If the extension does not work even after following the steps above, we are sorry, but Please contact us again.


Thank you.

 
Easy&Light
