### ISSUE TITLE
확장기능 세로에서 미작동

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1015]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:jinmo0817@yonsei.ac.kr<br><br>안녕하세요. 방금 다운받았습니다. 디스플레이 설정을 확장, 방향을 가로로 할때는 정상적으로 작동이 되는데 세로(대칭이동) 으로 설정시 태블릿에 배경화면 이미지만 뜨고 마우스 커서이동등의 동작이 전혀 이루어지지 않습니다. 확인 부탁드립니다. 감사합니다.<br><br>[EL_Display_899b51a1-d430-4bd7-80d4-70c616c4b4e2.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_899b51a1-d430-4bd7-80d4-70c616c4b4e2.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


고객님, 안녕하세요. Easy&Light 지원 팀 입니다.


문의해주신 내용에 대한 답변을 메일로 전달해드립니다.





혹시 사용하시는 환경이 Windows 11 인지요? 



현재 Windows 11의 경우 세로 모드일 때 Windows에서 제공하는 기능에 문제가 있어 화면 멈춤 현상 등이 발생할 수 있습니다.

Microsoft에서 오류를 수정하지 않으면 해당 문제는 해결이 어려울 것으로 보이며, 현재로서는 불편하시더라도 Windows 11에서는 가로 모드로 사용해주시길 바랍니다.




추가로 제품에 대해 궁금하거나 불편한 점은 언제든지 문의하여 주시기 바랍니다.



감사합니다.

Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 추가로 문의하였습니다

----

windows 11 맞습니다. 제가 궁금한것은 무료인 spacedesk 앱을 사용했을때는 wifi 기반 연결이라 다소 버벅임이 있었을뿐 세로모드 사용에 전혀 문제가 없었는데 유료앱인 귀 사의 앱은 이 기능을 지원하지 못한다는 말씀이신가요? ms에 문의해야하는 오류가 있다면 어떤 것인지 설명해주시면 감사하겠습니다.

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

[](https://github.com/edh-git/EL_Display_Hub/issues/goog_420061709)고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

문의해주신 내용에 대한 답변을 메일로 전달해드립니다.

정확하게 확인이 불가하나 spacedesk 화면 캡처 방식이 Twomon 제품과 다르기 때문에 가능한 것으로 보입니다. 
현재 "Twomon SE"는 DXGI를 통해서 화면 캡처를 진행하고 있으며, 세로 모드로 화면을 캡처하는 경우 "DXGI_ERROR_ACCESS_LOST" 에러 코드와 함께 정상적으로 동작하지 않습니다.


참고하실 수 있도록 아래 MS Q&A에 다른 사용자가 질문한 링크를 전달드립니다. 

https://docs.microsoft.com/en-us/answers/questions/796217/potrait-mode-screen-capturing-return-blank-image-o.html



제품에 대해 추가로 궁금한 점은 언제든지 회신하여 주시기 바랍니다.
감사합니다.

Easy&Light
