### ISSUE TITLE
120hz말고 다른 주사율은 사용할 수 없나요?

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1036]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:dkekao77@gmail.com<br><br>현재 갤럭시 tab6태블릿을 사용중인데 이 태블릿은 60hz까지밖에 지원하지 않습니다 그런데 twomon연결후 컴퓨터 설정에선 주사율이 120hz로 밖에 선택되지 않습니다 그로인해 프레임 드랍이 심한데 60hz로 구동할순 없나요?<br><br>[EL_Display_ec1e4278-4132-464f-a1fc-5769884e4762.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_ec1e4278-4132-464f-a1fc-5769884e4762.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----



고객님, 안녕하세요. Easy&Light 지원 팀 입니다.


문의해주신 내용에 대한 답변을 메일로 전달해드립니다.





현재 Twomon SE의 경우, 성능모드가 120hz, 45hz, 30hz로 구성되어 있으며, 

120hz로 캡처해도 실제로 전송 및 표시되는 화면은 60hz로 표시되기 때문에 차이가 없을 것으로 보입니다.




성능이 원활하지 않은것과 관련하여 PC 프로그램을 완전히 삭제 후 재설치하여 문제가 해결되는지 확인 부탁드립니다. 만약 재설치로도 문제가 해결되지 않을 시 PC 프로그램의 해상도가 권장 해상도로 설정되어 있는지 추가로 확인 부탁드립니다. 






감사합니다.





Easy&Light
