### ISSUE TITLE
Keyboard support ?

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1038]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:adynetro@yahoo.com<br><br>Can you add keyboard support for iPad . Most ipad have some kine of keyboard atachments, and it's easyer to use them when using the ipad.<br><br>[EL_Display_496729ae-b595-4dfa-878b-9027970e91db.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_496729ae-b595-4dfa-878b-9027970e91db.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.

Currently, only keyboards connected to a PC are supported.

We will forward your comments to our product manager.

Thank you for your nice comments about our products.

Easy&Light
