### ISSUE TITLE
can't detect device

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1040]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:jymambu@icloud.com<br><br>Hi I have sent inquiry a month ago and still no respond. I have paid and haven't got the benefit I supposed to get. Please help<br><br>[EL_Display_c8ed1d5f-5dbc-440f-bba7-4631c3fa29e1.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_c8ed1d5f-5dbc-440f-bba7-4631c3fa29e1.zip)

**Comment by Sienna-lee** [comment]
#890 사용자과 동일 사용자입니다.
