### ISSUE TITLE
세로 모드가 되지 않습니다.

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1083]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:drij024@naver.com<br><br>세로모드하면 화면 멈춤 증상있습니다. 또한 EL 디스플레이 설정에 확장 메뉴가 잘 되지 않습니다.<br><br>[EL_Display_b05d6c7e-200e-4f0c-b92e-56e80fb8c951.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_b05d6c7e-200e-4f0c-b92e-56e80fb8c951.zip)

**Comment by Sienna-lee** [comment]
#1083 사용자와 동일 사용자입니다.
