### ISSUE TITLE
듀얼로 사용하고 싶은데요

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1092]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:jinny0965@gmail.com<br><br>이렇게 화면이 뜨는데 어떻게 해야하나요?<br><br>[EL_Display_4b7fe3dd-8ce7-412f-989e-45201b02e714.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_4b7fe3dd-8ce7-412f-989e-45201b02e714.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


안녕하세요 고객님. Easy&Light 지원팀입니다.

문의하신 내용에 대한 답변을 아래 전달드립니다. 


이미지 등이 함께 첨부되지 않아 어떠한 문제인지 확인이 어려워 우선 아래와 같이 확장 화면이 표시되지 않을 시 설정할 수 있는 방법을 전달드립니다. 


먼저 PC 프로그램을 완전히 삭제 후 재설치하여 확인해주시기 바랍니다. 

PC 프로그램 재설치시에도 복제화면만 표시할 시, 아래와 같이 설정하여 확장 화면이 표시되는지 확인 부탁드립니다. 


1. Windows + P 키 입력하여 프로젝트 옵션을 확장으로 선택
EL_윈도우 확장.jpg



2. EL Display Hub에서 확장 디스플레이 선택

EL_확장 디스플레이 선택.png




위와 같이 설정하여도 문제가 계속된다면 고객지원의 '문의하기'를 통해 다시 한번 문의 부탁드립니다.
'문의하기'를 통해 문의 시 로그파일이 자동으로 첨부되며 기술팀에서 해당 로그 분석 후 해결 방안을 다시 한번 전달드리도록 하겠습니다.

감사합니다.

Easy&Light
