### ISSUE TITLE
키보드 마우스 지원 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1128]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:ihyunryu@gmail.com<br><br>아이패드에 연결된 블루투스 키보드, 혹은 스마트 커넥터 등으로 연결된 스마트 키보드/매직키보드로 메인 PC를 조작할 수는 없을까요? 터치 입력이 지원되는거 보면 분명 가능할 것 같습니다...<br><br>[EL_Display_f7fa5ec9-e94c-4699-92a7-8177268f3ece.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_f7fa5ec9-e94c-4699-92a7-8177268f3ece.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

문의해주신 내용에 대한 답변을 메일로 전달해드립니다.      

Twomon SE의 경우, 태블릿의 화면 터치 기능은 제공하지만 PC 화면을 태블릿에 표시하는 것과 더블어 입력 또한 PC에 입력된 것을 보여주게 됩니다. 
키보드 혹은 마우스 기능을 사용하기 위해서는, iPad와 연결된 키보드, 마우스가 아닌
Windows PC와 연결되어 있는 키보드 혹은 마우스를 사용해야 기능이 동작합니다.
아이패드에 연결할 경우 앱 내에서는 사용하실 수 없습니다. 
제품에 대해 추가로 궁금한 점은 언제든지 회신하여 주시기 바랍니다. 

감사합니다.

Easy&Light
