### ISSUE TITLE
Can I put my ipad screen on my computer

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1195]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:theclovergraves@gmail.com<br><br>it lets me stream mycomputer screen on my ipad but idk how to reverse it and stream my ipad on my comp<br><br>[EL_Display_df9da35a-a2e2-4370-b2f2-55cf9f1d2d45.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_df9da35a-a2e2-4370-b2f2-55cf9f1d2d45.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.

EasyCanvas can only display your PC's screen on your iPad.
It does not provide the ability to display the iPad's screen on a PC.

If you have any additional questions about the product, please reply.

thank you


Easy&Light
