### ISSUE TITLE
이번에도 답변 안주시면 그냥 삭제하도록 할께요

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1217]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:owollz@naver.com<br><br>브러쉬도 안먹히고 화면 터치만되고 그외에 작업은 하나도 안되네요 지금 문의넣은지 한달도 넘은거 같은데 답변도 없고 이번에는 꼭 답변 부탁드러ㅕ요<br><br>[EL_Display_0500926d-a740-4f89-87de-62dcb6e42778.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_0500926d-a740-4f89-87de-62dcb6e42778.zip)

**Comment by Juilliardsong** [comment]
관련 이슈: #1145, #1150

**Comment by Juilliardsong** [comment]
아래와 같이 답변함
---
안녕하세요 고객님. Easy&Light 지원팀입니다.
먼저, 먼저 답변이 늦어진 점 정말 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과
연결 도중 지속적으로 USB를 통한 연결이 해제 및 재연결 되는 로그가 확인되었으며,
이러한 문제는 USB포트의 전력 부족 혹은 연결 불량 문제로 의심됩니다.

"화면 전송"의 경우 USB를 통해 처리되는 데이터의 양이 많아서,
일반적인 PC와 디바이스 간의 연결이 정상적으로 동작하여도
실제 "화면 전송" 통신에는 실패할 수 있습니다.


이를 해결하기 위해 아래의 사항들을 조치해보십시오.
1. PC와 태블릿 간의 연결이 정상적인지 확인합니다.
2. USB 케이블 교체(가능한 정품 케이블 사용)합니다.
3. PC에 연결된 USB 포트 변경(후면 포트 이용)합니다.
4. 외부전원 USB 허브에 연결합니다.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.


현재 보내주신 로그에는 PC로그만 존재하여 정확한 분석에 어려움이 있습니다.
PC로그와 어플리케이션 측의 로그와 좀 더 자세한 증상을 설명해주신다면 정확하고 빠른 분석이 가능하니
번거로우시더라도 PC로그와 어플리케이션 로그를 모두 보내주시길 바랍니다.

[FAQ] 로그 취득 가이드 :
http://www.easynlight.com/supporttwomon/?faq=121


감사합니다.

Easy&Light
