### ISSUE TITLE
윈11에서 화면확장으로 세로보기 불가

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1220]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:qjflaapdlf@gmail.com<br><br>아이패드를 연결해서 아이패드 세로화면으로 확장하고자 디스플레이 설정에서 세로 모드로 변경했는데, 아이패드 화면이 멈춘 채로 마우스 커서가 보이거나 화면이 움직이지 않습니다... 터치했을 때 마우스가 아이패드로 옮겨가기는 하는데 화면은 안움직이는걸 알 수 있었어요<br><br>[EL_Display_e02b0e40-8e75-45f9-b4de-82b79ac0ae10.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_e02b0e40-8e75-45f9-b4de-82b79ac0ae10.zip)

**Comment by Juilliardsong** [comment]
아래와 같이 답변함
---
고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

Twomon SE를 사용하여 세로 화면으로 사용할 때 문제가 발생한다고 문의를 주셨습니다.

혹시 사용하시는 환경이 Windows 11 인가요?
현재 Windows 11의 경우 세로 모드일 때 Windows에서 제공하는 기능에 문제가 있어 화면 멈춤 현상 등이 발생할 수 있습니다.

Microsoft에서 오류를 수정하지 않으면 해당 문제는 해결이 어려울 것으로 보이며, 현재로서는 불편하시더라도 Windows 11에서는 가로 모드로 사용해주시길 바랍니다.

혹시 Windows 10에서 해당 문제가 발생하는거면 다시 한번 연락 부탁드립니다.

감사합니다.
