### ISSUE TITLE
아이패드 카메라 컴퓨터 사용

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1253]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:bjkbjk1@naver.com<br><br>아이패드의 카메라를 컴퓨터에서 사용할 수 있는 방법 가능하면 좋겠습니다<br><br>[EL_Display_3fbad925-2005-48d2-9367-2bae0c572efb.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_3fbad925-2005-48d2-9367-2bae0c572efb.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

안녕하세요 고객님. Easy&Light 지원팀입니다.
문의해주신 내용에 대한 답변을 메일로 전달해드립니다.

아쉽게도, Twomon SE 사용 중 아이패드의 카메라를 윈도우에서 인식하여 사용하는 것은 불가능 합니다.
위 기능 추가에 대해서는 기술팀이 검토해볼 수 있도록 내용을 전달하도록 하겠습니다. 

사용 중 궁금한 점이 있으시면 문의주시기 바랍니다.

감사합니다.


Easy&Light
