### ISSUE TITLE
How to change subscription to pay once?

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1255]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:Anggichrns13@gmail.com<br><br>How to change subscription to pay once?<br><br>[EL_Display_9dfa67f5-9b01-448b-9faa-39946658cf08.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_9dfa67f5-9b01-448b-9faa-39946658cf08.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----




Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.


EasyCanvas has two apps depending on the purchase method.(In-app/subscription)
Did you currently purchase the Subscription app?
Cancel and refund the app and purchase the app for in-app below.


https://apps.apple.com/us/app/id1228034134


Please refer below for how to cancel your subscription and refund.

https://support.apple.com/en-us/HT202039


If payment has been made, you can request a refund from Apple.

https://support.apple.com/en-us/HT204084



Thank you.

Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 메일로도 동일한 문의를 했습니다.

----

Title: I want to cancel my subscription to once pay

Questions: hello, my name is Anggita. I want to cancel my subscription to once pay. ive already use the 3 days trial and i didnt get the email for buy the app
