### ISSUE TITLE
in app subcribcion remove

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1259]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:uroevan@gmail.com<br><br>hello i want to remove the subscribtion of the app how i do it<br><br>[EL_Display_7c569698-35de-4aa1-891e-d1ef1d3d57ad.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_7c569698-35de-4aa1-891e-d1ef1d3d57ad.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.



Did you buy EasyCanvas(in-app)?
After the 3days trial, payment is not automatically made, so just leave it.


If you have purchased EasyCanvas subscription, please refer to the link below.

https://support.apple.com/en-us/HT202039


If payment has been made, you can request a refund from Apple.

https://support.apple.com/en-us/HT204084



Thank you.

Easy&Light
