### ISSUE TITLE
in app purcase remove

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1260]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:uroevan@gmail.com<br><br>hello i want to remove the in app purcase subscribtion how i do it?<br><br>[EL_Display_4e01a3e5-67a3-4c74-ae06-55e225e030ed.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_4e01a3e5-67a3-4c74-ae06-55e225e030ed.zip)

**Comment by Sienna-lee** [comment]
#1259 동일 사용자입니다.
