### ISSUE TITLE
Suddenly doesnt work

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1268]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:jmccall0213@gmail.com<br><br>I PAID for and was happily using Twomon SE to extend my displays on a tablet. I got an update and now the app doesnt work. Please fix or refund.<br><br>[EL_Display_ad56d61d-36c3-4be8-93a3-992e36e41f40.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_ad56d61d-36c3-4be8-93a3-992e36e41f40.zip)

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 추가로 메일을 보내왔습니다.

----


This is my second attempt to contact. I paid for the app, Twomon, and suddenly it stopped working. When I tried to redownload and update it, I was asked to repurchase the app. Is this fraud? This email is being forwarded to Google as well, for the record.

 

I have Twomon SE on my tablet, that I also had, WORKING JUST FINE on my computer, then BOOM! It stops working and I have to buy it again.
