### ISSUE TITLE
ipad连接电脑相关问题

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1281]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:a418651970@gmail.com<br><br>为什么ipad连接电脑充当副屏幕后 ipad没在充电<br><br>[EL_Display_2fb13eeb-6e51-49ce-aec0-9b5d5888862c.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_2fb13eeb-6e51-49ce-aec0-9b5d5888862c.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----




Hello. We are an Easy & Light support team.

I'm sending this email for your inquiry.


It can be charged while in use by connecting the cable, but this may not be possible if the battery consumption is higher.

Therefore, it is recommended to use a power source hub that supports USB3.0.


If you have any further questions, please feel free to reply to us. 


thank you
