### ISSUE TITLE
Easy Canvas no free trial

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1299]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:jsebastiansn@hotmail.com<br><br>I wanted to try the product in free trial mode, instead easy canvas charge to my account the entire cost of the product. It is my first time using the product and just want to try it for a couple of days. What can i do?<br><br>[EL_Display_dc9fc2a3-7d9d-46ed-a748-b02072c984fa.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_dc9fc2a3-7d9d-46ed-a748-b02072c984fa.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.


Have you used[ EasyCanvas](https://apps.apple.com/us/app/id1499946999)[ subscription](https://apps.apple.com/us/app/id1499946999)?
[EasyCanvas (in-app)](https://apps.apple.com/us/app/id1228034134) also offers a 3-day free trial.
The features of both products are identical.
If you would like a free trial, please try the above products.


If you want a refund, you can request a refund from Apple.

https://support.apple.com/en-us/HT204084

thank you


Easy&Light
