### ISSUE TITLE
nimiko

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1300]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:nathayathipsuk@gmail.com<br><br>-<br><br>[EL_Display_598baf4f-fd37-415f-b692-e0c8a607b908.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_598baf4f-fd37-415f-b692-e0c8a607b908.zip)

**Comment by Sienna-lee** [comment]
이슈 내용이 적혀있지 않아 해당 이슈를 종료합니다.
