### ISSUE TITLE
log file

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1321]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:avdhesh.kumawat@gmail.com<br><br>log<br><br>[EL_Display_323aef9d-8fcf-4e78-b857-41fc6ddc85b9.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_323aef9d-8fcf-4e78-b857-41fc6ddc85b9.zip)

**Comment by Sienna-lee** [comment]
#1313 사용자의 로그파일입니다.

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

What happened... ?? I didn't get any response
