### ISSUE TITLE
에러코드 A11002 같은 거 뜰 때, 재부팅 없이 해결할 수 있는 방법

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1331]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:dnr2144@gmail.com<br><br>요즘따라 에러코드(A11002)가 너무 많이 뜨는데, 전부다 해결법이 재부팅을 하라네요. 요즘 시대에 컴퓨터에 켜놓은 게 많아서 재부팅 하는 것도 굉장히 큰 비용입니다. 서비스 탭 가서 서비스 재시작을 하면 옛날에는 해결이 됐었는데 요즘은 무슨 `파이프를  끝내는데, 실패했다면서 그 방법도 안 먹히네요. 좋은 서비스인 것은 많지만 에러코드 떴을 때 재부팅 안 하고 해결하는 방법 좀 알려주세요. 그리고 원인도 좀 알려주세요. 왜 이런 에러가 발생하는지. 사용환경은 윈도우 10 + Ipad입니다.<br><br>[EL_Display_0714760c-9ec5-4e50-8ed9-0bb83bcf00c3.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_0714760c-9ec5-4e50-8ed9-0bb83bcf00c3.zip)

**Comment by Sienna-lee** [comment]
#1330 이슈와 동일한 사용자입니다.
