### ISSUE TITLE
모니터 송출 화면 설정 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1344]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:onize95@naver.com<br><br>iPad와 LG 그램 랩탑을 연결하였는데, iPad에 랩탑과 동일한 화면이 나오는데 이 화면을 듀얼모니터처럼 확장된 화면을 볼 수 있게 하고 싶은데 설정을 어떻게 해야 하나요? 랩탑과 iPad에 서로 다른 창을 띄워놓고 싶습니다.<br><br>[EL_Display_e0762c0c-f9ec-4b1f-8ae6-901a5af703aa.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_e0762c0c-f9ec-4b1f-8ae6-901a5af703aa.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----



고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

문의해주신 내용에 대한 답변을 메일로 전달해드립니다.


아래 방법을 이용하여 확장 화면이 표시되는 지 확인 부탁드립니다. 


1. Windows + P 키 입력하여 프로젝트 옵션을 확장으로 선택
EL_윈도우 확장.jpg



2. EL Display Hub에서 확장 디스플레이 선택

EL_확장 디스플레이 선택.png




위와 같이 설정했음에도 확장 화면이 표시되지 않는다면 PC 프로그램을 재설치 한 후 확인 부탁드립니다.

오류라고 생각 될 경우, 고객지원의 '문의하기'를 통해 다시 한번 문의 부탁드립니다.

감사합니다.

Easy&Light
