### ISSUE TITLE
타블렛처럼 커서가 미리 보이는 기능은 힘들까요?

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1383]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:tpgml3077@naver.com<br><br>컴퓨터에 타블렛을 연결하거나 아이패드 프로크리에이터 어플에서는 펜이 닫지 않아도 가까이대면 커서위치가 보이는데(또는 브러쉬위치) 이지캔버스에서도 이런기능이 있으면 좋을것 같습니다 혹시 가능할까요..?<br><br>[EL_Display_87ba45d5-273f-49ca-84c0-11b844357cbe.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_87ba45d5-273f-49ca-84c0-11b844357cbe.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

고객님, 안녕하세요. Easy&Light 지원 팀 입니다.
문의해주신 내용에 대한 답변을 메일로 전달해드립니다.  
아쉽게도, 호버링 기능은 Apple Pencil 및 iPad의 하드웨어적 기능 미지원으로 인하여 저희가 제공해 드리기 어려운 기능입니다.
원하시는 답변을 드리지 못하여 죄송하며, 이후 신규 기기등이 출시되어 해당 기능이 탑재될 경우 저희 제품에서도 지원할 수 있도록 담당자에게 의견을 전달하도록 하겠습니다.  
다른 의견이나 궁금한 점이 있으시다면 언제든지 문의주시기 바랍니다.
감사합니다.

Easy&Light
