### ISSUE TITLE
PC keeps disconnecting from iPad

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1385]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:www.woshixiaodu@gmail.com<br><br><br>PC keeps disconnecting from iPad<br><br>[EL_Display_6d00dae2-5669-4aa4-89d1-0203448b9690.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_6d00dae2-5669-4aa4-89d1-0203448b9690.zip)

**Comment by Sienna-lee** [comment]
#1384 와 동일한 사용자입니다
