### ISSUE TITLE
gdf

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1400]
Product:EasyCanvas<br><br>Device OS:Android<br><br>e-mail:reana123@mail.ru<br><br>gdf<br><br>[EL_Display_28997fed-9e0b-49fd-a6e0-be37b8932e2f.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_28997fed-9e0b-49fd-a6e0-be37b8932e2f.zip)

**Comment by Juilliardsong** [comment]
이슈에 아무런 내용이 없어 이슈 종료합니다.
추가 접수 오면 Reopne 합니다.
