### ISSUE TITLE
라이센스 문제

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1404]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:ewldn12@naver.com<br><br>아마존패드에 결제가 어려워 핸드폰으로 결제 후 같은 아마존패드에 같은 구글계정으로 들어가서 다운받으려는데 같은어플이 또 돈을 내라해서 그러는데 어떻게해야하나요.<br><br>[EL_Display_038aecff-4c56-49b6-8f90-fd326e52afed.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_038aecff-4c56-49b6-8f90-fd326e52afed.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----




고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

문의해주신 내용에 대한 답변을 메일로 전달해드립니다.


구매한 계정으로 다시 한번 재로그인하여 시도해보시기 바랍니다. 

동일 계정으로 로그인 되어 있는지 확인 하신 후, 탭에서  구글플레이스토어로 가셔서
우측 상단의 프로필을 눌러 ->앱 및 기기 관리-> 관리 -> 설치됨 필터를 설치되지 않음으로 변경하여 Twomon SE를 선택하여 우측 상단의 다운로드 버튼을 누르시면 됩니다. 

혹은 프로필 -> 결제 및 정기 결제 -> 예산 및 내역에서 앱을 선택하여 아래 표시되는  '보기'를 눌러 다운로드가 가능합니다. 


혹시 구입 직후에 각각의 태블릿에 설치 시도를 하셨는지요?
구매 직후 바로 다른 기기에서 시도할 시, 설치가 정상적으로 되지 않는경우가 있습니다.
시간의 여유를 두시고 다시 한 번 시도해보시기 바랍니다.



감사합니다.

Easy&Light
