### ISSUE TITLE
t

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1510]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:t<br><br>t<br><br>[EL_Display_a3ff3bdf-f403-47f3-8ec8-bb3bc4931638.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_a3ff3bdf-f403-47f3-8ec8-bb3bc4931638.zip)

**Comment by AdamPark0030** [comment]
테스트용 이슈입니다.
