### ISSUE TITLE
qwe

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1511]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:qwe<br><br>qw<br><br>[EL_Display_2c78b4b8-656f-480e-9bdc-6fdbf1eccb91.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_2c78b4b8-656f-480e-9bdc-6fdbf1eccb91.zip)

**Comment by AdamPark0030** [comment]
테스트용 이슈입니다.
