### ISSUE TITLE
qwe

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1512]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:qwe<br><br>qwe<br><br>[EL_Display_65311aaa-06ec-4dfe-84e8-c96ae98a613c.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_65311aaa-06ec-4dfe-84e8-c96ae98a613c.zip)

**Comment by AdamPark0030** [comment]
테스트용 이슈입니다.
