### ISSUE TITLE
wqewqewqwq

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1513]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:qweqwewqe<br><br>wqewqewqwq<br><br>[EL_Display_f972ff69-cf8b-488f-8142-578d04ca1258.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_f972ff69-cf8b-488f-8142-578d04ca1258.zip)

**Comment by AdamPark0030** [comment]
테스트용 이슈입니다.
