### ISSUE TITLE
wqewqwqewqqwe

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1514]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:qwewqqq<br><br>wqwqewqewqew<br><br>[EL_Display_136f30ff-baac-4194-8738-f6d490c32a0e.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_136f30ff-baac-4194-8738-f6d490c32a0e.zip)

**Comment by AdamPark0030** [comment]
테스트용 이슈입니다.
