### ISSUE TITLE
tqweqwe

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1515]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:test<br><br>qweqwewqewq<br><br>[EL_Display_c77b8da1-0076-426c-afb6-0475332140a1.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_c77b8da1-0076-426c-afb6-0475332140a1.zip)

**Comment by AdamPark0030** [comment]
테스트용 이슈입니다.
