### ISSUE TITLE
오른쪽 클릭 문의 

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#1527]
- 문의 날짜 : 2022년 11월 7일 오후 4시 36분
- 메일 주소 : dayle.ramsden@gmail.com

Title: right click easy canvas

Questions: Good Day, how can i perform a right click aciton using easy canvas on my ipad air paired to a windows pc. there is a guide for easy canvas pro but it doesnt work.

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello,  We are an Easy & Light support team.

I'm sending this email for your inquiry.


Do you want to use your Apple Pencil to operate your mouse?
The right-click action of the pen is long-press for more than 1 second.  

Please refer to the link below.

[https://eneasynlight.blogspot.com/2020/08/easycanvas-pro-right-click-function.html  ](https://eneasynlight.blogspot.com/2020/08/easycanvas-pro-right-click-function.html)



If it does not work properly, please contact us with log file.

http://www.easynlight.com/en/supporteasycanvas/?faq=54



Thank you.

Easy&Light

**Comment by Juilliardsong** [comment]
기획팀에서 전달한 방법으로 해결이 되지 않은 것 같습니다.
추가로 받은 로그 파일 첨부합니다.

[com.devguru.bypd 2022-11-07 10-42.log](https://github.com/edh-git/EL_Display_Hub/files/9968249/com.devguru.bypd.2022-11-07.10-42.log)
[com.devguru.bypd 2022-11-08 11-51.log](https://github.com/edh-git/EL_Display_Hub/files/9968250/com.devguru.bypd.2022-11-08.11-51.log)

**Comment by Juilliardsong** [comment]
로그에는 이상이 없어 아래와 같이 회신하였습니다.
---
I checked the log, but I couldn't find any problems.

In some programs, Apple Pencil long-touch gestures are blocked.
Please check if the right-click gesture is executed by pressing the Apple pencil for more than 1 second on the Windows desktop.

Thank you.

**Comment by Juilliardsong** [comment]
고객 추가 문의 접수
---
i understand it works when i use my finger on the desktop. the whole reason i want this to work is so that i can alt + hold down right click and drag. this is a quick way to resize a brush in photoshop and other adobe programs.do you know of other ways i could achieve this?

**Comment by Juilliardsong** [comment]
아래와 같이 회신하였습니다.
---
Unfortunately, there is no way we can do it if the program restricts it.
If the problem is solved by a new method in the future, we will notify you.

I'm sorry I couldn't help you.
Thank you.

**Comment by Juilliardsong** [comment]
추가 문의 접수하였습니다.
---
Good Morning, I would like to ask if it would create a better connection if i connect my ipad to the pc using usb 3.1 and connecting it via wifi at the same time?

**Comment by Juilliardsong** [comment]
아래와 같이 회신하였습니다.
---
Hello, We are an Easy & Light support team.

There is no difference in speed or stability as the wired and wireless connections are not simultaneously connected.

Thank you.

**Comment by Juilliardsong** [comment]
추가 문의 접수하였습니다.
---
oh ok thank you, and should is it recommended to use usb 3.1. im currently using a usb 2 cable and i see a reduction in quality

**Comment by Juilliardsong** [comment]
아래와 같이 회신하였습니다.
---
Hello, We are an Easy & Light support team.

The performance difference between USB 2.0 and 3.0 and 3.1 is not significant.
However, when using EasyCanvas, the tablet charging speed is faster with USB 3.1.

Thank you.
