### ISSUE TITLE
포토샵에서 펜사용 불가문의 드립니다.

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1530]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:reveriejohn5@naver.com<br><br>안녕하세요. 2017년식 LG 그램 노트북과 레노버 P11 글로벌롬을 연결하여 사용하고있습니다. P11 펜을 이용하여 화면을 터치하면 다른데서는 다 잘 인식이 되는데 포토샵의 작업 화면에서만 인식이 안됩니다. 포토샵의 주변부 파일 편집 이미지 레이어 등의 부분은 다 잘 인식이 되는데 작업부만 인식이 안되네요. 그림판등에서는 또 잘 인식이되고 잘 그려집니다. 무슨문제인지 궁금합니다. 포토샵은 2020버젼입니다. 전화를 주셔도 감사하겠습니다. 010 2910 3551 입니다<br><br>[EL_Display_24ab5d9d-7b40-4051-a2e5-5a5b5216ba52.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_24ab5d9d-7b40-4051-a2e5-5a5b5216ba52.zip)

**Comment by Juilliardsong** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.
----
고객님, 안녕하세요. Easy&Light 지원팀 입니다.


Twomon SE는 펜 입력을 터치로 인식하여 동작합니다.
그림판 등 대부분의 프로그램은 터치와 스타일러스 펜 입력을 동시에 입력 받는 프로그램이라
Twomon SE의 터치 및 펜 입력을 모두 이용하실 수 있습니다.

그러나 포토샵을 비롯하여 몇몇 프로그램은 스타일러스 펜과 마우스 입력만 가능하게 되어 있어,
터치로 인식되는 Twomon SE의 펜 동작은 입력이 불가능합니다.
포토샵의 작업 영역에는 스타일러스 펜 동작만 입력 가능이 가능한 것으로 알고 있습니다.

포토샵의 작업 영역에 스타일러스 펜을 사용하여 드로잉을 하시려면 드로잉에 특화된 앱을 사용하셔야 합니다.


추가로 궁금한 사항이 있으신 경우, 언제든 문의주세요.
감사합니다.
