### ISSUE TITLE
connection failed after I paid

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1532]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:motoforever@qq.com<br><br>Can't fix it after reinstalled it millions of times<br><br>[EL_Display_00f44cef-b154-4ae4-b353-d2847f6a4cba.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_00f44cef-b154-4ae4-b353-d2847f6a4cba.zip)

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 

## 원인 파악

PC 프로그램 크래시 발생으로 인하여 정상적인 연결이 불가능

### 크래시 원인

불분명함. 특별한 점은 

1. msinfo의 Windows Error Report 카테고리 확인 시 ffmpeg내부에서 크래시 발생하는것으로 보임.

2. 크래시 발생 위치를 어느정도 특정 할 수 있어보이므로 확인 필요.

3. 클라이언트로부터 메세지 수신 시 unknown 메세지 수신하는 경우가 있었으므로, 케이블 문제 확인 필요.

## 답변

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

첫 번째로 USB포트의 전력 부족 혹은 연결 불량 문제일 수 있습니다.
이를 해결하기 위해 아래의 사항들을 조치해보십시오.
1. PC와 태블릿 간의 연결이 정상적인지 확인합니다.
2. USB 케이블 교체(가능한 정품 케이블 사용,  데이터 통신이 가능한 케이블 사용)합니다.
3. PC에 연결된 USB 포트 변경(후면 포트 이용)합니다.
5. 외부전원 USB 허브에 연결합니다.

두 번째로 PC측과 태블릿 측의 오류일 수 있습니다.
1. PC를 재부팅하여 주십시오. (종료 옵션의 "다시 시작" 사용)
2. 태블릿을 재부팅하여 주십시오.
3. PC측의 EL Display Hub를 제거하신 뒤 새로운 인스톨러를 설치하여 재설치

[EL Display Hub] 설치 페이지 :  http://www.easynlight.com/easycanvas/

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/en/supporteasycanvas/?faq=54

감사합니다.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
제목 : Re: [EasyCanvas - 1532] connection failed after I paid
```
Hi, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

First, the USB port may be low power or poor connection.
Please take the following steps to resolve this issue.
1. Verify that the connection between the PC and the tablet is normal.
2. Replace the USB cable (use a genuine cable as possible, use a cable that enables data communication).
3. Change the USB port connected to the PC (using the rear port).
5. Connect to an external power USB hub.

Secondly, it may be an error on the PC side and on the tablet side.
1. Please reboot your PC. (Use "Restart" in the Shutdown option)
2. Reboot your tablet.
3. After removing the EL Display Hub on the PC side, install a new installer and reinstall it

[EL Display Hub] installation page: http://www.easynlight.com/en/easycanvas/

If the problem does not improve even after proceeding with the above measures, please contact us again with the application log.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Easy&Light
```
