### ISSUE TITLE
easycanvas cannot stop disconnecting.

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1539]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:urban.carole@gmail.com<br><br>Each 30 second, easycanvas loses the signal with the iPad making it unusable. I just updated to ipad Os 16, I don't know if it has to do with it. Thank you.<br><br>[EL_Display_cea1c6c1-c09f-4d3c-9b49-7dd07dbd70c7.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_cea1c6c1-c09f-4d3c-9b49-7dd07dbd70c7.zip)

**Comment by AdamPark0030** [comment]
## 원인 파악

1. WIFI 이용 시 keepalive packet sequence가 맞지 않은 경우 다수 발생
```
[2022-11-10 14:02:43.532][GENERAL:ERROR][4788:16668][bypd_server_core_proc_manager_keep_alive_thread:3730] WIFI Keep alive seq is invalid - server [78] and client [77]
[2022-11-10 14:02:43.737][GENERAL:ERROR][4788:16668][bypd_server_core_proc_manager_keep_alive_thread:3730] WIFI Keep alive seq is invalid - server [79] and client [77]
[2022-11-10 14:02:43.940][GENERAL:ERROR][4788:16668][bypd_server_core_proc_manager_keep_alive_thread:3730] WIFI Keep alive seq is invalid - server [80] and client [77]
[2022-11-10 14:02:44.140][GENERAL:ERROR][4788:16668][bypd_server_core_proc_manager_keep_alive_thread:3730] WIFI Keep alive seq is invalid - server [81] and client [77]
```

wifi 연결 이용 시에는 신호가 충분히 좋은 환경인지 확인 필요.

추가로 IOS 16에서 wifi 연결이 해제되는 버그가 있는것으로 보임.

https://www.macrumors.com/2022/10/27/ios-16-1-wifi-issues-for-users/

**Comment by AdamPark0030** [comment]
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 Wifi 연결이 원활하지 않은 것으로 보입니다.

Wifi 신호가 원활한 환경에서 EasyCanvas를 이용해주시길 바랍니다.

또한, IOS 16 업데이트 이후 wifi 연결 이슈가 있는것으로 보입니다. EasyCanvas를 사용하지 않을 때에도 문제가 발생하는지 확인 부탁드립니다.

[IOS 16 Issue ] : https://www.macrumors.com/2022/10/27/ios-16-1-wifi-issues-for-users/  

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

현재 보내주신 로그에는 PC로그만 존재하여 정확한 분석에 어려움이 있습니다.PC로그와 어플리케이션 측의 로그와 좀 더 자세한 증상을 설명해주신다면 정확하고 빠른 분석이 가능하니번거로우시더라도 아래의 링크를 참조하셔서 PC로그와 어플리케이션 로그를 모두 보내주시길 바랍니다.

[FAQ] 로그 취득 가이드 :http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

Easy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1539] easycanvas cannot stop disconnecting.
```
#### 본문
```
Hi, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

After reviewing the logs and symptoms you sent, it seems that the Wi-Fi connection is not smooth.

Please use EasyCanvas in an environment where Wi-Fi signals are smooth.

Also, it seems that there is a wifi connection issue after IOS 16 update. Please check if the problem occurs even when you are not using EasyCanvas.

[IOS 16 Issue ] : https://www.macrumors.com/2022/10/27/ios-16-1-wifi-issues-for-users/  

If the problem does not improve even after proceeding with the above measures, please contact us again with a new PC log and application log.

Currently, only PC logs exist in the log you sent, so there is a difficulty in accurate analysis.If you explain the PC log and the application log and the symptoms in more detail, you can analyze them accurately and quickly, so please refer to the link below and send both the PC log and the application log.

[FAQ] Log acquisition guide: http://www.easynlight.com/supporteasycanvas/?faq=97

Thank you.

Easy&Light
```
