### ISSUE TITLE
windows9  도 twomon se 를 사용할 수 있나요:?

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1543]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:kaistdgist@naver.com<br><br>windows9도 twomon se를 사용할 수 있나요?<br><br>[EL_Display_e40713c8-0905-4916-8a76-f1e25781bb27.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_e40713c8-0905-4916-8a76-f1e25781bb27.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----



고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

문의해주신 내용에 대한 답변을 메일로 전달해드립니다.


Twomon SE는 Windows 10 이상의 PC에서만 사용이 가능합니다. 

Windows 10 이하의 환경은 지원하지 않습니다.


제품에 대해 추가로 궁금한 사항은 언제든지 회신하여 주시기 바랍니다.

감사합니다.


Easy&Light
