### ISSUE TITLE
Refund my product

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1544]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:neusha.yousefi2003@gmail.com<br><br>I purchased the app today and would like to refund it<br><br>[EL_Display_5cc09fd6-f9b7-4725-bcfd-75faddb65a34.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_5cc09fd6-f9b7-4725-bcfd-75faddb65a34.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello, We're Easy&Light support team.

I'm sending this email for your inquiry.


If you would like a refund, please see below.


[How to get a refund]

1. App Store for iOS
We'd like to give you a refund but we are not in charge of the refund. We'll let you know how to get the refund from the iTunes store. Please refer to the following websites.

Contact Apple Support:
https://reportaproblem.apple.com/

How to get a refund from iTunes store:
https://support.apple.com/en-us/HT204084


2. Google play store for Android
Please click the following link, fill out and submit a refund request form.
https://docs.google.com/forms/d/1q0_e3fDsvldj5KLzch2OfUBKFCqcluPGNYAyT8TMt7Y/



I will try to make a better program.

Thank you.


Easy & Light

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

-----


Hello, We're Easy&Light support team.

I'm sending this email for your inquiry.


If you would like a refund, please see below.


[How to get a refund]

1. App Store for iOS
We'd like to give you a refund but we are not in charge of the refund. We'll let you know how to get the refund from the iTunes store. Please refer to the following websites.

Contact Apple Support:
https://reportaproblem.apple.com/

How to get a refund from iTunes store:
https://support.apple.com/en-us/HT204084


2. Google play store for Android
Please click the following link, fill out and submit a refund request form.
https://docs.google.com/forms/d/1q0_e3fDsvldj5KLzch2OfUBKFCqcluPGNYAyT8TMt7Y/



I will try to make a better program.

Thank you.


Easy & Light
