### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1545]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:neusha.yousefi2003@gmail.com<br><br>Refund my purchase today<br><br>[EL_Display_dac8700e-b543-4796-9b0b-0177480cef5e.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_dac8700e-b543-4796-9b0b-0177480cef5e.zip)

**Comment by Sienna-lee** [comment]
#1544 와 동일한 이슈입니다.
