### ISSUE TITLE
터치 시 멈춤

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#1546]
- 문의 날짜 : 2022년 11월 15일 오전 4시 13분
- 메일 주소 : ithamersz@gmail.com

Title: I\'m using an aftermarket stylus, works great! But normal touch stops working whenever I use the stylus.

Questions: Hello there, I am using an aftermarket stylus, Adonit Note+. The stylus works great. Although the moment I start using it. My normal tough control no longer registers. The pen still works fine. I have to exit and re-open the app from my ipad. For the touch to work again.

Regards Thamer..

[[EasyCanvas_-_Windows]_I_'m_using_an_aftermarket_stylus,_works_great!_But_normal_touch_stops_working_whenever_I_use_the_stylus..zip](https://github.com/edh-git/EL_Display_Hub/files/10008277/EasyCanvas_-_Windows._I_.m_using_an_aftermarket_stylus._works_great._But_normal_touch_stops_working_whenever_I_use_the_stylus.zip)

**Comment by AdamPark0030** [comment]
## 원인 파악

해당 사용자의 경우 써드파티 펜슬을 이용하고 있습니다.

현재 EasyCanvas는 정품 애플펜슬만 지원하기 때문에 써드파티 펜슬이 정상동작 하지 않을 수 있습니다.

## 답변

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

아쉽게도 이지캔버스의 경우 애플펜슬만 정식으로 지원하고 있습니다.

[EasyCanvas 지원 펜 목록] : http://www.easynlight.com/en/supporteasycanvas/?faq=57
현재로썬 다른 써드파티 펜슬 지원 계획이 없습니다.

이외 써드파티 입력장치들은 일부 마우스 기능으로 동작하며 사용이 가능할 수는 있으나, 
또 일부 펜들은 입력이 불가능한 사례들도 있었습니다.

이 점 참고 부탁드리며 긍정적인 답변을 드리지 못해 죄송합니다.

감사합니다.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1546] I'm using an aftermarket stylus, works great! But normal touch stops working whenever I use the stylus.
```
#### 본문
```
Hello, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

Unfortunately, in the case of Easy Canvas, only the Apple Pencil is officially supported.

[list of supported pens on EasyCanvas] : http://www.easynlight.com/en/supporteasycanvas/?faq=57
There are no other third-party pencil support plans at this time.

Other third-party input devices may operate with some mouse functions and may be available
There were also cases where some pens could not be entered.

Please refer to this point and I'm sorry for not giving you a positive answer.

Thank you.
```
