### ISSUE TITLE
애플펜슬 필압이 작동하지 않습니다

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1547]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:96015440@naver.com<br><br>현재 클립 스튜디오를 사용하고 있으며 재부팅, 앱 재설치 등 해결이 되지 않아 블로그에 올려주신 wintap에서 TabletPC로 변경을 했음에도 불구하고 필압이 작동하지 않습니다. 이지캔버스 내의 필압 조절을 사용해보아도 필압 조절이 작동하지 않습니다.<br><br>[EL_Display_c2823787-d259-430b-9f65-075a8342ddb0.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_c2823787-d259-430b-9f65-075a8342ddb0.zip)

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 
## 원인 파악

클립 스튜디오에서 필압 테스트 시 정상적으로 필압이 동작했습니다.

그러나 일부 펜의 경우 필압이 동작하지 않는 도구도 있었습니다.

이러한 점과 함께, 다른 사용자의 클립 스튜디오 필압 불가능 해결 사례 링크를 함께 첨부하여 문제 해결에 도움을 줄 수 있을 것 같습니다.

## 답변

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

저희측에서 클립 스튜디오의 필압 확인 결과 정상적으로 필압이 입력되는 것으로 확인됩니다.

또한 저희측에서 확인된 부분은 아니지만, 다른 클립 스튜디오 사용자의 필압 적용이 불가능 할 때의 해결 사례가 있어 링크 첨부해 드립니다.
[클립 스튜디오 필압 적용 불가능 현상 해결사례] https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=akasis4u&logNo=221410972600 

또한 입력 테스트 도중 일부 펜 도구는 필압 적용이 불가능한 것으로 보입니다.

펜 도구의 캘리그라피 도구의 경우 펜 차원에서 필압을 지원하지 않는 것으로 보입니다.

고객님께서 사용중인 펜 도구가 필압을 지원하는지 확인 부탁드립니다.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

감사합니다.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1547] 애플펜슬 필압이 작동하지 않습니다
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

저희측에서 클립 스튜디오의 필압 확인 결과 정상적으로 필압이 입력되는 것으로 확인됩니다.

또한 저희측에서 확인된 부분은 아니지만, 다른 클립 스튜디오 사용자의 필압 적용이 불가능 할 때의 해결 사례가 있어 링크 첨부해 드립니다.
[클립 스튜디오 필압 적용 불가능 현상 해결사례] https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=akasis4u&logNo=221410972600

또한 입력 테스트 도중 일부 펜 도구는 필압 적용이 불가능한 것으로 보입니다.

펜 도구의 캘리그라피 도구의 경우 펜 차원에서 필압을 지원하지 않는 것으로 보입니다.

고객님께서 사용중인 펜 도구가 필압을 지원하는지 확인 부탁드립니다.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

감사합니다.

Ea​​sy&Light
```
