### ISSUE TITLE
Lost Touch Support

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1548]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:joao.queiroz.lima@gmail.com<br><br>I lost touch support on my system. I can connect easy canvas from the iPad to Windows PC, and Apple Pencil works, but touch and gestures are not working.<br><br>[EL_Display_440bb0fc-83c4-40b8-894d-87ed9a800048.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_440bb0fc-83c4-40b8-894d-87ed9a800048.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1548] Lost Touch Support
```
#### 본문
```
Hello, customer. We are an easy&Light support team.

First of all, I apologize for the inconvenience.

Currently, there are only PC-side logs in the log you sent me, so it is difficult to analyze them accurately.
Both PC-side logs and application-side logs must be present to determine the cause accurately.
Please refer to the link below and send both the PC log and the application log.

Also, for accurate cause analysis, it can be helpful to identify the cause if you attach a video that can check the symptoms.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Ea​​sy&Light
```
