### ISSUE TITLE
ghost

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1560]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:jong9992008@gmail.com<br><br>Hy<br><br>[EL_Display_7cce8a57-15c1-4490-9792-c1ad97e6e50b.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_7cce8a57-15c1-4490-9792-c1ad97e6e50b.zip)

**Comment by Sienna-lee** [comment]
문의 내용이 없어 해당 이슈를 종료합니다
