### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1575]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:palace0261@naver.com<br><br>USB2.0 과 USB 3.0 케이블의 데이터 전송 속도 차이가 있는데 투몬 SE 를 사용함에 있어 화질이나 프레임차이가 있을까요?<br><br>[EL_Display_0419641f-e864-4a1a-bbfe-4a4ea2b1bc86.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_0419641f-e864-4a1a-bbfe-4a4ea2b1bc86.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----



고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

문의해주신 내용에 대한 답변을 메일로 전달해드립니다.


일반적으로 USB의 전송 속도는 큰 영향을 주지 않는 경우가 많습니다.

USB 버전의 상승으로 전송 속도가 향상될 경우, 미세한 차이는 있을 수 있지만 크게 체감될 수 있는 수준의 영향을 주지 못할 가능성이 높다고 보여집니다.

다만, USB 3.0이상을 사용하시면 2.0으로 연결하시는 것 보다 더 빠르게 충전하며 사용하실 수 있습니다.


제품에 대해 궁금한 점은 언제든지 회신하여 주시기 바랍니다.

감사합니다.

Easy&Light
