### ISSUE TITLE
120 Hz not mirroring on iPad Pro?

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1578]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:evanchugh@gmail.com<br><br>Hi, I'm using an iPad Pro to mirror my Windows PC. The iPad supports up to 120 Hz, but it appears to only display at 30-60FPS on my iPad. Is there a way to get this higher frame rate of 120? Thanks.<br><br>[EL_Display_a2026cc3-c809-404a-8df7-b5bbcfee9cdc.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_a2026cc3-c809-404a-8df7-b5bbcfee9cdc.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, We're Easy&Light support team.

I'm sending this email for your inquiry.


In the case of  Twomon SE, the performance mode consists of 60hz, 45hz, and 30hz,
For reasons such as performance and battery, the maximum screen refresh rate transmitted and displayed is 60hz.
Even in a tablet environment that is 120hz, it displays up to 60hz.


If you have any additional questions about the product, please feel free to reply.

Thank you.


Easy & Light
