### ISSUE TITLE
오류코드 A0011001,A0011003

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1586]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:chunghyeon99@naver.com<br><br>오류코드 A0011001,A0011003 이 발생하여 해결방안대로 수번 시도를 하였으나 결국 해결 되지 않았습니다 구매하여 사용한지 1시간도 안된거같은데 갑자기 이렇게 되니 너무 속상하네요 아마도 윈도우 업데이트를 하며 발생한 오류 같습니다 신속히 오류가 해결되면 좋겠네요 저는 윈도우 11을 사용중입니다<br><br>[EL_Display_7cdd85fe-534c-4d19-abca-1c89f68877be.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_7cdd85fe-534c-4d19-abca-1c89f68877be.zip)

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 

## 답변


안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

해당 문제의 경우 윈도우 11 업데이트 과정 중 "EL Dispay Hub"의 손상 혹은 디스플레이 드라이버와 충돌 문제일 수 있습니다.

이를 해결하기 위해 아래의 사항들을 조치해보십시오.
1. "EL Display Hub" 삭제
2. 윈도우 업데이트 확인 및 최신 윈도우로 업데이트
3. 그래픽 드라이버 업데이트 
[Intel] 드라이버 지원 프로그램 : https://www.intel.com/content/www/us/en/download-center/home.html
[AMD] 그래픽 드라이버 설치 페이지 : https://www.amd.com/support
[NVIDIA] 그래픽 드라이버 설치 페이지 : https://www.nvidia.co.kr/Download/index.aspx

4. PC 재부팅 (종료 옵션의 "다시 시작" 사용)
5. 새로운 인스톨러를 다운로드 받아 "EL Display Hub" 재설치
[EL Display Hub] 설치 페이지 : http://www.easynlight.com/en/twomonse/

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/en/supporttwomon/?faq=78

감사합니다.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1586] 오류코드 A0011001,A0011003
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

해당 문제의 경우 윈도우 11 업데이트 과정 중 "EL Dispay Hub"의 손상 혹은 디스플레이 드라이버와 충돌 문제일 수 있습니다.

이를 해결하기 위해 아래의 사항들을 조치해보십시오.
1. "EL Display Hub" 삭제
2. 윈도우 업데이트 확인 및 최신 윈도우로 업데이트
3. 그래픽 드라이버 업데이트 
[Intel] 드라이버 지원 프로그램 : https://www.intel.com/content/www/us/en/download-center/home.html
[AMD] 그래픽 드라이버 설치 페이지 : https://www.amd.com/support
[NVIDIA] 그래픽 드라이버 설치 페이지 : https://www.nvidia.co.kr/Download/index.aspx

4. PC 재부팅 (종료 옵션의 "다시 시작" 사용)
5. 새로운 인스톨러를 다운로드 받아 "EL Display Hub" 재설치
[EL Display Hub] 설치 페이지 : http://www.easynlight.com/en/twomonse/

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/en/supporttwomon/?faq=78

감사합니다.

Ea​​sy&Light 
```
