### ISSUE TITLE
아무 반응이 없습니다.

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1587]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:kangbs93@gmail.com<br><br>아이패드 프로 사용중입니다. 얼마전까지만 해도 잘 작동 됐었는데 이제 아무런 반응이 없습니다. 아이패드 어플에서도 분홍색 홈화면 그대로 이고 pc에서도 연결이 잡히지 않습니다. 급한대로 다른 어플 사용해봤는데 다른어플은 정상 작동하네요ㅜㅜ 그치만 성는은 투몬이 압도적이라 투몬 잃을수없습니다.<br><br>[EL_Display_0b299f45-6490-4c3e-abcd-787a5059b45d.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_0b299f45-6490-4c3e-abcd-787a5059b45d.zip)

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 

## 답변

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 타 프로그램과의 충돌 문제로 의심됩니다.

타 프로그램과의 충돌의 경우에는 주로 화면 공유 프로그램이나 화면 캡처 혹은 녹화 기능을 사용하는 프로그램 등과 충돌이 발생합니다. 

사용하시는 프로그램 중에서 해당 기능을 사용는 프로그램을 삭제 후 재부팅(종료 옵션의 "다시 시작" 사용)이후에 TwomonSE의 동작을 확인하여 주십시오.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

현재 보내주신 로그에는 PC로그만 존재하여 정확한 분석에 어려움이 있습니다. 

PC로그와 어플리케이션 측의 로그와 좀 더 자세한 증상을 설명해주신다면 정확하고 빠른 분석이 가능하니 
번거로우시더라도 PC로그와 어플리케이션 로그를 모두 보내주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1587] 아무 반응이 없습니다.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 타 프로그램과의 충돌 문제로 의심됩니다.

타 프로그램과의 충돌의 경우에는 주로 화면 공유 프로그램이나 화면 캡처 혹은 녹화 기능을 사용하는 프로그램 등과 충돌이 발생합니다.

사용하시는 프로그램 중에서 해당 기능을 사용는 프로그램과 Twomon SE를 삭제하신 후 재부팅(종료 옵션의 "다시 시작" 사용)이후에 TwomonSE를 재설치하여 동작을 확인하여 주십시오.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

현재 보내주신 로그에는 PC로그만 존재하여 정확한 분석에 어려움이 있습니다.

PC로그와 어플리케이션 측의 로그와 좀 더 자세한 증상을 설명해주신다면 정확하고 빠른 분석이 가능하니
번거로우시더라도 PC로그와 어플리케이션 로그를 모두 보내주시길 바랍니다.

[FAQ] 로그 취득 가이드 :
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light

```
