### ISSUE TITLE
Unable to connect wirelessly

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1591]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:pomponposh@gmail.com<br><br>I have the EasyCanvas Pro subscription for my iPad.I am able to use it as a second monitor when it is plugged into my PC (Windows) but when I unplug the iPad it no longer connects. I purchased the Pro version because I need to use my iPad wirelessly with my PC. Both devices are on the same WiFi network and EasyCanvas has permissions for Local Network, but it still cannot connect wirelessly.<br><br>[EL_Display_6942c975-16fa-426b-b2fa-41374f34b039.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_6942c975-16fa-426b-b2fa-41374f34b039.zip)

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 

## 답변

Hello, customer. We are an Easy&Light support team.

First of all, I apologize for the inconvenience.

After reviewing the logs and symptoms you sent, it seems that you are using VPN on your PC.

EasyCanvas cannot find a wirelessly connected tablet when using VPN.

Please try to connect wirelessly without using a VPN program.

If the problem does not improve even after proceeding with the above measures, please contact us again with a new PC log and application log.

Currently, only PC logs exist in the log you sent, so there is a difficulty in accurate analysis.

If you explain the PC log, the application log, and the symptoms in more detail, you can analyze them accurately and quickly
Please refer to the link below and send both the PC log and the application log even if it is inconvenient.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1591] Unable to connect wirelessly
```
#### 본문
```
Hello, customer. We are an Easy&Light support team.

First of all, I apologize for the inconvenience.

After reviewing the logs and symptoms you sent, it seems that you are using VPN on your PC.

EasyCanvas cannot find a wirelessly connected tablet when using VPN.

Please try to connect wirelessly without using a VPN program.

If the problem does not improve even after proceeding with the above measures, please contact us again with a new PC log and application log.

Currently, only PC logs exist in the log you sent, so there is a difficulty in accurate analysis.

If you explain the PC log, the application log, and the symptoms in more detail, you can analyze them accurately and quickly
Please refer to the link below and send both the PC log and the application log even if it is inconvenient.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.
```
