### ISSUE TITLE
black screen on my ipad

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1594]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:tianyangshao@gmail.com<br><br>when I connect my device (ipad) to my laptop through easycanvas. it's showing completing black on my ipad screen. Why is this happening. And how do I figure this out<br><br>[EL_Display_151c5d48-b086-4786-b6bd-57c539363db0.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_151c5d48-b086-4786-b6bd-57c539363db0.zip)

**Comment by AdamPark0030** [comment]
## 원인 파악

avcodec_open2() 호출 시 -542398533 리턴. 해당 오류코드는 "Generic error in an external library" 를 의미함.
OBS 포럼에서 해당 오류코드와 동일한 문제를 해결하는 방법을 안내할 수 있어보임.

https://obsproject.com/forum/threads/failed-to-open-nvenc-codec-generic-error-in-an-external-library-i-have-tried-everything.112568/

```
[2022-12-03 02:14:34.910][GENERAL:ERROR][6308:8280][bypd_proc_manager_create_codec_context:3901] encode_mode: 0x00000020, open error, ret: -542398533
[2022-12-03 02:14:34.910][GENERAL:ERROR][6308:8280][bypd_server_core_client_process_start_display_request:786] bypd_proc_manager_create_codec_context, ret: -542398533
```

**Comment by AdamPark0030** [comment]
## 답변

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

해당 문제의 경우 "EL Display Hub"의 손상 혹은 디스플레이 드라이버와 충돌 문제일 수 있습니다.

이를 해결하기 위해 아래의 사항들을 조치해보십시오.
1. "EL Display Hub" 삭제
2. 윈도우 업데이트 확인 및 최신 윈도우로 업데이트
3. 그래픽 드라이버 업데이트 
[Intel] 드라이버 지원 프로그램 : https://www.intel.com/content/www/us/en/download-center/home.html
[AMD] 그래픽 드라이버 설치 페이지 : https://www.amd.com/support
[NVIDIA] 그래픽 드라이버 설치 페이지 : https://www.nvidia.co.kr/Download/index.aspx

4. PC 재부팅 (종료 옵션의 "다시 시작" 사용)
5. 새로운 인스톨러를 다운로드 받아 "EL Display Hub" 재설치
[EL Display Hub] 설치 페이지 : http://www.easynlight.com/en/twomonse/

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

Ea​​sy&Light
