### ISSUE TITLE
업데이트 후 끊김

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#1595]
- 문의 날짜 : 2022년 12월 3일 오후 6시 12분
- 메일 주소 : daniel11021988@mitschang-manda.de

Hello.

Since updated to iPadOS 16 there is stuttering in the image. Tried it with 2 different strong gaming PCs.

Just try watching a Youtube Video with 60fps. It's not looking fluid like on a DisplayPort screen. But it did look fluid before the update.

Do you notice that as well and is there an update planned for the app?

Regards
Daniel

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello. We are an Easy & Light support team.

I'm sending this email for your inquiry.


Could you please send us the log file so our tech team can determine the exact problem?

If you make an inquiry through 'Inquiry' of the PC program, the log file is automatically attached. If the inquiry is not possible, you can manually extract the log file as shown below.



[Manual log collection procedure]

1. Enter Windows key > "Run" > Enter "msinfo32" > File > Save
2. Files existing in the path C:\ProgramData\devguru
3. A file existing in the path C:\Users\{username}\AppData\Local\Devguru (you can access the path with %localappdata%\Devguru)

[App log collection procedure]
　1. Android　　① Re-run the application on your device.　　② Tap on the app version at the bottom right of the main page about 10 times, then make sure a created log zip file named 'twomonse.log.archived.yyyymmddhhmmss.zip' in Download folder on your device.

　2. iOS　　① Connect the device to extract the logs to a PC.　　② Run iTunes and click it when the connected device appears on the upper tap.　　③ Click ‘File Sharing’ in the list to the left.　　④ Scroll down the updated screen and click the app (TwomonSE) to extract the log from the ‘App’ in the ‘File Sharing’ column. 　　⑤ Drag the log file at the bottom of ‘OOOO’s Documents' to each folder or desktop, 　　　　etc., or select the file and save it by clicking the ‘Save As’ button at the bottom right. 　　　


Please zip the all files and attach them.


Thank you.
Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

Attached are the log files.

I am not sure anymore whether the problem is due to the iPadOS 16 update, because I notice the same stuttering on another iPad as well which still has iPadOS 15. So maybe it has something to do with the Easy&Light Hub which replaced the TwomonSE app a while ago. I remember it working smoothly in the past long before that update.

This is how I test it and where I notice the stuttering most:

Watch the top circle in this video:
https://www.youtube.com/watch?v=_SzGQkI-IwM


[DMM log 01.zip](https://github.com/edh-git/EL_Display_Hub/files/10171916/DMM.log.01.zip)

**Comment by AdamPark0030** [comment]
## 원인파악

+ 해당 유저의 경우 화면 버벅임 현상으로 문의 한 것으로 보임.
+ proc 로그 중 destroy_filemap_context, dxgi_update_filemap_buffer 함수가 정상적으로 수행되지 않는 것으로 보임.
+ due Display, luminonCore IDDCX Adapter 설치되어 있음.

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
* 기존 수신 메일 답장으로 답변

#### 본문
```
Hello, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

As a result of reviewing the log and symptoms you sent, we found a conflict problem with other programs.

Conflicts can occur when used with screen-sharing programs or programs with screen capture or recording capabilities.

It appears that conflicts with "Duet Display" and "LuminonCore IDDCX Adapter" are occurring among the currently installed programs.
Delete "Duet Display", "Luminon Core IDDCX Adapter", and "EL Display Hub", reboot your PC (use the "Restart" option in the shutdown option), download the new installer and reinstall "EL Display Hub".

[Twomon SE] install link: http://www.easynlight.com/en/twomonse/

Also, please check if the performance mode option is set to the high performance in the EL Display Hub PC program.

If the problem does not improve even after proceeding with the above measures, please contact us again with a new PC log and application log.

Currently, only PC logs exist in the log you sent, so there is a difficulty in accurate analysis.
If you explain the PC log, the application log, and the symptoms in more detail, you can analyze them accurately and quickly
Please send both PC log and application log even if it is inconvenient.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporttwomon/?faq=78

Thank you.

Ea​​sy&Light
```

**Comment by AdamPark0030** [comment]
## 한글 원문

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

첨부해주신 유튜브 링크를 동일한 기기에서 확인한 결과 HDMI 또는 DP로 연결된 모니터에 비해 약간 튀는 현상이 있는것으로 확인되었습니다. 

해당 문제는 개발팀에 전달하여 개선 가능한지 확인 해보도록 하겠습니다.

감사합니다.

Ea​​sy&Light 

## 영문 번역

Hi, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

As a result of checking the YouTube link you attached on the same device, it was confirmed that there was a slight stand-out phenomenon compared to the monitor connected by HDMI or DP.

I will forward this issue to the development team to see if it can be improved.

Thank you.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1595] Easy&Light This is an answer to your question.
```
#### 본문
```
Hi, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

As a result of checking the YouTube link you attached on the same device, it was confirmed that there was a slight stand-out phenomenon compared to the monitor connected by HDMI or DP.

This problem has been the same since the past version, so I will send it to the development team to see if it can be improved.

Thank you.

Ea​​sy&Light
```
