### ISSUE TITLE
Can´t connect via wifi

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1600]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:alexandre.vieira@ceiia.pt<br><br>I connect with the usb and with the same wifi network but when i pull out the usb the connection fails<br><br>[EL_Display_67fc1a24-de26-412a-b58a-cda2003c291c.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_67fc1a24-de26-412a-b58a-cda2003c291c.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1600] Can´t connect via wifi
```
#### 본문
```
Hello, customer. We are an Easy&Light support team.

First of all, I apologize for the inconvenience.

After reviewing the logs and symptoms you sent, it seems that you are using VPN on your PC.

EasyCanvas cannot find a wirelessly connected tablet when using VPN.

Please try to connect wirelessly without using a VPN program.

If the problem does not improve even after proceeding with the above measures, please contact us again with a new PC log and application log.

Thank you.

Ea​​sy&Light
```
