### ISSUE TITLE
Hope it improves motion blur

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1601]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:1403449402@qq.com<br><br>Hello, I like your software very much, but I found a problem in the process of using it, that is, the image will be blurred when the window is dragged, which is very unfriendly to text expansion, and clarity is necessary, so it cannot Come on, my computer configuration is enough to run this software, maybe I can set the refresh rate by myself to keep the picture stable? I very much hope that you and the team can solve this problem, and wish the product better and better<br><br>[EL_Display_0e3bab86-6cb3-4cb4-9db7-6ac494ca6506.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_0e3bab86-6cb3-4cb4-9db7-6ac494ca6506.zip)

**Comment by AdamPark0030** [comment]
## 원인 분석

+ 해당 유저의 경우 앱 측에서 윈도우창을 드래그 할 경우 블러 현상이 발생하는 것처럼 보인다고 함.
+ 화면 주사율을 직접 선택 할 수 있는 기능 추가 요청

+ 로그상으로 client_state 검색 시 모두 DISCONNECTED 로그만 남아있음. 초기화, 연결 중, 연결완료 로그가 없음

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 

아래의 내용으로 답변 부탁드립니다.
+ 별도 주사율 선택 기능은 제공하지 않음.
+ client_state의 이상 현상으로 인해 재설치 요구

## 답변

Hi, customer. We are an Easy&Light support team.

After checking your symptoms, it seems that the program was not installed properly.

If you experience the same symptoms after reinstalling the program,
Please refer to the link below and reply with the log of the PC and application to check the exact symptoms.

In addition, the current EL Display Hub program has three options for choosing the current injection rate.

[EL Display Hub > Options > Performance Mode]
High Performance : 60 FPS
Medium Performance : 45 FPS
Low Performance : 30 FPS

I'm sorry, but we don't plan to add a function that allows you to select the injection rate separately. Please use the above options.

Thank you.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1601] Hope it improves motion blur
```
#### 본문
```
Hello, customer. We are an Easy&Light support team.

After checking your symptoms, it seems that the program was not installed properly.

If you experience the same symptoms after reinstalling the program,
Please refer to the link below and reply with the log of the PC and application to check the exact symptoms.

In addition, the current EL Display Hub program has three options for choosing the current injection rate.

[EL Display Hub > Options > Performance Mode]
High Performance : 60 FPS
Medium Performance : 45 FPS
Low Performance : 30 FPS

I'm sorry, but we don't plan to add a function that allows you to select the injection rate separately. Please use the above options.

Thank you.

Ea​​sy&Light
```

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 

## 답변

Hello, customer. We are an Easy & Light's support team.

The performance mode option affects only fps.

For resolution, you can set it through the "Resolution" option.

Thank you.

Easy and Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1601] Hope it improves motion blur
```
#### 본문
```
Hello, customer. We are an Easy & Light's support team.

The performance mode option affects only fps.

For resolution, you can set it through the "Resolution" option.

Thank you.

Easy and Light
```
