### ISSUE TITLE
Cannot connect Ipad pro to PC

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1605]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:thorntonhough@googlemail.com<br><br>I have reinstall and rebboted many times, tried three cables and differend usb sockets.  The HID devices are installed and working.  But   NO devices are connected<br><br>[EL_Display_3b966943-370e-452b-83bf-01e8fbb127a6.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_3b966943-370e-452b-83bf-01e8fbb127a6.zip)

**Comment by Sienna-lee** [comment]
해당 사용자가 문제가 해결되었다고 하여 이슈를 종료합니다.

#1606
