### ISSUE TITLE
필압관련 질문

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1615]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:jako1968@naver.com<br><br>안녕하세요 아이패드로 이지 캔버스 사용해보려고 설치했는데요 연결은 문제없이 되지만 포토샵 내에서 필압이 하나도 안먹어서 문의드립니다. 예를 들어, 포토샵 파일 내에 PSUserConfing 파일 안에 0을 1로 바꾸는 거라던가 인터넷 검색해서 해보라는 거 다 해봤는데 변한게 없네요 해결 방법 알려주시면 감사하겠습니다.<br><br>[EL_Display_ae337e53-f6b7-4d06-96d9-958e82027582.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_ae337e53-f6b7-4d06-96d9-958e82027582.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1615] 필압관련 질문
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

필압 적용의 경우 파일 경로 및 파일 명, 텍스트 파일의 내용에 오타가 있을 경우 정상 동작하지 않습니다.

파일명의 경우 "PSUserConfig.txt", 파일 내용의 경우 "UseSystemStylus 1" 두가지 값이 정확히 일치하는지 한번 더 확인 부탁드립니다.

[FAQ] 드로잉 프로그램에서 Apple Pencil의 필압 입력이 동작하지 않음 : http://www.easynlight.com/supporteasycanvas/?faq=118

또한, 이지캔버스의 경우 애플펜슬만 정식으로 지원하고 있습니다.

다른 써드파티 펜슬 사용 시 필압이 동작하지 않을 수 있습니다.

이 점 참고 부탁드립니다.

위 조치 사항을 취해도 동일한 문제가 발생하는 경우에는 아래의 로그 취득 가이드를 참조하여 어플리케이션 로그와 함께 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

Ea​​sy&Light 
```
