### ISSUE TITLE
마우스 아이콘만 표시

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#1619]
- 문의 날짜 : 2022년 12월 16일 오후 11시 42분
- 메일 주소 : kcamel@live.cn

Title: ipad2 can only see the mouse icon

Questions: When I use ipad to connect to PC, it can only display a \"mouse Icon\", please help to solve it. Thank you very much.

[[EasyCanvas_-_Windows]_ipad2_can_only_see_the_mouse_icon.zip](https://github.com/edh-git/EL_Display_Hub/files/10255072/EasyCanvas_-_Windows._ipad2_can_only_see_the_mouse_icon.zip)

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 
## 답변

Hello, customer. We are an Easy&Light support team.

First of all, I apologize for the inconvenience.

The device is identified as an IOS version that is not supported by Easy Canvas.

Please use it on apps that use iOS 12.2 or higher.

Thank you.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Easycanvas - 1619] ipad2 can only see the mouse icon
```
#### 본문
```
Hello, customer. We are an Easy&Light support team.

First of all, I apologize for the inconvenience.

The device is identified as an IOS version that is not supported by Easy Canvas.

Please use it on apps that use iOS 12.2 or higher.

Thank you.

Ea​​sy&Light
```

**Comment by RachelOh** [comment]
2023.2.12. 오후 5:40
---
Thank you for replied.
I've got it... And just an advise, because many people have old version IPad, and if your software can support, it will get more customer.

**Comment by RachelOh** [comment]
아래와 같이 답변
---
Hello, customer. We are an Easy & Light support team.

Thank you for your opinion and we will do our best for a better program.

Have a nice day.


Easy&Light
