### ISSUE TITLE
프로그램 아이콘 보이지 않음

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#1626]
- 문의 날짜 : 2022년 12월 21일 오후 4시 40분
- 메일 주소 : rararasup@gmail.com

제목: 문의시도 4일째

문의사항: 캡쳐참조 바탕화면은 나오는데 프로그램이 일절 안나옴
기능문제로 하니까 로그파일 넣으라고 그러는데
ipad로그는 힘들게 추출해서 넣었는데
pc는 어쩌라는건지도 모르겠고
프로그램내 문의도 웬종일 로그 추출하고있고
사실상 이거때문에 패드 샀는데 문의도 힘들고 짜증나고 무슨짓인가싶음
로그파일 추출한다고 웬종일 저러고있음

[[EasyCanvas - Windows] 문의시도 4일째.zip](https://github.com/edh-git/EL_Display_Hub/files/10275670/EasyCanvas.-.Windows.4.zip)

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 
## 답변
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님. PC 로그의 경우 EL Display Hub PC 프로그램 내에서 자동으로 수집하도록 되어 있으나, 해당 기능이 정상적으로 동작하지 않아 문의에 어려움을 겪으신 것 같습니다.

그러나, PC 로그 없이는 정확한 증상을 파악하기 어렵습니다. 죄송하지만 아래의 절차를 따라서 로그를 수동 수집하여 전송해주시면 최대한 빠르게 문제를 분석할 수 있도록 하겠습니다.

[로그 수동 수집 절차]

1. Windows키 입력 > "실행" > "msinfo32" 입력 > 파일 > 저장

2. C:\ProgramData\devguru 경로에 존재하는 파일

3. C:\Users\{사용자명}\AppData\Local\Devguru 경로에 존재하는 파일 ( %localappdata%\Devguru  로 경로에 접근 가능)

세 군데의 파일들을 압축하여 첨부해주세요.

다시한번 이용에 불편을 드려 죄송합니다.

감사합니다.

Easy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1626] 프로그램 아이콘 보이지 않음
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님. PC 로그의 경우 EL Display Hub PC 프로그램 내에서 자동으로 수집하도록 되어 있으나, 해당 기능이 정상적으로 동작하지 않아 문의에 어려움을 겪으신 것 같습니다.

그러나, PC 로그 없이는 정확한 증상을 파악하기 어렵습니다. 죄송하지만 아래의 절차를 따라서 로그를 수동 수집하여 전송해주시면 최대한 빠르게 문제를 분석할 수 있도록 하겠습니다.

[로그 수동 수집 절차]

Windows키 입력 > "실행" > "msinfo32" 입력 > 파일 > 저장

C:\ProgramData\devguru 경로에 존재하는 파일

C:\Users{사용자명}\AppData\Local\Devguru 경로에 존재하는 파일 ( %localappdata%\Devguru 로 경로에 접근 가능)

세 군데의 파일들을 압축하여 첨부해주세요.

다시한번 이용에 불편을 드려 죄송합니다.

감사합니다.

Easy&Light
```

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Windows키 입력 > "실행" > "msinfo32" 입력 > 파일 > 저장 < 이건 폴더가 아니고 뭔가 이상한게 뜨던데

C:\ProgramData\devguru 경로에 존재하는 파일  < 이거랑

C:\Users{사용자명}\AppData\Local\Devguru 경로에 존재하는 파일 ( %localappdata%\Devguru 로 경로에 접근 가능) <이것만 압축해서 보내드립니다

zip밖에 따로있는 로그파일은 현재 추출할수 있는 아이패드 로그파일입니다.
이걸로도 안되면 할수 없고요

현재 문제인건 4k해상도 작업용pc인데 바탕화면만 보이고 프로그램이 폴더조차 안보이는데요.
세로화면이라 그런가 싶어서 돌려도 봤고 커서가 오락가락하는게 어쩐지 추가화면으로 인식하는것같기도하고
문서용 저사양 노트북으로 하니까 보이더라고요. 이걸로 그림그릴순 없어서 보이나안보이나 테스트만 해봤습니다.

아무튼 로그파일 뽑을수있는건 다 뽑아봤으니 잘부탁드립니다.

[Re_ [Twomon SE - 1626] 프로그램 아이콘 보이지 않음.zip](https://github.com/edh-git/EL_Display_Hub/files/10302431/Re_.Twomon.SE.-.1626.zip)

**Comment by AdamPark0030** [comment]
## 답변

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

현재 EasyCanvas를 확장 화면모드로 사용하고 계신것으로 보입니다. 

바탕화면은 보이지만 프로그램 아이콘이 확장 화면으로 표시가 되지 않을 경우 연결된 메인 디스플레이에서 끌어서 확장 디스플레이에 놓으시면 됩니다. 

메인 디스플레이 화면을 복제하여 사용하고 싶으신 경우 EasyCanvas를 실행하여 PC와 연결 후 PC의 EL Display Hub 프로그램의 옵션 설정 > 화면 선택 메뉴를 선택하여 복제하고자 하는 모니터의 이름을 선택하시면 됩니다.

문제가 지속되면 다시 문의해주시길 바랍니다.

감사합니다.

Easy&Light
