### ISSUE TITLE
Cannot get program to connect

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1627]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:batcubed@gmail.com<br><br>Hello! As it says, I can't get the program to connect. I've attempted uninstalling, reinstalling, and restarting multiple times, as recommended, but the ipad app says &quot;Waiting for Connection...&quot; and the computer app says no device connected, even though the PC recognizes the ipad being plugged in. Please help!<br><br>[EL_Display_ee48adf6-e734-4e5c-891f-3e7ea91853e3.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_ee48adf6-e734-4e5c-891f-3e7ea91853e3.zip)

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 
## 한글 원문

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 USB포트의 전력 부족 혹은 연결 불량 문제로 의심됩니다.

"화면 전송"은 USB를 통해 처리되는 데이터의 양이 많아서, PC와 디바이스 간의 연결이 정상적으로 보여도 실제 통신에는 실패할 수 있습니다.

이를 해결하기 위해 아래의 사항들을 조치해보십시오.
1. PC와 태블릿 간의 연결이 정상적인지 확인합니다.
2. USB 케이블 교체(가능한 정품 케이블 사용)합니다.
3. PC에 연결된 USB 포트 변경(후면 포트 이용)합니다.
4. 외부전원 USB 허브에 연결합니다.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

현재 보내주신 로그에는 PC로그만 존재하여 정확한 분석에 어려움이 있습니다. 
PC로그와 어플리케이션 측의 로그와 좀 더 자세한 증상을 설명해주신다면 정확하고 빠른 분석이 가능하니 
번거로우시더라도 PC로그와 어플리케이션 로그를 모두 보내주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/en/supporteasycanvas/?faq=54

감사합니다.

Ea​​sy&Light 


## 영문 번역

Hi, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

As a result of reviewing the logs and symptoms you sent, it is suspected that the USB port has insufficient power or poor connection.

"Screen Transfer" has a large amount of data processed over USB, so even if the connection between the PC and the device appears normal, actual communication may fail.

Please take the following steps to resolve this issue.
1. Verify that the connection between the PC and the tablet is normal.
2. Replace the USB cable (use a genuine cable if possible).
3. Change the USB port connected to the PC (using the rear port).
4. Connect to the external power USB hub.

If the problem does not improve even after proceeding with the above measures, please contact us again with a new PC log and application log.

Currently, only PC logs exist in the log you sent, so there is a difficulty in accurate analysis.
If you explain the PC log, the application log, and the symptoms in more detail, you can analyze them accurately and quickly
Please send both PC log and application log even if it is inconvenient.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Easycanvas - 1627] Cannot get program to connect
```
#### 본문
```
Hi, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

As a result of reviewing the logs and symptoms you sent, it is suspected that the USB port has insufficient power or poor connection.

"Screen Transfer" has a large amount of data processed over USB, so even if the connection between the PC and the device appears normal, actual communication may fail.

Please take the following steps to resolve this issue.

  1. Verify that the connection between the PC and the tablet is normal.
  2. Replace the USB cable (use a genuine cable if possible).
  3. Change the USB port connected to the PC (using the rear port).
  4. Connect to the external power USB hub.

If the problem does not improve even after proceeding with the above measures, please contact us again with a new PC log and application log.

Currently, only PC logs exist in the log you sent, so there is a difficulty in accurate analysis.
If you explain the PC log, the application log, and the symptoms in more detail, you can analyze them accurately and quickly
Please send both PC log and application log even if it is inconvenient.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Ea​​sy&Light
```
