### ISSUE TITLE
화면캡쳐에 실패하였습니다 오류 어떻게 해결하나요

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1628]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:dksdbsdnr@naver.com<br><br>재부팅부터 어플및 프로그램 재설치까지 해봤는데 자꾸 뜹니다. 무슨원인인지 찾아도 안나오고 답답하네요. 해결방법좀 알려주세요<br><br>[EL_Display_0f60a1b2-b3fc-48ec-b5ff-7be649905048.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_0f60a1b2-b3fc-48ec-b5ff-7be649905048.zip)

**Comment by AdamPark0030** [comment]
## 원인파악

+ Aqua N player 설치되어 있는데, 설치된 상태에서 동작 확인

http://www.ybmnet.co.kr/center_2014/faqList.asp?strWord1=20&strWord2=3&strWoard=&intPage=1 링크에서 Aqua N Player 설치 후 성공적으로 연결 확인 함.

+ AMD driver 기능 중 녹화 기능이 캡쳐에 영향을 줄 수 있는지 (relive)


+ 외부 보안툴의 동작으로 인해 함수 콜이 실패
예: win32 api (user32 dll hook) 의 동작을 막는 필터가 있을 경우

미니덤프 파일에서 발견된 크래시 현상에 Uncharted Waters Origin (대항해시대) 게임이 개입한 흔적이 있음.
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/73160679/209769866-a2d583ab-81e4-4577-96a2-03cc6890bf8b.png)

**Comment by AdamPark0030** [comment]
## 답변

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

아래와 같은 사항을 점검해주세요.

1. 그래픽 카드 드라이버를 재설치 해보세요.
2. Uncharted Waters Origin 프로그램이 실행중일 때 문제가 발생하는지 확인 해주세요.

위와 같은 조치사항을 취하신 후 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

현재 보내주신 로그에는 PC로그만 존재하여 정확한 분석에 어려움이 있습니다. 
PC로그와 어플리케이션 측의 로그와 좀 더 자세한 증상을 설명해주신다면 정확하고 빠른 분석이 가능하니 
번거로우시더라도 아래의 링크를 참조하셔서 PC로그와 어플리케이션 로그를 모두 보내주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light
