### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1631]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:akmal9695@gmail.com<br><br>how to connect? i just follow tutorial but still waiting for connection<br><br>[EL_Display_824660a3-37ad-48f3-8153-fdafcacee78a.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_824660a3-37ad-48f3-8153-fdafcacee78a.zip)

**Comment by AdamPark0030** [comment]
## 원인파악

1. 전력부족 현상이 있어 보임.
2. EDID를 찾지 못함
3. 연결 이력 있음.

**Comment by AdamPark0030** [comment]
## 답변

Hi, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

As a result of reviewing the logs and symptoms you sent, it is suspected that the USB port has insufficient power or poor connection.

"Screen Transfer" has a large amount of data processed over USB, so even if the connection between the PC and the device appears normal, actual communication may fail.

Please take the following steps to resolve this issue.
1. Verify that the connection between the PC and the tablet is normal.
2. Replace the USB cable (use a genuine cable if possible).
3. Change the USB port connected to the PC (using the rear port).
4. Connect to the external power USB hub.

If the problem does not improve even after proceeding with the above measures, please contact us again with a new PC log and application log.

Currently, only PC logs exist in the log you sent, so there is a difficulty in accurate analysis.
If you explain the PC log, the application log, and the symptoms in more detail, you can analyze them accurately and quickly
Please send both PC log and application log even if it is inconvenient.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Ea​​sy&Light
