### ISSUE TITLE
ipad插上以后显示Bonjour服务无法启动

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1634]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:shuqi_wang@outlook.com<br><br>如题，没法用<br><br>[EL_Display_d8c52efa-844c-44ba-9a8e-c10c6008ebd0.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_d8c52efa-844c-44ba-9a8e-c10c6008ebd0.zip)

**Comment by AdamPark0030** [comment]
## 아래의 내용으로 답변 완료

```
RE:[EasyCanvas - 1634] ipad插上以后显示Bonjour服务无法启动
```

Hi, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

After reviewing the logs you sent me, it seems that some of the programs did not work properly.

In the case of Easycanvs, the "Bonjour Service" is used to connect to the iPad wirelessly, but it seems that the program is not working properly on your PC.

If this is a temporary error, you can resolve it by rebooting the PC (restarting the shutdown option).

If it is not resolved by a temporary solution, reinstalling the program will resolve it, and the installer may be damaged, so please download a new installer and proceed with the reinstallation.
1. Delete the EL Display Hub.
2. Reboot your PC. (Use "Restart" in the Shutdown option)
3. Reinstall the latest EL Display Hub installer.
[EL Display Hub] 설치 링크 : http://www.easynlight.com/en/easycanvas/
4. Reinstall the EL Display Hub.

If the problem does not improve even after proceeding with the above measures, please contact us again with a new PC log and application log.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.
