### ISSUE TITLE
컴퓨터에는 아이패드 인식되는데 아이패드에 화면이 안 뜹니다

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1637]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:sazz1114@naver.com<br><br>상기 내용과 같습니다 빠른 해결 부탁드립니다<br><br>[EL_Display_c708ae88-d0f4-4117-93ed-6f207a23b98e.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_c708ae88-d0f4-4117-93ed-6f207a23b98e.zip)

**Comment by AdamPark0030** [comment]
## 원인 파악

+ 충돌 발생 프로그램 설치 : Splashtop Wired XDisplay
+ 연결이력 없음

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 
## 답변

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

보내주신 로그와 증상을 검토한 결과, 타 프로그램과의 충돌 문제를 발견하였습니다.

화면 공유 프로그램이나 화면 캡처 혹은 녹화 기능이 있는 프로그램과 함께 사용할 경우 충돌이 발생할 수 있습니다.

현재 설치된 프로그램 중 "Splashtop Wired XDisplay"와 충돌이 발생하는 것으로 보입니다. 
"Splashtop Wired XDisplay"와 "EL Display Hub"를 삭제하신 뒤 PC를 재부팅(종료 옵션의 "다시 시작" 옵션 사용)한 뒤 새로운 인스톨러를 다운로드 받아 "EL Display Hub"를 재설치하여 주십시오.

[Twomon SE] 설치 페이지 : http://www.easynlight.com/twomonse/


위와 같은 조치사항들을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

현재 보내주신 로그에는 PC로그만 존재하여 정확한 분석에 어려움이 있습니다. 
PC로그와 어플리케이션 측의 로그와 좀 더 자세한 증상을 설명해주신다면 정확하고 빠른 분석이 가능하니 
번거로우시더라도 PC로그와 어플리케이션 로그를 모두 보내주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
 http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1637] 컴퓨터에는 아이패드 인식되는데 아이패드에 화면이 안 뜹니다
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

보내주신 로그와 증상을 검토한 결과, 타 프로그램과의 충돌 문제를 발견하였습니다.

화면 공유 프로그램이나 화면 캡처 혹은 녹화 기능이 있는 프로그램과 함께 사용할 경우 충돌이 발생할 수 있습니다.

현재 설치된 프로그램 중 "Splashtop Wired XDisplay"와 충돌이 발생하는 것으로 보입니다.
"Splashtop Wired XDisplay"와 "EL Display Hub"를 삭제하신 뒤 PC를 재부팅(종료 옵션의 "다시 시작" 옵션 사용)한 뒤 새로운 인스톨러를 다운로드 받아 "EL Display Hub"를 재설치하여 주십시오.

[Twomon SE] 설치 페이지 : http://www.easynlight.com/twomonse/

위와 같은 조치사항들을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

현재 보내주신 로그에는 PC로그만 존재하여 정확한 분석에 어려움이 있습니다.
PC로그와 어플리케이션 측의 로그와 좀 더 자세한 증상을 설명해주신다면 정확하고 빠른 분석이 가능하니
번거로우시더라도 PC로그와 어플리케이션 로그를 모두 보내주시길 바랍니다.

[FAQ] 로그 취득 가이드 :
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light
```
