### ISSUE TITLE
How do I use ipad as a drawing tablet?

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1638]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:patrickariasvfx@gmail.com<br><br>Above<br><br>[EL_Display_8f1cea57-64c4-4eca-8503-a026411b655e.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_8f1cea57-64c4-4eca-8503-a026411b655e.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, We're Easy&Light support team.

I'm sending this email for your inquiry.


After installing PC programs and apps on your PC and tablet, connect them using a USB cable.

Please refer to the link for details on how to use it.


https://www.youtube.com/watch?v=21jjQMJb-w0


For wireless connection, it must be wired for the first time.


If you cannot connect, please contact us again.

thank you



  Easy & Light
