### ISSUE TITLE
실행이 안 됩니다

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1639]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:jheum7@gmail.com<br><br>3주 정도 안 쓰다가 다시 연결했더니 아예 프로그램 실행이 안 됩니다.<br><br>[EL_Display_a5f5bcc3-e55c-4ee3-84b7-e8a0f7e9cda1.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_a5f5bcc3-e55c-4ee3-84b7-e8a0f7e9cda1.zip)

**Comment by AdamPark0030** [comment]
## 원인 파악

+ 정상동작하던 시기의 로그가 지워진 상태. 재설치 안내 후 동일 증상 발생 시 로그 재요청

**Comment by AdamPark0030** [comment]
## 답변

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

현재 과거의 연결 이력이 로그파일에 존재하지 않아, 정확한 원인 분석이 어렵습니다.

우선 아래의 조치를 취해보세요.

1. "EL Display Hub" 를 삭제하신 뒤 PC를 재부팅(종료 옵션의 "다시 시작" 옵션 사용)한 뒤 새로운 인스톨러를 다운로드 받아 "EL Display Hub"를 재설치하여 주십시오.
[EL Display Hub] 설치 페이지 : http://www.easynlight.com/twomonse/

2. PC와 태블릿 간의 연결이 정상적인지 확인
  1. PC와 태블릿 간의 연결이 정상적인지 확인합니다.
  2. USB 케이블 교체(가능한 정품 케이블 사용,  데이터 통신이 가능한 케이블 사용)합니다.
  3. PC에 연결된 USB 포트 변경(후면 포트 이용)합니다.
  4. 외부전원 USB 허브에 연결합니다.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

현재 보내주신 로그에는 PC로그만 존재하여 정확한 분석에 어려움이 있습니다. 
PC로그와 어플리케이션 측의 로그와 좀 더 자세한 증상을 설명해주신다면 정확하고 빠른 분석이 가능하니 
번거로우시더라도 아래의 링크를 참조하셔서 PC로그와 어플리케이션 로그를 모두 보내주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1639] 실행이 안 됩니다
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

현재 과거의 연결 이력이 로그파일에 존재하지 않아, 정확한 원인 분석이 어렵습니다.

우선 아래의 조치를 취해보세요.

1. "EL Display Hub" 를 삭제하신 뒤 PC를 재부팅(종료 옵션의 "다시 시작" 옵션 사용)한 뒤 새로운 인스톨러를 다운로드 받아 "EL Display Hub"를 재설치하여 주십시오.
[EL Display Hub] 설치 페이지 : http://www.easynlight.com/twomonse/

2. PC와 태블릿 간의 연결이 정상적인지 확인
    1. PC와 태블릿 간의 연결이 정상적인지 확인합니다.
    2. USB 케이블 교체(가능한 정품 케이블 사용,  데이터 통신이 가능한 케이블 사용)합니다.
    3. PC에 연결된 USB 포트 변경(후면 포트 이용)합니다.
    4. 외부전원 USB 허브에 연결합니다.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

현재 보내주신 로그에는 PC로그만 존재하여 정확한 분석에 어려움이 있습니다. 
PC로그와 어플리케이션 측의 로그와 좀 더 자세한 증상을 설명해주신다면 정확하고 빠른 분석이 가능하니 
번거로우시더라도 아래의 링크를 참조하셔서 PC로그와 어플리케이션 로그를 모두 보내주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light 
```
