### ISSUE TITLE
Easycanvas is not working in my ipad.

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1640]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:artsachingarg@gmail.com<br><br>Easy Canvas is not working in iPad. I tried many times but it is giving blank screen.<br><br>[EL_Display_4838598c-e9f7-4098-805d-5eaf46c37bce.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_4838598c-e9f7-4098-805d-5eaf46c37bce.zip)

**Comment by AdamPark0030** [comment]
## 답변

Hi, customer. Easy&Light support team.

First of all, I apologize for the inconvenience.

As a result of reviewing the logs and symptoms you sent, it is suspected that the USB port has insufficient power or poor connection.

"Screen Transfer" has a large amount of data processed over USB, so even if the connection between the PC and the device appears normal, actual communication may fail.

Please take the following steps to resolve this issue.

Verify that the connection between the PC and the tablet is normal.
Replace the USB cable (use a genuine cable if possible).
Change the USB port connected to the PC (using the rear port).
Connect to the external power USB hub.
If the problem does not improve even after proceeding with the above measures, please contact us again with a new PC log and application log.

Currently, only PC logs exist in the log you sent, so there is a difficulty in accurate analysis.
If you explain the PC log, the application log, and the symptoms in more detail, you can analyze them accurately and quickly
Please send both PC log and application log even if it is inconvenient.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Easycanvas - 1640] Easycanvas is not working in my ipad.
```
#### 본문
```
Hello customer, this is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

It seems that the problem is caused by not being able to get screen information from the display you are using.

If the problem persists even after reinstalling the PC program, please test using another monitor.

If you are having difficulty using it due to the problem, please refer to the procedure below and apply for a refund.

[How to get a refund]

1. App Store for iOS
We'd like to give you a refund but we are not in charge of the refund. We'll let you know how to get the refund from the iTunes store. Please refer to the following websites.

Contact Apple Support:
https://reportaproblem.apple.com/

How to get a refund from the iTunes store:
https://support.apple.com/en-us/HT204084

2. Google play store for Android
Please click the following link, fill out and submit a refund request form.
https://docs.google.com/a/devguru.co.kr/forms/d/1E2gdzCg8n09lwe2vFKG8tgcb5Ip082np8S_OXHf7q7g

I will try to make a better program.

Thank you.

Easy&Light
```
