### ISSUE TITLE
손쉬운 사용에 추가 했는데도 애플펜슬이 안먹혀요

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1647]
Product:EasyCanvas

Device OS:iOS

e-mail:[astraea7@naver.com](mailto:astraea7@naver.com)

윈도우 컴퓨터에서 아주 잘 사용하다가 맥으로 넘어오면서 새롭게 프로그램을 다운받았는데요, 맥에서는 EL display Hub 가 아니고 다른 프로그램이더라구요. 잘 받아서 실행했는데
연결도 되고, 아이패드에서 펜슬로 움직이면 모니터의 마우스도 따라 움직이는 것 까지는 돼요.
그런데 글씨나 그림이 전혀 안써집니다. ( 터치하면 클릭 되는 것도 안먹혀요) 그저 마우스 움직이는 것만 되는데...
이 사이트에서 찾아보니 손쉬운 사용에 추가 하는 방법이 있어서 그렇게 다 해보았는데도 여전히 같은 상황입니다. 수업때 잘 활용중인데 지금 너무 불편해요.
빠른 해결 답변 부탁드려요.

[EasyCanvas_20230105_1637551.zip](https://github.com/edh-git/EL_Display_Hub/files/10356206/EasyCanvas_20230105_1637551.zip)
[EasyCanvas_20230105_163755.zip](https://github.com/edh-git/EL_Display_Hub/files/10356208/EasyCanvas_20230105_163755.zip)

**Comment by james-kim-Devguru** [comment]
검토중

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1647] 손쉬운 사용에 추가 했는데도 애플펜슬이 안먹혀요
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

현재 이지캔버스에서 지원하는 스타일러스 펜은 다음과 같습니다.
- 아이패드 : 애플펜슬 1, 2

이지캔버스는 정품 애플펜슬만을 지원하고 있으며 만약 써드파티 펜을 사용하고 계시다면 정상동작 하지 않을 수 있습니다.


위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 아래의 로그 취득 가이드를 참조하여
'어플리케이션 로그'와 함께 재문의 부탁드립니다.

[FAQ] PC 및 어플리케이션 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
