### ISSUE TITLE
모니터 확장이 안되네요

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1648]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:ljh5566@kakao.com<br><br>모니터 복제만 되고 확장이 안되네요 확장을  클릭해도 잠깐 깜빡일뿐  작동 안합니다.<br><br>[EL_Display_68811864-98d7-453c-bb29-f254b263d0e4.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_68811864-98d7-453c-bb29-f254b263d0e4.zip)

**Comment by james-kim-Devguru** [comment]
검토중
