### ISSUE TITLE
Twomon SE Virtual HID Bus 드라이버가 PC에 없음

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1649]
Product:Twomon SE

Device OS:Android

e-mail:[kschoi33@daegu.ac.kr](mailto:kschoi33@daegu.ac.kr)

PC프로그램 EL Display Hub가 작동되지 않음. 작업관리자에서 Twomon SE Virtual HID Bus 드라이버를 찾았으나 없음.

[TwomonSE.log.archived.202301062308131.zip](https://github.com/edh-git/EL_Display_Hub/files/10369684/TwomonSE.log.archived.202301062308131.zip)
[TwomonSE.log.archived.20230106230813.zip](https://github.com/edh-git/EL_Display_Hub/files/10369685/TwomonSE.log.archived.20230106230813.zip)

**Comment by AdamPark0030** [comment]
+ PC 프로그램 로그 누락

**Comment by AdamPark0030** [comment]
@james-kim-Devguru 
## 답변
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저 이용에 불편을 드려 죄송합니다.

현재 PC 프로그램 로그가 누락되어 정확한 원인을 판단하기 어렵습니다.

우선 프로그램 재설치를 진행하여보시고 동일 증상이 발생한다면 

정확한 증상 확인을 위해 아래 링크를 참조해 PC 및 어플리케이션의 로그를 첨부하여 회신해주시기 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1649] Twomon SE Virtual HID Bus 드라이버가 PC에 없음
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

현재 PC 프로그램 로그가 누락되어 정확한 원인을 판단하기 어렵습니다.
드라이버가 존재하지 않는 것으로 보아, PC 프로그램이 정상적으로 설치되지 않은 것으로 보입니다.
프로그램 재설치를 진행하여보시고 동일 증상이 발생한다면
연결이 되지 않을 경우의 일반적인 사항을 검토하여 주십시오.

우선 아래 링크의 중간 동영상(Twomon SE 사용 동영상)을 참조하여 태블릿과 PC의 연결을 확인하여 주십시오.
[Twomon SE] 제품 소개 페이지 : http://www.easynlight.com/twomonse/

정상적으로 연결되지 않았을 경우에는 아래와 같은 사항을 점검하여 주십시오.

첫 번째로 USB포트의 전력 부족 혹은 연결 불량 문제일 수 있습니다.
이를 해결하기 위해 아래의 사항들을 조치해보십시오.
1. PC와 태블릿 간의 연결이 정상적인지 확인합니다.
2. USB 케이블 교체(가능한 정품 케이블 사용,  데이터 통신이 가능한 케이블 사용)합니다.
3. PC에 연결된 USB 포트 변경(후면 포트 이용)합니다.
4. 외부전원 USB 허브에 연결합니다.

두 번째로 PC측과 태블릿 측의 오류일 수 있습니다.
1. PC를 재부팅하여 주십시오. (종료 옵션의 "다시 시작" 사용)
2. 태블릿을 재부팅하여 주십시오.


위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 아래의 로그 취득 가이드를 참조하여 재문의 부탁드립니다.

[FAQ] PC 및 어플리케이션 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
