### ISSUE TITLE
twomon se 를 사용해서 디즈니 플러스 볼려고하는데

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1654]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:native35332@naver.com<br><br>화면이 안나옵니다.. 다른 것은 다 나오는데 어떻게 해야하나요?<br><br>[EL_Display_9ad729f0-e921-415d-8003-dc88e6d9e0e6.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_9ad729f0-e921-415d-8003-dc88e6d9e0e6.zip)

**Comment by RachelOh** [comment]
아래와 같이 답변
----
안녕하세요 고객님. Easy&Light 지원팀입니다.

"Twomon SE"의 경우 사용하시는 프로그램 혹은 사이트에서 화면 복제 및 캡처 방지가 되어있는 경우에는 

화면 복제에 실패하거나 화면 이미지 획득에 실패할 수 있습니다.

이용에 참조 부탁드립니다.


감사합니다.

Easy&Light
