### ISSUE TITLE
没声音

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1656]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:aboutme7732396@gmail.com<br><br>有显示但没声音<br><br>[EL_Display_7748b287-f29b-4900-acec-249e0aa0e3e0.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_7748b287-f29b-4900-acec-249e0aa0e3e0.zip)

**Comment by RachelOh** [comment]
아래와 같이 답변
----
Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.      

Sorry to say, Twomon SE doesn't support sound functions.

I'm sorry that I couldn't give you a positive answer.

Please contact us whenever you need our help.

Thanks.


Easy&Light
