### ISSUE TITLE
what do they mean by a you need a vertual display driver

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1657]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:jim2finn@hotmail.com<br><br>how to turn on or get a vertual dispay driver<br><br>[EL_Display_0b672a7b-023d-4793-9f46-f29babb7008d.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_0b672a7b-023d-4793-9f46-f29babb7008d.zip)

**Comment by RachelOh** [comment]
아래와 같이 답변
----
Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry. 

The virtual display driver is loaded automatically when you download the PC Program.

If the virtual display doesn't work properly, please reinstall the PC program completely 

and download the PC program again.

If you still have the problem, please contact us.

Sorry for the inconvenience.


Easy&Light
