### ISSUE TITLE
화면 회전은 어떻게 해야 하는지요?

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1661]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:sgtjung@gmail.com<br><br>윈도우10에 갤럭시탭A 2016사용하고 있는데 화면이 가로로 고정이됩니다. 세로로 전환이 안되는데 어떻게 하면 되는지요|<br><br>[EL_Display_e3e7c685-c482-4dd1-a408-b5362be7563a.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_e3e7c685-c482-4dd1-a408-b5362be7563a.zip)

**Comment by RachelOh** [comment]
아래와 같이 답변
----
고객님, 안녕하세요. Easy&Light 지원팀 입니다.

죄송하게도 Twomon SE는 화면 자동 틸트 기능을 지원하고 있지 않습니다.

화면 방향은 디스플레이 설정으로 들어가셔서 패드에 해당하는 스크린을 선택하신 후 

하단의 화면 방향에서 설정을 바꿔주시면 화면 방향 변경이 가능합니다.

사용 중 궁금한 점이 있으시면 언제든 문의주시기 바랍니다.

감사합니다.


Easy&Light
