### ISSUE TITLE
EasyCanvas 설치 관련 문의드립니다.

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1669]
Product:EasyCanvas

Device OS:Android

e-mail:[happychina@naver.com](mailto:happychina@naver.com)

**Comment by RachelOh** [comment]
아래와 같이 답변
----
고객님, 안녕하세요. Easy&Light 지원팀 입니다.

문의해주신 내용에 대한 답변을 메일로 전달해드립니다.

아쉽게도 갤럭시 노트8 모델은 지원하지 않으며, 갤럭시탭 S 시리즈에서 사용이 가능합니다.

원하시는 답변을 드리지 못해 죄송합니다.

제품 관련하여 궁금한 점이 있으시면 언제든 문의주시기 바랍니다.

감사합니다.



Easy&Light

**Comment by RachelOh** [comment]
2023. 1. 17. 오전 9:44
----
유튜브 영상을 보시면 삼성 갤럭시 노트8로 EasyCanvas를 사용하는 모습이 나옵니다.
혹시 잘 못된 답변을 주신게 아니신가 해서 해당 영상 주소 보내드립니다.
영상 확인 바랍니다.
https://www.youtube.com/watch?v=Mdp2MUkf5tw&t=148s

**Comment by RachelOh** [comment]
아래와 같이 답변
----
고객님, 안녕하세요. Easy&Light 지원팀 입니다.

환경에 따라 노트 모델도 사용이 가능할 수 있으나, 공식적으로 지원하고 있지 않습니다.

지원하는 모델에 대해서는 홈페이지 FAQ를 참고해주시기 바랍니다.
http://www.easynlight.com/supporteasycanvas/?faq=96

감사합니다.


Easy&Light

**Comment by RachelOh** [comment]
2023.1.17. 오전 10:25
----
빠른회신 감사드립니다.
제가 사용하고자 하는 목적은 PC 미러링 입니다.
현재 WIN11 사용중이며, 삼성 갤럭시 노트8 을 미러링 해서 사용하고자 합니다.
Easy&Light 제품중 어떤 제품이 궁합이 좋은지 어드바이스 부탁드립니다.
그럼 회신 기다리겠습니다.


ps:
그리고 어느 유튜버가 만든 영상을 보면 EasyCanvas 의 레이턴시가 거의 10ms 이하로 pc와 연결된 디바이스와 거의 끊김이 없다고 설명하더군요.
투문USB 및 투문SE 제품도 EasyCanvas 와 같은 성능을 내는지도 알고 싶습니다.
참고로 EasyCanvas 레이턴시 비교 영상으로 만든 유튜브 동영상 주소 아래에 첨부합니다.
05:35 부터 EasyCanvas 의 레이턴시 분석 영상이 나옵니다.
https://www.youtube.com/watch?v=64iP5sNabLA&t=306s

**Comment by RachelOh** [comment]
아래와 같이 답변
----
고객님, 안녕하세요. Easy&Light 지원팀 입니다.

최신 OS를 지원하는 Twomon SE 사용을 추천드립니다. 

제품 성능은 사용하시는 PC와 기기의 성능에 따라 차이가 있을 수 있는 점 참고 부탁드립니다.

Twomon SE를 다운 받아 사용해보시고, 원하시는 성능이 아니라면 환불 받으실 수 있습니다.
(구매 후 2시간 이내 제품은 구글을 통해 직접 환불이 가능하며, 
구매 후 2시간이 지났을 경우, 구매일로 부터 30일 이내의 제품만 환불 요청이 가능합니다.)

감사합니다.


Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

Twomon SE 사용시 tape-c to tape-c 로 핸드폰과 피시를 연결해 사용이 가능한가요?

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

A to C Type 케이블 뿐 아니라 C to C Type 케이블을 통한 연결도 가능합니다.


제품에 대해 추가로 궁금한 점은 언제든지 회신하여 주시기 바랍니다.

감사합니다. 


Easy&Light
