### ISSUE TITLE
작동하지 않습니다.

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1671]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:jinmo0817@yonsei.ac.kr<br><br>pc프로그램 설치후 태블릿을 연결해도 작동하지 않습니다. 태블릿은 s6 lite입니다.<br><br>[EL_Display_4eca9bb8-c690-490b-b8dd-7762d2c17052.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_4eca9bb8-c690-490b-b8dd-7762d2c17052.zip)

**Comment by AdamPark0030** [comment]
## 답변
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님의 증상을 확인한 결과 프로그램이 정상적으로 설치되지 않은 것 같습니다. 
프로그램 재설치를 진행하여보시고 동일 증상이 발생한다면 
정확한 증상 확인을 위해 아래 링크를 참조해 PC 및 어플리케이션의 로그를 첨부하여 회신해주시기 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light

**Comment by AdamPark0030** [comment]
## 답변완료

제목
```
Re: [Twomon SE: 1671] 작동하지 않습니다.
```
본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님의 증상을 확인한 결과 프로그램이 정상적으로 설치되지 않은 것 같습니다.
프로그램 재설치를 진행하여보시고 동일 증상이 발생한다면
정확한 증상 확인을 위해 아래 링크의 "수동 로그 추출 방법" 항목을 참조해 PC 및 어플리케이션의 로그를 첨부하여 회신해주시기 바랍니다.

[FAQ] 로그 취득 가이드 :
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light
```
