### ISSUE TITLE
Show cursor when hovering

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1672]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:luke_hughes@live.com<br><br>Hey there! I just bought easy canvas for windows and drawing in photoshop. I was wondering if there is a way to show the cursor while you are hovering? Similar to what you can do with the cintiq. Thank you!<br><br>[EL_Display_f38c0059-e58a-4dbf-aaff-4db45c903f47.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_f38c0059-e58a-4dbf-aaff-4db45c903f47.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, We are an Easy & Light support team.

I'm sending this email for your inquiry. 

Currently, hovering function is not provided.

We have a plan to support the hovering function.

But, I'm not sure of the exact schedule.

I hope that the hovering function can be released in the near future.

Thanks.


Easy&Light
