### ISSUE TITLE
파워포인트 주석 색상 변경 불가 

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#1674]
- 문의 날짜 : 2023년 1월 18일 오후 12시 13분
- 메일 주소 : [kmadhurao@gmail.com](mailto:kmadhurao@gmail.com)

Title: change colors while annotating

Questions: I am trying to write on ppt in slide show mode. I am able to annotate but unable to change the colors.

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, We are Easy&Light support team.

When the EasyCanvas app is not in use, does it work normally?

If you think it's an EasyCanvas error, please send us the log file.

Our technical team will check the problem and give you a solution.


[Manual log collection procedure]

1. Enter Windows key > "Run" > Enter "msinfo32" > File > Save
2. Files existing in the path C:\ProgramData\devguru
3. A file existing in the path C:\Users\{username}\AppData\Local\Devguru (you can access the path with %localappdata%\Devguru)

Please zip the three files and attach them.

[App log collection procedure]
　1. Android　　① Re-run the application on your device.　　② Tap on the app version at the bottom right of the main page about 10 times, then make sure a created log zip file named 'bypd.log.archived.yyyymmddhhmmss.zip' in Download folder on your device.

　2. iOS　　① Connect the device to extract the logs to a PC.　　② Run iTunes and click it when the connected device appears on the upper tap.　　③ Click ‘File Sharing’ in the list to the left.　　④ Scroll down the updated screen and click the app (EasyCanvas) to extract the log from the ‘App’ in the ‘File Sharing’ column. 　　⑤ Drag the log file at the bottom of ‘OOOO’s Documents' to each folder or desktop, 　　　　etc., or select the file and save it by clicking the ‘Save As’ button at the bottom right. 　　　


Please zip the all files and attach them.



Thank you.
Easy & Light

**Comment by RachelOh** [comment]
2023년 1월 19일 목요일 오후 1:06
----
Thanks for the response. First of all, I am running this application on IOS. Please share the procedure for IOS device.

Regards,
Madhu

**Comment by RachelOh** [comment]
아래와 같이 답변
----
Hello, We are Easy&Light support team.

I sent you the procedure for the iOS device below. 
Please read [App log collection procedure] - 2. iOS


[Manual log collection procedure]

1. Enter Windows key > "Run" > Enter "msinfo32" > File > Save
2. Files existing in the path C:\ProgramData\devguru
3. A file existing in the path C:\Users\{username}\AppData\Local\Devguru (you can access the path with %localappdata%\Devguru)

Please zip the three files and attach them.

[App log collection procedure]
　1. Android　　① Re-run the application on your device.　　② Tap on the app version at the bottom right of the main page about 10 times, then make sure a created log zip file named 'bypd.log.archived.yyyymmddhhmmss.zip' in Download folder on your device.

　2. iOS　　① Connect the device to extract the logs to a PC.　　② Run iTunes and click it when the connected device appears on the upper tap.　　③ Click ‘File Sharing’ in the list to the left.　　④ Scroll down the updated screen and click the app (EasyCanvas) to extract the log from the ‘App’ in the ‘File Sharing’ column. 　　⑤ Drag the log file at the bottom of ‘OOOO’s Documents' to each folder or desktop, 　　　　etc., or select the file and save it by clicking the ‘Save As’ button at the bottom right. 　　　


Please zip the all files and attach them.



Thank you.
Easy & Light

**Comment by RachelOh** [comment]
2023.3.6. 오후 8:36
---
Hi,
here are the log files as requested by you.

Regards,
Madhu

[easycanvas log.zip](https://github.com/edh-git/EL_Display_Hub/files/10904179/easycanvas.log.zip)

**Comment by james-kim-Devguru** [comment]
@RachelOh 
문의 사항 추측하니 파워포인트에서 슬라이드 쇼에서 펜입력 필기 시 색 변화하고 싶다는 내용 같습니다.
해당 기능은 파워포인트의 문제로 보이며, 터치 후 좌측 하단의 펜 모양을 통해서 제공 가능합니다.

해당 사항을 답변 남겨야할지 판단 부탁드립니다.

**Comment by RachelOh** [comment]
@james-kim-Devguru 
내용대로 답변한 후 해당내용은 파워포인트 문제로보이니 이후 질문은 ms쪽으로 하면될 것 같다고 답변해주시면 될 것 같습니다.

**Comment by RachelOh** [comment]
2023.3.9. 오후 5:18
---
HI,
Can you please review the inputs and provide the fix?

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1674] change colors while annotating
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

The currently sent log was only the app log, so it was not possible to conduct a complete review, and the app log you sent was a normal log with no problems.
In addition, we inform you that the answer may not be satisfactory because we cannot understand the exact request with a short inquiry.

The inquiry that the color does not change in the annotation in the slide show of PowerPoint that you inquired is understood to be the case of writing through pen input in the slice show.

As a result of our testing, we confirmed that handwriting is possible through pen input in PowerPoint's slice show, and that the color of the pen handwriting input through the pen shape in the lower left corner after touch can be adjusted.

In the case of EasyCanvas, it provides a function to send simple pen input to Windows, so it is difficult to provide additional help for that function. For additional inquiries, please contact Microsoft's PowerPoint related team.

If you have additional questions, please refer to the previous answers and ask again by attaching the PC log and application log, and please attach a photo or video of the problem situation to understand the detailed request.

Thank you

Easy&Light
```
