### ISSUE TITLE
Ipad showing black screen with cursor

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1680]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:fortnite90000567@gmail.com<br><br>My ipad is showing me black screen<br><br>[EL_Display_805ded2c-67da-4e3b-b90e-884c038ec6b7.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_805ded2c-67da-4e3b-b90e-884c038ec6b7.zip)

**Comment by james-kim-Devguru** [comment]
* https://github.com/edh-git/EL_Display_Hub/issues/1676
위 이슈와 같은 이슈로 함께 처리합니다.
