### ISSUE TITLE
pc app does see ipad

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1686]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:pictteh@gmail.com<br><br>what should i do? I bought subscription but it doesn't work! =C<br><br>[EL_Display_c818c2ef-50e3-40ff-89d8-ef185a1b6a3b.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_c818c2ef-50e3-40ff-89d8-ef185a1b6a3b.zip)

**Comment by RachelOh** [comment]
@james-kim-Devguru 
#1687 사용자와 동일한 사용자 입니다.

**Comment by AdamPark0030** [comment]
#1687 이슈에서 답변 완료 했습니다.
