### ISSUE TITLE
Cancelling 3 day free subscription

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1690]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:madelynnk2@gmail.com<br><br>I want to cancel the 3 day free subscription since I do not want to pay for the regular easycanvas subscription which is $11.99. I do not know if it will automatically renew so I wanted to cancel the free trial so I am not charged for EasyCanvas as I do not wish to continue using it.<br><br>[EL_Display_67124c05-3c6c-4641-8075-5b19fd0e9462.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_67124c05-3c6c-4641-8075-5b19fd0e9462.zip)

**Comment by RachelOh** [comment]
아래와 같이 답변
---
Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry. 

Sorry to say, we don't have any authority about a refund.

Please refer to the link below and If you have any questions, you can contact the App Store.

https://support.apple.com/en-us/HT202039
https://support.apple.com/en-us/HT204084


I'm sorry I couldn't give you any help.

Thanks.


Easy&Light
