### ISSUE TITLE
Cancel subscription of EasyCanvas 3 day free trial

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1691]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:madelynnk2@gmail.com<br><br>I don't want to pay for the EasyCanvas after the free trial is expired so I would like to cancel it as I won't be using EasyCanvas anymore.<br><br>[EL_Display_ab15a652-e957-47eb-92b9-8dda9cf30b26.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_ab15a652-e957-47eb-92b9-8dda9cf30b26.zip)

**Comment by RachelOh** [comment]
#1690 동일사용자
