### ISSUE TITLE
Error on easy canvas

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1695]
Product:EasyCanvas

Device OS:Android

e-mail:[wisnuwitantra@gmail.com](mailto:wisnuwitantra@gmail.com)

I cant connect my easy canvas on samsungtab s7 fe to my laptop.
![SmartSelect_20230127_113021](https://user-images.githubusercontent.com/77039864/215363458-59e8018b-650c-4c03-bf91-315c6e1fff57.jpg)

**Comment by RachelOh** [comment]
아래와 같이 답변
---
Hi, customer. Easy & Light Support.

First of all, I'm sorry for the inconvenience.

Please manually extract the log and respond to the mail for accurate symptom verification.

Manual log extraction method

[App log]
　1.Connect the machine to which you want to extract logs to your PC.
　2. Launch iTunes and click the device that you connected to the top tab.
　3. Click 'File Sharing' in the list on the left.
　4. Scroll down the updated screen and click the 'App' in the 'File Sharing' column on the 'Easy Canvas' to extract the log. 　　

[PC Log]
　　1. Enter Windows key → "Run" → Enter "msinfo32" → File → Save
　　2. Files present in the "C:\ProgramData\devguru" path
　　3. Files present in the "C:\Users\{username}\AppData\local\devguru" path

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Easy&Light

**Comment by RachelOh** [comment]
2023.2.1. 오후 1:20
---
i cant open the el display hub, what should i do?

**Comment by RachelOh** [comment]
아래와 같이 답변
---
Hi, customer. Easy & Light Support.

You can extract the log files even if you can't open the EL Display Hub.
Please follow the steps below and send us the log files.

Manual log extraction method

[App log]
　1. Android　　① Re-run the application on your device.　　② Tap on the app version at the bottom right of the main page about 10 times, then make sure a created log zip file named 'bypd.log.archived.yyyymmddhhmmss.zip' in Download folder on your device.

[PC Log]
　　1. Enter Windows key → "Run" → Enter "msinfo32" → File → Save
　　2. Files present in the "C:\ProgramData\devguru" path
　　3. Files present in the "C:\Users\{username}\AppData\local\devguru" path

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Easy&Light

**Comment by RachelOh** [comment]
2023.2.5. 오전 1:18
---
로그파일을 전달받았습니다.


[bypd.log.archived.yyyymmddhhmmss.zip](https://github.com/edh-git/EL_Display_Hub/files/10614127/bypd.log.archived.yyyymmddhhmmss.zip)

**Comment by RachelOh** [comment]
2023.2.7. 오후 12:36
---
hello i have sent you the log on my pc and my tablet

**Comment by james-kim-Devguru** [comment]
pc 로그 추가합니다. (RAR을 zip으로 변환하였습니다.)
[EL DISPLAY LOG.zip](https://github.com/edh-git/EL_Display_Hub/files/10684517/EL.DISPLAY.LOG.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1695] Error on easy canvas
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

After reviewing the logs you sent, it seems that the "USB Debugging" option on the Android side is not applied properly.

Refer to the link below and allow "USB Debugging".

[FAQ] Allow 'USB Debugging' permission or' Cancel USB Debugging permission' and try again (Android) : http://www.easynlight.com/en/supporttwomon/?faq=80

If it does not work after that, please reboot both PC and Android device.

If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

[App log]
① Re-run the application on your device.　　
② Tap on the app version at the bottom right of the main page about 10 times, then make sure a created log zip file named 'bypd.log.archived.yyyymmddhhmmss.zip' in Download folder on your device.

[PC Log]
1. Enter Windows key → "Run" → Enter "msinfo32" → File → Save
2. Files present in the "C:\ProgramData\devguru" path
3. Files present in the "C:\Users{username}\AppData\local\devguru" path

Thank you

Easy&Light
```
