### ISSUE TITLE
연결오류

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1698]
Product:Twomon SE

Device OS:Android

e-mail:[icanfly101@naver.com](mailto:icanfly101@naver.com)

화면선택에서 디스플레이 선택 옵션이 하나도 안나오네요 다른것도 마찬가지구요
연결이 안되는것같아요
태블릿에서도 \"PC프로그램 실행 후 PC와 태블릿을 연결해주세요\"라고만 나오네요

PC로그는 저장이 실패해서
텍스트랑 이미지로 보내요...이게 맞는지...

---------------------------------------------
OS 이름 Microsoft Windows 10 Home
버전 10.0.19044 빌드 19044
기타 OS 설명 사용할 수 없음
OS 제조업체 Microsoft Corporation
시스템 이름 DESKTOP-809M2Q3
시스템 제조업체 SAMSUNG ELECTRONICS CO., LTD.
시스템 모델 900X5L
시스템 종류 x64 기반 PC
시스템 SKU ATIV A5A5-A5A5-A5A5-A5A5-A5A5-PAFX
프로세서 Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz, 2304Mhz, 2 코어, 4 논리 프로세서
BIOS 버전/날짜 American Megatrends Inc. [P04AFX.036.160331.PS](http://p04afx.036.160331.ps/), 2016-03-31
SMBIOS 버전 3.0
포함된 컨트롤러 버전 255.255
BIOS 모드 UEFI
베이스보드 제조업체 SAMSUNG ELECTRONICS CO., LTD.
베이스보드 제품 NT900X5L-K3EO
베이스보드 버전 SGL8771A05-C01-G001-S0001+10.0.10586
플랫폼 역할 모바일
보안 부팅 상태 설정
PCR7 구성 바인딩 가능
Windows 디렉터리 C:\\WINDOWS
시스템 디렉터리 C:\\WINDOWS\\system32
부팅 장치 \\Device\\HarddiskVolume1
지역 한국
하드웨어 추상화 계층 버전 = \"10.0.19041.2251\"
사용자 이름 DESKTOP-809M2Q3\\jas
표준 시간대 대한민국 표준시
설치된 실제 메모리(RAM) 8.00GB
총 실제 메모리 7.88GB
사용 가능한 실제 메모리 3.39GB
총 가상 메모리 9.13GB
사용 가능한 가상 메모리 3.56GB
페이지 파일 공간 1.25GB
페이지 파일 C:\\pagefile.sys
커널 DMA 보호 해제
가상화 기반 보안 사용 안 함
장치 암호화 지원 자동 장치 암호화에 실패한 이유: 하드웨어 보안 테스트 인터페이스에 실패했으며 장치가 최신 대기 상태가 아닙니다.
Hyper-V - VM 모니터 모드 확장 예
Hyper-V - 두 번째 수준 주소 변환 확장 예
Hyper-V - 펌웨어에 가상화 사용 예
Hyper-V - Data Execution Protection 예

[TwomonSE.log.archived.20230129194621.zip](https://github.com/edh-git/EL_Display_Hub/files/10531221/TwomonSE.log.archived.20230129194621.zip)
![pc](https://user-images.githubusercontent.com/77039864/215364447-b03b1a84-87cf-4b80-8326-ad341e0a0c54.jpg)
![캡처](https://user-images.githubusercontent.com/77039864/215364450-45c4c814-d695-41fd-80f2-d537f0dc0f2c.jpg)
![20230129_195133](https://user-images.githubusercontent.com/77039864/215364451-4a513e1d-4ef7-4fa5-84db-f09e02cc2bd9.jpg)

**Comment by james-kim-Devguru** [comment]
검토중

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1698] 연결오류
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 어플리케이션 로그를 검토한 결과 연결 시도 관련 로그가 발생하지 않았습니다.

우선 아래 링크의 중간 동영상(Twomon SE 사용 동영상)을 참조하여 태블릿과 PC의 연결을 확인하여 주십시오.
[Twomon SE] 제품 소개 페이지 : http://www.easynlight.com/twomonse/

정상적으로 연결되지 않았을 경우에는 아래와 같은 사항을 점검하여 주십시오.

첫 번째로 USB포트의 전력 부족 혹은 연결 불량 문제일 수 있습니다.
이를 해결하기 위해 아래의 사항들을 조치해보십시오.
1. PC와 태블릿 간의 연결이 정상적인지 확인합니다.
2. USB 케이블 교체(가능한 정품 케이블 사용,  데이터 통신이 가능한 케이블 사용)합니다.
3. PC에 연결된 USB 포트 변경(후면 포트 이용)합니다.
4. 외부전원 USB 허브에 연결합니다.

두 번째로 PC측과 태블릿 측의 오류일 수 있습니다.
1. PC를 재부팅하여 주십시오. (종료 옵션의 "다시 시작" 사용)
2. 태블릿을 재부팅하여 주십시오. 

세 번째로 안드로이드 측의 "USB 디버깅" 옵션의 오류일 수 있습니다.
아래의 링크를 참조하셔서 "USB 디버깅"을 허용해주십시오.

[FAQ] 'USB 디버깅' 권한을 허용하거나 'USB 디버깅 권한 승인 취소'한 후 다시 시도 (Android) : http://www.easynlight.com/supporttwomon/?faq=123


위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 로그 취득 가이드를 참조하여 PC로그와 어플리케이션 로그를 첨부하여 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

[로그 수동 수집 절차]
1. Windows키 입력 > "실행" > "msinfo32" 입력 > 파일 > 저장
2. C:\ProgramData\devguru 경로에 존재하는 파일
3. C:\Users\{사용자명}\AppData\Local\Devguru 경로에 존재하는 파일 ( %localappdata%\Devguru  로 경로에 접근 가능)

세 군데의 파일들을 압축하여 첨부해주세요.

감사합니다.

Ea​​sy&Light 
```

**Comment by RachelOh** [comment]
2023.2.14. 오전 11:17
---
아래 사항들 조치해도 안됩니다
구글에 환불 조치 요청했는데 안된다고 하고, 개발자에게 직접 문의하라고 합니다
환불처리해주세요

**Comment by RachelOh** [comment]
환불처리완료
---
고객님, 안녕하세요. Easy&Light 지원팀입니다.
 
금일 주문번호 GPA.3372-8527-2179-47318에 대한 환불 처리를 완료하였습니다.

환불 내역에 대한 자세한 사항은 구글 계정을 통하여 확인하실 수 있습니다.

https://play.google.com/store/account
 
감사합니다.

Easy&Light
