### ISSUE TITLE
아이패드 매직키보드 이용시 클릭 문제

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1711]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:archkkw@naver.com<br><br>아이패드 매직키보드의 트랙패드를 통해 클릭을 할 경우 첨부 사진에서와 같이 터치했을때의 회색 반투명한 점이 생긴 후 사라지지 않습니다. 이 경우, 실제 마우스의 커서가 계속 깜빡이는 오류가 발생하게 됩니다.<br><br>[EL_Display_aa64e294-f261-468f-9ead-c4d7635ce667.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_aa64e294-f261-468f-9ead-c4d7635ce667.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1711] 아이패드 매직키보드 이용시 클릭 문제
```
#### 본문
```
고객님 안녕하세요. Easy&Light 지원팀입니다.

문의해주신 내용에 대한 답변을 메일로 전달해드립니다.

현재 Twomon SE에서는 매직키보드를 비롯한 아이패드와 연결된 장치에서의 입력 기능을 지원하고 있지 않습니다.
따라서 매직키보드의 기능이 일부 사용 가능하여도 정상 동작하지 않을 수 있습니다.

키보드 혹은 트랙패드 기능을 사용하기 위해서는 아이패드와 연결된 장치가 아닌
Windows PC와 연결되어 있는 키보드 혹은 마우스를 사용해야 기능이 정상적으로 동작합니다.

추가적으로 일반 블루투스 마우스나 블루투스로 연결된 매직 트랙패드에서는 정상 동작을 확인하였으며,
매직키보드의 트랙패드의 동작 문제로 보이며 해당 장치를 초기화하거나 아이패드를 재부팅하여 보시길 바랍니다.

제품 사용 중 궁금하거나 불편한 사항은 언제든지 문의하여 주시기 바랍니다.

감사합니다.

Easy&Light
```

* 참조 : https://github.com/edh-git/EL_Display_Hub/issues/1563
