### ISSUE TITLE
미작동

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1743]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:jinmo0817@yonsei.ac.kr<br><br>안녕하세요. 지난번에 작동이 안되는 문제로 문의를 드렸습니다. pc에 윈도우를 새로 설치하고 귀사의 프로그램을 설치했는데도 작동이 되지 않네요. 안내해주신대로 pc의 log를 추출하려고 하였으나 C드라이브에 Devguru 경로가 없어서 우선 앱에서 추출한것만 보내드립니다. 빨리 해결하고 싶네요. 감사합니다.<br><br>[EL_Display_7e910d4e-1084-4b58-9c8c-515fa81aa091.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_7e910d4e-1084-4b58-9c8c-515fa81aa091.zip)

**Comment by james-kim-Devguru** [comment]
* 연관 이슈 : https://github.com/edh-git/EL_Display_Hub/issues/1671

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1743] 미작동
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

고객님께서 새로 보내주신 로그를 검토한 결과 안드로이드 측의 "USB 디버깅" 옵션이 제대로 적용되지 않은 것으로 보입니다. 

아래의 링크를 참조하셔서 "USB 디버깅"을 허용해주십시오.

[FAQ] 'USB 디버깅' 권한을 허용하거나 'USB 디버깅 권한 승인 취소'한 후 다시 시도 (Android) : http://www.easynlight.com/supporttwomon/?faq=123

이후에도 동작하지 않을 경우 PC와 안드로이드 디바이스 모두 재부팅하여 주십시오.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
