### ISSUE TITLE
컴퓨터 프로그램 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1749]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:parkminjae0411@naver.com<br><br>fhd 모니터를 사용할때는 문제 없었는데 qhd 모니터가 달린 노트북이나 모니터를 사용할때 프로그램이 4분의 1크기로 짤립니다<br><br>[EL_Display_ffc37f55-84a3-4770-a299-73e2db14f475.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_ffc37f55-84a3-4770-a299-73e2db14f475.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1749] 컴퓨터 프로그램 문의
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 새로 보내주신 로그를 검토한 결과 특별한 이상 사항이 발견되지 않았습니다.

일시적인 오류일 수 있으며 PC를 재부팅(종료 옵션의 "다시 시작")을 통해서 해결될 수 있습니다.

재부팅 후 해결되지 않았을 경우에는 프로그램을 재설치하면 해결되며, 설치 프로그램이 손상되었을 수 있으므로 새로운 설치 프로그램을 다운로드 받아서 재설치 진행해주시길 바랍니다.
1. EL Display Hub를 삭제합니다.
2. PC 재부팅합니다. (종료 옵션의 "다시 시작" 사용)
3. 최신 EL Display Hub 인스톨러 재설치합니다.
[EL Display Hub] 설치 링크 : http://www.easynlight.com/twomonse/
4. EL Display Hub 재설치합니다.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.
또한, 현재 로그 상으로 문제가 확인되지 않으므로, 증상이 발생하는 화면을 캡처해서 보내주시면 감사하겠습니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```

**Comment by james-kim-Devguru** [comment]
사용자 답변

---

<img width="700" alt="화면 캡처 2023-02-28 145827" src="https://user-images.githubusercontent.com/66463237/221835640-65016580-cdba-4774-9b25-7daf099fcc0f.png">

재설치 등등 제가 할 수 있는 노력은 다 해봤는데도 문제가 계속 남아있습니다. 증상 사진으로 첨부해서 보냅니다.

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1749] 컴퓨터 프로그램 문의
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

화면의 배율 등의 문제로 DPI 설정 충돌로 인하여 UI가 제대로 표시되지 않는 문제로 보입니다.

* 이전 앱 또는 프로그램이 Windows와 호환되도록 설정 (높은 DPI 설정 변경) : https://support.microsoft.com/ko-kr/windows/%EC%9D%B4%EC%A0%84-%EC%95%B1-%EB%98%90%EB%8A%94-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8%EC%9D%B4-windows%EC%99%80-%ED%98%B8%ED%99%98%EB%90%98%EB%8F%84%EB%A1%9D-%EC%84%A4%EC%A0%95-783d6dd7-b439-bdb0-0490-54eea0f45938#ID0EBH=Windows_10

위 링크의 "높은 DPI 설정 변경" 부분과 첨부해드린 이미지를 참조하셔서 수정하시면 됩니다.

1. "C:\Program Files (x86)\EL Display Hub"의 EL_Display_Hub.exe 파일의 우클릭 - 속성 실행
2. 호환성 - 높은 DPI 설정
3. 높은 DPI 조정 재정의 - "시스템(고급)"
4. PC 프로그램 재실행


위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light 
```

**Comment by james-kim-Devguru** [comment]
#### 첨부 이미지

![1](https://user-images.githubusercontent.com/66463237/221835891-2f703272-28dd-4689-8768-950b2c7a7ad7.png)
![2](https://user-images.githubusercontent.com/66463237/221835898-e43fa5de-2aee-4d58-bfc3-59d6c4a7a16a.png)
![3](https://user-images.githubusercontent.com/66463237/221835904-e3427703-168a-4e7d-a0d6-77d5969a7de2.png)

**Comment by RachelOh** [comment]
사용자에게 답변이 왔습니다.
2023.2.28. 오후 3:00
---
재설치 등등 제가 할 수 있는 노력은 다 해봤는데도 문제가 계속 남아있습니다. 증상 사진으로 첨부해서 보냅니다.

<img width="700" alt="화면 캡처 2023-02-28 145827" src="https://user-images.githubusercontent.com/77039864/222291372-976e0259-0db2-4bec-b33e-e6bf4edb143d.png">

**Comment by james-kim-Devguru** [comment]
* https://github.com/edh-git/EL_Display_Hub/issues/1749#issuecomment-1447984044
* 위 코멘트로 답변 완료된 사항입니다.
