### ISSUE TITLE
동영상 화면이 검정색이에요

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1754]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:24691116@naver.com<br><br>메인 화면에서는 동영상이 잘 보이는데 아이패드로 브라우저를 넘기면 자막만 재생되고 화면은 검정색이에요. 처음 사용할 때는 안그랬는데 어느 순간 이렇게 오류가 발생하네요<br><br>[EL_Display_0a3bc12f-5a56-431c-bfd1-170fc21ef99a.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_0a3bc12f-5a56-431c-bfd1-170fc21ef99a.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1754] 동영상 화면이 검정색이에요
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님게서 보내주신 첨부 이미지와 로그를 검토한 결과 동영상 측의 보안 정책 문제로 보입니다.
EL Display Hub의 경우 화면을 캡처하여 태블릿으로 공유하는 프로그램으로,
유료 동영상이나 DRM으로 보호되는 컨텐츠의 경우 제공자의 정책에 따라서 표시가 불가능할 수 있습니다.

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다. 

Easy&Light
```

**Comment by RachelOh** [comment]
2023.3.2. 오후 5:04
---
답변 감사합니다.
