### ISSUE TITLE
문의하기 테스트 메일입니다.

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1763]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:jk34011@naver.com<br><br>Twomon SE / Android<br><br>[EL_Display_c4592625-0e19-49e4-8758-ac984578a516.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_c4592625-0e19-49e4-8758-ac984578a516.zip)

**Comment by jeffrey-Devguru** [comment]
테스트 용으로 종료 처리합니다.
