### ISSUE TITLE
Unable to Start Using EasyCanvas - Stuck at Pay Page

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1769]
Product:EasyCanvas

Device OS:iOS

e-mail:[humi926@hotmail.com](mailto:humi926@hotmail.com)

After installing, my screens stop at the pay page. Neither selecting trial nor pay sends me to another page. The buttons just give me a fake pressed animation without any action.

Please help on the issue cause I really want to start using your product. Thanks.

Regards,
Humi

![8CE1DB37-FD9A-44BC-BABF-AE185D6D5FA2](https://user-images.githubusercontent.com/77039864/223340559-9de719e8-3762-4a87-ade4-cbdfdd8f717d.png)

**Comment by RachelOh** [comment]
로그파일 요청
---
Hello, We are Easy&Light support team.
To know the cause of the problem, we need log files to analyze.

Our technical team will check the problem and give you a solution.


[Manual log collection procedure]

1. Enter Windows key > "Run" > Enter "msinfo32" > File > Save
2. Files existing in the path C:\ProgramData\devguru
3. A file existing in the path C:\Users\{username}\AppData\Local\Devguru (you can access the path with %localappdata%\Devguru)

Please zip the three files and attach them.

[App log collection procedure]
　1. Android　　① Re-run the application on your device.　　② Tap on the app version at the bottom right of the main page about 10 times, then make sure a created log zip file named 'bypd.log.archived.yyyymmddhhmmss.zip' in Download folder on your device.

　2. iOS　　① Connect the device to extract the logs to a PC.　　② Run iTunes and click it when the connected device appears on the upper tap.　　③ Click ‘File Sharing’ in the list to the left.　　④ Scroll down the updated screen and click the app (EasyCanvas) to extract the log from the ‘App’ in the ‘File Sharing’ column. 　　⑤ Drag the log file at the bottom of ‘OOOO’s Documents' to each folder or desktop, 　　　　etc., or select the file and save it by clicking the ‘Save As’ button at the bottom right. 　　　


Please zip the all files and attach them.



Thank you.
Easy & Light

**Comment by RachelOh** [comment]
2023.3.9. 오후 3:20
---
Morning,

 

Thanks for your reply. Please check my manual and app log files in attachment.

 

For the app log, because I cannot find the “file sharing” option in iTunes, I tried using the Real-time System Log function in a application called “iTools”. Hope this help on your investigation.

 

Please contact me anytime if there is any issue. Thank you.

 

Best regards,

Humi Lam

[Humi_EasyCanvas_ManualAndAppLog.zip](https://github.com/edh-git/EL_Display_Hub/files/10937640/Humi_EasyCanvas_ManualAndAppLog.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1769] Unable to Start Using EasyCanvas - Stuck at Pay Page
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

After reviewing the log sent by the customer, it seems that the app is not working normally.

Please try the following actions.
1. Check if the Internet connection of the iPad and the AppStore are working normally.
2. Please try again after reinstalling Easycanvas.
3. Reboot your iPad.

If the problem does not improve even after taking the above measures, please refer to the link below and try again and attach a new app log.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you

Easy&Light
```
