### ISSUE TITLE
라데온그래픽카드 PC에 사용중인데

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1772]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:bu3820@naver.com<br><br>이 어플 연결하면 모니터 144프레임 제한이 안됩니다.. 태블릿이랑 PC랑 연결해제하면 다시 144 프레임 제한되구요..<br><br>[EL_Display_c4badf88-dc9b-4792-9eb4-e9c3cadb902a.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_c4badf88-dc9b-4792-9eb4-e9c3cadb902a.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1772] 라데온그래픽카드 PC에 사용중인데
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 그래픽 카드 대역폭 문제일 수 있습니다.
저희 제품은 연결 시 모니터가 추가로 연결되는 방식으로 동작하며, 
사용 중이신 모니터인 4K 144hz에서 사용되는 대역폭을 추가로 연결된 모니터에서 분할해서 사용하므로,144 프레임 설정이 불가할 수 있습니다.

더 좋은 제품을 만들기 위해 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

그럼 해결 방법이 없나요?? 그리고 wqhd 144hz입니다

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1772] 라데온그래픽카드 PC에 사용중인데
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

모니터 출력 부분은 사용하시는 운영체제인 windows와 그래픽 카드 제조사에서 
설정한 정책에 따라서 출력이 조절되는 것으로 도움 드리기가 어렵습니다.

해당 증상을 해결하거나 완화를 위해서는 해상도를 조절하여 시도해 볼 수 있습니다.
메인 모니터의 해상도를 낮추거나 Twomon SE 장치의 해상도를 낮춰서 테스트하여 주십시오.

감사합니다.

Ea​​sy&Light 
```
