### ISSUE TITLE
윈도우 노트북과 연결이 안됩니다.

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#1776]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:9180jsj@naver.com<br><br>분홍화면에서 넘어가질 않네요. 선연결 하였습니다.<br><br>[EL_Display_0c622cc3-bd03-4606-ae26-223a81945668.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_0c622cc3-bd03-4606-ae26-223a81945668.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1776] 윈도우 노트북과 연결이 안됩니다.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 PC 측과 태블릿 측의 로그에서 연결 시도 관련 로그가 발생하지 않았습니다.

우선 아래 링크의 중간 동영상(Twomon SE 사용 동영상)을 참조하여 태블릿과 PC의 연결을 확인하여 주십시오.
[Twomon SE] 제품 소개 페이지 : http://www.easynlight.com/twomonse/

정상적으로 연결되지 않았을 경우에는 아래와 같은 사항을 점검하여 주십시오.

첫 번째로 USB포트의 전력 부족 혹은 연결 불량 문제일 수 있습니다.
이를 해결하기 위해 아래의 사항들을 조치해보십시오.
1. PC와 태블릿 간의 연결이 정상적인지 확인합니다.
2. USB 케이블 교체(가능한 정품 케이블 사용,  데이터 통신이 가능한 케이블 사용)합니다.
3. PC에 연결된 USB 포트 변경(후면 포트 이용)합니다.
4. 외부전원 USB 허브에 연결합니다.

두 번째로 PC측과 태블릿 측의 오류일 수 있습니다.
1. PC를 재부팅하여 주십시오. (종료 옵션의 "다시 시작" 사용)
2. 태블릿을 재부팅하여 주십시오.

위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 아래의 로그 취득 가이드를 참조하여 재문의 부탁드립니다.

[FAQ] PC 및 어플리케이션 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

더 좋은 제품을 만들기 위해 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```

**Comment by RachelOh** [comment]
2023.3.17. 오후 12:10
---
안녕하세요.

연결 후에 화면에 물방울 두 개와 커서가 계속 보이고 있습니다.
패드에서도 노트북에서도 동일하고 보이고 있는데 해결책 회신 부탁드립니다.
사진은 첨부로 전달드립니다.

감사합니다.
정순주드림

**Comment by RachelOh** [comment]
2023.3.17. 오후 12:30
---
추가메일 드립니다.
연결은 되었으나 듀얼모니터로 사용하기 위함이지만 서브모니터처럼 확장이 되지 않고 메인모니터와 동일한 화면만 출력중입니다.
관련 사진 첨부로 전달드립니다.

![photo_0 (1)](https://user-images.githubusercontent.com/77039864/226232193-441869a5-a1de-46e0-b26b-bfa6efdfa7db.PNG)

**Comment by RachelOh** [comment]
2023.3.21. 오후 3:05
---
확인만 하시고 회신이 없어 재발송 드립니다.

**Comment by RachelOh** [comment]
1차답변 
---
고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

voc메일 확인 후 사내 voc 관리 시스템에 등록을 하게 됩니다.

현재 고객님의 문의는 로그파일과 함께 개발팀에 전달된 상태이며, 개발팀에서 문제 확인중에 있습니다.

로그 분석 후 답변을 드릴 예정이니 조금만 기다려 주시기 바랍니다.

감사합니다.


Easy&Light

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1776] 윈도우 노트북과 연결이 안됩니다.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

첫 번째로 문의 주신 물방울 모양의 경우 윈도우 터치에 대한 표시입니다.
터치가 발생한 지점에 해당 모양이 표시됩니다.
터치를 하지 않은 경우에도 물방울 모양이 보이시는 경우 태블릿 측에서 터치 이벤트가 발생 중이라는 의미이며, 화면을 닦은 뒤 재연결 부탁드립니다.
계속 문제가 발생한다면  태블릿과 PC를 재부팅하여 주십시오.

두 번째로 문의 주신 내용에 대해서는 이미지 만으로 파악이 어렵습니다.
로그를 첨부하여 주시면 상세한 분석이 가능합니다.

아래 사항은 일반적인 확장이 불가능한 상황에 대한 조치 방안입니다.
해당 문제의 경우 OS 측에서 확장 모니터에 대한 복제 모드로 동작 중인 경우입니다.
다음과 같은 방식으로 확장 모드를 실행하여 주십시오.

1. EL Display Hub에서 "화면 선택"의 디스플레이 리스트에서 "확장" 목록을 선택해 확장 시도합니다.
2. 확장에 실패한 상황을 확인합니다. (확장 항목이 사라졌으며, 화면은 복제중인 상태)
3. "설정" - "시스템" - "디스플레이"로 진입하여 "다중 디스플레이"항목을 "바탕 화면을 이 디스플레이에 확장"을 사용하게 변경합니다.
    또는 "Windows키" + "P" 키를 통해서 "확장"을 선택 합니다.
    - 해당 상황에서 화면이 깜빡거리거나 연결이 해제되는 등의 문제가 발생할 수 있습니다.
    - 화면이 깜빡거린 뒤, 디스플레이 드라이버 관련 오류가 출력될 수 있습니다.
4. PC를 재부팅합니다.
5. EL Display Hub의 "화면 선택"의 디스플레이 리스트의 "확장"을 선택하여 다시 화면 확장을 시도합니다.


위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 로그 취득 가이드를 참조하여 PC로그와 어플리케이션 로그를 첨부하여 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97
[로그 수동 수집 절차]
세 군데의 파일들을 압축하여 첨부해주세요.
1. Windows키 입력 > "실행" > "msinfo32" 입력 > 파일 > 저장
2. C:\ProgramData\devguru 경로에 존재하는 파일
3. C:\Users\{사용자명}\AppData\Local\Devguru 경로에 존재하는 파일 ( %localappdata%\Devguru  로 경로에 접근 가능)

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.

감사합니다.

Ea​​sy&Light 
```

**Comment by RachelOh** [comment]
2023.3.25. 오전 8:10
---
3/17일 구매 이후로 지금까지 단 한번도 제대로 써보지를 못했네요.
서비스 대응도 너무 느리시고, 해결없이 핑퐁만 되어서 사용 어렵습니다.
환불 요청합니다.

**Comment by RachelOh** [comment]
환불 가이드 전달
---
고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

먼저 이용에 불편을 드리게 되어 죄송합니다.
iOS 앱의 경우, 개발사에서 환불을 진행할 수 있는 권한이 없이 때문에 애플 측에 문의하셔야 합니다.
iOS 앱 환불 가이드를 전달드리오니 확인해주시기 바랍니다.


[App Store for iOS 환불 가이드] 
애플 앱스토어에서 판매되는 앱은 모두 애플에서 관리합니다. 저희는 고객님의 구매 정보를 가지고 있지 않기 때문에 애플리케이션 환불을 진행할 권리가 없습니다. 아래 링크를 참조 부탁드립니다.Apple Support 사이트 링크 :[https://reportaproblem.apple.com/﻿](https://reportaproblem.apple.com/)
﻿iTunes store 에서 환불 받는 방법 :https://support.apple.com/ko-kr/HT204084


감사합니다.
Easy&Light
