### ISSUE TITLE
Can\'t connect

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1787]
Product:EasyCanvas

Device OS:iOS

e-mail:[alanschezarwork@gmail.com](mailto:alanschezarwork@gmail.com)

I am trying connecting my ipad pro to my PC(win10). I think I got some connections already because I can directly view my internal storage through file browser now. However, el display hub still says no device connected.

**Comment by RachelOh** [comment]
아래와 같이 답변
---
Hello, We are Easy&Light support team.

Please send us the log file.

Our technical team will check the problem and give you a solution.


[Manual log collection procedure]

1. Enter Windows key > "Run" > Enter "msinfo32" > File > Save
2. Files existing in the path C:\ProgramData\devguru
3. A file existing in the path C:\Users\{username}\AppData\Local\Devguru (you can access the path with %localappdata%\Devguru)

Please zip the three files and attach them.

[App log collection procedure]
　1. Android　　① Re-run the application on your device.　　② Tap on the app version at the bottom right of the main page about 10 times, then make sure a created log zip file named 'bypd.log.archived.yyyymmddhhmmss.zip' in Download folder on your device.

　2. iOS　　① Connect the device to extract the logs to a PC.　　② Run iTunes and click it when the connected device appears on the upper tap.　　③ Click ‘File Sharing’ in the list to the left.　　④ Scroll down the updated screen and click the app (EasyCanvas) to extract the log from the ‘App’ in the ‘File Sharing’ column. 　　⑤ Drag the log file at the bottom of ‘OOOO’s Documents' to each folder or desktop, 　　　　etc., or select the file and save it by clicking the ‘Save As’ button at the bottom right. 　　　


Please zip the all files and attach them.



Thank you.
Easy & Light

**Comment by RachelOh** [comment]
2023.3.23. 오후 11:06
---
Hello

Thanks for the reply! All the logs in attachment. Another thing I want to mention is with my ipad plugged in my PC just charging. EL display hub alerted me to unplug it for update meaning it does detected my ipad. But it still says no device detected.

Regards
Alan

[Logs.zip](https://github.com/edh-git/EL_Display_Hub/files/11058451/Logs.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1787] Can\'t connect
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

As a result of reviewing the logs and symptoms sent by the customer, the PC detected the connection, but
After connecting, the socket connection for actual communication with the tablet is failing.

First, reboot the iPad and try to connect.
If you cannot connect after that, please reinstall the application.

This symptom also occurs when the USB port is out of power or has a bad connection.

"Screen transfer" is a large amount of data processed through USB, so even if the connection between the PC and the device looks normal, actual communication may fail.

To solve this, try the following measures.
1. Check if the connection between PC and tablet is normal.
2. Replace the USB cable (use a genuine cable if possible).
3. Change the USB port connected to the PC (using the rear port).
4. Connect to an external powered USB hub.


If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

We will always strive for better products and services.
Thank you

Easy&Light
```
