### ISSUE TITLE
No device connected aqt Windows 11

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1791]
Product:EasyCanvas

Device OS:iOS

e-mail:[lucas.a.werner@googlemail.com](mailto:lucas.a.werner@googlemail.com)

Hallo Easy&Lieght Team,

i have the EL Display Hub installed at Windows 11, bevor i worked on Windows 10 it was completly good working app with my Ipad. Now with Windows 11 the EL Display Hub find no devices and my Ipad with the easyCanvas does not connect. Please help me fix this problem, because i need it for my Bachelor thesis. I paid for the App and on Windows 10 it was totaly fine!? I did already the way of uninstalling and installing a new time, it does not work.

Greetings

Lucas

![eldisplayhub](https://user-images.githubusercontent.com/77039864/226261726-718906b2-4db1-499c-b415-6afffa2ee9a4.jpg)

**Comment by RachelOh** [comment]
로그파일 요청
---
Hello, We are Easy&Light support team.

Please send us the log file.

Our technical team will check the problem and give you a solution.


[Manual log collection procedure]

1. Enter Windows key > "Run" > Enter "msinfo32" > File > Save
2. Files existing in the path C:\ProgramData\devguru
3. A file existing in the path C:\Users\{username}\AppData\Local\Devguru (you can access the path with %localappdata%\Devguru)

Please zip the three files and attach them.

[App log collection procedure]
　1. Android　　① Re-run the application on your device.　　② Tap on the app version at the bottom right of the main page about 10 times, then make sure a created log zip file named 'bypd.log.archived.yyyymmddhhmmss.zip' in Download folder on your device.

　2. iOS　　① Connect the device to extract the logs to a PC.　　② Run iTunes and click it when the connected device appears on the upper tap.　　③ Click ‘File Sharing’ in the list to the left.　　④ Scroll down the updated screen and click the app (EasyCanvas) to extract the log from the ‘App’ in the ‘File Sharing’ column. 　　⑤ Drag the log file at the bottom of ‘OOOO’s Documents' to each folder or desktop, 　　　　etc., or select the file and save it by clicking the ‘Save As’ button at the bottom right. 　　　


Please zip the all files and attach them.



Thank you.
Easy & Light

**Comment by RachelOh** [comment]
2023.4.19. 오후 10:33
---
Hallo  EL Display Hub Team,

below my Log-Files. I dont no how i have to do this on my tablet, sorry. I hope you can help me.

Greetings

[el diplay hub windows.zip](https://github.com/edh-git/EL_Display_Hub/files/11278806/el.diplay.hub.windows.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1791] No device connected aqt Windows 11
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

As a result of reviewing the logs and symptoms sent by the customer, no logs related to connection attempts have occurred in the logs on the PC and tablet sides.

First of all, please check if the tablet is properly connected to the PC via USB, and if the PC can access the tablet device.

If it is not properly connected, check the following items.

First, it may be a problem with insufficient power or poor connection of the USB port.
To solve this, try the following measures.
1. Check if the connection between PC and tablet is normal.
2. Replace the USB cable (use a genuine cable if possible, use a cable capable of data communication).
3. Change the USB port connected to the PC (using the rear port).
4. Connect to an external powered USB hub.

Second, it could be an error on the PC side and the Ipad side.
1. Reboot your PC. (Use "Restart" in Shutdown Options)
2. Reboot the iPad. (settings-general-shutdown-later start ipad)

Thirdly, a conflict with iTunes on the PC side may have occurred.
Connection between PC and iPad may fail if iTunes from the Microsoft Store is installed. Please delete iTunes and EL Display Hub and reinstall EL Display Hub.
If you need to use iTunes together, please use iTunes for Windows.
[Apple] Download and use iTunes for Windows: https://support.apple.com/HT210384

If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you

Easy&Light
```
