### ISSUE TITLE
연결불가

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1792]
Product:

Device OS:

e-mail:[3284960085@qq.com](mailto:3284960085@qq.com)

昨天还好好的今天就这样了，重启没效果，重装软件也没效果。我该怎样做？期待您的回复！
어제는 괜찮았는데 오늘은 이렇습니다 다시 시작해도 소용없고 소프트웨어를 재설치해도 소용이 없습니다. 나는 무엇을해야합니까 귀하의 회신을 기대하겠습니다!
![39CB3822@A2E28727 37B01664 png](https://user-images.githubusercontent.com/77039864/226490238-4040a363-b9cb-41a9-a623-5a916059351a.jpg)
![01625A65@2AF5BB12 37B01664 png](https://user-images.githubusercontent.com/77039864/226490241-5de8e154-f91c-470d-939b-e72229714b80.jpg)
![292A040C@15D9F576 37B01664 png](https://user-images.githubusercontent.com/77039864/226490243-dec01096-7df0-4f87-b2be-83f0e2c7075e.jpg)

**Comment by RachelOh** [comment]
로그파일 요청
---
Hello, We are Easy&Light support team.

Please send us the log file.

Our technical team will check the problem and give you a solution.


[Manual log collection procedure]

1. Enter Windows key > "Run" > Enter "msinfo32" > File > Save
2. Files existing in the path C:\ProgramData\devguru
3. A file existing in the path C:\Users\{username}\AppData\Local\Devguru (you can access the path with %localappdata%\Devguru)

Please zip the three files and attach them.

[App log collection procedure]
　1. Android　　① Re-run the application on your device.　　② Tap on the app version at the bottom right of the main page about 10 times, then make sure a created log zip file named 'bypd.log.archived.yyyymmddhhmmss.zip' in Download folder on your device.

　2. iOS　　① Connect the device to extract the logs to a PC.　　② Run iTunes and click it when the connected device appears on the upper tap.　　③ Click ‘File Sharing’ in the list to the left.　　④ Scroll down the updated screen and click the app (EasyCanvas) to extract the log from the ‘App’ in the ‘File Sharing’ column. 　　⑤ Drag the log file at the bottom of ‘OOOO’s Documents' to each folder or desktop, 　　　　etc., or select the file and save it by clicking the ‘Save As’ button at the bottom right. 　　　


Please zip the all files and attach them.



Thank you.
Easy & Light

**Comment by RachelOh** [comment]
2023.3.21. 오후 2:29
---
thanks for reply.

[log.zip](https://github.com/edh-git/EL_Display_Hub/files/11035066/log.zip)

**Comment by RachelOh** [comment]
2023.3.25. 오후 4:04
---
Still not working properly.
Looking forward to your reply.
[新建文件夹.zip](https://github.com/edh-git/EL_Display_Hub/files/11073608/default.zip)

**Comment by RachelOh** [comment]
2023.4.3. 오후 3:05
---
我似乎找到了问题所在，首先，我没有显示器，因为我在学校，我想直接用ipad做显示器。或许是因为没有显示器的缘故无法连接，现在，我先用“parsec”这个软件远程控制我的pc，这会使pc创建一个虚拟屏幕，此时，连接到pc并且已经打开easycanvas的ipad会出现pc的屏幕。所以我现在已经可以使用了，虽然很麻烦，我尝试过用其他方法的创建一个虚拟屏幕，但是没有作用，我不知道这是为什么，所以想请教一下贵公司。另外，我看到了“easylight”创建的有线屏幕刷新率是120hz，但是肉眼观测明显没有120hz。我使用“testufo”这个网站测试屏幕刷新率只有64hz左右并且看上去似乎并不稳定，相较于30hz并没有很大差距。我想知道如何真正用到120hz。（我的ipad支持120hz并且使用的有线连接）

I seem to have found the problem. First of all, I don't have a monitor because I'm at school and I want to use my iPad directly as a monitor. Perhaps it is because there is no display that I cannot connect. Now, I will use the" parsec "software to remotely control my PC, which will cause the PC to create a virtual screen. At this time, an iPad connected to the PC and already opened easycanvas will display the screen of the PC. So I am now ready to use it. Although it is troublesome, I have tried other methods to create a virtual screen, but it has no effect. I don't know why, so I would like to consult your company. In addition, I have seen that the refresh rate of the wired screen created by "easilight" is 120 hz, but it is obviously not as high as 120 hz by naked eye observation. "I used the website" testufo "to test that the screen refresh rate was only around 64 hz and seemed unstable, not much different from 30 hz.". I want to know how to actually use 120 hz. (My iPad supports 120 hz and uses a wired connection)

[easycanvas.zip](https://github.com/edh-git/EL_Display_Hub/files/11143604/easycanvas.zip)

**Comment by james-kim-Devguru** [comment]
* 현재 EL Display Hub의 fps가 30, 45, 60으로 설정되어 있음
* 가상 화면 확장이 모니터 없이 가능한지 확인필요

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1792] Unable to connect
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, I'm really sorry for the very late reply.

Only EasyCanvas can be used without a connected monitor.
After connecting EasyCanvas in an environment where the existing monitor exists, set the screen to extended and check if the extended screen is normal.
Afterwards, if the existing monitor is removed, the screen is output only through EasyCanvas.

Currently, EasyCanvas supports 30hz, 45hz, and 60hz, but 120hz is not yet supported.

Thank you

Easy&Light
```
