### ISSUE TITLE
윈도우 프로그램 화면 선택에서 확장 모드가 되지 않습니다.

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1795]
Product:Twomon SE

Device OS:iOS

e-mail:[onenife@hanmail.net](mailto:onenife@hanmail.net)

Window 10 Pro, 사양은 AMD Ryzen 5 4600U with Radeon Graphics 2.10 GHz, RAM: 16GB 입니다.
iPad Air 4세대 사용 중이며, ios 버전은 16.3.1, usb pd 단자와 연결해서 사용 중입니다.

아이패드 앱스토어에서 다운을 받아서 처음 몇번 썼을 때는 확장 모드가 실행되다가 어느 순간부터는 확장모드를 선택을 하면, 화면이 깜빡이다가 확장모드는 사라지고, Display 1만 뜨고 메뉴에는 다른 모니터는 보이지가 않습니다. 다시 실행했을 때도, 문제는 같으며, 윈도우 프로그램을 삭제했다가 재설치를 하여도 같았습니다. (사실 이렇게 된지는 꽤 오래되었습니다.)
복제 화면이 되는 것에 만족하며 쓰고는 있지만, 확장을 이유로 산 것도 있기에, 생각보다 활용도가 떨어져 현재는 거의 사용하지 않다시피 하고 있습니다.
이유와 문제, 그리고 해결 방법은 없는지 궁금해서 문의를 합니다.

[EL_Display_c46a8c82-4d88-48e6-a826-e7e62061625e.zip](https://github.com/edh-git/EL_Display_Hub/files/11024003/EL_Display_c46a8c82-4d88-48e6-a826-e7e62061625e.zip)
[Devguru.zip](https://github.com/edh-git/EL_Display_Hub/files/11024004/Devguru.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1795] 윈도우 프로그램 화면 선택에서 확장 모드가 되지 않습니다.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그를 검토한 결과 OS 측에서 확장 모니터에 대한 복제로 동작 중인 점을 확인하였습니다.
다음과 같은 방식으로 확장 모드를 실행하여 주십시오.

1. EL Display Hub에서 "화면 선택"의 디스플레이 리스트에서 "확장" 목록을 선택해 확장 시도합니다.
2. 확장에 실패한 상황을 확인합니다. (확장 항목이 사라졌으며, 화면은 복제중인 상태)
3. "설정" - "시스템" - "디스플레이"로 진입하여 "다중 디스플레이"항목을 "바탕 화면을 이 디스플레이에 확장"을 사용하게 변경합니다.
    또는 "Windows키" + "P" 키를 통해서 "확장"을 선택 합니다.
    - 해당 상황에서 화면이 깜빡거리거나 연결이 해제되는 등의 문제가 발생할 수 있습니다.
    - 화면이 깜빡거린 뒤, 디스플레이 드라이버 관련 오류가 출력될 수 있습니다.
4. PC를 재부팅합니다.
5. EL Display Hub의 "화면 선택"의 디스플레이 리스트의 "확장"을 선택하여 다시 화면 확장을 시도합니다.


위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 로그 취득 가이드를 참조하여 PC로그와 어플리케이션 로그를 첨부하여 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
