### ISSUE TITLE
pc service

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1798]
Product:EasyCanvas

Device OS:iOS

e-mail:[monomarsh@yahoo.com](mailto:monomarsh@yahoo.com)

just installed the new update and get a "pc service" error message right away. I appreciate the attempt, but TRY AGAIN PLEASE. Would love for this application to work properly ;)

[EL_Display_b5246596-d602-47dd-8b2d-8c83ed7095eb.zip](https://github.com/edh-git/EL_Display_Hub/files/11024060/EL_Display_b5246596-d602-47dd-8b2d-8c83ed7095eb.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1798] pc service
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

In that case, the program appears to be corrupted during the update installation process.

To solve this, try the following measures.
1. Delete "EL Display Hub"
2. Reboot PC (Use "Restart" in Shutdown option)
3. Download the new installer and reinstall "EL Display Hub"
[EL Display Hub] installation page: http://www.easynlight.com/en/easycanvas/

If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporttwomon/?faq=78

Thank you

Easy&Light
```
