### ISSUE TITLE
갑자기 연결이 안됩니다. 도와 주세요!

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1814]
Email : [bluepoet72@gmail.com](mailto:bluepoet72@gmail.com)
Device OS: Android
Product: Twomon SE

전 엘지그램 2020년 형을 쓰고 있습니다. 기존에 윈도우10으로 된 윈도우 노트북에서 삼성 갤럭시탭s8 울트라를 연결해서 사용하고 있는데 노트북이 강제로 갑자기 윈도우11로 업그레이드가 된 이후 연결이 안되고 있습니다. 프로그램을 모두 삭제하고 재설치해도 안되네요. 왜 그럴까요?

[EL_Display_83e3d470-0a7e-4388-abd2-989704c20c9c.zip](https://github.com/edh-git/EL_Display_Hub/files/11058528/EL_Display_83e3d470-0a7e-4388-abd2-989704c20c9c.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1814] 갑자기 연결이 안됩니다. 도와 주세요!
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그를 검토한 결과 안드로이드 측의 "USB 디버깅" 옵션이 제대로 적용되지 않은 것으로 보입니다. 

아래의 링크를 참조하셔서 "USB 디버깅"을 허용해주십시오.

[FAQ] 'USB 디버깅' 권한을 허용하거나 'USB 디버깅 권한 승인 취소'한 후 다시 시도 (Android) : http://www.easynlight.com/supporttwomon/?faq=123

이후에도 동작하지 않을 경우 PC와 안드로이드 디바이스 모두 재부팅하여 주십시오.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```
