### ISSUE TITLE
안녕하세요. 문의드립니다.

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1816]
Email : [ultramarin6@naver.com](mailto:ultramarin6@naver.com)
Device OS: iOS
Product: EasyCanvas

이번에 신티크에서 새로이 아이패드로 넘어오면서 귀사의 제품을 이용하게 되었습니다.

무난히 잘 작동하여 만족스럽게 작업했습니다.

다만 아이팬슬의 각 스트로크 별로 미세한 순간 지연이 있는 것 같습니다. 살짝 꺾인 선이 확인됩니다. 첨부파일 보냅니다.

이를 해결하기 위해서 좀 더 양질의 C타입 케이블을 구매 해 볼 생각입니다만,

문의도 같이 남깁니다.

개인적으로 시도 해 볼 수 있는 방법들이 있다면 가르쳐 주시면 좋겠습니다.

또한 프로그램의 개선도 이루어지길 바랍니다.

앞으로도 잘 쓰겠습니다. 감사합니다.

<img width="737" alt="스크린샷 2023-03-25 082514" src="https://user-images.githubusercontent.com/77039864/227815717-0f7e1c1c-0865-4379-b98e-205958f5e30b.png">

[EL_Display_2c9f0169-9d8f-451a-85e6-225bffbe1d72.zip](https://github.com/edh-git/EL_Display_Hub/files/11073565/EL_Display_2c9f0169-9d8f-451a-85e6-225bffbe1d72.zip)

**Comment by james-kim-Devguru** [comment]
---
#### 제목
```
Re: [EasyCanvas - 1816] 안녕하세요. 문의드립니다.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 답변이 많이 늦어진 점 정말 죄송합니다.

문의 주신 내용인 미세한 지연의 경우, 그래픽 카드의 성능 문제로 추측됩니다.
현재 연결된 모니터 2대의 해상도가 각 4K, QHD며, 추가로 EasyCanvas가 연결된 상태로 보입니다.
EasyCanvas의 화면을 캡처하여 인코딩하는 과정이 그래픽 카드를 통해 이뤄지며,
출력 중인 모니터의 개수 및 해상도에 영향을 받아 미세한 지연이 발생할 수 있습니다.
또한 EasyCanvas의 옵션이 FHD로 선택되어 현재는 미세한 지연이지만, 최고 해상도로 선택한 경우 지연이 더 심해질 수도 있습니다.

추가로 문의 주신 USB 케이블의 경우 USB 3.0 이상의 케이블을 사용하는 경우 좀 더 나은 성능을 제공할 수 있습니다.


추가로 궁금한 사항이 있으신 경우, 언제든 문의주세요.

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```
