### ISSUE TITLE
TwomonSE asus 게이밍 노트북 GPU모드 문의

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1819]
Email : [guong0911@gmail.com](mailto:guong0911@gmail.com)
Device OS: iOS
Product: Twomon SE

현재 Asus RogFlow x16 을 사용중입니다. TwomonSE 어플을 사용하여 아이패드를 보조모니터로 연결할 때 노트북의 GPU 모드를 표준모드로 설정하면 연결이 되지만, Ultimate로 변경하면 'USB장치에 더 많은 전력이 필요할 수 있습니다' 라는 메시지와 함께 연결이 되지 않습니다.

<img width="244" alt="스크린샷 2023-03-26 163801" src="https://user-images.githubusercontent.com/77039864/227817220-2efbfe9f-a46c-450f-a939-d3642ee9791a.png">

[EL_Display_68e17f14-43d4-48ec-a7b7-1ce36fdf8f46.zip](https://github.com/edh-git/EL_Display_Hub/files/11073622/EL_Display_68e17f14-43d4-48ec-a7b7-1ce36fdf8f46.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1819] TwomonSE asus 게이밍 노트북 GPU모드 문의
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 화면 캡처 부분이 정상적으로 동작하지 않는 것을 확인하였습니다. 
노트북의 이산 GPU 환경에서 발생할 수 있는 문제입니다.

우선 증상이 발생할 때 재설치를 통하여, 인스톨러에서 해당 문제를 해결할 수 있는 옵션을 설정하게 시도하여 주십시오.

재설치 이후에도 해결이 되지 않을 경우 그래픽 드라이버의 옵션을 설정하여 해결이 가능합니다. 
링크를 참조하셔서 옵션을 "통합 그래픽"으로 변경해주시길 바랍니다.

[FAQ : Twomon SE가 동작하지 않습니다.] "NVIDIA 제어판에서 3D 설정 변경해주세요" : http://www.easynlight.com/supporttwomon/?faq=123
    * 등록 필요 프로그램 : C:\Program Files (x86)\EL Display Hub\EL_Display_service_proc.exe


위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

Ea​​sy&Light 
```
