### ISSUE TITLE
Extended screen failure

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1839]
Email : [haolunxu045@gmail.com](mailto:haolunxu045@gmail.com)
Device OS: iOS
Product: Twomon SE

Hi there,
I just bought Twomon SE for my Windows PC and ipad (ios), and I intended to use my ipad as a extended screen. I followed the instruction on your website saying that hit "Win + P" to set my ipad as an extende screen, but it seemed that my PC couldn't detect my ipad because there was no response when hitting "extend" on the side bar, the ipad could only copy the screen from my Windows PC. After that I tried to connect the two devices again, but the PC program kept saying "incorrectly installed". I wondered if it was because I didn't install the correct usb driver, and I checked thev official website again, but the apple driver is unavaliable on Windows (it's itunes). By the way, the cable I am using is a usb-c cable. Couldyou help to figure out what's wrong with my devices?

[EL_Display_e2197d40-7575-4ea6-84eb-e34ee02c25c2.zip](https://github.com/edh-git/EL_Display_Hub/files/11154299/EL_Display_e2197d40-7575-4ea6-84eb-e34ee02c25c2.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1839] Extended screen failure
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

As a result of reviewing the log sent by the customer, it was confirmed that the OS was operating as a replication for the extended monitor.
Execute extended mode in the following way.

1. In EL Display Hub, try expanding by selecting the "Expand" list from the display list of "Screen Selection".
2. Check the circumstances under which expansion failed. (Expansion items have disappeared, and the screen is being duplicated)
3. Go to "Settings" - "System" - "Display" and change the "Multiple displays" item to "Extend the desktop onto this display".
     Or select "Extension" through "Windows key" + "P" key.
     - In that situation, problems such as screen flickering or disconnection may occur.
     - After the screen flickers, an error related to the display driver may be displayed.
4. Reboot your PC.
5. Try extending the screen again by selecting "Expansion" from the display list of "Select Screen" of EL Display Hub.


If the problem is not improved even after taking the above measures, please refer to the Log Acquisition Guide and attach the PC log and application log and ask again.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

Once again, we apologize for any inconvenience caused.
We will try to make better products.

Thank you

Easy&Light
```
