### ISSUE TITLE
Windows 11 - Blank Screen on iPad and Cannot get back to Extend Mode

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1846]
Email : [ericwatk@outlook.com](mailto:ericwatk@outlook.com)
Device OS: iOS
Product: EasyCanvas

Dear DevGuru,

I bought the sub for EasyCanvas and Twomon. Twomon work reliably. EasyCanvas with USB is a problem. When first installed, upon connection to hub, it shows a blank screen on the iPad, only the toolbar is visible. After fiddling with display options in Windows 11, I made the mistake of trying only on the iPad instead of extend monitors. Now, whenever it connects, my main windows monitor goes black (loses signal) and the iPad has the same black screen with only the toolbar.

[EL_Display_189764d7-bc48-49a6-a1a5-b2790d48238d.zip](https://github.com/edh-git/EL_Display_Hub/files/11186757/EL_Display_189764d7-bc48-49a6-a1a5-b2790d48238d.zip)

**Comment by james-kim-Devguru** [comment]
* proc에서 잘못되 display를  capture하려고 시도함
    * display4가 확장된 display인데 display7를 캡처하려고함

* 두 번째 화면에만 표시하게 설정한 것 같은데, 해당 문제는 win + p 단축키를 통해서 수정안내 필요

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1846] Windows 11 - Blank Screen on iPad and Cannot get back to Extend Mode
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, I'm really sorry for the very late reply.

After reviewing the logs you sent us, it appears that the problem is that the connection is unstable and the wrong display is being selected as a result of repeated connecting and disconnecting several times.

The problem is suspected to be a lack of power in the USB port or a bad connection problem.

"Screen transfer" is a large amount of data processed through USB, so even if the connection between the PC and the device looks normal, actual communication may fail.

To solve this, try the following measures.
1. Check if the connection between PC and tablet is normal.
2. Replace the USB cable (use a genuine cable if possible).
3. Change the USB port connected to the PC (using the rear port).
4. Connect to an external powered USB hub.


Also, when connected, only the iPad side is displayed, but if it is difficult to use because it does not work normally, try changing the screen settings of windows even if it is not visible through "Windows key + P" after connecting to expand or duplicate.

If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporttwomon/?faq=78

Thank you

Easy&Light
```

**Comment by james-kim-Devguru** [comment]
#### 한글 원본
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 답변이 많이 늦어진 점 정말 죄송합니다.

고객님께서 보내주신 로그를 검토한 결과 연결이 불안정하여 여러 차례 연결 및 해제가 반복된 결과 잘못된 디스플레이가 선택되는 문제로 보입니다.

해당 문제는 USB포트의 전력 부족 혹은 연결 불량 문제로 의심됩니다.

"화면 전송"은 USB를 통해 처리되는 데이터의 양이 많아서, PC와 디바이스 간의 연결이 정상적으로 보여도 실제 통신에는 실패할 수 있습니다.

이를 해결하기 위해 아래의 사항들을 조치해보십시오.
1. PC와 태블릿 간의 연결이 정상적인지 확인합니다.
2. USB 케이블 교체(가능한 정품 케이블 사용)합니다.
3. PC에 연결된 USB 포트 변경(후면 포트 이용)합니다.
4. 외부전원 USB 허브에 연결합니다.


또한 연결 시 아이패드 측만 표시되지만 정상적으로 동작하지 않아 사용이 어려운 경우, 연결 후 "Windows키 + P"를 통해서 보이지 않더라도 windows의 화면 설정을 변경하여 확장이나, 복제 등으로 변경하는 시도를 하여 주십시오.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/en/supporttwomon/?faq=78

감사합니다.

Ea​​sy&Light 
```

**Comment by RachelOh** [comment]
2023.5.14. 오후 4:45
---
Thanks indeed Easy&Light

 

I’ll try another cable with the extremely old 32 bit A1430 iPad, although, I have been using Twomon reliably with the A1430 at a high resolution, via the cable concerned.

 

I bought a newer second hand 64bit iPad from the Apple Pre-Owned store (plus a Zagg Stylus) and there is no problem with Easy Canvas at a high resolution, using a cable. As a result of test connecting the new iPad, I was able to get Windows out of blank screen mode when using Easy Canvas, yet the keyboard shortcut shall help in future.

 

You should not be mistaken about Twomon and Easy Canvas as being good value for money, with very old and new iPads. I am particularly impressed that Easy&Light products can display reasonably fast at the native resolution of the iPad, although this requires me to wear glasses.

 

All the best and keep well,
