### ISSUE TITLE
twomon se에서 보장하는 케이블 연결 속도

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1889]
Email : [3.14159265@khu.ac.kr](mailto:3.14159265@khu.ac.kr)
Device OS: iOS
Product: Twomon SE

안녕하세요, twomon se를 구매하고 신세계를 체험중인 대학생입니다....만!
저의 현재 pc인 갤럭시북3pro(썬더볼트3지원)와 아이패드12.9 5세대(썬더볼트3지원)로 연결 중, 사용중인 구형 케이블의 전송속도가 문제가되어 화질이 저하되는 문제가 발생하고있는 것 같습니다! 따라서 케이블을 40Gbps를 지원하는 최신 썬더볼트3 규격으로 구매하려하는데, 혹시 twomon se에서 지원하는 최대 케이블 속도가 이보다 낮아 문제가 해결되지않을 수 있을까요?

[EL_Display_a7ab2872-01d9-49a6-bd4a-76f73b6babff.zip](https://github.com/edh-git/EL_Display_Hub/files/11305495/EL_Display_a7ab2872-01d9-49a6-bd4a-76f73b6babff.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1889] twomon se에서 보장하는 케이블 연결 속도
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 답변이 많이 늦어진 점 정말 죄송합니다.

문의주신 내용인 케이블 속도의 경우 OS와 기기 특성마다 동작이 다르며,
Twomon SE의 경우 USB 통신을 사용하여 케이블이 좋아지는 경우 성능이 향상될 수는 있습니다.
다만, 화면 전환이 많은 작업(게임 등)과 해상도가 매우 높은 경우를 제외하면 USB 2.0 정도로도 사용이 가능하며 USB 3.0을 통해서는 원할한 사용이 가능합니다.

현재 수집된 로그상 화질 저하를 느끼시는 이유는 가상 디스플레이의 해상도가 ipad 측의 실제 표시하는 디스플레이의 해상도보다 낮아서 발생하는 문제로 보입니다.
해당 문제를 해결하기 위해서는 EL Display Hub로 아이패드에 표시하는 화면의 해상도를 가장 높은 해상도로 설정하시면 해결 될 것으로 보입니다.

위와 같은 조치사항들을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporttwomon/?faq=121

더 좋은 제품을 만들기 위해 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```
