### ISSUE TITLE
화면 확장설정

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1894]
Email : [xraccoonx@naver.com](mailto:xraccoonx@naver.com)
Device OS: Android
Product: Twomon SE

화면 확장 설정 문의드립니다.

태블릿을 보조모니터로 사용하려 앱을 구매해서 설치 완료했습니다.
PC 설정창 화면선택에서 확장을 선택하니 제대로 실행되었습니다.
헌데, 컴퓨터를 재부팅하거나 껏다 켜면 화면선택이 확장으로 되어있는 것이 아니라 자꾸 다른 모니터 복제화면으로 바뀝니다.
왜 이런걸까요?

[EL_Display_ab5791d0-64e8-4e4b-90d8-4bcf68e80b8b.zip](https://github.com/edh-git/EL_Display_Hub/files/11305553/EL_Display_ab5791d0-64e8-4e4b-90d8-4bcf68e80b8b.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1894] 화면 확장설정
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 답변이 많이 늦어진 점 정말 죄송합니다.

보내주신 로그와 증상을 검토한 결과, 타 프로그램과의 충돌로 인한 문제로 확인됩니다.
화면 공유 프로그램이나 화면 캡처 혹은 녹화 기능이 있는 프로그램과 함께 사용할 경우 충돌이 발생할 수 있습니다.

현재 로그상 Display Link 장치가 존재하여 화면 확장이나 캡처 등에서 오류가 발생하여 재시도 과정에서 복제로 설정되는 것으로 보입니다.

해당 장치와 프로그램을 삭제 후에도 동일한 이슈가 발생되는지 확인부탁드립니다.

위와 같은 조치사항들을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light 
```
