### ISSUE TITLE
getting A0011001 then A0011002

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1904]
Email : [christophe.marchina@gmail.com](mailto:christophe.marchina@gmail.com)
Device OS: iOS
Product: EasyCanvas

Hello, I managed to get easycanvas run on a different PC but no luck here. Seems that service EL display Hub is supposed to start automatically but it doesnt. Then I start it manually then I get 11002 error. Thanks for your help BR -- cm

[EL_Display_17df5c2f-77bb-42ae-8c24-1feb4ad712ba.zip](https://github.com/edh-git/EL_Display_Hub/files/11338401/EL_Display_17df5c2f-77bb-42ae-8c24-1feb4ad712ba.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1904] getting A0011001 then A0011002
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

After reviewing the logs and symptoms sent by the customer, it seems to be a problem of failing to obtain screen information from the display being used.

To solve this, try the following measures.

1. Delete "EL Display Hub"
2. Check for Windows updates and update to the latest Windows
3. Update graphics driver
     [Intel] Driver Support Program: https://www.intel.com/content/www/us/en/download-center/home.html
     [AMD] Graphics driver installation page: https://www.amd.com/support
     [NVIDIA] Graphics driver installation page: https://www.nvidia.co.kr/Download/index.aspx
4. Reboot PC (Use "Restart" in Shutdown option)
5. Download the new installer and reinstall "EL Display Hub"
     [EL Display Hub] installation page: http://www.easynlight.com/easycanvas/

If the same problem occurs after reinstallation, change the cable connecting the monitor to the PC or change the port.

We will always strive for better products and services.
Thank you

Easy&Light
```

**Comment by RachelOh** [comment]
2023.5.3. 오후 4:54
---
Hello,

Thank you for contacting me back.

Your analysis is totally right : no physical screen device is connected to this PC. 

It’s only when I connect one screen through hdmi that I can start using easy canvas.

Does that mean that easy Canva could be enhanced to work without a connected screen ? Or it’s just impossible ?

Thanks for your assistance !

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1904] getting A0011001 then A0011002
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, I'm really sorry for the very late reply.

Only EasyCanvas can be used without a connected monitor.
After connecting EasyCanvas in an environment where the existing monitor exists, set the screen to extended and check if the extended screen is normal.
Afterwards, if the existing monitor is removed, the screen is output only through EasyCanvas.

Thank you

Easy&Light
```

**Comment by RachelOh** [comment]
2023.5.16. 오후 9:36
---
Hello, no worries about the delay. Thanks for answering me !
That is an interesting workaround you mentioned but it cannot apply to me as my server is ( sort of ) hosted in a data center with no screen attached to it. 
Maybe an enhancement to easy canvas might be to remove this physical device dependency completely ? Br — cm

**Comment by james-kim-Devguru** [comment]
@RachelOh 
헤드 리스 시스템에서 자동으로 확장 모드로 실행되어 이지 캔버스를 메인 모니터로 사용하게 해달라는 의견입니다.
다음과 같이 답변해도 되는지 검토 부탁드리며, 
해당 기능을 검토해야하는 경우 알려주시면, 다음 시즌 개발을 위해 이슈로 등록해두겠습니다.

해당 사용자에게 아래와 같이 회신할 예정입니다.
---
#### 제목
```
Re: [EasyCanvas - 1904] getting A0011001 then A0011002
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

We need additional review to see if the feature suggested by the customer can be implemented, and we plan to review the proposal within the team.

At this time, it is not possible to clearly say whether the proposed function will be reflected in future services.

Thank you

Easy&Light
```

#### 한글 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

고객님께서 제안해주신 기능에 대해 구현이 가능한지 추가로 검토가 필요하며, 
팀 내부에서 해당 제안에 대해서 검토를 진행할 예정입니다.

현재로서는 제안하신 기능을 향후 서비스에 반영될지에 대해 명확히 말씀드릴 수 없는 상황입니다.

감사합니다.

Easy&Light
```

**Comment by RachelOh** [comment]
@james-kim-Devguru 
네 위 내용대로 답변해도 좋을 것 같습니다
