### ISSUE TITLE
Windows app crashing without error message

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1905]
Email : [piotrherbich@wp.pl](mailto:piotrherbich@wp.pl)
Device OS: iOS
Product: EasyCanvas

Hello,
I want to use app as external display, or duplicate of a main display - PSA.
App used to work fine before update to \"el display hub\" - now it\'s crashing few seconds after booting. There are no conflicting software - PSA. Diagnosis run - PSA results.
Multiple reboots and reinstalls have been done.
Windows application is crashing regardless, if ipad is connected via usb or not, and regardless of setting chosen in \'el display hub\'
Please assist,
Thank you

/example from logs from ipad app will be inputted below. I\'m unable to attach logs from windows app, as it\'s constantly crashing - I cannot make this ticket from the application \'inquiry\' tab

[logs-from-ipad.txt](https://github.com/edh-git/EL_Display_Hub/files/11338444/logs-from-ipad.txt)
[logs-from-ipad1.txt](https://github.com/edh-git/EL_Display_Hub/files/11338445/logs-from-ipad1.txt)
![Zrzut-ekranu-2023-04-26-152231](https://user-images.githubusercontent.com/77039864/234731900-b39d6011-4fd9-4a6b-8dc7-11faa5c76866.jpg)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1905] Windows app crashing without error message
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

In that case, the program appears to be corrupted during the update installation process.

To solve this, try the following measures.
1. Delete "EL Display Hub"
2. Reboot PC (Use "Restart" in Shutdown option)
3. Download the new installer and reinstall "EL Display Hub"
[EL Display Hub] installation page: http://www.easynlight.com/en/easycanvas/

If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporttwomon/?faq=78

[Manual log collection procedure]
Please zip and attach the three files.
1. Enter Windows Key > "Run" > Enter "msinfo32" > File > Save
2. Files that exist in the C:\ProgramData\devguru path
3. Files in the path C:\Users\{username}\AppData\Local\Devguru (you can access the path with %localappdata%\Devguru)

We will always strive for better products and services.
Thank you

Easy&Light
```
