### ISSUE TITLE
PC 프로그램 설치 오류 (빠른 답변 요망)

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1908]
Email : [fresh0630@hanamail.net](mailto:fresh0630@hanamail.net)
Device OS: Android
Product: Twomon SE

Twomon SE PC프로그램 (El display Hub) 설치를 다시 계속 해봐도 오류메세지가 뜨고 모바일(안드로이드 태블릿) 기기와 연결이 되지 않습니다.
어제 문의남겼는데 답변이 없어서 다시 문의드립니다. 빠른 시간 내에 답변 부탁드립니다.

[EL_Display_6e05986b-1699-4e0e-aca5-1fba6ab81d23.zip](https://github.com/edh-git/EL_Display_Hub/files/11368816/EL_Display_6e05986b-1699-4e0e-aca5-1fba6ab81d23.zip)
![그림1](https://user-images.githubusercontent.com/77039864/235554864-d5835a05-0c7b-4f25-bf0d-287db3298595.png)

**Comment by RachelOh** [comment]
2023.4.27. 오후 1:17
---
Twomon SE PC 프로그램 (El display hub) 설치를 계속 다시 해봐도 설치오류 메세지가 뜨고 모바일 기기 (안드로이드 태블릿
과 연결이 되지 않습니다. 어제 문의남겼는데 답변이 없으셔서 빠른 답변 부탁드립니다.


[EL_Display_f684d757-99f1-4da9-b09f-5b33435625bf.zip](https://github.com/edh-git/EL_Display_Hub/files/11368820/EL_Display_f684d757-99f1-4da9-b09f-5b33435625bf.zip)
)

**Comment by RachelOh** [comment]
2023.4.27. 오후 2:10
---
Twomon SE PC 프로그램(El display hub) 설치시 계속 오류메세지가 뜨고
모바일 기기(안드로이드 태블릿)과의 연결이 안됩니다.
해결방법 관련하여 빠른 답변 부탁드립니다.

로그파일 추출 관련하여 아래 가이드를 보고 모바일 기기에서는 확인이 되어 첨부드립니다.
그런데 PC에서 로그파일 추출은 아래 가이드에 있는대로 따라 해보았지만 확인이 되지 않습니다.
--------------------------------------------
3. 수동 로그 추출 방법

[PC 로그]
　　1. Windows키 입력 → \"실행\" → \"msinfo32\" 입력 → 파일 →저장
　　2. C:ProgramDatadevguru 경로에 존재하는 파일
　　3. C:Users{사용자명}AppDataLocalDevguru 경로에 존재하는 파일 ( %localappdata%Devguru 로 경로에 접근 가능)
------------------------------------------------------

확인할 수 있는 다른 방법을 알려주시면 감사하겠습니다.
(PC에서 로그파일 추출이 안되는데 첨부를 안하면 문의 자체가 되지 않아서
PC프로그램 진단 관련한 내용으로 대체하여 첨부드립니다.

[TwomonSE.log.archived.202304271327541.zip](https://github.com/edh-git/EL_Display_Hub/files/11368830/TwomonSE.log.archived.202304271327541.zip)
![그림2](https://user-images.githubusercontent.com/77039864/235555131-81ed32a9-9798-442f-b18a-bc2ad6f937be.png)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1908] PC 프로그램 설치 오류
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 iPad와 유선 연결에 사용되는 AMDS가 중지되어 있는 것으로 파악되었습니다.

우선, 아래의 링크를 참조하여 해당 프로그램을 재시작하여 주시길 바랍니다.
[FAQ] Twomon SE PC프로그램이 실행되지 않습니다. : http://www.easynlight.com/supporttwomon/?faq=124

'서비스'에서 Apple Mobile Device Service의 상태가 '실행 중' 인지 확인(iOS)
　　1. Ctrl + Alt + Delete키를 눌러 '작업 관리자'를 실행
　　2. [서비스]탭을 누른 후 이름이 'Apple Mobile Device Service'인 서비스의 상태가 '실행 중'인지 확인
　　3. 서비스의 상태가 '중지됨'일 경우 마우스 오른쪽 버튼을 클릭하여 서비스를 '시작' 혹은 '다시 시작'하여 서비스가 실행되는지 확인
　　4. 서비스 상태가 '실행 중'으로 변경되면 Twomon SE PC프로그램을 재실행


계속 AMDS(Apple Mobile Device Service) 실행 실패의 경우 사용중이신 보안 프로그램에서 AMDS의 실행을 발행하는 것일 수 있습니다. 사용하시는 보안 소프트웨어가 있으시다면 설정을 통해서 AMDS와 EL Display Hub를 허용 혹은 예외 설정을 부탁립니다.

보안 프로그램의 문제가 아닐 경우 아래의 링크와 같이 Apple에서 제공하는 "Windows에서 AMDS 재시작하기"를 참조하여 AMDS를 재시작 부탁드립니다.
[Apple FAQ] : https://support.apple.com/ko-kr/HT203188

1. iTunes를 닫고 현재 연결된 iPhone, iPad 또는 iPod의 연결을 모두 분리합니다. 
2. 컴퓨터의 키보드에서 Windows 로고 키와 R 키를 동시에 눌러 실행 명령에 접근합니다.
3. services.msc를 입력하고 '확인'을 클릭합니다. 서비스 콘솔이 열립니다. 
4. 'Apple Mobile Device 서비스'를 마우스 오른쪽 버튼으로 클릭하고 바로 가기 메뉴에서 '속성'을 클릭합니다.
5. 시작 유형 팝업 메뉴를 '자동'으로 설정합니다.
6. 서비스 상태에서 '중지'를 클릭합니다.
7. 서비스가 중지되면 서비스에서 '시작'을 클릭합니다.
8. '확인'을 클릭합니다.
9. 컴퓨터를 재시동합니다.


위 가이드의 조치 이후에도 AMDS가 제대로 동작하지 않으실 경우에는 AMDS를 재설치하기 위하여 아래의 지침에 따라서 EL Display Hub를 재설치 해주시길 바랍니다.
1. 프로그램 제거 또는 기능에서 "EL Display Hub"를 제거합니다.
2. 아래의 항목의 프로그램이 있을 경우 해당 프로그램도 제거합니다.
    - "Apple Mobile Device Support"
    - "Apple 응용 프로그램 지원(32비트)"
    - "Apple 응용 프로그램 지원(64비트)"
3. PC를 재부팅합니다. (종료 옵션의 "다시 시작" 사용)
4. EL Display Hub를 재설치 합니다. (최신 인스톨러를 다운받아서 사용해주십시오.)
    [EL Display Hub 설치 링크] : http://www.easynlight.com/easycanvas/

위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 로그 취득 가이드를 참조하여 PC로그와 어플리케이션 로그를 첨부하여 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
