### ISSUE TITLE
연결시 장치 찾을 수 없음

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1910]
Email : [seein1123@daum.net](mailto:seein1123@daum.net)
Device OS: iOS
Product: Twomon SE

유에스비 연결과 동시 프로그램 실행하여도 연결장치가 전혀 뜨지 않습니다.
- ipad os 16 ver, MP213KH/A, IPAD PRO(12.9-inch) (6th generation)

![캡처1](https://user-images.githubusercontent.com/77039864/235555757-f4651d5e-f5ab-48b2-aba3-c0aa531b1b22.JPG)
[EL_Display_7d062123-6db4-4632-9293-ee6da6393262.zip](https://github.com/edh-git/EL_Display_Hub/files/11368847/EL_Display_7d062123-6db4-4632-9293-ee6da6393262.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1910] 연결시 장치 찾을 수 없음
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

보내주신 로그와 증상을 검토한 결과, EL Display Hub 프로그램의 백그라운드 서비스 일부가 정상적으로 동작하지 않는 문제를 확인하였습니다.

해당 문제의 경우 보통 타 프로그램과의 충돌로 발생하며, 화면 공유 프로그램이나 화면 캡처 혹은 녹화 기능이 있는 프로그램과 함께 사용할 경우 충돌이 발생할 수 있습니다.

충돌이 발생할만한 프로그램과 "EL Display Hub"를 삭제하신 뒤 PC를 재부팅(종료 옵션의 "다시 시작" 옵션 사용)한 뒤 새로운 인스톨러를 다운로드 받아 "EL Display Hub"를 재설치하여 주십시오.

[Twomon SE] 설치 페이지 : http://www.easynlight.com/twomonse/

위와 같은 조치사항들을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.
또한 좀 더 상세한 로그 파악을 위하여, "PC 시스템 정보 함께 첨부"를 체크하여 주십시오.

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
