### ISSUE TITLE
Error: PC Program service could not be started (Error Code: A0011002)

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1912]
Email : [registration@adrenochrom.com](mailto:registration@adrenochrom.com)
Device OS: iOS
Product: EasyCanvas

Hi,

i get this Message every singe Day on my Windows PC and Laptop.
Both are running the latest Windows 10 Versions.
The Service itself IS running and the Programm is running fine.
Before the switch to this Software everything was fine.
I have deinstalled and reinstalled the Programm and the App several times.
PC programm diagnosis is fine and can`t find any conflicting programs.
All Updates (System and Applications) are the latest versions.
Rebooting several times a day is can not be a solution!
Deinstalling and reinstalling is not a fix!

With the old App everything was fine!

![EasyCanvasCrash](https://user-images.githubusercontent.com/77039864/235556367-68d1fada-eb4b-4a45-a6f1-9ff6aee0c1a3.JPG)
[EL_Display_683af049-8d9e-4e4d-90e6-aeebf4385cb5.zip](https://github.com/edh-git/EL_Display_Hub/files/11368861/EL_Display_683af049-8d9e-4e4d-90e6-aeebf4385cb5.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1912] Error: PC Program service could not be started (Error Code: A0011002)
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

As a result of reviewing the logs and symptoms you sent, we found a problem with conflicts with other programs.

Conflicts may occur when used with screen sharing programs or programs that have screen capture or recording capabilities.

It appears to be conflicting with "Duet Display", one of the currently installed programs.
After deleting "Duet Display" and "EL Display Hub", reboot the PC (use the "Restart" option in the shutdown option), download a new installer and reinstall "EL Display Hub".

[EL Display Hub] installation page: http://www.easynlight.com/en/easycanvas/


If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporttwomon/?faq=78

Thank you

Easy&Light
```

**Comment by RachelOh** [comment]
2023.5.5. 오전 12:12
---
Hi,

 

thanks a lot for your answer !

Duet Display was already deinstalled!

i now have cleaned the Registry Entries of Duet Display, deinstalled EL Display Hub and rebooted my Computer and hope this will help in the future.

 

Anyway, i never had theese Problems with your old Windows App.

 

The EL Display Hup App also looks a little strange.

![image002](https://user-images.githubusercontent.com/77039864/236710887-b53df407-f561-4ec1-8d34-ca88268f1096.png)

Best Regards

 

Ronny
