### ISSUE TITLE
the PC program(EL Display Hub). it does not connect

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1913]
Email : [shopsweb@gmail.com](mailto:shopsweb@gmail.com)
Device OS: iOS
Product: EasyCanvas

Hello I bought your easycanvas app which I installed on an Ipad pro 12.9 (1 generation) which works, but by connecting it to the pc (I downloaded your desktop app EL Display Hub_4.7.3.8_Setup) it does not connect, a message appears saying that the service has not started

Can you help me or refund me please?

Thanks in Advance

Error message : PC Program service cannot be started.
Error code : A0011001, A0011002, A0012001, A0012002, A0012004

[EL_Display_645a750a-40fe-48ae-a86c-cfe47ff713e6.zip](https://github.com/edh-git/EL_Display_Hub/files/11368939/EL_Display_645a750a-40fe-48ae-a86c-cfe47ff713e6.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1913] the PC program(EL Display Hub). it does not connect
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

After reviewing the logs you sent us, it appears that part of the program is not working properly.

For that issue, if it's a temporary error, you can fix it by rebooting your PC ("Restart" in the Shutdown option).

If the temporary solution does not solve the problem, reinstalling the program will solve the problem. Since the installer may be damaged, please download a new installer and reinstall it.
1. Delete EL Display Hub.
2. Reboot your PC. (Use "Restart" in Shutdown Options)
3. Reinstall the latest EL Display Hub installer.
[EL Display Hub] Installation link: http://www.easynlight.com/en/easycanvas/
4. Reinstall EL Display Hub.

If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you

Easy&Light
```

**Comment by RachelOh** [comment]
2023.5.3. 오후 8:50
---
thanks! i fixed it
regards
Francesco Parrello
