### ISSUE TITLE
Calibration Issues

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1914]
Email : [meganoreilly06@gmail.com](mailto:meganoreilly06@gmail.com)
Device OS: iOS
Product: EasyCanvas

hey! i just got easycanvas, and i have been having issues with drawing on my ipads screen. whenever i try to draw on it, there is a good 1/8 of an inch space between where the tip of the apple pencil is on the screen and the line that is being drawn. this is making it very hard to be able to draw using this app, and i would like to hear suggestions on how to fix it. thanks!

[EL_Display_5009b4b6-3d98-40d5-a441-3c0485ab8728.zip](https://github.com/edh-git/EL_Display_Hub/files/11368948/EL_Display_5009b4b6-3d98-40d5-a441-3c0485ab8728.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1914] Calibration Issues
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

It seems that the problem can be solved by adjusting the options of "Touch Coordinate Calibration Item" in the menu of EL Display Hub. (Please test using several options.)

Additionally, if normal coordinates cannot be set due to EL Display Hub option changes, please refer to the link below to change the graphic driver settings.
[FAQ] I touched the screen, but hte coordinates do not match. : http://www.easynlight.com/en/supporttwomon/?faq=85


If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54


Thank you

Easy&Light
```
