### ISSUE TITLE
Resizing canvas smaller than the limit

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1918]
Email : [luke.bruegmann@icloud.com](mailto:luke.bruegmann@icloud.com)
Device OS: iOS
Product: EasyCanvas

Hello,
I want to resize the vanvas on my IPad very small. The normal smallest size is still to big for me. Is it possible to make it even smaller?

[EL_Display_52d1a8d1-daa5-40eb-b57f-63a2cba811df.zip](https://github.com/edh-git/EL_Display_Hub/files/11368991/EL_Display_52d1a8d1-daa5-40eb-b57f-63a2cba811df.zip)
![IMG_5394](https://user-images.githubusercontent.com/77039864/235559277-f5bf05ce-8eaf-4839-8faf-c9b50e512d11.jpg)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1918] Resizing canvas smaller than the limit
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

In Easycanvas, the currently sent image is the minimum size, so it seems difficult to make the screen smaller additionally.

Thank you

Easy&Light
```

**Comment by RachelOh** [comment]
@james-kim-Devguru 
네 괜찮을것 같습니다.
