### ISSUE TITLE
After using the Apple Pencil, the Finger Touch is not recognized anymore

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1924]
Email : [benedo.pro@hotmail.com](mailto:benedo.pro@hotmail.com)
Device OS: iOS
Product: EasyCanvas

Dear Easy & Light Team,

I just started using your amazing App Easy Canvas for iPad, with the basic, standard settings.

Devices used: iPad Pro 11\" 2nd gen - IOS 16.4.1 and Windows 11 (with Nvidia GTX GPU and i7 CPU).

Here is the issue. It is on the iPad side:

As long as I don\'t use the Apple Pencil, I can use my fingers on my iPad and the touch events are well recognized (with a small animated circle when touched). Then, if I use the Apple Pencil it makes all the following finger events not working anymore. And I didn\'t tap the lock button in the inteface. When I close and restart the App on the iPad, fingers work again until I use the Pencil, than fingers are not recognized anymore, etc.

On the PC side, when I restart the app, nothing changes until I restart the app on the iPad.

Could you look up on that and help me please?

Thank you very much, I am at your disposal for any tests you need to perform :)

Bye!

Ben

[com.devguru.bypd-2023-05-01-20-10.log](https://github.com/edh-git/EL_Display_Hub/files/11369036/com.devguru.bypd-2023-05-01-20-10.log)
[com.devguru.bypd-2023-05-01-20-101.log](https://github.com/edh-git/EL_Display_Hub/files/11369038/com.devguru.bypd-2023-05-01-20-101.log)
[com.devguru.bypd-2023-05-01-20-103.log](https://github.com/edh-git/EL_Display_Hub/files/11369044/com.devguru.bypd-2023-05-01-20-103.log)
[com.devguru.bypd-2023-05-01-20-102.log](https://github.com/edh-git/EL_Display_Hub/files/11369047/com.devguru.bypd-2023-05-01-20-102.log)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1924] After using the Apple Pencil, the Finger Touch is not recognized anymore
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

The stylus pens currently supported by EasyCanvas are as follows.
- iPad: Apple Pencil 1, 2

EasyCanvas supports only the genuine Apple Pencil, and if you are using a third-party pen, it may not work properly.

If the supported genuine Apple Pencil does not work normally, remove the Apple Pencil from Bluetooth and connect it again.

If you have any additional questions, please feel free to ask.

We will always strive for better products and services.
Thank you

Easy&Light
```

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1924] After using the Apple Pencil, the Finger Touch is not recognized anymore
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First, I really apologize for the long delay in responding.

In the case of that problem, it seems to be a setting error on the ipad side,
Rebooting the iPad may solve the problem.
If the same problem occurs after rebooting, please remove the connection of "Apple Pencile" from the Bluetooth list, reboot and connect again to check the operation.

If the problem does not improve even after taking the above measures, refer to the log acquisition guide below.
Please inquire again with the 'Application Log'.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

We will try to make better products.
Thank you

Easy&Light
```
