### ISSUE TITLE
ColorMatching Of Displays

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1929]
Email : [alexander.schwindt.1988@gmail.com](mailto:alexander.schwindt.1988@gmail.com)
Device OS: iOS
Product: EasyCanvas

Is it possible to get the same look of colors. It seems like the ipad displays a muted kind of color compaired to my display.
Maybe it is possible to adjust it through giving diferent colorprofiles in the app? Or some kind of setting. My Monitors are running RGB color profile, where as the ipad has P3 i believe.

[EL_Display_b2ecc0b7-c28a-43dd-8f55-9f6fa9e9d8bb.zip](https://github.com/edh-git/EL_Display_Hub/files/11392183/EL_Display_b2ecc0b7-c28a-43dd-8f55-9f6fa9e9d8bb.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1929] ColorMatching Of Displays
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

Easycanvas currently does not support the color adjustment function you inquired about.
[FAQ]: http://www.easynlight.com/en/supporteasycanvas/?pageid=1&mod=list&keyword=color

If you want to change the color of the displayed screen, please modify the options of your tablet.

Thank you

Easy&Light
```

#### 한글 원본
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

Easycanvas에서는 현재 문의 주신 색상 조정 기능을 지원하지 않고 있습니다.
[FAQ] : http://www.easynlight.com/en/supporteasycanvas/?pageid=1&mod=list&keyword=color

표시되는 화면의 색상을 변경하고 싶은 경우 태블릿의 옵션을 수정하여 주십시오.

감사합니다.

Ea​​sy&Light 
```

@RachelOh 
위와 같이 답변하려하는데 검토 부탁드립니다.

**Comment by RachelOh** [comment]
@james-kim-Devguru 
위 내용대로 답변해도 좋을 것 같습니다
