### ISSUE TITLE
touch input not working

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1931]
Email : [martingampe@metastocks.de](mailto:martingampe@metastocks.de)
Device OS: iOS
Product: EasyCanvas

Hello,

taps with my finger do not register at all on the screen, only apple pencil input works. Finger input works when I try to press buttons on the easycanvas overlay (like undo).
I'm using Windows 10 and just bought the license. I need finger input for touch gestures. Please advise how I can fix it. Thanks!

[EL_Display_2f34c3e8-80ff-4af1-a257-eece14f98a10.zip](https://github.com/edh-git/EL_Display_Hub/files/11416392/EL_Display_2f34c3e8-80ff-4af1-a257-eece14f98a10.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1931] touch input not working
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

The stylus pens supported by EasyCanvas are as follows.
- iPad: Apple Pencil 1, 2

EasyCanvas supports only the genuine Apple Pencil, and if you are using a third-party pen, it may not work properly.

If the touch does not work when using the genuine Apple Pencil, release the touch lock through the padlock-shaped button on the "Toolbar" of Easycanvas.

If the problem does not improve even after taking the above measures, refer to the log acquisition guide below.
Please inquire again with the 'Application Log'.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

If you have any additional questions, please feel free to ask.
Thank you

Easy&Light
```

**Comment by RachelOh** [comment]
2023.5.9. 오전 1:08
---
Dear support team,

Using the lock symbol did not change it when I had the problem. I
managed to fix it in the meantime by restarting my iPad. Now the touch
input works. So this can be a possible solution for other customers if
they face the same problem.

What didn't happen before the restart, but happens now: after the
connection is established, the screen is squished together (pressed
flat), only changing the resolution in the display to another value (and
then setting it back to the desired resolution) fixes it. Not sure why
it happens. If you have any ideas about that please give me a hint. It's
not a huge problem, just a bit annoying. Thanks.

(using 2021 iPad Pro, Apple Pencil 2, iPad-OS is updated)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1931] touch input not working
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

Thanks for sharing how the problem could be solved.

The information you inquired about could not be analyzed because there was no log. For log collection, please extract logs from ipad and submit inquiries through inquiry in PC program.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

Also, for a more detailed log understanding, check "Attach with PC system information".


We will also guide you through common solutions if the screen display is not normal.

1. Delete "EL Display Hub"
2. Check for Windows updates and update to the latest Windows
3. Update graphics driver
     [Intel] Driver Support Program: https://www.intel.com/content/www/us/en/download-center/home.html
     [AMD] Graphics driver installation page: https://www.amd.com/support
     [NVIDIA] Graphics driver installation page: https://www.nvidia.co.kr/Download/index.aspx
4. Reboot PC (Use "Restart" in Shutdown option)
5. Download the new installer and reinstall "EL Display Hub"
     [EL Display Hub] installation page: http://www.easynlight.com/en/easycanvas/

Thank you

Easy&Light
```
