### ISSUE TITLE
키오스크에 프로그램이 설치되지않습니다

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1943]
Email : [aeternus_k@naver.com](mailto:aeternus_k@naver.com)
Device OS: Android
Product: Twomon SE

피씨버전이 윈도우기반 키오스크에 설치가 잘 되지않습니다

[EL_Display_c94b1cd1-73d4-471d-8576-cbe1b3670099.zip](https://github.com/edh-git/EL_Display_Hub/files/11426008/EL_Display_c94b1cd1-73d4-471d-8576-cbe1b3670099.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1943] 키오스크에 프로그램이 설치되지않습니다
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그를 검토한 결과 가상 드라이버 실행 시 오류가 발생하는 문제로 보이며,해당 문제의 경우 Windows 10 OS 버전이 Twomon SE가 지원하지 않는 버전으로 보입니다.
Twomon SE의 경우 Windows 10 버전이 1703 이상이어야 하므로, 현재 Windows 버전에서는 사용이 어렵습니다. 자세한 사양은 아래의 FAQ를 참조하여 주십시오.
    [FAQ] Twomon SE PC프로그램을 설치할 수 없어요 : http://www.easynlight.com/supporttwomon/?faq=130

Twomon SE의 원할한 사용을 위해서는 Windows를 업데이트하여 주시길 바랍니다.

위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 로그 취득 가이드를 참조하여 PC로그와 어플리케이션 로그를 첨부하여 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

더 좋은 제품을 만들기 위해 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```

**Comment by RachelOh** [comment]
2023년 5월 9일 화요일 오후 4:06
---
혹시, 어플결제한거에 대해 환불이 가능할까요?

사용하려던 기기가 일반PC가 아닌 영업용 키오스크인데, 키오스크사에 문의해보니 윈도우 업데이트가 불가능한 OS라는 답변이 와서 사용이 불가능한 상황입니다..

**Comment by RachelOh** [comment]
환불 가이드 안내
---
안녕하세요. Easy&Light 지원팀입니다.

환불을 원하실 경우, 아래 내용을 참고하여 주시기 바랍니다. 

[환불 가이드]
1. Playstore for Android하단의 링크로 접속하시어 필요한 내용을 기입 후 제출해주시면 확인하여 환불 절차를 진행해드리겠습니다.[Android] Easy&Light 제품 환불 요청서https://docs.google.com/forms/d/1wFxbQS5wg3u1QbMLG_ZQDM2ExNbDHC9xraPje5_hBbo/edit?urp=gmail_link
2. App Store for iOS애플 앱스토어에서 판매되는 앱은 모두 애플에서 관리합니다. 저희는 고객님의 구매 정보를 가지고 있지 않기 때문에 애플리케이션 환불을 진행할 권리가 없습니다. 아래 링크를 참조 부탁드립니다.Apple Support 사이트 링크 :[https://reportaproblem.apple.com/﻿](https://reportaproblem.apple.com/)
﻿iTunes store 에서 환불 받는 방법 :https://support.apple.com/ko-kr/HT204084

더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

**Comment by RachelOh** [comment]
2023.5.9. 오후 4:13
---
혹시 SE 버전말고 다른 버전은 해당 윈도우에서도 사용가능한 버전이 있나요?

**Comment by RachelOh** [comment]
아래와 같이 답변
---
안녕하세요. Easy&Light 지원팀입니다.

Twomon SE와 비교해 비교적 오래된 OS를 지원하는 TwomonUSB가 있습니다.

한번 설치하여 사용해보신 후, 원활하게 동작하지 않을 시  환불요청을 해주시면 환불처리를 해드리도록 하겠습니다.

감사합니다.


Easy&Light
