### ISSUE TITLE
Ipad Pro not detected with usb C adaptor

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1947]
Email : [siew.yeepeng@gmail.com](mailto:siew.yeepeng@gmail.com)
Device OS: iOS
Product: EasyCanvas

HI,
When i use easy Canvas, my ipad pro lose the battery power very quickly. And the usb port on my ipad, cannot charge and connect to the laptop concurrently.
So,I bought a usb C adaptor to connect to my ipad. This adaptor has two usb C output, one for power delivery to my ipad and one with projecting 4K video function, thunderbolt port. But when i connect the usb C from my adaptor to ipad and the other end to the laptop, Easy Canvas did not detect my ipad pro. Can i know why?

[EL_Display_81f27d95-4431-4a77-abcd-9abb08f14da2.zip](https://github.com/edh-git/EL_Display_Hub/files/11437094/EL_Display_81f27d95-4431-4a77-abcd-9abb08f14da2.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1947] Ipad Pro not detected with usb C adaptor
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

After reviewing the logs you sent us, we couldn't find any connection records related to the iPad.

First of all, check the connection between the tablet and PC via USB by referring to the video in the middle of the link below (video using Twomon SE).
[Twomon SE] Product introduction page: http://www.easynlight.com/en/twomonse/

If it is not properly connected, check the following items.

First, it may be a problem with insufficient power or poor connection of the USB port.
To solve this, try the following measures.
1. Check if the connection between PC and tablet is normal.
2. Replace the USB cable (use a genuine cable if possible, use a cable capable of data communication).
3. Change the USB port connected to the PC (using the rear port).
4. Connect to an external powered USB hub.

Second, it could be an error on the PC side and the tablet side.
1. Reboot your PC. (Use "Restart" in Shutdown Options)
2. Reboot your tablet.

Also, from the log, it seems that the Android connection attempt is still being made, and the "USB Debugging" option on the Android side is not applied properly.

If you are using EasyCanvas on Android, please refer to the link below and allow "USB Debugging".

[FAQ] Allow 'USB Debugging' permission or' Cancel USB Debugging permission' and try again (Android) : http://www.easynlight.com/en/supporttwomon/?faq=80

If it does not work after that, please reboot both PC and Android device.

If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/supporttwomon/?faq=121

We will always strive for better products and services.
Thank you

Easy&Light
```

**Comment by RachelOh** [comment]
2023.5.10. 오후 8:51
---
Dear Sir,

I have tried your suggestion. When i charge the ipad up, then connect the adaptor to the ipad, then the laptop, easy canvas could detect the ipad connected to the adaptor. 

thank you for the technical support. Your suggestion has resolved the issue of easy canvas not detecting the ipad through  the adaptor.

Thank you. We can close the case now.

Regards,
Ms Siew
