### ISSUE TITLE
一台电脑能用，另外一台无法使用

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1963]
Email : [zfloli@outlook.com](mailto:zfloli@outlook.com)
Device OS: iOS
Product: EasyCanvas

ipad端口已经购买了使用，在A电脑首次连接使用成功，但是因为工作需要，我需要切换B电脑使用操作。当B电脑下载电脑端软件并用数据线连接IPad，尝试多次都未能成功连接。电脑端软件现实未连接设备，但是电脑信息已弹出询问，是否信任电脑。证明两者已经成功连接。我想咨询，是否软件端进行了限制？只能单台电脑使用？如果不是，麻烦告知解决方法，感谢！（双电脑系统未WIN11 ipda为2018 por。 不确定B电脑Type-C是否属于雷电端口，A电脑Type-C端口为雷电，但都是属于轻薄笔记本，充电数据连接共用的端口，所以应该电力输出是足够的）

아이패드 포트를 구매하여 사용중이며 처음으로 컴퓨터 A에 성공적으로 연결하여 사용하였으나 업무상의 필요로 인해 동작 전환이 필요합니다. B 컴퓨터의 컴퓨터 B가 컴퓨터 소프트웨어를 다운로드하고 데이터 케이블로 아이패드에 연결하면 여러 번 시도한 후 연결에 실패합니다. 컴퓨터 소프트웨어는 실제로 장치에 연결되어 있지 않지만 컴퓨터를 신뢰할지 여부를 묻는 컴퓨터 정보가 팝업됩니다. 두 개가 성공적으로 연결되었음을 증명하십시오. 소프트웨어 측에 제한이 있는지 묻고 싶습니다. 단일 컴퓨터에서만 사용할 수 있습니까? 그렇지 않다면 해결책을 알려주세요. 감사합니다! (WIN11 ipda가 없는 듀얼 컴퓨터 시스템은 2018 por. 컴퓨터 B의 Type-C가 Thunderbolt 포트에 속하는지, 컴퓨터 A의 Type-C 포트가 Thunderbolt인지 잘 모르겠지만 둘 다 얇고 가벼운 노트북에 속합니다 . 및 충전 데이터 연결에 의해 공유되는 포트이므로 전원 출력이 충분해야 함)

[EL_Display_b4f8b6a8-c4d2-47c9-a4d3-33a1a3b7ac72.zip](https://github.com/edh-git/EL_Display_Hub/files/11503162/EL_Display_b4f8b6a8-c4d2-47c9-a4d3-33a1a3b7ac72.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1963] 一台电脑能用，另外一台无法使用
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

It is possible to use it on two computers, which is the method you inquired about,
As a result of reviewing the logs and symptoms you sent, we found a problem with conflicts with other programs.

Conflicts may occur when used with screen sharing programs or programs that have screen capture or recording capabilities.

It appears to be conflicting with "Duet Display", one of the currently installed programs.
After deleting "Duet Display" and "EL Display Hub", reboot the PC (use the "Restart" option in the shutdown option), download a new installer and reinstall "EL Display Hub".

[EL Display Hub] installation page: http://www.easynlight.com/en/easycanvas/


If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporttwomon/?faq=78

Thank you

Easy&Light
```
