### ISSUE TITLE
waiting for connection

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1965]
Email : [elisabeth.gertsch@hotmail.com](mailto:elisabeth.gertsch@hotmail.com)
Device OS: Android
Product: EasyCanvas

Dear Sir or Madam,

I am trying to connect my windows laptop with a galaxy s6 lite tablet,
i reinstalled the app and the program , restarted the tablet and the computer but still they don’t connect to each other, it only says waiting for connection on the tablet and in the hub - program diagnosis is shows a problem with the device connection status.

They are in the same Wi-Fi, is there a way you can help me ?

Thank you

[EL_Display_a4041757-007e-4fd8-9372-1f5a87cce813.zip](https://github.com/edh-git/EL_Display_Hub/files/11503169/EL_Display_a4041757-007e-4fd8-9372-1f5a87cce813.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 1965] waiting for connection
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

After reviewing the logs you sent, it seems that the "USB Debugging" option on the Android side is not applied properly.

Refer to the link below and allow "USB Debugging".

[FAQ] Allow 'USB Debugging' permission or' Cancel USB Debugging permission' and try again (Android) : http://www.easynlight.com/en/supporttwomon/?faq=80

If it does not work after that, please reboot both PC and Android device.

If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

We will always strive for better products and services.
Thank you

Easy&Light
```
