### ISSUE TITLE
Touch (finger) input is not working

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1973]
Email : [amashaal70@gmail.com](mailto:amashaal70@gmail.com)
Device OS: Android
Product: EasyCanvas

Touch (finger) input is not working or I dont know how to make it work. I am using galaxy tab s8 plus and the pin input works great, however touch input from fingers is not working, hence I cannot scroll.
also is there an option to use the tablet software keyboard to input to macbook?
I dont have log file yet

**Comment by RachelOh** [comment]
아래와 같이 답변
---
Hello, We are Easy&Light support team.
Sorry to say, we need log files to figure out the problem.

Please send us the log files.

Our technical team will check the problem and give you a solution.



[App log collection procedure]
　1. Android　　① Re-run the application on your device.　　② Tap on the app version at the bottom right of the main page about 10 times, then make sure a created log zip file named 'bypd.log.archived.yyyymmddhhmmss.zip' in Download folder on your device.

　2. iOS　　① Connect the device to extract the logs to a PC.　　② Run iTunes and click it when the connected device appears on the upper tap.　　③ Click ‘File Sharing’ in the list to the left.　　④ Scroll down the updated screen and click the app (EasyCanvas) to extract the log from the ‘App’ in the ‘File Sharing’ column. 　　⑤ Drag the log file at the bottom of ‘OOOO’s Documents' to each folder or desktop, 　　　　etc., or select the file and save it by clicking the ‘Save As’ button at the bottom right. 　　　


Please zip the all files and attach them.



Thank you.

**Comment by RachelOh** [comment]
2023.5.24. 오후 4:32
---
Attached log file

Please also advice how can I use keyboard from the galaxy tab s8 plus to write on macbook

[Easycanvas.log.archived.20230524103037.zip](https://github.com/edh-git/EL_Display_Hub/files/11560222/Easycanvas.log.archived.20230524103037.zip)

**Comment by james-kim-Devguru** [comment]
@RachelOh 
현재 지원되지 않는 환경으로 해당 사용자에게 아래와 같이 회신할 예정입니다.
내용 검토 부탁드립니다.
---
#### 제목
```
Re: [EasyCanvas - 1973] Touch (finger) input is not working
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

It seems that it is difficult to use EasyCanvas in the environment you are using.
Currently, EasyCanvas for Mac only supports iPad connection, with the following limitations:
Android connection, screen extension and wireless connection not supported

Therefore, EasyCanvas does not officially support Mac PC - Android Tablet, so errors such as touch operation may occur.

The function of transferring the keyboard input of the tablet you inquired additionally to the PC does not exist in EasyCanvas, and additional plans are undecided. If you want to use a keyboard, connect it to the PC side and use it.

We apologize for any inconvenience caused, and If you want a refund, please refer to the guide below.

[How to get a refund]

1. App Store for iOS
We'd like to give you a refund but we are not in charge of the refund. We'll let you know how to get the refund from the iTunes store. Please refer to the following websites.

Contact Apple Support:
https://reportaproblem.apple.com/

How to get a refund from iTunes store:
https://support.apple.com/en-us/HT204084

2. Google play store for Android
Please click the following link, fill out and submit a refund request form.
https://docs.google.com/forms/d/1q0_e3fDsvldj5KLzch2OfUBKFCqcluPGNYAyT8TMt7Y/viewform?edit_requested=true

We will always strive for better products and services.
Thank you

Easy&Light
```


#### 한글 원본
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

고객님께서 이용중인 환경에서는 EasyCanvas를 이용하기 어려울 것으로 보입니다.
현재 Mac용 EasyCanvas는 iPad 연결만 지원하며, 다음과 같은 제한사항을 같습니다.
Android connection, screen extension and wireless connection not supported

따라서, EasyCanvas는 Mac PC - Android Tabelet을 정식적으로 지원하지 않아서 터치 동작 등의 오류가 발생할 수 있습니다.

추가적으로 문의해주신 Tablet의 키보드 입력이 PC로 전달되는 기능은 EasyCanvas에 존재하지 않으며, 추가 계획은 미정입니다. 키보드를 사용하고 싶으신 경우에는 PC측에 키보드를 연결하여 사용하여 주십시오.

이용에 불편을 드려 죄송하며, 환불을 원하시면 아래 내용을 참고해주세요.

[환불 가이드]
1. Playstore for Android하단의 링크로 접속하시어 필요한 내용을 기입 후 제출해주시면 확인하여 환불 절차를 진행해드리겠습니다.[Android] Twomon SE/TwomonAir/TwomonUSB 환불 요청서https://docs.google.com/forms/d/1wFxbQS5wg3u1QbMLG_ZQDM2ExNbDHC9xraPje5_hBbo/edit?urp=gmail_link

2. App Store for iOS애플 앱스토어에서 판매되는 앱은 모두 애플에서 관리합니다. 저희는 고객님의 구매 정보를 가지고 있지 않기 때문에 애플리케이션 환불을 진행할 권리가 없습니다. 아래 링크를 참조 부탁드립니다.Apple Support 사이트 링크 :https://reportaproblem.apple.com/﻿
﻿iTunes store 에서 환불 받는 방법 :https://support.apple.com/ko-kr/HT204084

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다. 

Easy&Light
```

**Comment by RachelOh** [comment]
@james-kim-Devguru 
네 답변해도 좋을 것 같습니다
