### ISSUE TITLE
손가락 인식 관련

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1974]
Email : [gkstnqls120@gmail.com](mailto:gkstnqls120@gmail.com)
Device OS: iOS
Product: EasyCanvas

easy canvas 내에서 손가락 인식이 안되게 할 수 없나요? 클립스튜디오 캔버스를 내릴 때 꼭 두 손가락으로 해야하는지 궁금합니다.
또한 애플펜슬을 사용할 때 계속 손이 인식되어 점이 찍히는데 이것도 해결할 방법을 알고싶습니다.

[EL_Display_fc805d98-f9de-4e65-9c4a-f28c4e9020da.zip](https://github.com/edh-git/EL_Display_Hub/files/11538012/EL_Display_fc805d98-f9de-4e65-9c4a-f28c4e9020da.zip)

**Comment by james-kim-Devguru** [comment]
@RachelOh 

해당 사용자에게 아래와 같이 회신하려고 합니다.
3번 항목에 대해서 호버링 여부에 대해서 안내해도 되는지 검토 부탁드립니다.

---
#### 제목
```
Re: [EasyCanvas - 1974] 손가락 인식 관련
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

문의 주신 사항에 대해 답변드리겠습니다.

1) EasyCanvas 내에서 손가락 인식 비활성화 방법

EasyCanvas 앱의 툴바에서 두번째 항목인 자물쇠 버튼을 클리가하여 터치 입력을 비활성화 할 수 있습니다. 해당 버튼을 통해서 터치가 잠금된 경우에는 터치 사용이 불가능합니다.

2) 클립스튜디오 내의 두 손가락 조작

EasyCanvas의 경우 태블릿의 터치 입력을 PC로 전달하는 역할을 하며, PC 측의 터치 입력에 대한 동작은 각 프로그램에서 처리하므로 해당 문의 사항은 클립스튜디오에게 문의해보셔야 할 것으로 보입니다. 
추가적으로 클립 스튜디오의 "터치 조작"관련 TIPS를 첨부해드립니다.
    [3. 터치 조작] : https://tips.clip-studio.com/ko-kr/articles/556

3) 애플펜슬 이용 시 손이 인식되어 점이 찍히는 문제

아이패드의 경우 아이패드 프로 12.9형 6세대, 아이패드 프로 11형 4세대에서만 호버링을 지원하며, EasyCanvas에서는 아직 호버링을 지원하지 않아서 스타일러스와 터치 입력이 모두 PC로 바로 전달됩니다. 
해당 문제를 방지하기 위해서는 1번 항목으로 안내해드린 방법인 EasyCanvas의 터치 입력을 비활성화 하시는 것을 추천드립니다.

더 좋은 제품을 만들기 위해 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```

**Comment by RachelOh** [comment]
@james-kim-Devguru 
네 위 내용대로 답변해도 좋을 것 같습니다.
