### ISSUE TITLE
게임 실행시 보조모니터로 사용하는 태블릿의 Twomon SE가 멈춥니다.

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1980]
Email : [kim_junyeong@naver.com](mailto:kim_junyeong@naver.com)
Device OS: Android
Product: Twomon SE

갤럭시 탭 7 fe dptj twomon se를 사용해 보조모니터로 사용중 메인 모니터에 게임을 오래 실행시 보조모니터로 사용하는 태블릿의 화면이 멈춥니다. 어플이 멈추는것으로 보이며 볼륨 업다운, 상태창 내리기, 홈화면으로 가는 제스쳐 등 터치는 먹습니다.

[log.zip](https://github.com/edh-git/EL_Display_Hub/files/11594663/log.zip)
[TwomonSE.log.archived.20230526005539.zip](https://github.com/edh-git/EL_Display_Hub/files/11594664/TwomonSE.log.archived.20230526005539.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [TwomonSE - 1980] 게임 실행시 보조모니터로 사용하는 태블릿의 Twomon SE가 멈춥니다.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

해당 문제의 경우 Twomon SE에서 Direct X 기술을 사용하여 화면을 캡처하는 기능과 게임에서 Direct X  등에서 사용되는 기술의 문제이며, 
전체 화면을 표시하는 타 프로그램과도 해당 문제가 발생합니다.

해당 문제를 해결하기 위해서는 게임의 설정에서 전체 화면을 사용하지 않을 경우 해결이 가능합니다. 
게임의 인게임 옵션에서 "테두리 없음"이나 "창"을 사용하실 경우 해당 문제가 발생하지 않으실 것으로 보입니다.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

[로그 수동 수집 절차]
1. Windows키 입력 > "실행" > "msinfo32" 입력 > 파일 > 저장
2. C:\ProgramData\devguru 경로에 존재하는 파일
3. C:\Users\{사용자명}\AppData\Local\Devguru 경로에 존재하는 파일 ( %localappdata%\Devguru  로 경로에 접근 가능)

세 군데의 파일들을 압축하여 첨부해주세요.

감사합니다.

Ea​​sy&Light 

```
