### ISSUE TITLE
원인모를 갑작스런 미작동

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1981]
Email : [yein@ucsb.edu](mailto:yein@ucsb.edu)
Device OS: iOS
Product: Twomon SE

잘 사용하고 있었는데 어느날부터 연결이 안되네요. 오류메시지가 뜨는것도 아니에요 그냥 안돼요.. 케이블도 새걸로 해봤는데 안되는걸 보면 다른 하드웨어 문제는 아닌것 같아요. 근데 도무지 이유도 모르겠고, 아이패드도 노트북도 업데이트도 다 되어있는데,,, 어떡하면 좋을까요?

[EL_Display_9f61b3e7-a194-4046-91d9-fc360c7bb340.zip](https://github.com/edh-git/EL_Display_Hub/files/11594667/EL_Display_9f61b3e7-a194-4046-91d9-fc360c7bb340.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [TwomonSE - 1981] 원인모를 갑작스런 미작동
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그를 검토한 결과 EL Display Hub 프로그램의 일부가 제거된 상태로 보입니다. 

설치 프로그램이 손상되었을 수 있으므로 새로운 설치 프로그램을 다운로드 받아서 재설치 진행해주시길 바랍니다.
1. EL Display Hub를 삭제합니다.
2. PC 재부팅합니다. (종료 옵션의 "다시 시작" 사용)
3. 최신 EL Display Hub 인스톨러 재설치합니다.
    [EL Display Hub] 설치 링크 : http://www.easynlight.com/twomonse/
4. EL Display Hub 재설치합니다.

위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 로그 취득 가이드를 참조하여 PC로그와 어플리케이션 로그를 첨부하여 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
