### ISSUE TITLE
설치 직후에만 연결되고 이후 PC 부팅후에는 연결안됨.

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1993]
Email : [dongjunkim@outlook.com](mailto:dongjunkim@outlook.com)
Device OS: Android
Product: Twomon SE

설치시에는 잘 연결되나, 이후 PC 부팅 부터는 연결안됨.

재설치하면 재설치 직후에는 연결되나, 이후 PC 부터는 연결안됨.

![twomonse](https://github.com/edh-git/EL_Display_Hub/assets/77039864/a15ab344-90fb-4392-a5b1-58ad14e9df87)
[EL_Display_73015970-fbee-44a8-b5d1-f979204c8ce1.zip](https://github.com/edh-git/EL_Display_Hub/files/11619884/EL_Display_73015970-fbee-44a8-b5d1-f979204c8ce1.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1993] 설치 직후에만 연결되고 이후 PC 부팅후에는 연결안됨.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

보내주신 로그와 증상을 검토한 결과, 타 프로그램과의 충돌 문제를 발견하였습니다.

화면 공유 프로그램이나 화면 캡처 혹은 녹화 기능이 있는 프로그램과 함께 사용할 경우 충돌이 발생할 수 있습니다.

현재 설치된 프로그램 중 "Duet Display"와 충돌이 발생하는 것으로 보입니다. 
"Duet Display"와 "EL Display Hub"를 삭제하신 뒤 PC를 재부팅(종료 옵션의 "다시 시작" 옵션 사용)한 뒤 새로운 인스톨러를 다운로드 받아 "EL Display Hub"를 재설치하여 주십시오.

[EL Display Hub] 설치 페이지 : http://www.easynlight.com/en/easycanvas/


위와 같은 조치사항들을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 :  http://www.easynlight.com/en/supporttwomon/?faq=78

감사합니다.

Ea​​sy&Light 
```
