### ISSUE TITLE
아이패드에서 화면 출력시 세로로 나옵니다.

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#1996]
Email : [sangpil486@naver.com](mailto:sangpil486@naver.com)
Device OS: iOS
Product: Twomon SE

제목과 같습니다.

![KakaoTalk_20230601_142944282](https://github.com/edh-git/EL_Display_Hub/assets/77039864/ae7fa94c-ad11-4be2-b7f9-e2b638248cdc)
[com.devguru.ntwomon 2023-06-01 04-41.log](https://github.com/edh-git/EL_Display_Hub/files/11621491/com.devguru.ntwomon.2023-06-01.04-41.log)
[EL_Display_9e46c76e-3436-4559-97a4-82fef8406ce8.zip](https://github.com/edh-git/EL_Display_Hub/files/11621492/EL_Display_9e46c76e-3436-4559-97a4-82fef8406ce8.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 1996] 아이패드에서 화면 출력시 세로로 나옵니다.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

해당 증상과 로그를 확인해본 결과 정상적인 동작으로 확인됩니다.
연결하신 PC의 모니터가 기본적으로 세로 모양(1600x2560)이며, 출력 시에는 90도로 회전하여 표시하고 있는 것으로 보입니다.

현재의 상태는 앱의 경우 태블릿에서 가로로 표시하도록 고정되어있으며,
PC측 화면을 캡처한 뒤 90도로 회전하여 표시하여 세로로 나오는 것처럼 출력되었습니다.

추가로 궁금한 사항이 있으신 경우, 언제든 문의주세요.
더 나은 제품과 서비스를 위해 항상 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```

**Comment by RachelOh** [comment]
2023.6.1. 오후 5:58
---
혹시 다른 해결방법은 없을까요??

어플에서 세로 가로 회전이 적용되면 좋을것 같은데요 ㅠㅠ

**Comment by james-kim-Devguru** [comment]
@RachelOh 
해당 사용자에게 아래와 같이 회신해도 되는지 검토 부탁드립니다.

---
#### 제목
```
Re: [Twomon SE - 1996] 아이패드에서 화면 출력시 세로로 나옵니다.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

세로 화면 출력에 대한 다른 해결 방법은 검토해본 결과 없습니다.

문의해주신 앱 내에서의 화면 회전 기능의 경우 
해당 기능에 대해서 내부적으로 회의를 통해서 반영할 수 있도록 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```

**Comment by RachelOh** [comment]
@james-kim-Devguru 
아래 내용으로 답변 부탁드리겠습니다.

```
안녕하세요 고객님. Easy&Light 지원팀입니다.

세로 화면 출력에 대한 다른 해결 방법을 검토해본 결과 어려울 것으로 보입니다.

문의해주신 앱 내에서의 화면 회전 기능의 경우, 

추후 업데이트 시 해당내용 관련하여 논의해보도록 하겠습니다.

감사합니다.

Ea​​sy&Light 
```

**Comment by james-kim-Devguru** [comment]
* 알려주신 내용으로 답변하였습니다.
