### ISSUE TITLE
피씨와 패드 와이파이 연결 불가

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#2003]
Email : [jini878@naver.com](mailto:jini878@naver.com)
Device OS: iOS
Product: Twomon SE

같은 와이파이 연결 중인데 검색할 수 없다고뜸

[EL_Display_6407e43d-7a91-432f-9a76-b9593cd27fd7.zip](https://github.com/edh-git/EL_Display_Hub/files/11649971/EL_Display_6407e43d-7a91-432f-9a76-b9593cd27fd7.zip)

**Comment by james-kim-Devguru** [comment]
@RachelOh 

해당 사용자에게 아래와 같이 답변해도 되는지 검토 부탁드립니다.

---
#### 제목
```
Re: [Twomon SE - 2003] 피씨와 패드 와이파이 연결 불가
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

문의 주신 제품인 Twomon SE의 경우 무선 연결을 지원하지 않는 제품입니다.
무선 연결 기능을 사용하시기 위해서는 EasyCanvas를 이용해주시길 바랍니다.

감사합니다.

Ea​​sy&Light 
```

**Comment by RachelOh** [comment]
@james-kim-Devguru 
문의 제품은 Twomon SE로 표시되어있었는데, 혹시 로그파일 확인해보면 EasyCanvas 사용자는 아닌가요??
(로그상에 bypd....관련 내용을 본 것 같아서 EasyCanvas 사용자는 아닌가 생각했어요.)
Twomon SE사용자가 맞다면 위 내용대로 보내도 좋을 것 같습니다.

**Comment by james-kim-Devguru** [comment]
연결 기록이 없어, 로그로는 어떤 앱을 사용중인지 파악이 불가합니다. 
혹시 모르니 EasyCanvas인 경우 추가 로그 요청을 포함하여 전송하겠습니다.

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2003] 피씨와 패드 와이파이 연결 불가
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

문의 주신 제품인 Twomon SE의 경우 무선 연결을 지원하지 않는 제품입니다.
무선 연결 기능을 사용하시기 위해서는 EasyCanvas를 이용해주시길 바랍니다.

로그 상으로는 제품 연결 시도를 확인하지 못 하였습니다.
EasyCanvas를 사용 중인 경우 아래의 방법을 통해 PC 프로그램의 로그와 앱 측의 로그를 함께 보내주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

[로그 수동 수집 절차]
1. Windows키 입력 > "실행" > "msinfo32" 입력 > 파일 > 저장
2. C:\ProgramData\devguru 경로에 존재하는 파일
3. C:\Users\{사용자명}\AppData\Local\Devguru 경로에 존재하는 파일 ( %localappdata%\Devguru  로 경로에 접근 가능)

세 군데의 파일들을 압축하여 첨부해주세요.

감사합니다.

Easy&Light
```
