### ISSUE TITLE
연결 오류 관련

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#2015]
Email : [nastuno@naver.com](mailto:nastuno@naver.com)
Device OS: Android
Product: Twomon SE

안녕하세요
저는 샤오미패드5를 사용하고 있습니다.
개발자보드 활성화 후 usb 디버깅 활성화 후 pc와 연결하려고 하면 아무런 반응이 없습니다.
연결이 안되고 패드에서는 twomon se 빨간색 화면만 유지되고 있습니다.
혹시나 호환성에 문제가 있는건지요?
패드 재부팅, PC 재부팅도 해 보았으며, google 드라이버도 재설치 해 보았으나
연결이 안되고 있습니다.
확인 바랍니다.

[Twomon_20230608_112253.zip](https://github.com/edh-git/EL_Display_Hub/files/11698939/Twomon_20230608_112253.zip)
[com.devguru.ntwomon.zip](https://github.com/edh-git/EL_Display_Hub/files/11698940/com.devguru.ntwomon.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2015] 연결 오류 관련
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.  
현재 로그를 확인해본 결과 Twomon USB, Twomon Air를 위한 PC프로그램을 설치하신 것으로 보입니다.
Twomon SE, Easycanvas의 PC 프로그램은 EL Display Hub입니다.

PC측의 "Twomon PC Program"을 제거하신 뒤 EL Display Hub용 인스톨러를 설치하여 재설치 부탁드립니다.
[EL Display Hub] 설치 페이지 :  http://www.easynlight.com/easycanvas/

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면,
아래의 로그 취득 가이드를 참조하여 어플리케이션 로그와 함께 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
