### ISSUE TITLE
아이패드 프로 업데이트 이후 연결이 안돼요!

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#2016]
Email : [sol586@naver.com](mailto:sol586@naver.com)
Device OS: iOS
Product: Twomon SE

이전에 잘 사용하였는데 최근 업데이트 이후 오랫만에 사용 할려고 하니,
안돼네요. 프로그램 삭제 후 재 설치 하여도 똑같은 증상이네요.
윈도우에서는 패드가 인식 되는데. 프로그램에서는 인식을 못하네요.

<img width="1280" alt="오류" src="https://github.com/edh-git/EL_Display_Hub/assets/77039864/2859e60c-fb43-4367-8409-26fda7bdddb0">

[EL_Display_05a8ed82-2a3c-48a8-8e05-841020eb5f25.zip](https://github.com/edh-git/EL_Display_Hub/files/11699085/EL_Display_05a8ed82-2a3c-48a8-8e05-841020eb5f25.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2016] 아이패드 프로 업데이트 이후 연결이 안돼요!
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 EL Display Hub에서 사용하는 일부 프로그램이 정상적으로 동작하지 않는 것으로 보입니다.

아래의 링크를 참조하여 해당 프로그램을 재시작하여 주시길 바랍니다.
[FAQ] Twomon SE PC프로그램이 실행되지 않습니다. : http://www.easynlight.com/supporttwomon/?faq=124

'서비스'에서 Apple Mobile Device Service의 상태가 '실행 중' 인지 확인(iOS)
　　1. Ctrl + Alt + Delete키를 눌러 '작업 관리자'를 실행
　　2. [서비스]탭을 누른 후 이름이 'Apple Mobile Device Service'인 서비스의 상태가 '실행 중'인지 확인
　　3. 서비스의 상태가 '중지됨'일 경우 마우스 오른쪽 버튼을 클릭하여 서비스를 '시작' 혹은 '다시 시작'하여 서비스가 실행되는지 확인
　　4. 서비스 상태가 '실행 중'으로 변경되면 Twomon SE PC프로그램을 재실행

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```
