### ISSUE TITLE
포토샵 애플펜슬 인식

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#2020]
Email : [dis2011@naver.com](mailto:dis2011@naver.com)
Device OS: iOS
Product: EasyCanvas

안녕하세요?

애플펜슬 작동에 있어서 문의 드립니다.

이지캔버스를 사용하는데, 포토샵 브러쉬가 안먹습니다.

노트북은 갤럭시 북3 프로 이고, 패드는 아이패드 프로 12.9 m1 모델입니다.

프로그램을 통한 호환성 체크가 있길래 확인해보니 문제가 없습니다.

뭐가 문제인지 알 수 있을까요? 클릭은 잘 되는데

브러쉬는 아에 그려지질 않습니다.

클립스튜디오는 브러쉬는 먹는데 필압이 아에 안먹구용

툴은 포토샵 2023 최신버전 정품 사용중입니다.
클립스튜디오는 1.0 정품 사용하고 있습니다.

앱이나 프로그램 문제인거 같아 노트북 태블릿 재설치를 했으나

증상 동일합니다.

뭐가 문제일까요?

[EL_Display_d40a9739-5611-42aa-9657-95937df98bc9.zip](https://github.com/edh-git/EL_Display_Hub/files/11716470/EL_Display_d40a9739-5611-42aa-9657-95937df98bc9.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2020] 포토샵 애플펜슬 인식
```
#### 본문
```
고객님, 안녕하세요. Easy&Light 지원팀 입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님의 증상과 로그를 검토한 결과 각 드로잉 프로그램에서 stylus의 입력이 WinTab으로 동작하는 것으로 보입니다.
EasyCanvas의 경우 Windows 표준 입력 방식인 Windows Ink를 사용하여 아래의 FAQ 링크를 참조하셔서 프로그램 설정을 진행하여 주시길 바랍니다.
    [FAQ] 드로잉 프로그램에서 Apple Pencil의 필압 입력이 동작하지 않습다. : http://www.easynlight.com/supporteasycanvas/?faq=118

위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 아래의 로그 취득 가이드를 참조하여
'어플리케이션 로그'와 함께 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporttwomon/?faq=121

추가로 궁금한 사항이 있으신 경우, 언제든 문의주세요.
감사합니다.
```
