### ISSUE TITLE
device not connecting

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#2021]
Email : [neapolitanrime@gmail.com](mailto:neapolitanrime@gmail.com)
Device OS: iOS
Product: EasyCanvas

no matter what i do my device cannot connect. i look at the diagnosis and it said the "device connection status" was (!)

it was literally fine last week idk whats wrong. i did everything they said in the faq and nothing. also my ipad version is 4.6.8R and the version on desktop in 4.7.3.8 and wont let me update any further on my ipad so i dont know whats up with that.

[EL_Display_106357b1-c2fc-4c01-a520-be099262b37d.zip](https://github.com/edh-git/EL_Display_Hub/files/11716478/EL_Display_106357b1-c2fc-4c01-a520-be099262b37d.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2021] device not connecting
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

After reviewing your logs, we are seeing that authentication for wireless connectivity is failing.
In the case of EasyCanvas, authentication between the PC and the tablet is performed during wired connection for wireless connection, and then wireless connection is possible.

Currently, it seems that the authentication for wireless connection has been initialized on the customer's log, and to solve the problem, please use it after connecting the PC and tablet by wire.

If the problem does not improve even after taking the above measures, refer to the log acquisition guide below.
Please inquire again with the 'Application Log'.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

We will try to make better products.
thank you

Easy&Light
```
