### ISSUE TITLE
Constant problems with desktop app and windows service.

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#2023]
Email : [anibaaaal@gmail.com](mailto:anibaaaal@gmail.com)
Device OS: iOS
Product: EasyCanvas

Hello,
I'm having trouble with the desktop app EL Display Hub, this has been going on for years actually. Amost always I always get an error message that the service couldn't be started and my ipad won't connect via usb or wireless. When I start the windows service manually the error dissapears but the ipad won't connect still. Sometimes it works but almost never, after a few minutes the service gets stopped again.
I must add that I have formatted my computer at least twice since i purchased the app and this error persists.
I have also reinstalled the app multiple times.
I hope you can find a solution.
Thank you in advance.

[EL_Display_63c52b93-0c94-4074-957e-f202e70fcdf2.zip](https://github.com/edh-git/EL_Display_Hub/files/11716496/EL_Display_63c52b93-0c94-4074-957e-f202e70fcdf2.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2023] Constant problems with desktop app and windows service.
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

As a result of reviewing the logs and symptoms sent by the customer, it was confirmed that the screen capture part did not work normally.
This is a possible issue in the discrete GPU environment of laptops.

First, through reinstallation, try to set options in the installer that can solve the problem.

If the problem is not resolved even after reinstallation, it can be solved by setting the options of the graphics driver.
Please refer to the link and change the option to "Integrated Graphics".

[FAQ : Cannot connect Twomon SE to a PC] "Please change 3D settings in NVIDIA Control Panel" : http://www.easynlight.com/en/supporttwomon/?faq=80

If the problem does not improve even after taking the above measures, please attach a new PC log and application log and contact us again.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you

Easy&Light
```
