### ISSUE TITLE
Mac App Does Not Open

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#2027]
Email : [katrinapineda0206@gmail.com](mailto:katrinapineda0206@gmail.com)
Device OS: iOS
Product: EasyCanvas

Hello,
I downloaded your app onto my Mac from your website but then it refuses to open. I tried it on two different Macs on macOS 12. What else can I try? I can\'t send a log because the app doesn\'t even open.

Also, what is the difference between the two iPad apps? One says Easy Canvas and one says Easy Canvas Sub. Do they both do the same thing? Thanks!

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2027] Mac App Does Not Open 
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

In the case of EasyCanvas Mac program, there is no separate window.
When running the program on Mac, check the EasyCanvas icon in the upper right corner.

The difference between EasyCanvas and EasyCanvas Sub is the difference in purchasing method.
EasyCanvas can be licensed as a one-time purchase,
For EasyCanvas Sub, you can purchase a yearly subscription license.

If the problem does not improve even after taking the above measures, please contact us again.

Thank you

Ea​​sy&Light 
```
