### ISSUE TITLE
연결이 안됨

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#2031]
Email : [wjddn2033@naver.com](mailto:wjddn2033@naver.com)
Device OS: Android
Product: Twomon SE

연결이 계속 안됩니다.
pc와의 연결이 실패하였습니다.
동일 네트워크에서 서버 pc를 찾을 수 없거나 방화벽, 네트워크 설정으로~~~~
이런 메세지가 계속 나와서 사용할수가 없어요. 제가 할수있는 조치사항을 자세히 알려주세요.

[Twomon_20230615_000910.zip](https://github.com/edh-git/EL_Display_Hub/files/11752140/Twomon_20230615_000910.zip)
[Twomon_20230615_0009101.zip](https://github.com/edh-git/EL_Display_Hub/files/11752142/Twomon_20230615_0009101.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2031] 연결이 안됨
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.  
현재 로그를 확인해본 결과 Twomon USB, Twomon Air를 위한 PC프로그램을 설치하신 것으로 보입니다.
Twomon SE, Easycanvas의 PC 프로그램은 EL Display Hub입니다.

PC측의 "Twomon PC Program"을 제거하신 뒤 EL Display Hub용 인스톨러를 설치하여 재설치 부탁드립니다.
[EL Display Hub] 설치 페이지 :  http://www.easynlight.com/twomonse/

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면,
아래의 로그 취득 가이드를 참조하여 어플리케이션 로그와 함께 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
