### ISSUE TITLE
[이지캔버스 문의] 클립스튜디오 사용 중 오류 문의

### ISSUE THREAD

**Issue by RachelOh** [edh-git/EL_Display_Hub#2072]
Email : [someonecall109@gmail.com](mailto:someonecall109@gmail.com)
Device OS: Android
Product: EasyCanvas

사용환경: 갤럭시 s6 lite + windows 10
PC: AMD Ryzen 7 5800H with Radeon Graphics, 16GB RAM

안녕하세요.
이지캔버스를 통해 s6 lite와 클립 스튜디오로 그림을 그리는 중 올가미 툴(선택도구)에서 오류가 발생하여 문의드립니다.
첨부한 영상과 동일하게, 선택도구인 올가미 툴을 이용해도 선택이 간헐적으로 되는 것을 확인했습니다.
이때 클립스튜디오의 환경설정 중 [태블릿-사용하는 태블릿 서비스]에서 TabletPC를 선택할 때 나타나는 오류이며, Wintab을 선택했을 때는 올가미 툴이 오류 없이 실행됩니다. (Wintab은 필압이 지원되지 않는다고 알고 있습니다)
클립스튜디오를 최신 버전으로 업데이트했으며, 이지캔버스 또한 최신버전인데 오류가 발생하여 불편함을 겪고 있습니다.
해당 오류는 왜 일어나는지, 고칠 방법은 없는지 궁금합니다.
감사합니다.

[EL_Display_4865985b-ee14-4099-bbf7-2f1e8875de11.zip](https://github.com/edh-git/EL_Display_Hub/files/11900902/EL_Display_4865985b-ee14-4099-bbf7-2f1e8875de11.zip)

https://github.com/edh-git/EL_Display_Hub/assets/77039864/185ab1cd-d99e-426e-a8ff-7475f20675fc

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2072] [이지캔버스 문의] 클립스튜디오 사용 중 오류 문의
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

해당 증상을 확인한 결과 클립 스튜디오의 stylus의 입력 종료 감지 방법과 안드로이드의 stylus 입력 종료 신호의 동작의 차이로 발생한 것으로 보입니다.

현재 해당 문제를 우회하여 사용하기 위한 방안을 안내해드리겠습니다.
1. EasyCanvas 앱에서 도구 모음의 가장 하단에서 두 번째 필압 조정 팝업을 실행합니다.
2. 좌측 하단의 점을 살짝 우측으로 조정합니다.

위와 같은 조치사항들을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporttwomon/?faq=121

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다

Easy&Light
```

![클립스튜디오 올가미 오류 수정을 위한 필압 조정](https://github.com/edh-git/EL_Display_Hub/assets/66463237/3f7bc65b-4719-47a8-83b3-2d1f90dbb2a4)
