### ISSUE TITLE
전력 이상으로 인한 연결 해제

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2094]
- 문의 날짜 : 2023년 7월 3일 오후 11시 26분
- 메일 주소 : [goldpig1008@naver.com](mailto:goldpig1008@naver.com)

**노트북하고 아이패드 듀얼화면 연결시**

노트북에 전원공급하고 아이패드 연결시 전력이상으로 연결이 해지가 됩니다.
노트북 전원공급 안하고 연결하면 잘 연결이 됩니다. 무슨 문제 일까요?
[EL_Display_3bef6908-bebb-48dd-a6f3-e009fb2cda44.zip](https://github.com/edh-git/EL_Display_Hub/files/11943484/EL_Display_3bef6908-bebb-48dd-a6f3-e009fb2cda44.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2094] 노트북하고 아이패드 듀얼화면 연결시
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 답변이 많이 늦어진 점 정말 죄송합니다.

보내주신 로그에서는 별다른 특이점이 없으며, USB 연결 해제로 인한 연결 종료 로그를 확인하였습니다.

Twomon SE의 경우 USB 연결을 통한 통신을 진행하며, 
OS나 장치의 문제로 인하여 USB 연결이 해제되거나 연결이 불안정한 경우 연결이 해제될 수 있습니다.
노트북 전원 공급 시 아이패드와 PC 측의 USB 연결이 해제되는 경우 노트북과 태블릿 제조사 측에 문의가 필요해보입니다.

USB 연결이 해제되지 않고, Twomon SE의 연결이 해제되는 USB포트의 전력 부족 혹은 연결 불량문제 일 수 있습니다.
이를 해결하기 위해 아래의 사항들을 조치해보십시오.

1. PC와 태블릿 간의 연결이 정상적인지 확인합니다.
2. USB 케이블 교체(가능한 정품 케이블 사용)합니다.
3. PC에 연결된 USB 포트 변경(후면 포트 이용)합니다.
4. 외부전원 USB 허브에 연결합니다.

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다

Easy&Light
```
