### ISSUE TITLE
바이러스 포함 팝업 표시

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2100]
- 문의 날짜 : 2023년 7월 6일 오전 10시 2분
- 메일 주소 : [thomasbrake@live.com](mailto:thomasbrake@live.com)

Title: cant open windows software

Questions: whenever i try to run it it says the file contains a virus

**Comment by Sienna-lee** [comment]
@james-kim-Devguru 

#2099 이슈는 웹사이트 문제인줄 알고 이후에 개선하겠다고 회신하였는데 혹시 해당 이슈와 동일한 문제인지 확인 부탁드립니다.
로그파일을 받을 필요가 있는지도 확인 부탁드립니다.

**Comment by Sienna-lee** [comment]
해당 사용자가 추가로 메일을 보내왔습니다.

I've finally got the software to download but now when I try to open it my computer tells me that it contains viruses and does not let me open the app. Please help

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2100] cant open windows software
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, I'm really sorry for the very late reply.

In the case of the virus you inquired about, it is highly likely to be a false positive, and the cause of the symptom is usually as follows.

1. If the system setting time is not normal
2. Windows update is not up to date

Check and change the above settings and try installation.

If the problem does not improve even after taking the measures, it seems to be a problem with the antivirus program you are using.
Please inquire again by describing the vaccine and environment you are using (OS information and version, PC specifications, etc.).

Thank you

Easy&Light
```
