### ISSUE TITLE
제스처 사용 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2113]
- 문의 날짜 : 2023년 07월 11일 오전 4시 55분
- 메일 주소 : [abhaypratap1383@gmail.com](mailto:abhaypratap1383@gmail.com)

**gestures not working**

gestures not working even if the lock symbol is unlock.
please help
[EL_Display_46d9a75f-0cc7-471f-ba95-0b177ebc808d.zip](https://github.com/edh-git/EL_Display_Hub/files/12009770/EL_Display_46d9a75f-0cc7-471f-ba95-0b177ebc808d.zip)

**Comment by Sienna-lee** [comment]
해당 사용자가 추가로 아래와 같이 메일을 보내왔습니다.

----


I have recently subscribe to your product, and it is working like a charm. but the gestures are not working even the lock is unlocked. i cant able to use the gestures. Any help will be appreciated.
thanks


[EL_Display_7f476bba-0162-44e6-8686-a0a86934d770.zip](https://github.com/edh-git/EL_Display_Hub/files/12009783/EL_Display_7f476bba-0162-44e6-8686-a0a86934d770.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2113] gestures not working
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, I'm really sorry for the very late reply.

Gestures in EasyCanvas are input based on Windows touch actions.
Currently, EasyCanvas provides two multi-touch points, and gestures are executed through those points.
Please check supported gestures through the FAQ below.
[FAQ] I want to know about the supported gestures. : http://www.easynlight.com/en/supporteasycanvas/?faq=59

If the problem does not improve even after taking the above measures, refer to the log acquisition guide below.
Please inquire again with the 'Application Log'.

I would appreciate it if you could explain in more detail, such as whether the touch is not being input, whether the gesture is not working in a specific program, or whether the multi-point touch is not working.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

If you have any additional questions, please feel free to ask.
Thank you

Easy&Light
```
