### ISSUE TITLE
연결 시 인터넷 사용 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2129]
- 문의 날짜 : 2023년 7월 16일 오후 11시 30분 
- 메일 주소 : [rudwns2693@naver.com](mailto:rudwns2693@naver.com)

**인터넷 연결만 안되요**

화면 확장 및 사용은 잘 되지만 연결만 하면 인터넷 사용이 안됩니다. 인터넷도 다른 노트북도 케이블도 바꿔봤지만 여전히 인터넷을 잘 쓰다가도 연결만 하면 인터넷만 안되는데 원인을 알고 싶습니다.
[EL_Display_e9f38600-1802-4897-8add-3f94215902b4.zip](https://github.com/edh-git/EL_Display_Hub/files/12065582/EL_Display_e9f38600-1802-4897-8add-3f94215902b4.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2129] 인터넷 연결만 안되요
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

로그 상으로는 별다른 특이점을 확인하지 못했습니다.
추가로 해당 증상과 유사한 증상으로 추측되는 사항에 대해서 공유드립니다.

* 참조 링크 : https://www.asus.com/kr/support/FAQ/1004004/

해당 증상은 USB 3.0 디바이스를 연결하는 경우 2.4GHz 장치에 간섭 문제로 wi-fi나 bluetooth에 문제가 생기는 이슈입니다.
문제를 회피하기 위해서는 USB 3.0 포트가 아닌 2.0 포트로 사용하거나 Wi-Fi를 5GHz로 연결하면 됩니다.

위 방법으로 해결이 되지 않을 경우  해당 증상의 경우 PC 및 태블릿 제조사 측에 문의가 필요할 것으로 보입니다.

감사합니다.

Ea​​sy&Light
```
