### ISSUE TITLE
VOC::앱 업데이트 안내

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#214]
e-mail:gogo589@naver.com<br><br>EL Disply Hub 업데이트 이후 듀얼모니터가 안됩니다. 아이패드 버전 업데이트가 필요한지 확인 부탁드립니다<br><br>[EL_Display_15abc631-7f34-4285-82c1-2205e2950aad.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_15abc631-7f34-4285-82c1-2205e2950aad.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 부탁드립니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

EL Disply Hub 업데이트 이후 태블릿 측의 앱스토어 혹은 구글플레이스토어를 방문하여 어플리케이션 업데이트를 확인하여 주십시오.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 재문의 해주시길 바랍니다.

감사합니다.

Ea​​sy&Light 
```
