### ISSUE TITLE
드라이버 설치 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2141]
- 문의 날짜 : 2023년 7월 21일 오전 6시 2분
- 메일 주소 : [lilmisskaikai@gmail.com](mailto:lilmisskaikai@gmail.com)

**Driver installation problem still not resolved**

Unfortunately even after following all of the previous advice and manually uninstalling the drivers, the program still will not install correctly and in the device manager the drivers are showing a code 28 error message. *which is unfortunate as it worked perfectly previously and there have been no system changes to disrupt it as far as I am aware.*
Your help regarding this matter is greatly appreciated even if this problem cannot be resolved.
Thank you
![1 (1)](https://github.com/edh-git/EL_Display_Hub/assets/77039816/9cda92e8-d13d-414a-8f2f-73fa71b35b40)
![2](https://github.com/edh-git/EL_Display_Hub/assets/77039816/0fca67df-aeee-4338-859b-b02f773c678b)
![3 (1)](https://github.com/edh-git/EL_Display_Hub/assets/77039816/a078fd9d-0057-4e5f-8713-faf13bd84ddd)
[EL_Display_23dbc2a4-1677-4f28-be99-b3a175eaab1a.zip](https://github.com/edh-git/EL_Display_Hub/files/12115418/EL_Display_23dbc2a4-1677-4f28-be99-b3a175eaab1a.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2141] Driver installation problem still not resolved
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

We found existing data similar to your symptoms.
These problems were due to driver conflicts due to cumulative Windows updates, and it worked normally when the update was removed.
Attempts to remove recent updates up to the date of the problem.

* How to uninstall Windows Update: https://support.microsoft.com/en-us/windows/how-to-uninstall-a-windows-update-c77b8f9b-e4dc-4e9f-a803-fdec12e59fb0
* Similar case reference link
     - https://community.spiceworks.com/topic/2114487-windows-10-pro-keyboard-mouse-driver-is-unavailable?page=1#entry-7573925
     - https://answers.microsoft.com/en-us/windows/forum/all/drivers-unavailable-for-usb-keyboard-and-mous/0c8e935b-b251-42d2-8896-6794716d25f0


If you've uninstalled recent updates and still have the problem, update to the latest version of Windows to see if a version of Windows exists that fixes the problem.
Please update your PC to 21H1, the latest Windows 22H2.


If it does not work even after the above methods, it seems that you need to do a clean installation after formatting to the latest Windows.

We will always strive for better products and services.
thank you

Easy&Light
```
