### ISSUE TITLE
화이트 박스 표시 오류

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2146]
- 문의 날짜 : 2023년 7월 25일 오후 3시 53분
- 메일 주소 : [guillouxavier@gmail.com](mailto:guillouxavier@gmail.com)

Hi having some issues:
the connection works both with wifi and cable, but when i draw in photoshop, the strokes are replaced by large white squares as if its not able to process it. (attached)

Some time the strokes appear after while sometimes not.
i have an ipad pro 12.9 4th gen with ios 16.5.1
windows 10 pc with nvdia 1060 6gb, cpu i78700 3.2gh + 64gb ram

thank you for your help,

best,

xavier

[EL_Display_f19ff44b-0aaa-4693-a8e5-da9947abc023.zip](https://github.com/edh-git/EL_Display_Hub/files/12166759/EL_Display_f19ff44b-0aaa-4693-a8e5-da9947abc023.zip)
![Capture](https://github.com/edh-git/EL_Display_Hub/assets/77039816/4852c20d-1f5c-4c6e-b961-62a344147602)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2146] bug drawing - white squares instead of brush strokes
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

First of all, we apologize for any inconvenience caused.

The problem seems to be a problem with Photoshop and the graphics driver,
I checked the article similar to the symptoms you inquired in the Photoshop community.
* Reference link: https://community.adobe.com/t5/photoshop-ecosystem-bugs/white-squares-appearing-while-using-eraser-or-brush-tool/idi-p/13743534

Please refer to the above link and solve the problem in the way below.

First, update your graphics drivers
1. Check for Windows updates and update to the latest Windows
2. Update graphics drivers
     [Intel] Driver Support Program: https://www.intel.com/content/www/us/en/download-center/home.html
     [AMD] Graphics driver installation page: https://www.amd.com/support
     [NVIDIA] Graphics driver installation page: https://www.nvidia.co.kr/Download/index.aspx
3. Reboot PC (Use "Restart" in Shutdown option)

Second, GPU Acceleration Settings
1. Settings - Performance - Check if "Use Graphics Processor (G)" is checked in the Graphics Processor Settings.
2. If the option is not turned on, touch and gestures do not work normally.
3. If it is not checked, check it, save the settings, restart Photoshop, and check the status.

Third, update to the latest Photoshop

Fourth, enable the old GPU mode (pre-2016) setting
* Reference link: https://helpx.adobe.com/kr/photoshop/kb/troubleshoot-gpu-graphics-card.html
1. Choose Edit > Preferences > Technology Preview.
2. Enable older GPU mode (pre-2016).
3. Quit and restart Photoshop for the changes to take effect.


We will always strive for better products and services.
Thank you

Easy&Light
```

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

Thank you so much!

It seems that it was not an easycanvas issue but indeed a photoshop setting issue > your last piece

Thank you so much for your help really appreciate it. Happy to leave a great review

Best, 

Xaiver
