### ISSUE TITLE
포토샵 툴 표시되지 않음

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2169]
- 문의 날짜 : 2023년 8월 2일 오전 6시 22분
- 메일 주소 : [khs820313@naver.com](mailto:khs820313@naver.com)

**포토샵 문의**

수고하십니다.

갤탭7fe랑 윈10 연결해서 포토샵 작업하고 있습니다.

첨부한 이미지를 보면
왼쪽이 갤탭 화면이고, 오른쪽은 pc 모니터 화면입니다.

오른쪽 모니터 화면에 빨간색으로 표시한 펜 툴과 브러쉬 모양이 갤탭에서는 표기가 되지 않습니다.
브러쉬 모양 크기가 갤탭에서 표기가 되지 않으니 두께 조정이 힘듭니다.

펜툴이나 브러쉬툴만 안보이는게 아니라,
그냥 포토샵 툴들의 모양이 모두 표기가 되지 않는다고 보면 됩니다.

해결 방법이 있을까요?

[EL_Display_a9c67ba6-3a96-449a-88a1-db7ea917af8c.zip](https://github.com/edh-git/EL_Display_Hub/files/12235204/EL_Display_a9c67ba6-3a96-449a-88a1-db7ea917af8c.zip)

**Comment by james-kim-Devguru** [comment]
* 이미지의 경우 이멜일 참조 (큰 파일이라 업로드 실패)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2169] 포토샵 문의
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 답변이 많이 늦어진 점 정말 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 사용 중인 디스플레이에서 화면 정보 획득 및 캡처 부분에 문제가 있는 것으로 보입니다.

해당 문제는 타 프로그램과의 충돌 문제로 인해 발생하는 것으로 추측되며,
화면 공유 프로그램이나 화면 캡처 혹은 녹화 기능이 있는 프로그램과 함께 사용할 경우 충돌이 발생할 수 있습니다.

현재 설치된 프로그램 중 "SuperDisplay"와 충돌이 발생하는 것으로 보입니다. 
"SuperDisplay"와 "EL Display Hub"를 삭제하신 뒤 PC를 재부팅(종료 옵션의 "다시 시작" 옵션 사용)한 뒤 새로운 인스톨러를 다운로드 받아 "EL Display Hub"를 재설치하여 주십시오.

[EL Display Hub] 설치 페이지 : http://www.easynlight.com/easycanvas/

위와 같은 조치사항들을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다.

```
