### ISSUE TITLE
프로그램 삭제 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2175]
- 문의 날짜 : 2023년 8월 3일 오전 9시 3분 
- 메일 주소 : realzin0105@gmail.com

제목: 애플 기기 연결 해제 후 삭제를 진행하여 주시기 바랍니다 경고문

문의사항: 안녕하세요? 무선연결이 잘 되지 않아 pc 에서 el display 프로그램을 삭제하고 재설치 하려는 도중
애플 기기 연결 해제 후 삭제를 진행하여 주시기 바랍니다라는 경고창이 떠서 문의드립니다
아이패드에서 easycanvas 어플을 삭제해도 그대로고.. 어플 내에서 연결을 해제하는 방법을 찾기 어려워서 문의드립니다 ㅠ

![캡처 (5)](https://github.com/edh-git/EL_Display_Hub/assets/77039816/c28993f7-c3ae-4157-9418-5165982c3392)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Easycanvas - 2175] 애플 기기 연결 해제 후 삭제를 진행하여 주시기 바랍니다 경고문
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
해당 경고창의 경우 PC에 USB를 통해서 아이패드나 아이폰과 같이 애플 기기가 연결된 경우 발생하는 경고창입니다.

PC에서 애플 기기를 연결 해제하신 뒤 프로그램을 제거하여 주시고,
애플 기기를 연결 해제한 뒤 프로그램 제거에 실패하는 경우, PC를 재부팅하고 삭제를 시도하여 주십시오.


위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 발생하신 증상 및 로그를 첨부하여 재문의 해주시길 바랍니다.

[로그 수동 수집 절차]
1. Windows키 입력 > "실행" > "msinfo32" 입력 > 파일 > 저장
2. C:\ProgramData\devguru 경로에 존재하는 파일
3. C:\Users\{사용자명}\AppData\Local\Devguru 경로에 존재하는 파일 ( %localappdata%\Devguru  로 경로에 접근 가능)

세 군데의 파일들을 압축하여 첨부해주세요.

감사합니다.

Easy&Light
```
