### ISSUE TITLE
성능 문의 

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2184]
- 문의 날짜 : 2023년 8월 7일 오전 1시 40분
- 메일 주소 : [vnjackai560@gmail.com](mailto:vnjackai560@gmail.com)

 **120hz is just 60hz?**

i recently bought easycanvas for drawing on my pc and i noticed both 120hz and 60hz setting on my ipad doesnt change anything as it still remained 60hz
i know this use signal thing to work so i wanna ask if this is my cable fault or the app being frame-locked since when moving window is 60hz but when moving the shortcut logo, its 120hz
i use ipad pro 2018

[EL_Display_5135045b-64f2-4d3b-98bd-173ab69b8851.zip](https://github.com/edh-git/EL_Display_Hub/files/12271168/EL_Display_5135045b-64f2-4d3b-98bd-173ab69b8851.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2184] 120hz is just 60hz?
```
#### 본문
```
Hello, customer. This is Easy&Light support team.

Currently EasyCanvas consists of 60Hz, 45Hz, 30Hz.
For reasons such as performance and battery, the maximum screen refresh rate transmitted and displayed is set to 60Hz.
So even if your tablet supports 120Hz, it will display up to 60Hz.

If you have any additional questions, please feel free to ask.

Thank you

Easy&Light
```
