### ISSUE TITLE
연결 불안정

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2196]
- 문의 날짜 : 2023년 8월 10일 오전 11시 3분
- 메일 주소 : [noname1979@hanmail.net](mailto:noname1979@hanmail.net)

**연결이 불안정함**

- 연결장비 : PC window10 / 갤럭시탭 S7+
- 케 이 블 : 플렉스 USB 3.2 gen1 C타입 고속충전 케이블 200cm
- 증 상 : USB 케이블 연결된 상태에서 사용 중, 아무증상없이 갑자기
연결이 끊어져서 태블릿에 빨간색 홈페이지가 뜨고 바로 다시
자동으로 연결 복구됨. 1시간에 2~3회 반복.
복구되는 순간 전체 모니터가 한번 깜빡임.
- PC에 연결된 기존 모니터 4대 + Twomon SE로 1대 추가 사용중

[EL_Display_1ee39b0f-15f6-48a7-9678-f8508a9e3723.zip](https://github.com/edh-git/EL_Display_Hub/files/12309383/EL_Display_1ee39b0f-15f6-48a7-9678-f8508a9e3723.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2196] 연결이 불안정함
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 USB포트의 전력 부족 혹은 연결 불량 문제로 의심됩니다.

로그상 USB 연결이 해제되는 것으로 보이며, 다시 재연결 되는 것으로 보입니다.
아래와 같은 사항을 점검하여 주십시오.

첫 번째로 USB포트의 전력 부족 혹은 연결 불량 문제일 수 있습니다.
이를 해결하기 위해 아래의 사항들을 조치해보십시오.
1. PC와 태블릿 간의 연결이 정상적인지 확인합니다.
2. USB 케이블 교체(가능한 정품 케이블 사용,  데이터 통신이 가능한 케이블 사용)합니다.
3. PC에 연결된 USB 포트 변경(후면 포트 이용)합니다.
4. 외부전원 USB 허브에 연결합니다.

두 번째로 PC측과 태블릿 측의 오류일 수 있습니다.
1. PC를 재부팅하여 주십시오. (종료 옵션의 "다시 시작" 사용)
2. 태블릿을 재부팅하여 주십시오.

위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 아래의 로그 취득 가이드를 참조하여 재문의 부탁드립니다.

[FAQ] PC 및 어플리케이션 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

더 좋은 제품을 만들기 위해 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```
