### ISSUE TITLE
아이튠즈 오류 발생

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2208]
- 문의 날짜 : 2023년 8월 14일 오후 10시 40분
- 메일 주소 : [appledevicefile@naver.com](mailto:appledevicefile@naver.com)

**아이튠즈 실행 시 오류 발생합니다.**

마이크로소프트에서 다운 받은 아이튠즈를 실행 시 파일 첨부한 화면이 뜹니다. '예' 버튼을 눌러서 진행할 경우 twomon se에서 아이패드를 인식하지 못하는 경우가 발생합니다. 이 경우에는 어떻게 해야 할까요?

![캡처 (6)](https://github.com/edh-git/EL_Display_Hub/assets/77039816/3d008e6d-239c-42b3-acee-18e7a2da9fe6)
[EL_Display_efb5f404-4343-4d7e-8158-6cc797312313.zip](https://github.com/edh-git/EL_Display_Hub/files/12354529/EL_Display_efb5f404-4343-4d7e-8158-6cc797312313.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2208] 아이튠즈 실행 시 오류 발생합니다.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

PC측의 iTunes와 충돌이 발생하였을 수 있습니다.
Microsoft Store 측의 iTunes가 설치되어 있는 경우 PC와 아이패드 간의 연결에 실패할 수 있습니다. 
iTunes와 EL Display Hub를 삭제하시고 EL Display Hub를 다시 설치하여 주시길 바랍니다.


iTunes를 같이 사용해야할 경우 Windows용 iTunes를 사용하여 주시길 바랍니다.
[Apple] Windows용 iTunes 다운로드 및 사용하기 : https://support.apple.com/ko-kr/HT210384

또는 Microsoft Store 측의 iTunes를 계속 사용하기 위해서는 설정을 진행하여 주십시오.
1. "설정" - "앱" - "앱 및 기능" - "iTunes" - "고급 옵션"으로 이동
2. "앱 사용 권한"의 "백그라운드 앱"을 "켬"으로 설정
3. "로그인하여 실행"의 "iTunes Mobile Device 보조 응용 프로그램" 및 "iTunes 보조 응용 프로그램"을 "켬"으로 설정
4. PC 재부팅


위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

Ea​​sy&Light 
```
