### ISSUE TITLE
포토샵 실행 시 성능 저하

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2227]
- 문의 날짜 : 2023년 8월 25일 오후 3시 40분
- 메일 주소 : [dis2011@naver.com](mailto:dis2011@naver.com)

노트북에서 이지캔버스 설치만 하면 포토샵 버벅거림이 생겨버립니다.

제거를 하면 그 버벅임이 사라지구요.

노트북으로 사용중이긴 한데 노트북 사양또한 요즘 본체급 성능을 내는 노트북인데도

심히 버벅거리내요.

이지캔버스만 설치하면 바로 포토샵이 버벅거리는데 문제가 뭘까요?

듀얼모니터로좀 쓰고싶은데 버벅거림 때문에 작업자체를 못할 지경입니다.

버벅거림 해결하기위해 노트북 초기화도 해봤고 포토샵 재설치도 해봤습니다.

알고보니 이지캔버스 삭제하니 포토샵 버벅거림이 완전히 사라지더군요..

원인이 뭔지 알 수 있을까요?

[EL_Display_be67dbea-9edf-4159-b49d-ddfbf147b082.zip](https://github.com/edh-git/EL_Display_Hub/files/12449224/EL_Display_be67dbea-9edf-4159-b49d-ddfbf147b082.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2227] 이지캔버스 와 포토샵 문제
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

해당 문제의 경우 EL Display Hub가 캡처 및 인코딩에 GPU를 사용하여 발생하는 문제로 보이며,
포토샵에서도 GPU를 이용한 기능을 활용하는 것으로 보이며, 두 프로그램이 충돌하여 발생하는 것으로 보입니다.

문제 해결을 위해서는 포토샵 GPU Acceleration 설정을 확인하여 주십시오.
설정 - 성능 - 그래픽 프로세서 설정의 "그래픽 프로세서 사용(G)"가 체크를 해제합니다.
단, 해당 옵션이 켜져 있지 않을 경우 터치 및 제스처가 정상적으로 동작하지 않을 수 있습니다.

* 참조 링크
    * https://community.adobe.com/t5/photoshop-ecosystem-discussions/touch-gestures-not-working/m-p/11270004
    * https://helpx.adobe.com/photoshop/kb/troubleshoot-gpu-graphics-card.html#multiple-gpus

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다

Easy&Light
```
