### ISSUE TITLE
화질 문제

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2229]
- 문의 날짜 : 2023년 8월 26일 오후 5시 47분 
- 메일 주소 : [qkwnsgn@naver.com](mailto:qkwnsgn@naver.com)

4k 동영상 재생시 화질이 깨집니다.
작업표시줄 아이콘도 화질이 좋지 않네요.
원래그런것인지 문의드립니다.

windows 11
intel i5-12500
ram dual 16G+16G
ssd nvme wd black sn770

[EL_Display_015917d4-7438-4b70-8861-206b5026ca6e.zip](https://github.com/edh-git/EL_Display_Hub/files/12449304/EL_Display_015917d4-7438-4b70-8861-206b5026ca6e.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2229] 화질 문제
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

로그를 검토해본 결과 현재 확장 화면의 해상도가 1492x1042로 설정되어 있으며, 
아이패드의 원본 화질인 2388x1668에 비하여 해상도가 낮아 화질이 저하되어 표현될 수 있습니다.
PC 프로그램에서 해상도를 최대로 선택하여 주십시오.

이후에도 같은 문제가 발생하는 경우에는 EL Display Hub가 화면 캡처 및 인코딩에 GPU를 사용하여, 동영상 재생에서 사용되는 GPU와 병목이 발생해 문제가 발생할 수 있습니다.
해당 경우에는 PC 프로그램에서 "성능 모드"를 낮춰서 주사율을 낮춰 테스트하여 주시길 바랍니다.

위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 로그 취득 가이드를 참조하여 PC로그와 어플리케이션 로그를 첨부하여 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다.

Easy&Light
```
