### ISSUE TITLE
twomon se 성능이슈

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#223]
e-mail:raptor210@snu.ac.kr<br><br>이전에 아이패드 twomon se와 pc 프로그램간 연결이 되지 않는다고 문의드렸으나 아이패드 앱 재설치 후 연결은 됩니다. 하지만 이전과 비교하여 사용하기 어려울 정도로 속도가 느려졌습니다. 최고 성능으로 설정하여도 FPS가 너무 낮습니다.<br><br>[EL_Display_94133a1f-25db-4655-9769-392a049c195b.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_94133a1f-25db-4655-9769-392a049c195b.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.


이번 업데이트로 사용자 설정의 "해상도"와 "성능 모드"의 기본값이 높은 품질이 선택되도록 변경되었습니다.
설정이 변경되어 PC 및 태블릿의 사양에 따라서 성능이 다소 느려질 수 있으며,
아래의 FAQ를 참조하셔서 "해상도"와 "성능 모드"의 설정을 변경하여 주시길 바랍니다.

[FAQ] 화면 갱신이나 반응속도가 느려요. : http://www.easynlight.com/supporteasycanvas/?faq=112

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않거나 다른 문의 사항이 있으시다면 재문의 부탁드립니다.

감사합니다.

Ea​​sy&Light 
```
