### ISSUE TITLE
프로그램 설치 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2239]
- 문의 날짜 : 2023년 8월 30일 오후 12시 8분
- 메일 주소 : [marsci@hanmail.net](mailto:marsci@hanmail.net)

제목: 프로그램 설치가 되지 않습니다.

문의사항: 안녕하세요.
어제까지는 사용을 해 왔는데..(간혹 재설치 등이 필요했지만?? )
금일 오전에 아이패드와 연동이 되지 않아 프로그램 삭제 후 다시 설치를 하려고 하는데 설치가 되지 않고 있습니다.
\"adb\" 프로그램이 읽히지 않는다는 메시지가 나옵니다. 무시하고 설치하면 \"End Uninstall EasyCanvas
End Uninstall EasyCanvas Pro
End Uninstall Twomon SE
대상 폴더: C:\\Program Files (x86)\\EL Display Hub
압축 해제: EL_Display_Hub.exe... 100%
압축 해제: EL_Display_service_proc.exe... 100%
압축 해제: EL_Display_log_grabber.exe... 100%
압축 해제: duplicateoutput_checker.exe... 100%
압축 해제: nvidia-license.txt... 100%
압축 해제: EL_Display_service.exe... 100%
압축 해제: EL_Display_server_core.dll... 100%
압축 해제: EL_Display_vhidbuslib.dll... 100%
압축 해제: EL_Display_vdispiddlib.dll... 100%
압축 해제: avcodec-58.dll... 100%
압축 해제: avformat-58.dll... 100%
압축 해제: avutil-56.dll... 100%
압축 해제: swresample-3.dll... 100%
압축 해제: swscale-5.dll... 100%
기록할 수 없음: C:\\Program Files (x86)\\EL Display Hub\\AdbWinApi.dll
\"
이런 메시지가 나옵니다.

확인 부탁드립니다.

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2239] 프로그램 설치가 되지 않습니다.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

보내주신 증상을 검토한 결과 설치 중 adb.exe 프로그램이 제대로 동작하지 않아서, 설치에 실패하는 것으로 보입니다.

해당 증상의 경우 기존 실행 중이던 adb.exe 프로그램이 정상적으로 동작하지 않는 경우 발생하는 문제입니다.

일시적인 오류일 경우에는 PC를 재부팅(종료 옵션의 "다시 시작")이후 재설치를 통해서 해결할 수 있습니다.
재부팅 이후에도 동작하지 않을 경우에는 "작업 관리자"를 실행하여 "백그라운드 프로세스"에서 adb.exe를 종료 시킨 뒤 프로그램을 설치하여 주시길 바랍니다.

위와 같은 조치사항들을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 :  http://www.easynlight.com/en/supporttwomon/?faq=78

[로그 수동 수집 절차]
1. Windows키 입력 > "실행" > "msinfo32" 입력 > 파일 > 저장
2. C:\ProgramData\devguru 경로에 존재하는 파일
3. C:\Users\{사용자명}\AppData\Local\Devguru 경로에 존재하는 파일 ( %localappdata%\Devguru  로 경로에 접근 가능)

세 군데의 파일들을 압축하여 첨부해주세요.


감사합니다.

Ea​​sy&Light 
```
