### ISSUE TITLE
바탕화면 아이콘 표시되지 않음

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2319]
- 문의 날짜 : 2023년 10월 2일 오전 8시 58분
- 메일 주소 : [ioi8204@naver.com](mailto:ioi8204@naver.com)

**이상합니다**

컴퓨터에 설치하고 아이패드에 설치후 연결하면 아이패드에 pc 바탕화면만
뜨고 아무것도 안보입니다.시작메뉴는 보이는데 바탕화면 아이콘과 아무것도 안보입니다

[EL_Display_beb8a626-f23c-41cb-99ad-40d297050121.zip](https://github.com/edh-git/EL_Display_Hub/files/12798152/EL_Display_beb8a626-f23c-41cb-99ad-40d297050121.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2312] 이상합니다
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

보내주신 로그에서는 별다른 이상을 발견하지 못하였습니다.

현재 제품이 확장 모드로 사용되는 것으로 보입니다.
EasyCanvas는 최초 연결 시 자동으로 확장 모드로 시작되며, 
PC에 모니터를 추가로 연결한 것과 같이 사용하시면 됩니다.

복제 모드로 사용하기 위해서는 EL Display Hub 프로그램을 실행 시켜서
"화면 선택" 항목에서 Display를 변경하여 주십시오.

추가 문의 사항이 있으시다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```
