### ISSUE TITLE
그래픽 특정 옵션 적용 시 작동 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2326]
- 문의 날짜 : 2023년 10월 5일 오후 1시 17분 
- 메일 주소 : [yrs03143@naver.com](mailto:yrs03143@naver.com)

**ASUS ROG Flow X16 (2023) GV601 모델 그래픽 특정 옵션 적용 시 작동 불가에 관한 문의**

안녕하세요, 현재 ASUS ROG Flow X16 (2023) GV601 모델을 사용중이며, 아이패드 프로 12.9인치 6세대 모델을 함께 사용 중입니다. 다름 아니라 ASUS에서 제공하는 프로그램인 Armoury Crate에서 GPU의 모드를 표준(성능과 배터리 수명의 밸런스, Windows 기본값)에서 Ultimate(최대 성능, 전력 최대 이용)로 변경 시 Twomon SE 앱을 통해 디스플레이 인식은 되나, 아이패드의 Twomon SE 앱 화면이 멈춰 아무 작업도 할 수 없는 상태가 됩니다. 앱 종료 후 재실행을 해도 같은 문제가 발생했고, GPU 모드를 표준으로 변경하니 다시 정상 작동 하는 것을 확인했습니다. GPU모드 변경에 따라 앱의 작동 여부가 어떠한 상관관계가 있는것인지, 모드를 변경하더라도 정상작동하게 하려면 어떻게 해야하는지 여쭤보고 싶습니다.

[EL_Display_83c1c82c-542b-401a-a449-cb224aca583a.zip](https://github.com/edh-git/EL_Display_Hub/files/12825733/EL_Display_83c1c82c-542b-401a-a449-cb224aca583a.zip)
![스크린샷 2023-10-05 131322](https://github.com/edh-git/EL_Display_Hub/assets/77039816/dfc90c43-64e6-4c12-bcc4-9081ef2a87a8)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2326] ASUS ROG Flow X16 (2023) GV601 모델 그래픽 특정 옵션 적용 시 작동 불가에 관한 문의
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 화면 캡처 부분이 정상적으로 동작하지 않는 것을 확인하였습니다. 
해당 문제는 노트북의 이산 GPU 환경에서 발생할 수 있는 문제입니다.

우선 해당 문제가 발생하는 환경에서 재설치를 통하여, 인스톨러에서 해당 문제를 해결할 수 있는 옵션을 설정하게 시도하여 주십시오.

재설치 이후에도 해결이 되지 않을 경우 그래픽 드라이버의 옵션을 설정하여 해결이 가능합니다. 
링크를 참조하셔서 옵션을 "통합 그래픽"으로 변경해주시길 바랍니다.

[FAQ : Twomon SE가 동작하지 않습니다.] "NVIDIA 제어판에서 3D 설정 변경해주세요" : http://www.easynlight.com/supporttwomon/?faq=123

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

Ea​​sy&Light 
```
