### ISSUE TITLE
선 떨림 문제

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2329]
- 문의 날짜 : 2023년 10월 9일 오후 11시 1분
- 메일 주소 : [snsnk7@naver.com](mailto:snsnk7@naver.com)

**선 떨림 문제** 

안녕하세요 항상 수고가 많으십니다 . 다름이 아니라 가로세로 직선을 그을때는 문제가 없는데 대각선이 들어가면 선이 많이 떨립니다 곡선도 마찬가지이구요.
다른 앱 사용시에는 문제가 없는걸로 보아서 패드 문제는 아닌것 같습니다.
혹시 해결방법이 있을까요?

![제목 없음-1](https://github.com/edh-git/EL_Display_Hub/assets/77039816/f1317587-e061-4c35-b2b1-61f598103507)
[EL_Display_0f7bce16-93f7-4878-a95b-1be39f7fbba0.zip](https://github.com/edh-git/EL_Display_Hub/files/12851544/EL_Display_0f7bce16-93f7-4878-a95b-1be39f7fbba0.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2330] 선 떨림 문제
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

문의해주신 문제는 애플 펜슬의 지터링 현상으로 보입니다.

타 어플리케이션에서 정상적으로 동작하는 경우 각 앱에서 보정이 진행되어 정상적으로 보일 수 있으며, EasyCanvas의 경우 태블릿에서 입력된 스타일러스 입력을 PC의 스타일러스 입력으로 전달하는 프로그램으로 해당 문제에 대한 수정은 어려울 것으로 보입니다.

추가로 지터링 현상의 경우 태블릿의 화면 보호 필름이나 강화 유리 등을 통해서 문제가 심화될 수 있습니다.

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```
