### ISSUE TITLE
설정 변경 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#233]
e-mail:hoonok77@naver.com<br><br>설정 변경은 어떻게 하나요? 양쪽에 같은 화면만 나오네요..<br><br>[EL_Display_63a63d5b-3316-4e74-b749-9ff34423ca9c.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_63a63d5b-3316-4e74-b749-9ff34423ca9c.zip)

**Comment by AdamPark0030** [comment]
아래와 같이 답변 부탁드립니다.
----
```
안녕하세요 고객님, Easy & Light 지원 팀 입니다.

먼저 이용에 불편함을 드려 정말 죄송합니다.

복제화면이 아닌 확장 화면으로 사용하는 방법을 안내해 드립니다.

1. PC와 태블릿을 유선으로 연결합니다.

2. 연결 시 옵션 설정 탭의 오른쪽에 연결된 기기가 있는지 확인합니다.

3. 연결된 기기가 존재한다면, 화면 선택 옵션에서 "확장" 옵션을 선택합니다.

위와 같은 조치사항을 취하신 후 문제가 지속된다면 태블릿 로그를 첨부하여 재문의 해주시길 바랍니다.

감사합니다.

Easy&Light.
```
![image](https://user-images.githubusercontent.com/73160679/150262242-60b2a2cc-3ce5-48ab-9279-ad630e67bd5f.png)

**Comment by AdamPark0030** [comment]
#277 에서 답변되었으므로 이슈를 닫습니다.
