### ISSUE TITLE
Windows Ink 비활성화 문의

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2340]
- 문의 날짜 : 2023년 10월 14일 오전 9시 45분
- 메일 주소 : [edmundham2005@gmail.com](mailto:edmundham2005@gmail.com)

**Mapping Issue (Windows Ink)**

Hi! I was wondering if there is anyway to configure in settings to disable Windows Ink in this application? I keep trying to use my iPad as a drawing tablet but Windows Ink keeps preventing me.
[EL_Display_cf7bbb88-5e8f-4ffd-9350-6a2f72a61ebf.zip](https://github.com/edh-git/EL_Display_Hub/files/12911097/EL_Display_cf7bbb88-5e8f-4ffd-9350-6a2f72a61ebf.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2340] Mapping Issue (Windows Ink)
```
#### 본문
```
Hello, customer. This is the Easy&Light support team.

EasyCanavas transmits input based on Windows Ink through a virtual HID driver when inputting Stylus, and there is no setting to disable this function.

If you set the stylus input value in the program you are using to use wintab, it is assumed that this is the desired function.
However, please note that when set to wintab, the pen pressure and tilt values of the stylus are not transmitted properly.

If you have any additional questions, please contact us at any time.
Thank you

Easy&Light
```
