### ISSUE TITLE
앱 실행 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2366]
- 문의 날짜 : 2023년 10월 24일 오후 10시 25분 
- 메일 주소 : [ainsley_bilton@hotmail.co.uk](mailto:ainsley_bilton@hotmail.co.uk)

**Application wont start**

I can't start the application. The service won't start. Event log details below:

Faulting application name: EL_Display_service.exe, version: 4.7.3.8, time stamp: 0x641413b1
Faulting module name: nvcuvid.dll, version: 7.17.14.5671, time stamp: 0x5f75524c
Exception code: 0xc0000005
Fault offset: 0x0014c581
Faulting process ID: 0x0x7C4
Faulting application start time: 0x0x1DA067CE31C8044
Faulting application path: C:\Program Files (x86)\EL Display Hub\EL_Display_service.exe
Faulting module path: C:\WINDOWS\SYSTEM32\nvcuvid.dll
Report ID: 27ff9d97-cdf2-4841-85d8-d0d57070c1b0
Faulting package full name:
Faulting package-relative application ID:

[EL_Display_2a9fab9a-5ddb-48e5-8b85-98b71e24e0db.zip](https://github.com/edh-git/EL_Display_Hub/files/13167305/EL_Display_2a9fab9a-5ddb-48e5-8b85-98b71e24e0db.zip)
[EL_Display_09a51ef6-9b18-451a-bdb0-efd586d4f08d.zip](https://github.com/edh-git/EL_Display_Hub/files/13167306/EL_Display_09a51ef6-9b18-451a-bdb0-efd586d4f08d.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2366] Application wont start
```
#### 본문
```
Hello, customer. This is the Easy&Light support team.

First of all, we apologize for any inconvenience caused.

After reviewing the logs and symptoms you sent, it appears that an error occurs in an encoding-related function.
Please proceed with the update and reinstallation as follows.

1. Delete “EL Display Hub”
2. Check Windows updates and update to the latest Windows.
3. Update graphics drivers
      [Intel] Driver Support Program: https://www.intel.com/content/www/us/en/download-center/home.html
      [AMD] Graphics driver installation page: https://www.amd.com/support
      [NVIDIA] Graphics driver installation page: https://www.nvidia.co.kr/Download/index.aspx
4. Reboot your PC (using “Restart” in the shutdown options).
5. Reinstall “EL Display Hub” by downloading the new installer (run the installer by “right-clicking - Run as administrator” during installation).
      [EL Display Hub] Installation page: http://www.easynlight.com/en/easycanvas/

If the problem does not improve after taking the above measures, please re-inquire by attaching new PC logs and application logs.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

thank you

Easy&Light
```
