### ISSUE TITLE
원격 관련 에러 수정 요청

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2370]
- 문의 날짜 : 2023년 10월 25일 오후 3시 35분 
- 메일 주소 : [sotae69@gmail.com](mailto:sotae69@gmail.com)

**원격 관련 에러 수정 요청**

예전 버전에서는 pc를 원격으로 붙었다가 다시 로그인해도 정상적으로 나왔지만 최근 버전에서는 나오지 않음.
[추가 요청 사항]
설치형 프로그램인데 열어놨던 서비스 관련해서 위치좀 기억해서 다시 그 위치에서 열리도록 개발 요청

[EL_Display_2a5eba72-c1d5-4cc7-a3b8-99d34292dc63.zip](https://github.com/edh-git/EL_Display_Hub/files/13167387/EL_Display_2a5eba72-c1d5-4cc7-a3b8-99d34292dc63.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2370] 원격 관련 에러 수정 요청
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

원격 접속 해제 후 화면 캡처에 실패하는 것으로 보이며,
로그 상의 오류 코드는 31로 ERROR_GEN_FAILURE 오류이며 해당 오류는 연결된 장치가 제대로 동작하지 않을 때 발생하는 오류로, 원격 접속 시 OS의 상에서 장치 작동에 문제가 되는 것으로 보입니다.

해당 증상은 OS의 캡처 기능의 종속적인 문제로 OS나 디스플레이 드라이버 등이 수정된 것으로 보여 저희 측에서는 수정이 어렵습니다.

또한 열려있는 윈도우의 창 위치를 기억하여 해당 위치에 재배치하는 기능의 경우 현재는 윈도우 10 이상의 OS에서 실제 모니터의 화면을 기억하는 동작이 탑재되어, 해당 기능을 사용하고 있습니다.
개선이 가능한 점을 검토하여, 
추후 업데이트 시 해당내용 관련하여 논의해보도록 하겠습니다.

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```
