### ISSUE TITLE
해상도 변경 

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2375]
- 문의 날짜 : 2023년 10월 30일 오후 6시 16분
- 메일 주소 : [rudgns8678@naver.com](mailto:rudgns8678@naver.com)

**디스플레이 해상도를 더 낮게**

디스플레이 해상도를 800x600 정도까지 내리고 싶습니다.
방법을 알려주세요.
[EL_Display_7d7d0793-04ee-4e10-979b-0e15b2f918ea.zip](https://github.com/edh-git/EL_Display_Hub/files/13210940/EL_Display_7d7d0793-04ee-4e10-979b-0e15b2f918ea.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2375] 디스플레이 해상도를 더 낮게
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

문의하신 기능은 현재 지원되지 않는 기능입니다.
Twomon SE의 가상 디스플레이의 최하 해상도는 연결된 태블릿 장치의 절반 해상도를 지원하고 있습니다.

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다. 

Easy&Light
```
