### ISSUE TITLE
고스트 터치 현상 발생

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2392]
- 문의 날짜 : 2023년 11월 4일 오후 9시 43분
- 메일 주소 : [fkwls13@naver.com](mailto:fkwls13@naver.com)

**아이패드프로 12.9인치 3세대와 윈도우 11과 물렸을 떄 오류.**

안녕하세요,
이번에 투섬 se 를 구매 후, 일부 오류가 있어 문의드립니다.

1. 앱 구매 후 잘 확장모니터를 사용중인데, 아이패드 쪽에 고스트 터치 현상이 발생됩니다. 예를들어 문서작업을 하는데 자동으로 문단이 선택된다지 하는데, 재부팅을 해보고 다시 실행해봐도 무슨문제인지 감이 안잡힙니다.

혹시나해서 무선마우스(블루투스 x) 아닌걸로도 교체해서 테스트해봤는데 여전합니다. 저와같은 사례있는지 여부와 해결방법있을지 문의드립니다.

(USB C to C는 애플 정품 케이블)

2.윈도우 11 - 아이패드 12.9 3세대 와 확장모니터 연결 시

[EL_Display_892c7ecb-e325-4574-9922-7b849d0afb94.zip](https://github.com/edh-git/EL_Display_Hub/files/13261369/EL_Display_892c7ecb-e325-4574-9922-7b849d0afb94.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2392] 아이패드프로 12.9인치 3세대와 윈도우 11과 물렸을 떄 오류.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

EasyCanvas의 경우 태블릿의 터치 입력을 PC로 전달하는 역할을 합니다.
PC 측에서는 입력된 터치 정보를 가상 장치를 통해서 실제 터치 장치처럼 Windows OS에서처리합니다.

고스트 터치가 발생하는 것은 iPad에서 고스트 터치가 발생한 것이며, 
해당 문제는 아이패드의 화면에 이물질이 묻었거나, 두꺼운 필름 혹은 강화 유리를 부착한 경우 발생하는 문제로 알려져 있습니다.

화면을 부드러운 천 등으로 닦은 뒤 발생 여부를 확인하시고, 동일한 이슈가 계속 발생한다면 애플 측에 문의해보셔야 할 것으로 보입니다.


화질의 경우 화면의 해상도가 낮을 경우 아이패드의 레티나 디스플레이와의 괴리로 인한 화질 저하가 느껴질 수 있습니다.
로그를 검토해본 결과 현재 확장 화면의 해상도가 1366x1024로 설정되어 있는 것으로 보이며,
PC 프로그램에서 해상도를 최대 해상도로 설정하신 뒤 상태를 확인하여 주십시오. 


위의 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 아래의 로그 취득 가이드를 참조하여 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

더 좋은 제품을 만들기 위해 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
```
