### ISSUE TITLE
화웨이 태블릿에서 이용불가

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#240]
e-mail:ing.galvan.754@gmail.com<br><br>Hello,<br>I aid for my Twomon SE on my huawei tablet, but now with this recent update, I cann't use it any more, and I cann't find the APK update on the huawei app store.<br><br>Regards<br><br>[EL_Display_2864a536-8cb4-4412-a114-eb9ff78a63eb.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_2864a536-8cb4-4412-a114-eb9ff78a63eb.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
Hello, customer. Easy&Light support team.

First of all, we apologize for the inconvenience.

Currently, the Twomon SE app is pending approval in the Huawei App Gallery.

We will make it available for download as soon as possible.

thank you.

Easy&Light
```
