### ISSUE TITLE
트라이얼 사용 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2401]
- 문의 날짜 : 2023년 11월 7일 오후 5시 17분
- 메일 주소 : [hans.august@gmail.com](mailto:hans.august@gmail.com)

**Can't access the trial**

Hello. When opening the iPad app, it takes me directly to the payment prompt, even though I haven't used the app before. It does say that I can try the app for 3 days, but there's no other actions to take than to pay or to restore. I have attached a screenshot of the iPad screen described.

The iPad is connected with wire to my PC, software is up to date, and it's open on the PC. When running the "PC program diagnosis" I get one red exclamation mark on "Device connection status", but no error codes to see. I have tried un- and reinstalling both the pc and iPad apps.

![photo_2023-11-07_08-52-34](https://github.com/edh-git/EL_Display_Hub/assets/77039816/bcdf8606-2036-4684-b322-ed4cd1a21fcf)
[EL_Display_b3664762-1857-4971-b24d-703a7f8b8974.zip](https://github.com/edh-git/EL_Display_Hub/files/13290597/EL_Display_b3664762-1857-4971-b24d-703a7f8b8974.zip)

**Comment by Sienna-lee** [comment]
@james-kim-Devguru 

해당 사용자가 트라이얼을 사용하지 않았는데 사용이 불가하다고 합니다.
혹시 확인할 방법이 있을까요?
확인 방법이 없을 경우, 앱 재설치 및 계정 로그인과 EasyCanvas 구독형 트라이얼 사용을 가이드하도록 하겠습니다.

**Comment by james-kim-Devguru** [comment]
@Sienna-lee 
iOS의 trial의 경우 앱스토어의 인앱 상품을 구매하는 방식으로 처리되며,
앱스토어의 응답을 통해서 구매 여부를 확인합니다.

해당 값을 저희 측에서 수정은 어려우므로 제시하신 구독형 트라이얼 사용과 계정 확인 코멘트를 하면 될 것 같습니다.

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, We are an Easy & Light support team.

I'm sending this email for your inquiry.  

Would you like to check by logging in to your App Store account again?

The App Store provides information on whether to use a trial.

Since the developer cannot verify the user's account, it is not possible to check whether it is being used.

If the problem is not resolved, please try the EasyCanvas subscription app trial.
You can use it for free for 3 days.

https://apps.apple.com/us/app/id1499946999


You must cancel your subscription before it proceeds to avoid payment. Even if you cancel your subscription, you can still use it for free for 3 days.

If you have any questions about the product, please reply at any time.

Thank you.


Easy&Light
