### ISSUE TITLE
프로그램 UI 깨짐

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2405]
- 문의 날짜 : 2023년 11월 8일 오전 9시 18분
- 메일 주소 : [onepieceotc@gmail.com](mailto:onepieceotc@gmail.com)

**설치 후 이상발생**

처음에 설치를 잘 하고 사용하다가 나중에 어떠한 오류로 인해서 재설치를 진행했습니다.
재설치를 할 때 일부 파일들을(adb 등) 불러올수 없다. 란 오류가 떳는데
중단하고 재부팅 후 설치를 다시 진행하니 설치가 진행 되더라고요.
근데 설치 후 해당 사진처럼 이상하게 나옵니다.

모니터는 4k 에 글카는 2070super라 스펙은 부족함이 없습니다.

애초에 처음에는 잘 썻습니다.

<img width="349" alt="1" src="https://github.com/edh-git/EL_Display_Hub/assets/77039816/1e7a19ac-400b-4cad-b4cb-57dc42fdffcf">

[EL_Display_51175279-68f3-4ade-b146-eecbeae2002b.zip](https://github.com/edh-git/EL_Display_Hub/files/13290721/EL_Display_51175279-68f3-4ade-b146-eecbeae2002b.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2405] 설치 후 이상발생
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

화면의 배율 등의 문제로 DPI 설정 충돌로 인하여 UI가 제대로 표시되지 않는 문제로 보입니다.

* 이전 앱 또는 프로그램이 Windows와 호환되도록 설정 (높은 DPI 설정 변경) : https://support.microsoft.com/ko-kr/windows/%EC%9D%B4%EC%A0%84-%EC%95%B1-%EB%98%90%EB%8A%94-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8%EC%9D%B4-windows%EC%99%80-%ED%98%B8%ED%99%98%EB%90%98%EB%8F%84%EB%A1%9D-%EC%84%A4%EC%A0%95-783d6dd7-b439-bdb0-0490-54eea0f45938#ID0EBH=Windows_10

위 링크의 "높은 DPI 설정 변경" 부분과 첨부해드린 이미지를 참조하셔서 수정하시면 됩니다.

1. "C:\Program Files (x86)\EL Display Hub"의 EL_Display_Hub.exe 파일의 우클릭 - 속성 실행
2. 호환성 - 높은 DPI 설정
3. 높은 DPI 조정 재정의 - "시스템(고급)"
4. PC 프로그램 재실행


위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

Ea​​sy&Light 
```
