### ISSUE TITLE
해상도 문제

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2408]
- 문의 날짜 : 2023년 11월 8일 오후 5시 27분
- 메일 주소 : [leyal@giview.com](mailto:leyal@giview.com)

Title: When using 4K screen with scale, the SE screen gives faulty resolution report

Questions: Hi,

I develop an application which uses the main screen and a tablet for control. Upon startup of the program it figures up which is the screen to use and deploy the windows for each. When using a 4K monitor on Windows 10, with scaling of 125% or 150%, (but the Towmon SE powered tablet uses its normal resolution of 960X600 at 100% scaling), the image on the tablet gets too large for the reported resolution.

My log file for the screens monitors reports that: (tabbed text)
Header X1 Y1 X2 Y2 Width Height Scale Primary Findings
Connected monitor -1440 0 0 900 1440 900 100% No
Connected monitor 0 0 3840 2160 3840 2160 140% Yes Acceptable screen

This happens in the attached configuration, as well in the most updated Windows 10, Windows 11 and Twomon SE versions.
I figure the resolutions using

I\'m using EnumDisplayMonitors in C++ and Screen.AllScreens in C# and get the same results. I guess that Windows do strange things with scale factors and resolutions. If there is a different API commands to use (preferred for C#) it will be very helpful.

Thanks,
Eyal

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2408] When using 4K screen with scale, the SE screen gives faulty resolution report
```
#### 본문
```
First of all, we would like to thank you very much for using our product and for your detailed analysis.

I would like to collect logs and environment information for detailed analysis of your inquiry.
Please refer to the information below and send us more detailed information about the logs and specifications of our PC program and the logs and specifications of our tablet PC.


[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

or

[Log manual collection procedure]
1. Enter Windows key > “Run” > Enter “msinfo32” > File > Save
2. File existing in the C:\ProgramData\devguru path
3. Files existing in the C:\Users\{user name}\AppData\Local\Devguru path (the path can be accessed through %localappdata%\Devguru)

Please compress and attach the three files above.


We will strive to create better products.
Thank you

Easy&Light
```

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

Hi,

 

Thanks for your response.

 

I attach the log files you requested, including the logs from two different users on the same computer.

 

Thanks,

Eyal


[Twomon PC Logs.zip](https://github.com/edh-git/EL_Display_Hub/files/13304456/Twomon.PC.Logs.zip)
