### ISSUE TITLE
화면 색상 차이

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2424]
- 문의 날짜 : 2023년 11월 16일 오전 4시 20분
- 메일 주소 : [luis.tjdongin@gmail.com](mailto:luis.tjdongin@gmail.com)

**색상이 많이 다르게 나옵니다.**

안녕하세요.
윈도우 화면에 비해 아이패드에서는 화면이 너무 밝게 나와서 색상이 많이 차이가 납니다. 조금 차이나는 것이 아니라 아이패드 화면만 보면서는 그래픽 작업이 거의 불가능한 정도여서 그래픽 작업 시는 펜타블랫처럼 사용할 수 밖에 없습니다.
밝기 또는 색감을 조정하는 방법이 있을까요?

![IMG_8613](https://github.com/edh-git/EL_Display_Hub/assets/77039816/5503e8a1-68dc-4138-989d-6c10c48c8d8b)
![스크린샷 2023-11-16 041453](https://github.com/edh-git/EL_Display_Hub/assets/77039816/7d84a2dc-97f9-453c-b1dd-4c6f250ae2b6)
[EL_Display_1e7ec65e-45c4-4d2a-bd13-57a34641e3d3.zip](https://github.com/edh-git/EL_Display_Hub/files/13371116/EL_Display_1e7ec65e-45c4-4d2a-bd13-57a34641e3d3.zip)

**Comment by Sienna-lee** [comment]
해당 사용자가 추가로 메일을 보내왔습니다.

----

**(아이패드 화면 색상)전체 화면으로 캡쳐 이미지 다시 보내드립니다.**

너무 밝아서 색상이 잘 보이지 않는 화면이 아이패드입니다.
아이패드에서 크롬 리모트데스크으로 화면 공유했을 때에는 동일한 색상으로 출력되는 것을 확인했습니다.

![IMG_8614](https://github.com/edh-git/EL_Display_Hub/assets/77039816/45ba3a4d-7785-4f44-8bba-4f6a08ced1e3)
![스크린샷 2023-11-16 043632](https://github.com/edh-git/EL_Display_Hub/assets/77039816/b9ad175a-435c-4e38-8acd-c4849d435483)
[EL_Display_bd38840a-7228-4562-a631-6764793d5a5f.zip](https://github.com/edh-git/EL_Display_Hub/files/13371132/EL_Display_bd38840a-7228-4562-a631-6764793d5a5f.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2424] 색상이 많이 다르게 나옵니다.
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
해당 문제는 사용하시는 모니터와 Windows 설정에서 HDR 기능을 켜서 발생하는 문제입니다.
현재 EasyCanvas는 HDR에 대한 기능을 지원하지 않습니다.

정상적인 사용을 위해서는 HDR 기능을 꺼주시길 바랍니다.

1. "설정" > "시스템" > 디스플레이"로 이동
2. 복제에 사용하고 있는 디스플레이를 선택
3. "HDR 사용"을 끕니다.

HDR 기능의 경우추후 업데이트 시 해당내용 관련하여 논의해보도록 하겠습니다.

감사합니다

Easy&Light
```

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

안녕하세요.
보내주신 답변대로 하니 문제가 해결됐습니다.

감사합니다!!
