### ISSUE TITLE
커서 위치 오류

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2437]
- 문의 날짜 : 2023년 11월 18일 오후 7시 35분
- 메일 주소 : [neaveg2020@gmail.com](mailto:neaveg2020@gmail.com)

**Inaccurate cursor positioning**

When I try to draw my cursor on PC isn't right under the apple pencil tip, it can be positioned higher or lower, or slightly to the side. How do I fix that?

![photo_2023-11-18_15-25-58](https://github.com/edh-git/EL_Display_Hub/assets/77039816/37283a60-32d7-4f3d-977d-36e38e92fc15)
[EL_Display_a6c670b0-1060-4615-83f6-e955d1febd66.zip](https://github.com/edh-git/EL_Display_Hub/files/13405423/EL_Display_a6c670b0-1060-4615-83f6-e955d1febd66.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2437] Inaccurate cursor positioning
```
#### 본문
```
Hello, customer. This is the Easy&Light support team.

First of all, we apologize for any inconvenience caused.

It appears that the problem can be solved by adjusting the options in the "Touch coordinate correction item" in the EL Display Hub menu. (Please test using various options.)

Additionally, if normal coordinate settings are not possible due to changing the EL Display Hub option, please refer to the link below and change the graphics driver settings.
[FAQ] I touched the screen, but hte coordinates do not match. : http://www.easynlight.com/en/supporttwomon/?faq=85


If the same error occurs even after updating the PC program
Please refer to the log acquisition guide below and re-inquire with the application log.

[FAQ] Log acquisition guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

We will strive to create better products.
Thank you

Easy&Light
```
