### ISSUE TITLE
세로모드 불가, 고해상도 조정시 튕김

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#244]
e-mail:DublinDk@outlook.com<br><br>1. 세로모드 안됨<br>-작업창 전환 안되고<br>디스플레이 설정에서 식별 안됨.<br>2. 고해상도 조정시 튕김<br><br>UI는 예쁜대 오류 투성이네요...<br>시범 가동안하시고 업데이트 올리셨나요..<br><br><br>[EL_Display_219b4367-c7fc-4aaf-8466-a4fe7a4a76a1.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_219b4367-c7fc-4aaf-8466-a4fe7a4a76a1.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

윈도우 10에서 세로 모드로 동작시 오류가 발생하는 문제를 확인하였습니다.
해당 문제 해결하기위한 수정을 진행 중이며, 최대한 빠르게 수정 버전을 배포하도록 노력하겠습니다.
새로운 버전이 배포될 버전에서의 동작을 확인부탁드립니다.

또한 현재 윈도우11의 경우 세로 모드일 때 Windows에서 제공하는 기능에 문제가 있는 것으로 판단됩니다.
Microsoft에서 오류를 수정하지 않으면 해당 문제는 해결이 어려울 것으로 보이며,
현재로서는 불편하시더라도 Windows 11에서는 가로 모드로 사용해주시길 바랍니다.

감사합니다.

Ea​​sy&Light 
```
