### ISSUE TITLE
PC 시작 시 에러코드 표시

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2440]
- 문의 날짜 : 2023년 11월 20일 오후 8시 27분 
- 메일 주소 : [okwnet32@gmail.com](mailto:okwnet32@gmail.com)

**Error code A0011001 occurs every time I start the PC.**

Reinstalling the application and restarting the PC" is indicated as the action to take when the error code A0011001 is encountered. Certainly, if I do that, the first startup goes well, but from the next startup, the error code A0011001 is displayed again. I have reinstalled it many times already. Please let me know if there is a way to deal with this.

[EL_Display_557a538d-acd0-423e-ac14-de578fbfeca0.zip](https://github.com/edh-git/EL_Display_Hub/files/13420479/EL_Display_557a538d-acd0-423e-ac14-de578fbfeca0.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2440] Error code A0011001 occurs every time I start the PC.
```
#### 본문
```
Hello, customer. This is the Easy&Light support team.

First of all, we apologize for any inconvenience caused.

After reviewing the logs and symptoms you sent, we discovered a conflict with another program.

Conflicts may occur when used with screen sharing programs or programs with screen capture or recording functions.

There appears to be a conflict with "Duet Display" among the currently installed programs.
After deleting "Duet Display" and "EL Display Hub", reboot your PC (using the "Restart" option in the shutdown option), then download a new installer and reinstall "EL Display Hub".

[EL Display Hub] Installation page: http://www.easynlight.com/en/easycanvas/


If the problem does not improve after taking the above measures, please re-inquire by attaching new PC logs and application logs.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you

Easy&Light
```
