### ISSUE TITLE
세로화면 표시

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2461]
- 문의 날짜 : 2023년 11월 29일 오후 10시
- 메일 주소 : [bjyking2112@naver.com](mailto:bjyking2112@naver.com)

**출력되는 태블릿이 세로만 나와요**

컴퓨터는 리전고
태블릿은 갤럭시 탭S8울트라 이구요
연결 안정성 및 속도는 너무나 좋아서 유로 결재 하고 싶은데요
제 능력으로 도저히 해결 방법을 모르겠어여
리전고는 정상적으로 가로방향으로 출력되는데 태블릿 출력화면은 세로방향으로만 나와서 도저히 사용을 하수가 없어요 프로그램 재설치 다하고 설정 이것저것 건드려봐도 해결 방법이 없습니다.

[EL_Display_f479d52d-9061-40b6-9788-aa616b50c632.zip](https://github.com/edh-git/EL_Display_Hub/files/13494826/EL_Display_f479d52d-9061-40b6-9788-aa616b50c632.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2461] 출력되는 태블릿이 세로만 나와요
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

해당 증상과 로그를 확인해본 결과 현재 프로그램 상 정상적인 동작으로 확인됩니다.

연결하신 PC(리전고)의 모니터가 기본적으로 세로 모양(1600x2560)이며, 출력 시에는 90도로 회전하여 표시하고 있는 것으로 보입니다.

현재의 상태는 앱의 경우 태블릿에서 가로로 표시하도록 고정되어있으며,
PC측 화면을 캡처한 뒤 90도로 회전하여 표시하여 세로로 나오는 것처럼 출력되었습니다.

현재 프로그램 상으로는 세로 화면 출력에 대한 다른 해결 방법을 검토해본 결과 어려울 것으로 보이며, 화면 확장으로 사용하는 경우에만 사용이 가능할 것으로 보입니다.
추후 업데이트 시 세로 화면을 대응하기 위한 방안에 대해 논의해보도록 하겠습니다.

추가로 궁금한 사항이 있으신 경우, 언제든 문의주세요.
더 나은 제품과 서비스를 위해 항상 노력하겠습니다.

감사합니다.

Ea​​sy&Light  
```
