### ISSUE TITLE
브라우저 드로잉 패드 사용 불가 

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2473]
- 문의 날짜 : 2023년 12월 1일 오전 10시 52분
 - 메일 주소 : [nickmcdozxtra@gmail.com](mailto:nickmcdozxtra@gmail.com)

**Question about why browser drawing pads don't work with EasyCanvas**

Hello, I just bought EasyCanvas to connect my iPad to my windows 11 PC. The reason I bought it was precisely to use a browser canvas in a program called "ComfyUI" which allows you to use Stable Diffusion + Sketch at the same time. Any idea how to prevent EasyCanvas from registering the apple pencil's contact as a mouse click, andi instead set it up as a mouse drag (so the programs draws) Thanks!

[EL_Display_4b1adad7-4670-4bea-a3a2-cc72d8e0bbf4.zip](https://github.com/edh-git/EL_Display_Hub/files/13540784/EL_Display_4b1adad7-4670-4bea-a3a2-cc72d8e0bbf4.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2473] Question about why browser drawing pads don't work with EasyCanvas
```
#### 본문
```
Hello, customer. This is the Easy&Light support team.

The function you are inquiring about appears to require a stylus to move the mouse, like a pen tablet.

In the case of EasyCanvas, it was developed to function as a graphic tablet, so this function does not exist. After examining other solutions, it appears that it will be difficult to use this method.

The touch and stylus of EasyCanvas operate identically to the touch and stylus devices connected to the actual window through the virtual HID driver. In particular, the stylus implements Windows Ink-related functions. Please check whether the program you are using has an option related to these functions.

We will discuss this feature in a future update.

Thank you

Easy&Light
```
