### ISSUE TITLE
Twomon Air 시스템 오류 발생

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#249]
e-mail:nemgist84@gmail.com<br><br>투몬 SE 랑 투몬 Air 두개다 사용는데, <br>이번 업데이트로 통합 프로그램이 된건가요...?<br><br>그리고, 투몬 Air 사용할 때 자꾸 시스템 오류가 나서<br>재부팅을 해야하네요. 그래서 SE만 사용하게 됩니다.<br><br>[EL_Display_38fc7ac8-1a06-4811-b90f-b6df5f17a6e9.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_38fc7ac8-1a06-4811-b90f-b6df5f17a6e9.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

EL Display Hub는 Twomon SE, Easycanvas Easycanvas Pro의 통합 PC 프로그램입니다.

현재 보내주신 로그의 경우 EL Display Hub의 로그입니다.
Twomon Air의 문제를 해결을 위하여 아래 링크를 참조하여 PC프로그램과 어플리케이션의 로그를 보내주시길 바랍니다.
[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporttwomon/?faq=79

감사합니다.

Ea​​sy&Light 
```
