### ISSUE TITLE
화면 비율 문의

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2508]
- 문의 날짜 : 2023년 12월 12일 오전 9시 41분
- 메일 주소 : [beaver03@naver.com](mailto:beaver03@naver.com)

**화면 비율**

안녕하세요 확장디스플레이로 활용 시, 첨부해 드린 이미지 처럼 화면이 패드의 전체 화면을 보이지 않습니다.
기존에는 정상적으로 사용하였는데 금일부터 이렇게 되서 보입니다.
[EL_Display_0dd28fc6-85b8-44fc-81b1-d5316fa1a1a5.zip](https://github.com/edh-git/EL_Display_Hub/files/13642398/EL_Display_0dd28fc6-85b8-44fc-81b1-d5316fa1a1a5.zip)
![스크린샷_20231212_093937](https://github.com/edh-git/EL_Display_Hub/assets/77039816/5a98c3d4-3fb1-4f09-bb6e-bb1a3cd18f95)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2508] 화면 비율
```
#### 본문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

PC 측의 로그를 확인해본 결과 연결된 태블릿에서 화면 정보를 기존에는 1750x1096으로 전달하였지만, 12-12일 연결로그에서는 "1314x2100"으로 전달되었습니다.

태블릿 측의 설정 중 변경된 것이 있는지 확인 부탁드리며,
변경된 점이 없을 경우 안드로이드 장치를 재부팅한 뒤 테스트하여 주시길 바랍니다.


위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.
추가 분석을 위해서는 어플리케이션 로그가 필요합니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다.

Ea​​sy&Light  
```
