### ISSUE TITLE
애플펜슬 입력 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2512]
- 문의 날짜 : 2023년 12월 13일 오후 9시 5분
- 메일 주소 : [gksrudtlr2@icloud.com](mailto:gksrudtlr2@icloud.com)

**에플팬슬 사용 안됨**

노트북이랑 연결해서 그림판이나 GoodNode사용시 에플펜슬로 필기가 안됩니다
[EL_Display_0fa3f710-407c-4110-b38c-6bb8f8f0a1da.zip](https://github.com/edh-git/EL_Display_Hub/files/13666605/EL_Display_0fa3f710-407c-4110-b38c-6bb8f8f0a1da.zip)

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [Twomon SE - 2512] 에플팬슬 사용 안됨
```
#### 본문
```
고객님, 안녕하세요. Easy&Light 지원팀 입니다.

먼저, 이용에 불편을 드려 죄송합니다.

포토샵을 비롯한 몇몇 프로그램은 그리는 등의 기능을 스타일러스 펜과 마우스 입력만 가능하게 되어 있어 터치로 인식되는 동작은 작엽 영역에 입력이 불가능하며, 스타일러스 펜 동작만 입력 가능이 가능합니다.

Twomon SE의 경우 터치 입력만 지원하며 애플 펜슬의 입력도 터치로 변환되어 포토샵 등의 스타일러스 전용 입력이 필요한 프로그램에서는 사용이 어렵습니다.
해당 프로그램에서 펜 입력이 필요하실 경우 Twomon SE를 환불하시고, 스타일러스 및 무선 연결을 지원하는 EasyCanvas를 이용해주시길 바랍니다.

[EasyCanvas] : http://www.easynlight.com/easycanvas/

환불 방법은 아래와 같습니다.

[환불 가이드]
1. Playstore for Android
하단의 링크로 접속하시어 필요한 내용을 기입 후 제출해주시면 확인하여 환불 절차를 진행해드리겠습니다.
[Android] Twomon SE/TwomonAir/TwomonUSB 환불 요청서 : https://docs.google.com/forms/d/1wFxbQS5wg3u1QbMLG_ZQDM2ExNbDHC9xraPje5_hBbo/edit?urp=gmail_link

2. App Store for iOS
애플 앱스토어에서 판매되는 앱은 모두 애플에서 관리합니다. 
저희는 고객님의 구매 정보를 가지고 있지 않기 때문에 애플리케이션 환불을 진행할 권리가 없습니다. 
아래 링크를 참조 부탁드립니다.
Apple Support 사이트 링크 :https://reportaproblem.apple.com
iTunes store 에서 환불 받는 방법 :https://support.apple.com/ko-kr/HT204084



스타일러스 입력이 필요한 프로그램 뿐만 아니라 스타일러스를 통한 기본적인 터치 동작도 되지 않을 경우에는 아이패드의 설정에 오류가 발생한 것일 수 있습니다.

해당 경우 아이패드를 재부팅하는 경우 문제가 해결될 수 있으며,
재부팅 후에도 동일한 문제가 발생하는 경우 블루투스 목록에서 "Apple Pencile"의 연결을 제거하고 재부팅 후 다시 연결하여 동작을 확인하여 주십시오.

추가로 궁금한 사항이 있으신 경우, 언제든 문의주세요.
감사합니다.

Ea​​sy&Light 
```

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

두 재품의 차이가 무엇인가요??
Easy Canvas에서도 Twomon Se 처럼 보조 모니터로 사용이 가능한건가요?

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

문의해주신 내용에 대한 답변을 메일로 전달해드립니다.

Twomon SE의 경우에는 확장, 복제화면을 지원하며 USB케이블을 통한 유선연결만 가능합니다.

EasyCanvas는 태블릿을 드로잉타블렛처럼 활용할 수 있도록 필압 기능까지 지원하고 있으며 유,무선 연결 모두 가능합니다.
(단, Mac환경에서는 무선연결, 확장화면 기능을 지원하지 않습니다.)

EasyCanvas도 확장 및 복제 기능을 모두 지원하므로 보조 모니터처럼 활용이 가능합니다. 

EasyCanvas의 경우, 3일 간 무료로 사용 가능한 무료체험 기간을 제공하고 있으니 원하시는 기능인지 직접 사용해보실 수 있습니다.

제품에 대해 더 궁금한 점이 있으시면 언제든 문의 주시기 바랍니다.

감사합니다.


Easy&Light
