### ISSUE TITLE
연결 해제

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#2516]
- 문의 날짜 : 2023년 12월 15일 오전 2시 32분 
- 메일 주소 : [jasonkirbyy@gmail.com](mailto:jasonkirbyy@gmail.com)

**Constant Repeating Issue with connectivity**

Hi,

I have been using this application since June.

I must use microsoft word for my studies but I need to draw a lot of diagrams on word, so I use this application to allow for that.

I hadn't any issues for the first few months, but after a while the iPad stopped connecting to EL Display hub, despite the laptop recognising it is plugged in.

The solution was to uninstall the program and reinstall it. Good as new!

This has worked for a few months now, but it has gotten to the point where everytime my iPad disconnects or my computer sleeps, the iPad is no longer detected by EL Display hub and I must reinstall.

To reinstall the iPad must be disconnected and the ads program must be closed from task manager.

I have to constantly do this in lesson, pretty much every hour now and it is really slowing my learning, because whilst other people have written notes and done the practise questions, I am faffing around with the applications to get them working.

Please can I request help on how this issue can be resolved?

Kind regards,

Jason Kirby

[EL_Display_514bd767-dff1-4bcb-899e-6cc425ed466d.zip](https://github.com/edh-git/EL_Display_Hub/files/13679792/EL_Display_514bd767-dff1-4bcb-899e-6cc425ed466d.zip)

**Comment by Devguru-Dave** [comment]
지속적으로 그래픽 드라이버 문제가 발생하고 있습니다.
EL 프로그램 삭제 후 그래픽 드라이버 및 윈도우 업데이트를 안내하면 될 것 같습니다.

**Comment by james-kim-Devguru** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

---
#### 제목
```
Re: [EasyCanvas - 2516] Constant Repeating Issue with connectivity
```
#### 본문
```
Hello, customer. This is the Easy&Light support team.

First of all, we apologize for any inconvenience caused.

After reviewing the logs and symptoms you sent, it appears that an error occurs in an encoding-related function.
Please proceed with the update and reinstallation as follows.

1. Delete “EL Display Hub”
2. Check Windows updates and update to the latest Windows.
3. Update graphics drivers
      [Intel] Driver Support Program: https://www.intel.com/content/www/us/en/download-center/home.html
      [AMD] Graphics driver installation page: https://www.amd.com/support
      [NVIDIA] Graphics driver installation page: https://www.nvidia.co.kr/Download/index.aspx
4. Reboot your PC (using “Restart” in the shutdown options).
5. Reinstall “EL Display Hub” by downloading the new installer (run the installer by “right-clicking - Run as administrator” during installation).
      [EL Display Hub] Installation page: http://www.easynlight.com/easycanvas/

If the problem does not improve after taking the above measures, please re-inquire by attaching new PC logs and application logs.

[FAQ] Log acquisition guide: http://www.easynlight.com/supporteasycanvas/?faq=97

We will strive to create better products.
Thank you

Easy&Light
```
