### ISSUE TITLE
실행불가

### ISSUE THREAD

**Issue by Juilliardsong** [edh-git/EL_Display_Hub#2525]
|항목|내용|
|---|---|
|날짜|12월 21일 (목) 오후 7:04|
|메일|beatz4die@gmail.com|
|제목|[Twomon SE - Windows] pc 프로그램 서비스를 시작할 수 없습니다. 만 계속 나와요|
|내용|Device OS: iOS<br>Product: Twomon SE<br>반복해서 지우고 설치해도 저 메시지만 뜨고 사용이 안됩니다.<br>에러코드 A0011001<br>14000원 주고 아이패드에서 앱 샀는데 이게 뭔가요|
|첨부파일|1. ![스크린샷 2023-12-21 185747](https://github.com/edh-git/EL_Display_Hub/assets/68727895/7d8ab89c-caa0-4f75-ade0-8a454435ff4b)<br>2. [EL_Display_9ccc2fef-f8fc-4ef7-9e0f-9de84d4c8fb8.zip](https://github.com/edh-git/EL_Display_Hub/files/13747792/EL_Display_9ccc2fef-f8fc-4ef7-9e0f-9de84d4c8fb8.zip)|

**Comment by kimkh83** [comment]
로그 확인 결과 nvcuvid.dll 오류로 보입니다.

-----------------------------------------------------------------------------------------------------
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

보내주신 로그와 증상을 검토한 결과, 인코딩 관련 기능에 오류가 발생하는 것으로 보입니다.
아래와 같이 업데이트와 재설치를 진행하여 주십시오.

1. "EL Display Hub" 삭제
2. 윈도우 업데이트 확인 및 최신 윈도우로 업데이트
3. 그래픽 드라이버 업데이트 
    [Intel] 드라이버 지원 프로그램 : https://www.intel.com/content/www/us/en/download-center/home.html
    [AMD] 그래픽 드라이버 설치 페이지 : https://www.amd.com/support
    [NVIDIA] 그래픽 드라이버 설치 페이지 : https://www.nvidia.co.kr/Download/index.aspx
4. PC 재부팅 (종료 옵션의 "다시 시작" 사용)
5. 새로운 인스톨러를 다운로드 받아 "EL Display Hub" 재설치
    [EL Display Hub] 설치 페이지 : https://www.easynlight.com/easycanvas

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : https://easynlight.oqupie.com/portal/2248/article/51286

또한 좀 더 상세한 로그 파악을 위하여, "PC 시스템 정보 함께 첨부"를 체크하여 주십시오.

[ PC 환경 수집 ]
Windows키 입력 > "실행" 검색 및 실행 > "msinfo32" 입력 > 파일 > 저장

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
-------------------------------------------------------------------------------------------------------
