### ISSUE TITLE
연결 불가

### ISSUE THREAD

**Issue by Juilliardsong** [edh-git/EL_Display_Hub#2526]
|항목|내용|
|---|---|
|날짜|12월 21일 (목) 오후 7:22 |
|메일|[ryan@mattisoncentral.com](mailto:ryan@mattisoncentral.com)|
|제목|[EasyCanvas - Windows] Unable to connect|
|내용|Device OS: Android<br>Product: EasyCanvas<br><br>Running on a Samsung Galaxy Tab S6 Lite running Android 13 and One UI 5.1.1. Using a USB cable I am unable to connect to the tablet. I've reinstalled and restarted multiple times, but still unable to get a connection.<br>PC is running Windows 11.|
|첨부파일|1. [EL_Display_efb00975-7949-4d12-b29d-d6dfa8fa16bb.zip](https://github.com/edh-git/EL_Display_Hub/files/13747811/EL_Display_efb00975-7949-4d12-b29d-d6dfa8fa16bb.zip)|

**Comment by kimkh83** [comment]
ADB USB Debugging 허용이 정상적이지 않은 것으로 보입니다.

---------------------------------------------------------------------------------------------------
Hello, customer. This is the Easy&Light support team.

First of all, we apologize for any inconvenience caused.

After reviewing the log sent by the customer, it appears that the "USB debugging" option on the Android side was not applied properly.

Please refer to the link below and allow “USB Debugging”.

[FAQ] Troubleshooting Connection Issues : https://easynlight.oqupie.com/portal/2247/article/52180
  - Please refer to "[Andoird Solutions] If there is an error on your PC or tablet" section.

If it doesn't work after that, reboot both your PC and Android device.

If the problem does not improve after taking the above measures, please re-inquire by attaching new PC logs and application logs.

[FAQ] Log Acquisition Guide: https://easynlight.oqupie.com/portal/2247/article/52187

We will always strive for better products and services.
Thank you

Easy&Light
---------------------------------------------------------------------------------------------------
