### ISSUE TITLE
Twomon SE를 메인 모니터로 사용

### ISSUE THREAD

**Issue by Juilliardsong** [edh-git/EL_Display_Hub#2527]
|항목|내용|
|---|---|
|날짜|2023. 12. 21. 오후 8:14|
|메일|r9213@naver.com|
|제목|[Twomon SE - Windows] 투몬SE를 메인모니터로 사용할 시 '서비스시작할수 없음'|
|내용|Device OS: Android<br>Product: Twomon SE<br><br>일반모니터 없이 투몬SE를 메인모니터로 사용하려합니다.<br><br>문제는 일반모니터 없이, 태블릿만 USB연결된 상태에서는<br>PC는 부팅이 되지만 투몬SE를 켜논 태블릿은 PC화면이 뜨질 않습니다.<br><br>위 상황에서 부팅된 PC에 일반모니터에 HDMI연결하여 확인해보면<br>첨부파일과 같은 오류가 발생합니다. 프로그램 재설치를 해도<br>같은 오류가 발생합니다.<br><br>하지만 일반모니터를 먼저 연결한 상태에서 PC부팅이 완료된 후<br>PC에 태블릿과 USB연결하고 투몬SE를 연결하면 오류없이 화면이 나옵니다.<br><br>예상하건데, 일반모니터가 미연결인 상태에서는 투몬SE 관련 서비스가<br>실행이 안되어 발생한 오류 같습니다.<br>* 일반모니터 없음->> 윈도우에서 최초 디스플레이 해상도 미인식->>투몬SE 프로그램, 서비스 실행오류(?)<br><br>일반모니터 미연결인 상태에서도 투몬 관련 서비스가 정상실행 된다면 해결될듯 한데.....이와 관련한 해결방법을 문의드립니다.|
|첨부파일|1. ![제목 없음](https://github.com/edh-git/EL_Display_Hub/assets/68727895/a68c99a3-90bc-4728-9df7-da78bfe2e15d)<br>2. [EL_Display_0e91a8b9-4585-466d-aa04-32e6bb2acae1.zip](https://github.com/edh-git/EL_Display_Hub/files/13747847/EL_Display_0e91a8b9-4585-466d-aa04-32e6bb2acae1.zip)|

**Comment by kimkh83** [comment]
제임스가 사용자와 동일한 환경을 보유하고 있어 Twomon SE를 메인 모니터로 사용해 보려하였으나 해당 환경에서는 확장보단 Display list를 먼저 진행하며 해당 시점에 오류가 발생하여 Twomon SE를 메인 모니터로 활용할 수 없는 환경을 확인하였습니다.
아래와 같이 답변 부탁드립니다.

----------------------------------------------------------------------------------------------------------------
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 고객님의 환경에서는 Twomon SE를 메인 모니터로 사용할 수 없는 환경임을 확인하였습니다.

아쉽지만 Twomon SE는 별도의 모니터와 함께 사용을 부탁드립니다.
Twomon SE를 메인 모니터로 사용하고자 구매하여 사용이 어려울 경우 환불을 진행하여 주시길 바랍니다.

환불 방법은 아래와 같습니다.

[환불 가이드]
1. Playstore for Android
하단의 링크로 접속하시어 필요한 내용을 기입 후 제출해주시면 확인하여 환불 절차를 진행해드리겠습니다.
[Android] Twomon SE/TwomonAir/TwomonUSB 환불 요청서 : https://docs.google.com/forms/d/1wFxbQS5wg3u1QbMLG_ZQDM2ExNbDHC9xraPje5_hBbo/edit?urp=gmail_link

더 나은 제품과 서비스를 위해 항상 노력하겠습니다.
감사합니다.

Ea​​sy&Light 
----------------------------------------------------------------------------------------------------------------
