### ISSUE TITLE
업데이트 후 확장 시 블랙스크린 표시

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#263]
e-mail:앱 통합 후 블랙스크린만 나옵니다.<br><br>복제모드에서는 제대로 나옵니다. 문제는 확장모드로 하면 어느 해상도 어느 품질을 설정하든 잠깐 화면만 나왔다가 바로 블랙스크린을 띄웁니다. 내부적으로는 확장이 잘 되고 있는 것으로 나옵니다.<br><br>[EL_Display_c9d22e4c-97ec-4263-ba61-824ed7cca44c.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_c9d22e4c-97ec-4263-ba61-824ed7cca44c.zip)

**Comment by Juilliardsong** [comment]
이메일 누락으로 답변 불가
