### ISSUE TITLE
터치좌표 안맞음

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#264]
e-mail:dltpgml8781@naver.com<br><br>윈도우에 아이패드로 이지캔버스pro 쓰려고하는데 아이펜슬이랑 화면에 보이는 펜 좌표가 크게 엇나가있습니다.. 앱스토어 리뷰보니까 화면배율설정 변경하라고하셨는데 세개 있는거 다 해도 안바뀌는데 어떡해야하나요..? 참고로  메인말고 듀얼모니터랑 화면연결해둔상태입니다!<br><br>[EL_Display_d521b754-70b4-4c8a-a79b-44b34482eef0.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_d521b754-70b4-4c8a-a79b-44b34482eef0.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

현재 디스플레이 드라이버 관련 문제를 해결한 버전이 업데이트 되었습니다. 
PC 프로그램 업데이트를 부탁드립니다.

PC프로그램으로 업데이트 이후에도 동일한 오류가 발생하는 경우
아래의 로그 취득 가이드를 참조하여 어플리케이션 로그와 함께 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
