### ISSUE TITLE
업데이트 후 성능저하

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#265]
e-mail:cwh9702@naver.com<br><br>아이패드 에어 1세대에 투몬 SE를 이용해 보조모니터로 잘 사용중에 있었는데<br>오늘 새로운 소프트웨어 버전이 나왔다는 업데이트 알림이 나와 앱과 PC프로그램 둘다 업데이트를 했더니<br>아이패드 에어 1세대가 구형모델이라 더이상 지원하는게 어려운것인지 사용할 수 없을정도로 화면이 약 15~20초 간격으로 새로고침되어 반영되더라구요<br><br>투몬 USB버전을 새로 구입하여 사용해 보니까 정상동작하는데 더이상 투몬SE 버전은 아이패드 에어 1세대에서 사용할 수 없는건지 <br>아니면 해결 가능한 오류사항인지 알 수 있을까요?<br><br>[EL_Display_d835a9df-f12d-4983-b34a-d3e4ebdf5068.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_d835a9df-f12d-4983-b34a-d3e4ebdf5068.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.


이번 업데이트로 사용자 설정의 "해상도"와 "성능 모드"의 기본값이 높은 품질이 선택되도록 변경되었습니다.
설정이 변경되어 PC 및 태블릿의 사양에 따라서 성능이 다소 느려질 수 있으며,
아래의 FAQ를 참조하셔서 "해상도"와 "성능 모드"의 설정을 변경하여 주시길 바랍니다.

[FAQ] 화면 갱신이나 반응속도가 느려요. : http://www.easynlight.com/supporteasycanvas/?faq=112

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않거나 다른 문의 사항이 있으시다면 재문의 부탁드립니다.

감사합니다.

Ea​​sy&Light 
```
