### ISSUE TITLE
업데이트 후 확장화면 불가

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#267]
e-mail:mostless@gmail.com<br><br>안녕하세요.<br>아이패드 프로 3세대에 Twomon SE를 지난 9월에 구입하여 몇달 간 잘 사용하고 있었는데, 최신업데이트가 존재한다고 알림이 와서 업데이트 했더니 완전 엉망이 되어버렸네요.<br><br>기존 PC버전의 Twomon 과는 다르게 EL Display Hub가 작동되면 일반적인 더블 모니터가 아니라 화면이 복제가 되서 똑같은 화면이 노트북과 아이패드에 떠있습니다.<br><br>기존 Twomon에서는 그걸 조절할 수 있고 해상도 조정도 간편했는데 너무 UI도 그렇고 편의성도 엉망이어서 쓰기가 어려울 정도인것같습니다.. 해상도도 기존에는 각각 기기를 조정하여 아이패드 화면에 꽉맞는 화면으로 따로 설정할 수 있었는데 지금은 안되는 것 같구요...<br><br>관련해서 화면 복제가 아닌 확장으로 변경할 수 있는 방법 등에 대한 설명 부탁드립니다... 안되면 이전버전이 훨~~~~~씬 괜찮은거같아서 롤백할 수 있는 방법이라도 찾고싶네요 정말...<br><br>[EL_Display_3713b300-ca4d-4b4e-9cb6-3e4f382f12df.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_3713b300-ca4d-4b4e-9cb6-3e4f382f12df.zip)

**Comment by AdamPark0030** [comment]
아래와 같이 답변 부탁드립니다.
----
```
안녕하세요 고객님, Easy & Light 지원 팀 입니다.

먼저 이용에 불편함을 드려 정말 죄송합니다.

현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

Twomon SE와 같이 듀얼 모니터로 활용하는 방법을 아래에 안내해 드리겠습니다.

1. PC와 태블릿을 유선으로 연결합니다.

2. 연결 시 옵션 설정 탭의 오른쪽에 연결된 기기가 있는지 확인합니다.

3. 연결된 기기가 존재한다면, 화면 선택 옵션에서 "확장" 옵션을 선택합니다.

4.  화면선택 아래의 해상도 옵션에서 해상도를 변경할 수 있으니 설정 해보시길 바랍니다.

위와 같은 조치사항을 취하신 후 문제가 지속된다면 태블릿 로그를 첨부하여 재문의 해주시길 바랍니다.

감사합니다.

Easy&Light.
```
![image](https://user-images.githubusercontent.com/73160679/150262242-60b2a2cc-3ce5-48ab-9279-ad630e67bd5f.png)

**Comment by AdamPark0030** [comment]
사용자에게 답변전송 완료했습니다.
