### ISSUE TITLE
화웨이 앱스토어에서 투몬SE 검색불가

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#269]
e-mail:cjswoalfm@naver.com<br><br>매니저님 문의드려요~<br>혹시 티몬SE가 이 프로그램으로 바뀐건가요?!<br>테블릿에서 이거 깔아서 연결해서 쓰려고 하니까 사라져서요..ㅠㅠ<br>유료결제했는데..ㅠㅠ 왜 안될까요<br><br>[EL_Display_2bdeae73-773d-49e9-aee2-68a85954d76d.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_2bdeae73-773d-49e9-aee2-68a85954d76d.zip)

**Comment by AdamPark0030** [comment]
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

현재 Twomon SE  앱이 Huawei App Gallery에서 reject되어 확인 후 다시 앱 심사중이므로, 

빠른 시일내에  설치하실 수 있도록 하겠습니다.  

감사합니다.

Ea​​sy&Light 
```

**Comment by AdamPark0030** [comment]
사용자에게 답변전송 완료했습니다.
