### ISSUE TITLE
연결 불가 이슈

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#270]
e-mail:cjswoalfm@naver.com<br><br>매니저님 ㅠㅠ 테블릿이랑 연결이 안되어용..ㅠㅠ<br><br>[EL_Display_4e41bc50-7d86-4034-a05e-4802cefaea1c.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_4e41bc50-7d86-4034-a05e-4802cefaea1c.zip)

**Comment by harvey-lee-devguru** [comment]
#272 이슈와 같은 사용자 VOC 이며, 해당 이슈를 보면 연결 불가는 해결된 것으로 보입니다.
