### ISSUE TITLE
디스플레이 확장 모드 변경 불가 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#272]
e-mail:cjswoalfm@naver.com<br><br>매니저님 ㅠㅠ 이제 어플 새로 깔아서 어플이 켜지기까진 했는데...<br>이제는 화면이 복제만 되고 , 확장이 안되네요..ㅠㅠ<br>도와주세용..ㅠㅠ일해야하는데<br><br>[EL_Display_550dc0a2-8326-49f9-b0a7-ddc3ee645254.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_550dc0a2-8326-49f9-b0a7-ddc3ee645254.zip)

**Comment by harvey-lee-devguru** [comment]
EL_Display_server_core.dll_EL_Display_service.exe_0.log 로그를 확인해 보면,

[2022-01-20 12:41:42.099][GENERAL:INFO][6664:7524][bypd_server_core_proc_manager_display_list_changed:1035] prev_topology_mode: 1, new_topology_mode: 2

과 같은 부분이 있는데요, 윈도우 디스플레이 세팅에서 복제로 세팅되어 있는것으로 보입니다.

WIN+P 키를 눌러서 확장을 선택하면 이슈가 해결될 것으로 보입니다.

**Comment by harvey-lee-devguru** [comment]
아래과 같이 답변하였습니다.

==================================================================================

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

제품이 디스플레이 복제모드로만 동작하는 문제를 문의 주셨는데요,

윈도우의 다중 디스플레이 설정이 복제모드로 세팅되어 있는것으로 보입니다.

키보드의 "WIN + P"를 이용해서 프로젝트 선택을 "확장"으로 변경해 주시면 이후로는 EL Display 제품을  정상적으로 확장화면으로 이용하실 수 있습니다.

감사합니다.

Easy&Light

**Comment by Sienna-lee** [comment]
아래와 같이 사용자가 회신하였습니다.

----

마스터님 ^^ 해결완료했어용~~

 

화질 너무 좋아졌네용

 

감사드려용 ^^
