### ISSUE TITLE
EL Display Hub 설정 변경 문의

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#277]
- 문의 날짜 : 2022년 1월 19일 (수) 오후 10:58
- 이메일 : hoonok77@naver.com

제목: EL display hub 업데이트 관련

문의사항: EL display hub로 업데이트 되고 나서 설정 변경은 어떻게 하나요? 양쪽에 같은 화면만 나오네요.

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

고객님, 안녕하세요. Easy&Light 지원 팀 입니다.


문의해주신 내용에 대한 답변을 메일로 전달해드립니다.




통합 PC 프로그램인 EL Display Hub의 옵션 설정 -> 화면 선택에서 복제 및 확장할 화면을 선택하실 수 있습니다. 

화면 선택 및 PC 프로그램의 구성에 대해 참고하실 수 있도록 관련 포스팅 링크를 아래 전달드립니다. 

https://blog.naver.com/easynlight/222626582372


위 설정 방법으로도 변경이 불가할 경우, 로그파일과 함께 문의하여주시면 어떠한 문제인지 확인하여 해결 방안을 전달드리도록 하겠습니다. 감사합니다. 


- 로그 추출 가이드 : http://www.easynlight.com/supporttwomon/?faq=121


더 나은 프로그램을 만들기 위해 노력하겠습니다.


감사합니다.


Easy&Light

**Comment by AdamPark0030** [comment]
#233 이슈와 동일한 이슈로 보입니다. 답변완료된 이슈이므로 #233 이슈를 close 하겠습니다.

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

아이패드에도 같은 화면만 나와요

"확장" 버튼이 뜨긴 하는데 그거 클릭하면 다시 display1만 나오고 안 되네요

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

로그파일도 함께 보냈던 것 같은데요

**Comment by Sienna-lee** [comment]
첨부된 로그파일이 없어 사용자에게 다시 한번 요청하였습니다.

----


고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

보내주신 메일을 확인해본 결과 첨부한 로그파일이 확인되지 않습니다.

이전에 13일 문의건에 대해서는 로그파일이 첨부되어 있었으나 업데이트 이후 1월 19일문의에서는 로그파일이 함께 전달되지 않았습니다.


번거로우시겠지만 로그파일을 다시 한번 생성하여 보내주시면 해당 내용을 담당자에게 전달하여 문제 확인 후 해결 방안을 전달드리도록 하겠습니다.


- 로그 추출 가이드 : http://www.easynlight.com/supporttwomon/?faq=121  


감사합니다. 


Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

이번에도 PC, 아이패드 둘 다 보내야 하나요? 무엇이 이리 잘 안 되는게 많은지요?


----


로그파일을 보내드리면 그 다음은 어떤 절차가 진행되는 건가요? 저번에 로그파일 보내고 해결책으로 업데이트 된건가요? 업데이트는 모든 사람한테 다 해당된 건가요?


----



문의하기에서 앱로그 파일 첨부도 안 됩니다.


----



앱로그파일 보냈습니다.

**Comment by Sienna-lee** [comment]
해당 사용자가 PC프로그램 문의하기를 이용하여 로그파일을 전달하였습니다.


----
https://github.com/edh-git/EL_Display_Hub/issues/341

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

EL Display Hub로 업데이트 이후 특정 환경에서 기존 프로그램에서 설정되어 있던 OS 측의 복제/확장과 EL Display Hub의 복제/확장 기능 간의 충돌이 발생하는 것으로 확인되었습니다.
현재 원인 파악 중에 있으며, 해당 증상을 해결하기 위해서는 다음과 같이 조치 부탁드립니다.

1. EL Display Hub에서 "화면 선택"의 디스플레이 리스트에서 "확장" 목록을 선택해 확장 시도합니다.
2. 확장에 실패한 상황을 확인합니다. (확장 항목이 사라졌으며, 화면은 복제중인 상태)
3. "설정" - "시스템" - "디스플레이"로 진입하여 "다중 디스플레이"항목을 "바탕 화면을 이 디스플레이에 확장"을 사용하게 변경합니다.
    또는 "Windows키" + "P" 키를 통해서 "확장"을 선택 합니다.
    - 해당 상황에서 화면이 깜빡거리거나 연결이 해제되는 등의 문제가 발생할 수 있습니다.
    - 화면이 깜빡거린 뒤, 디스플레이 드라이버 관련 오류가 출력될 수 있습니다.
4. PC를 재부팅합니다.
5. EL Display Hub의 "화면 선택"의 디스플레이 리스트의 "확장"을 선택하여 다시 화면 확장을 시도합니다.

또한 EL Display Hub의 디스플레이 드라이버가 구버전의 윈도우나 특정 환경에서 동작에 실패하는 문제가 확인되었습니다.
해당 문제를 해결한 PC 프로그램을 배포하였으며, 업데이트 후 증상을 확인하여 주십시오.

다음 버전의 PC프로그램으로 업데이트 이후에도 동일한 오류가 발생하는 경우
아래의 로그 취득 가이드를 참조하여 어플리케이션 로그와 함께 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
