### ISSUE TITLE
연결이 수시로 끊김

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#287]
e-mail:jungmato66@gmail.com<br><br>Twomon SE앱 유저입니다.<br>EL Display Hub로 통합되기 이전 Twomon SE프로그램 단일 사용할 땐 문제없다가 오늘 업데이트 후 사용해보니 아이패드와 컴퓨터의 연결이 수시로 끊깁니다.<br>도움 부탁드립니다.<br><br>[EL_Display_d87209f0-6b74-42cb-a4f8-99f8463b5b05.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_d87209f0-6b74-42cb-a4f8-99f8463b5b05.zip)

**Comment by harvey-lee-devguru** [comment]
-메모-
로그상에는 실제로 usbmuxd로 detach와 attach가 반복해서 발생하고 있음.
케이블 연결을 확인해볼 필요가 있어보이긴 하는데,
PC 프로그램 업데이트 전에는 잘 사용했다고 하니, AMDS 버전을 변경한 이력이 있는지 확인이 필요.

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변하였습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

현재 디스플레이 드라이버 관련 문제를 해결한 버전이 업데이트 되었습니다. 
PC 프로그램 업데이트를 부탁드립니다.

또한 업데이트 이후에도 동일한 오류가 반복되는 경우에는 USB포트의 전력 부족 혹은 연결 불량 문제일 수 있습니다.

"화면 전송 기능"은 USB를 통해 처리되는 데이터의 양이 많아서, PC와 디바이스 간의 연결이 정상적으로 보여도 실제 통신에는 실패할 수 있습니다.

이를 해결하기 위해 아래의 사항들을 조치해보십시오.
1. PC와 태블릿 간의 연결이 정상적인지 확인합니다.
2. USB 케이블 교체(가능한 정품 케이블 사용)합니다.
3. PC에 연결된 USB 포트 변경(후면 포트 이용)합니다.
4. 외부전원 USB 허브에 연결합니다.

위의 조치사항들을 취하신 이후에도 동일한 오류가 발생하는 경우
아래의 로그 취득 가이드를 참조하여 어플리케이션 로그와 함께 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
