### ISSUE TITLE
업데이트 후 작동 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#288]
- 문의 날짜 :  2022년 1월 20일 오후 1시 57분
- 메일 주소 : lambs18@icloud.com

Title: Driver initialization error

Questions: when I update to EL Display HUB. My Twomonse & EasyCanvas doesn\'t work.
Error message : There was a problem with the virtual display driver.
Error code : A0030001
Solutions : Restart the program after rebooting the PC

I\'ve restarted my computer and software many times. It doesn\'t work. I dont know how to get EL Display HUB log file.

[[TwomonUSB_-_Windows]_Driver_initialization_error.zip](https://github.com/edh-git/EL_Display_Hub/files/7902825/TwomonUSB_-_Windows._Driver_initialization_error.zip)

**Comment by Sienna-lee** [comment]
해당 사용자가 TwomonUSB 제품을 선택하여 문의하였으나 문의 내용을 보니 SE 및 EasyCanvas 제품을 사용중인것으로 되어 해당 프로젝트에 이슈를 생성합니다.

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
Hello, customer. Easy&Light support team.

First of all, we apologize for the inconvenience.
Currently, there are a lot of inquiries about the update, so the response is delayed.

In older versions of Windows, there is a problem that the virtual display device does not run normally.
To solve this problem, please take the following actions.
1. Please delete EL Display Hub.
2. Please update to the latest Windows (21H1, build 19043 or later).
3. Reinstall EL Display Hub with the latest version.
[EL Display Hub] Installation page: http://www.easynlight.com/en/easycanvas/


Also, even after the latest Windows update, the operation of the virtual display device may fail due to other issues.
We are working on a solution for this issue and will try to fix it as soon as possible.

Thank you.

Easy & Light
```
