### ISSUE TITLE
포토샵 사용 시 선 끝에 점 찍히는 현상

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#297]
e-mail:wldls0821@gmail.com<br><br>업뎃 후 포토샵에서 사용시 저렇게 선 끝에 점이 찍히는 현상이 발생합니다 윈도우 업뎃, 프로그램을 지웠다 깔아봐도 똑같아요<br><br>[EL_Display_f24792c3-8a44-4202-bab7-a230f8d7ee98.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_f24792c3-8a44-4202-bab7-a230f8d7ee98.zip)

**Comment by AdamPark0030** [comment]
아래와 같이 답변 완료 했습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

고객님. 해당 문제의 원인을 현재 파악중에 있으며, 먼저 아래의 조치를 취해보시길 바랍니다.

1. 포토샵의 상단 메뉴에서 편집 > 환경 설정 > 성능 선택
2. 그래픽 프로세서 설정 옵션의 그래픽 프로세서 사용 선택
3. 포토샵 재실행

이후 문제가 지속된다면 어플리케이션 로그와 함께 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light 
```
![image](https://user-images.githubusercontent.com/73160679/153363972-85a28c28-7177-446c-bfc4-4b676d22d81f.png)
![graphic_processer_settings](https://user-images.githubusercontent.com/73160679/153364159-2386b1fc-5a39-4da5-9823-5872be817cc7.png)
