### ISSUE TITLE
VOC::윈도우10 세로 모드 문제

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#300]
e-mail:skjung0000@gmail.com<br><br>사용하는 환경<br>iPad 5th gen iOS15.1, Twomon SE 최신버전<br>윈도우10홈 21H1, EL Display Hub 최신버전<br><br>문제<br>- TwomonSE를 EL Display Hub 최신버전으로 업데이트한 이후부터, 화면방향을 세로로 설정하면 화면이 멈춰버립니다.<br>- 확장모드로 설정해서 한쪽으로 마우스 커서를 넘겨도 마우스 커서가 표시되지 않습니다. <br>- 마우스가 보이지 않으나 실제로는 마우스가 돌아다니는 것 같으며, 대충 감으로 클릭한 후에 화면방향을 가로로 변경해서 확인하면 마우스가 상호작용한 흔적이 보입니다.<br>- 작업표시줄의 단축아이콘을 터치하면 작동하는 것으로 보아 터치스크린 입력은 제대로 작동하고 있습니다.<br><br>이전과 같이 세로 해상도로 화면을 출력해서 사용하고 싶습니다. EL Display Hub로 업데이트한 이후로 새롭게 나타난 증상인만큼, 해당 증상을 조속히 해결해주셨으면 좋겠습니다.<br><br>2022년 새해 복 많이 받으시고, 사업 번창하시길 바랍니다. <br>감사합니다.<br><br>[EL_Display_76d5583e-c8e8-41ee-a465-4d353340c2fa.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_76d5583e-c8e8-41ee-a465-4d353340c2fa.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

윈도우 10에서 세로 모드로 동작시 오류가 발생하는 문제를 확인하였습니다.
해당 문제 해결하기위한 수정을 진행 중이며, 최대한 빠르게 수정 버전을 배포하도록 노력하겠습니다.
새로운 버전이 배포될 버전에서의 동작을 확인부탁드립니다.

또한 현재 윈도우11의 경우 세로 모드일 때 Windows에서 제공하는 기능에 문제가 있는 것으로 판단됩니다.
Microsoft에서 오류를 수정하지 않으면 해당 문제는 해결이 어려울 것으로 보이며,
현재로서는 불편하시더라도 Windows 11에서는 가로 모드로 사용해주시길 바랍니다.

감사합니다.

Ea​​sy&Light 
```
