### ISSUE TITLE
VOC::#306과 동일 이슈

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#307]
e-mail:syx627511687@gmail.com<br><br>Since I updated to the new version, I have not been able to use it properly, the old version did not have this driver problem<br>I checked the device manager according to the tutorial on the official website and found that the driver for easy&amp;light display HUB virtual display is showing an error, how can I fix it?<br><br>[EL_Display_ecf9b63e-883a-4e4d-8313-3e255160e389.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_ecf9b63e-883a-4e4d-8313-3e255160e389.zip)

**Comment by james-kim-Devguru** [comment]
* 동일 이슈 존재 : https://github.com/edh-git/EL_Display_Hub/issues/306
