### ISSUE TITLE
앱 재구매 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#310]
e-mail:banana8414@ikesa.kr<br><br>좋은 프로그램을 만들어주셔서 감사합니다.. 하지만 제가 애플펜슬이 사용 가능한 이지캔버스의 존재를 모르고 투몬을 덜컥 구매를 해버렸습니다.. 혹시 변경을 할 수 있을까요.....?<br><br>[EL_Display_23b553c1-753f-4da2-ba6e-27ac495674ca.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_23b553c1-753f-4da2-ba6e-27ac495674ca.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

먼저 답변이 늦어지게 되어 죄송합니다.문의해주신 내용에 대한 답변을 아래 전달해드립니다.


앱스토어 정책상 앱 교환은 불가능하며, Twomon 제품은 환불받으시고 EasyCanvas로 재구매하셔야 합니다.
재구매 시 참고하실 수 있도록 아래 환불 가이드를 전달드립니다. 


[환불 가이드]
1. Playstore for Android하단의 링크로 접속하시어 필요한 내용을 기입 후 제출해주시면 확인하여 환불 절차를 진행해드리겠습니다.[Android] Twomon SE/TwomonAir/TwomonUSB 환불 요청서https://docs.google.com/forms/d/1wFxbQS5wg3u1QbMLG_ZQDM2ExNbDHC9xraPje5_hBbo/edit?urp=gmail_link

2. App Store for iOS애플 앱스토어에서 판매되는 앱은 모두 애플에서 관리합니다. 저희는 고객님의 구매 정보를 가지고 있지 않기 때문에 애플리케이션 환불을 진행할 권리가 없습니다. 아래 링크를 참조 부탁드립니다.Apple Support 사이트 링크 :[https://reportaproblem.apple.com/﻿](https://reportaproblem.apple.com/)
﻿iTunes store 에서 환불 받는 방법 :https://support.apple.com/ko-kr/HT204084



더 궁금한 점이 있으시면 언제든 문의주시기 바랍니다.
감사합니다.

Easy&Light
