### ISSUE TITLE
이지캔버스와 이지캔버스 프로의 차이 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#312]
e-mail:airwing8@nate.com<br><br>안녕하세요.<br>이번에 뭔가 대대적인 업데이트를 한것 같은데 제품군에 대한 문의를 드립니다.<br>전에는 이지캔버스 / 이지캔버스 프로 제품군으로 나뉘어져 있었는데..<br>이번 업데이트를 통해서 두제품이 통합된것인가요?<br>저는 이지캔버스프로의 데스크탑앱이 윈도우상에서 자주 먹통이되어 무선연결이 안되는 현상이 있어 어느 한쪽으로 안착하지 못하고 제 컴퓨터 환경에 맞는 제품 테스트를 위해서 두가지를 다 사용해보고 있었습니다.. 그런데 갑자기 기존의 파란색이던 이지캔버스 아이콘도 이지캔버스 프로처럼 붉은색 아이콘으로 갑자기 바뀌었고.. 그렇다고 이렇다 할 안내도 제대로 없고...게다가 이지앤라이트 홈페이지까지 먹통이라 더 혼란스럽네요..<br><br>요점은,<br>1. 전에는 이지캔버스와 이지캔버스 프로의 차이가 무선연결을 지원하냐 안하냐의 차이였는데, 이제는 그런 차이 없이 '이지캔버스'로 통합되어 무선연결을 비롯하여 동일한 기능을 지원하는 것인지요?<br><br>2. 1번과 같다면 차이는 1회구매 / 년구독의 차이만 있다는것인데, 만약 그렇다면 1회구매라는 말은 앱구매(영구 라이센스)라고 이해하면 되는지요?  '1회 구매' 라는 문구가 조금 헷갈리네요.<br><br>답변부탁드립니다.<br><br>PS. 이것은 여담입니다만, <br>기존의 프로제품은 앱을 구매하고 싶어도 구독 이외에는 앱구매 자체가 없었기 때문에 어쩔수 없이 구독을 하였는데, 저처럼 앱구매 의도가 있었으나 구독을 할수 밖에 없던 사용자들이 조금 아쉬울듯 합니다. <br>저도 어쩔수 없이 구독 시작한지 딱 한달밖에 안 되었는데.. 앱구매하려면 이중지출을 해야하네요. 이렇게 판매정책을 확 바꾸실 계획이 있었다면 미리 사용자들에게 공지를 주시거나, 혹은 일정기간의 이벤트성으로라도 앱구독 상태에서 할인된 가격으로 바로 앱구매로 넘어갈수 있도록 기존 프로사용자들에 대한 배려를 해주셨으면 좋았겠다는 생각이 듭니다.<br><br><br>[EL_Display_2ebd1bb3-e030-489c-b7ff-751edce8349e.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_2ebd1bb3-e030-489c-b7ff-751edce8349e.zip)

**Comment by Sienna-lee** [comment]
고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

먼저 답변이 늦어지게 되어 죄송합니다.
문의해주신 내용에 대한 답변을 아래 전달해드립니다.


Easy&Light 제품군의 성능 개선 및 사용 편의를 위해 통합 PC 프로그램(EL Display Hub)으로 업데이트 되었습니다.



Q. 전에는 이지캔버스와 이지캔버스 프로의 차이가 무선연결을 지원하냐 안하냐의 차이였는데, 이제는 그런 차이 없이 '이지캔버스'로 통합되어 무선연결을 비롯하여 동일한 기능을 지원하는 것인지요?


A. 기존에 유선 연결만 지원하던 EasyCanvas와 유,무선 연결을 지원하던 EasyCanvas Pro는 동일한 기능을 지원하게 되었으며, 구매 방식에 따라 EasyCanvas(인앱)와 EasyCanvas Subscription(구독)으로 제공하게 되었습니다. 



Q. 1번과 같다면 차이는 1회구매 / 년구독의 차이만 있다는것인데, 만약 그렇다면 1회구매라는 말은 앱구매(영구 라이센스)라고 이해하면 되는지요? '1회 구매' 라는 문구가 조금 헷갈리네요.

A. 1회 구매는 인앱 결제로 한번 구매하면 추가 결제 없이 사용 가능한 영구 라이센스가 맞습니다. 



애플의 경우, 앱스토어 정책상 개발사에서 환불이 불가능하여 애플에 직접 환불을 진행하셔야 합니다. 아래 환불 가이드로 전달드리오니 참고 부탁드립니다. 


환불 요청 : https://support.apple.com/ko-kr/HT204084
구독 취소 : https://support.apple.com/ko-kr/HT202039


이번 업데이트로 인해 두 제품을 모두 구매한 사용자분들이 불편을 겪게 된 것 같아 죄송합니다. 추후 동일한 문제가 발생하지 않도록 의견 주신 내용은 담당자에게 전달하도록 하겠습니다. 


제품 이용에 불편을 드려 죄송합니다.
더 나은 서비스를 제공할 수 있도록 노력하겠습니다.


Easy&Light
