### ISSUE TITLE
다운그레이 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#324]
e-mail:horang5164@gmail.com<br><br>다운그레이드 시켜달라고요<br><br>강제적으로 업데이트 시켜놓고 이따구로 못쓰게 만들어버리면 어쩌자고요<br><br>답변 바로바로 오는것도 아니고<br><br>아 ㅈ댔네 진짜 ㅅㅂ<br><br>[EL_Display_0d27d533-be4b-428e-bbfa-89220dc8714a.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_0d27d533-be4b-428e-bbfa-89220dc8714a.zip)

**Comment by Juilliardsong** [comment]
#344 이슈로 통합
