### ISSUE TITLE
Wi-Fi 연결 방법 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#325]
e-mail:sjd.junior.jr@gmail.com<br><br>How to use wifi mode in Easycanvas Sub?<br><br>[EL_Display_baf5b87b-c124-47b3-b78e-d792a68c5428.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_baf5b87b-c124-47b3-b78e-d792a68c5428.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello, customer. We are an Easy & Light support team. 
First of all, I'm really sorry for the delay in answering.


Please refer to the link below to connect wirelessly.
http://www.easynlight.com/en/supporteasycanvas/?faq=95

If you have any further questions, please reply to us.

Thank you.


Easy&Light
