### ISSUE TITLE
지브러시 펜슬 입력 불가

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#326]
e-mail:cheols_94@naver.com<br><br>어제 지브러쉬에서 펜슬로 터치가 안된다는 문의를 남겼는데 아직 답변 메일이 오지않아서 다시 문의 남깁니다.<br><br>[EL_Display_d00015ec-89f1-4300-a70b-39b0c37a5031.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_d00015ec-89f1-4300-a70b-39b0c37a5031.zip)

**Comment by Juilliardsong** [comment]
#385 이슈로 통합합니다.
