### ISSUE TITLE
다운그레이 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#329]
e-mail:herobonsang@hanmail.net<br><br>구버전으로 라도 사용할수 있는 방법이 없는지? <br>컴퓨터 연결 프로그램은 예전에 받았던 구버전으로 재설치 해 봤는데 <br>ipad에서 업데이트를 안해서 싶어 어플 업데이트 했다가 이젠 아예 구버전 연결자체가 불가로 나오네요   ㅡㅡ;.... 복구 방업이 있을까요?<br><br>[EL_Display_2838460e-e2ce-4fe2-a164-2a44e42f3b95.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_2838460e-e2ce-4fe2-a164-2a44e42f3b95.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

안녕하세요. Easy&Light 지원팀입니다.
우선 답변이 늦어지게 되어 죄송합니다. 
더 사용하시기 편리하도록 업데이트를 진행했는데 저희 쪽에서 예상하지 못했던 문제가 발생했습니다. 꼼꼼하게 체크하지 못해 죄송합니다.

PC 프로그램(EL Display Hub)이 업데이트 되었습니다.
이전 버전에서 연결이 불가했던 문제는 최신 버전으로 업데이트하면 해결될 것으로 보입니다. 현재 최신 버전은 v4.6.4.0입니다.

최신버전으로 업데이트 했음에도 연결이 되지 않는다면 죄송하지만 다시 한번 문의 접수를 부탁드립니다.(EL Display Hub의 [고객지원] - [문의하기]를 통해 문의 접수)

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

Easy&Light
