### ISSUE TITLE
space desk와의 충돌이슈

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#331]
e-mail:zaltys7542@gmail.com<br><br>PC 업데이트 이후로 연결이 안돼요<br>다운그레이드 없나요<br><br>[EL_Display_040374a5-78e6-45a4-98c3-c9a9718ba1d4.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_040374a5-78e6-45a4-98c3-c9a9718ba1d4.zip)

**Comment by harvey-lee-devguru** [comment]
space desk와의 충돌로 발생하는 VOC로 보임

**Comment by harvey-lee-devguru** [comment]
아래와 같이 답변하였습니다.
===================
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

보내주신 로그와 증상을 검토한 결과, 타 프로그램과의 충돌 문제를 발견하였습니다.

화면 공유 프로그램이나 화면 캡처 혹은 녹화 기능이 있는 프로그램과 함께 사용할 경우 충돌이 발생할 수 있습니다.

현재 설치된 프로그램 중 "spacedesk"와 충돌이 발생하는 것으로 보입니다.
"spacedesk"와 "EL Display HUB"를 삭제하신 뒤 PC를 재부팅(종료 옵션의 "다시 시작" 옵션 사용)한 뒤 새로운 인스톨러를 다운로드 받아 " EL Display HUB "를 재설치하여 주십시오.

감사합니다.

Easy&Light
