### ISSUE TITLE
느려짐 현상으로 다운그레이 요청

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#344]
e-mail:horang5164@gmail.com<br><br>내가 성능이랑 해상도도 안건드려봤겠어요?<br><br>멀쩡히 잘되던거 업데이트 이상하게 해놓고 누굴탓해요?<br><br>환불하던가 다운그레이드 시켜달라고요<br><br>왜 같은 말을 두번씩 하게만들어요?<br><br>[EL_Display_f2875122-b815-4467-aa13-12609883856b.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_f2875122-b815-4467-aa13-12609883856b.zip)

**Comment by Juilliardsong** [comment]
#317 #324  이슈 참조

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


안녕하세요. Easy&Light 지원팀입니다.
우선 답변이 늦어지게 되어 죄송합니다. 

더 사용하시기 편리하도록 업데이트를 진행했는데 저희 쪽에서 예상하지 못했던 문제가 발생했습니다. 꼼꼼하게 체크하지 못해 죄송합니다.

PC 프로그램(EL Display Hub)이 업데이트 되었습니다.

다시 예전 버전과 동일한 성능으로 사용하실 수 있도록 조치하였습니다.
현재 최신 버전은 v4.6.4.0입니다.

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

Easy&Light
