### ISSUE TITLE
연결 불가. 환불 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#356]
e-mail:asamaru81@naver.com<br><br>잘 사용하던 앱을 업데이트 이후 사용 못하고 있습니다.<br>연결이 안되고 아이패드에서 업데이트도 안되고<br>먹통이 됐는데 환불해 주시면 다른 프로그램 사용하겠습니다.<br><br>[EL_Display_5fd1cf1b-ddc2-4aa7-abeb-2bef0d01c50e.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_5fd1cf1b-ddc2-4aa7-abeb-2bef0d01c50e.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

안녕하세요. Easy&Light 지원팀입니다.
우선 답변이 늦어지게 되어 죄송합니다. 
더 사용하시기 편리하도록 업데이트를 진행했는데 저희 쪽에서 예상하지 못했던 문제가 발생했습니다. 꼼꼼하게 체크하지 못해 죄송합니다.

PC 프로그램(EL Display Hub)이 업데이트 되었습니다.
이전 버전에서 연결이 불가했던 문제는 최신 버전으로 업데이트하면 해결될 것으로 보입니다. 현재 최신 버전은 v4.6.4.0입니다.

최신버전으로 업데이트 했음에도 연결이 되지 않는다면 죄송하지만 다시 한번 문의 접수를 부탁드립니다.(EL Display Hub의 [고객지원] - [문의하기]를 통해 문의 접수)

환불을 원하실 경우, 아래 내용을 참고하여 주시기 바랍니다. 

[환불 가이드]
1. Playstore for Android하단의 링크로 접속하시어 필요한 내용을 기입 후 제출해주시면 확인하여 환불 절차를 진행해드리겠습니다.[Android] Twomon SE/TwomonAir/TwomonUSB 환불 요청서https://docs.google.com/forms/d/1wFxbQS5wg3u1QbMLG_ZQDM2ExNbDHC9xraPje5_hBbo/edit?urp=gmail_link
2. App Store for iOS애플 앱스토어에서 판매되는 앱은 모두 애플에서 관리합니다. 저희는 고객님의 구매 정보를 가지고 있지 않기 때문에 애플리케이션 환불을 진행할 권리가 없습니다. 아래 링크를 참조 부탁드립니다.Apple Support 사이트 링크 :[https://reportaproblem.apple.com/﻿](https://reportaproblem.apple.com/)
﻿iTunes store 에서 환불 받는 방법 :https://support.apple.com/ko-kr/HT204084


다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

Easy&Light
