### ISSUE TITLE
VOC::기능 관련 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#361]
e-mail:sch2rzo@gmail.com<br><br>구매하고 편히 이용중입니다 .<br>혹시 1920 1080으로 모니터 1과 같은 해상도를 이용할 수는 없나요 ?<br>아이패드프로 11인치 5세대 이용중입니다 .<br><br>[EL_Display_6819721f-d86e-46a1-a01d-2fe0927ea70a.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_6819721f-d86e-46a1-a01d-2fe0927ea70a.zip)

**Comment by Sienna-lee** [comment]
확장은 태블릿 해상도 비율에 따라서만 사용이 가능하며, 복제는 pc 해상도에 따라서만 사용이 가능

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


안녕하세요. Easy&Light 지원팀입니다.
우선 답변이 늦어지게 되어 죄송합니다. 

문의하신 내용에 대한 답변을 아래 전달드립니다. 


화면 확장의 경우 태블릿의 해상도 비율에 따라서 사용이 가능하며, 화면 복제의 경우  PC 해상도 비율에 따라서만 사용이 가능합니다.

사용하시려는 화면 모드에 따라 위와 같이 설정이 가능합니다. 


제품에 대해 추가로 궁금한 점은 언제든지 회신하여 주시기 바랍니다.

감사합니다.


Easy&Light
