### ISSUE TITLE
VOC::스타일러스 좌표 문제

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#362]
e-mail:pompompurin2004@gmail.com<br><br>To whom it may concern, <br>I use windows 10 and ipad pro. <br>I used Easy canva happily before because the pen point of apple pencil and the drawing point of ipad screen worked very well and matched in the right poistion. <br>However, today the software forced me to update, and things was getting wrong. <br>Easy canva works as bad as Easy canva pro (I bought pro as well, so I know how it worked)-- the pen point of apple pencil and the drawing point of ipad are not in the same place.<br>I am very upleased and unhappy with the update. It just made the software work poor, and ruin my work. <br>Please watch the video. <br>I would like to know how to solve the porblem. <br>Thank you.<br><br>[EL_Display_cc5c87b1-5fd4-4361-ac24-02b011857ffd.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_cc5c87b1-5fd4-4361-ac24-02b011857ffd.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변하였습니다.
```
Hello, customer. Easy&Light support team.

First of all, we apologize for the inconvenience.
Currently, there are a lot of inquiries about the update, so the response is delayed.

The version that solves the current display driver related issues has been updated.
Please update your PC program.

Also, it seems that the problem can be solved by adjusting the options of "Touch Coordinate Correction Item" in the menu of EL Display Hub. (Please test using various options.)

Additionally, if the coordinates cannot be set normally due to changing the options of the EL Display Hub, please refer to the link below to change the settings of the graphic driver.
[FAQ] I touched the screen, but hte coordinates do not match. : http://www.easynlight.com/en/supporttwomon/?faq=85


If the same error occurs even after updating to a PC program
Please refer to the log acquisition guide below and ask again with the application log.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54


Once again, we apologize for the inconvenience.
We will do our best to make better products.

Thank you.

Easy & Light
```
