### ISSUE TITLE
VOC::신규 기능 추가 요청 (화면 색 보정 기능)

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#376]
e-mail:mutalikpunit@gmail.com<br><br>Hi. I'm very happy with my purchase of EasyCanvas pro and its working better after the recent upadte. However, i have one major area of concern that hasnt been addressed in the recent update. As i am a photographer and primarily use the ipad as a digitizer to use with photoshop, color accuracy is of  great importance for me. I have noticed that the screen on my ipad does not accurately represent the colors i seen on my calibrated laptop screen. So i wish to convey my request to add a feature that allows me to make color calibration adjustments on the screen that the ipad mirrors via EasyCanvas. I would highly appreciate the feature addition. Thank you.<br><br>[EL_Display_593e0f94-295f-45a4-a1a8-9b7a1e8894d0.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_593e0f94-295f-45a4-a1a8-9b7a1e8894d0.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. We are an Easy&Light support team. 

We know that color accuracy is important on digitizer.

I will convey your opinion to our team in charge.

We will do our best for a better program.

Thanks.


Easy&Light
