### ISSUE TITLE
트라이얼 사용 불가

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#377]
e-mail:dubhashiravi@gmail.com<br><br>I had downloaded a trial version of Easycanvas on 14/01/22. 2 days back I got a message both on my PC and iPad that the software has to updated to a newer version. Today I updated it but now I cannot continue the trial as my iPad is giving me a dialog box where I have to purchase to continue. Request you to look into it so that I can continue with the trial. I am essentially using it to paint in Rebelle 5.<br><br>[EL_Display_ed29cedf-96e6-439d-8e09-8a0b5c2e9f3e.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_ed29cedf-96e6-439d-8e09-8a0b5c2e9f3e.zip)

**Comment by Juilliardsong** [comment]
@Sienna-lee
EasyCanvas - Subscription도 동일한 제품이니 이걸로 무료 사용 해보라고 하면 될 것 같아요.

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello, customer. We are an Easy & Light support team.

I'm sending this mail for your inquiry.

You can use the trial version of the EasyCanvas app.
Download a trial version of EasyCanvas.

It provides the same features as the previous EasyCanvas Pro.
Trial versions of EasyCanvas are not automatically billed after the trial is over.

Thanks.

Easy&Light
