### ISSUE TITLE
무선 연결 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#378]
e-mail:jappiejaabir@gmail.com<br><br>How do I get it to connect wirelessly like it claims it does?<br><br>[EL_Display_a95cecff-b0be-45da-bf93-bc9b558c782a.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_a95cecff-b0be-45da-bf93-bc9b558c782a.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. Easy&Light support team.

I'm sending this email for your inquiry.


Please refer to the link below to connect wirelessly.

http://www.easynlight.com/en/supporteasycanvas/?faq=95


If you can't connect, please contact us with the log file.
Our technical team will solve your problem.

http://www.easynlight.com/en/supporteasycanvas/?faq=54


thank you.


Easy&Light
