### ISSUE TITLE
느려짐 현상 - Twomon SE

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#383]
e-mail:cwh9702@naver.com<br><br>이번 업데이트로 사용자 설정의 &quot;해상도&quot;와 &quot;성능 모드&quot;의 기본값이 높은 품질이 선택되도록 변경되었습니다.<br>설정이 변경되어 PC 및 태블릿의 사양에 따라서 성능이 다소 느려질 수 있으며,<br>아래의 FAQ를 참조하셔서 &quot;해상도&quot;와 &quot;성능 모드&quot;의 설정을 변경하여 주시길 바랍니다.<br><br>라고 답변을 주셨는데 업데이트 이전에도 최고성능에 중간정도의 해상도를 이용하고 있었습니다. 새 업데이트 이후 기본값이 높은 품질이 선택되도록 변경되었다고 해 제일 낮은 품질에 낮은 성능을 선택해도 똑같이 느린건 동일하네요...<br><br>아이패드 에어 1세대에서는 TwomonSE버전을 이젠 못쓴다고 생각해야할거같아요<br><br>[EL_Display_b58fc1da-f9e1-4284-b38f-394aef1660dc.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_b58fc1da-f9e1-4284-b38f-394aef1660dc.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

안녕하세요. Easy&Light 지원팀입니다.
우선 답변이 늦어지게 되어 죄송합니다. 

더 사용하시기 편리하도록 업데이트를 진행했는데 저희 쪽에서 예상하지 못했던 문제가 발생했습니다. 꼼꼼하게 체크하지 못해 죄송합니다.

PC 프로그램(EL Display Hub)이 업데이트 되었습니다.

다시 예전 버전과 동일한 성능으로 사용하실 수 있도록 조치하였습니다.
현재 최신 버전은 v4.6.4.0입니다.

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

Easy&Light
