### ISSUE TITLE
VOC::원격 지원

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#390]
e-mail:hwang9190@naver.com<br><br>EL display 문의<br><br>[EL_Display_217dcc9d-bdfd-49dd-8810-f11f487e421b.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_217dcc9d-bdfd-49dd-8810-f11f487e421b.zip)

**Comment by james-kim-Devguru** [comment]
* 원격 지원으로 해결
