### ISSUE TITLE
업데이트 후 기능 문제

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#396]
e-mail:parkmimmi824@gmail.com<br><br>안녕하세요.<br><br>PC 프로그램을 EL Display Hub로 업데이트 이후, 프로그램이 정상 작동하지 않는 것을 확인하여 문의 메일 드립니다.<br>사용 앱은 Twomon SE, 기기는 Air2(iOS), 소프트웨어 버전은 15.2입니다.<br><br>현재 유선 연결 시 배경 화면 출력 및 터치 입력은 정상 작동하나, 마우스 포인터가 출력되지 않는 현상, 프로그램 창이 출력되지 않는 현상 등... 터치 입력 외 모든 기능이 작동하지 않는 상태입니다.<br><br>빠른 답변 부탁드립니다.<br>감사합니다.<br><br>[EL_Display_a394d662-7577-4d26-a7d5-59d1131a6f5c.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_a394d662-7577-4d26-a7d5-59d1131a6f5c.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

안녕하세요. Easy&Light 지원팀입니다.우선 답변이 늦어지게 되어 죄송합니다. 

더 사용하시기 편리하도록 업데이트를 진행했는데 저희 쪽에서 예상하지 못했던 문제가 발생했습니다. 꼼꼼하게 체크하지 못해 죄송합니다.

PC 프로그램(EL Display Hub)이 업데이트 되었습니다.
다시 예전 버전과 동일한 성능으로 사용하실 수 있도록 조치하였습니다.
현재 최신 버전은 v4.6.4.0입니다.

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.Easy&Light
