### ISSUE TITLE
앱 사용 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#407]
- 문의 날짜 : 2022년 1월 24일 오전 2시 27분
- 메일 주소 : dubhashiravi@gmail.com

Title: Trial Period terminated after updating software

Questions: I had downloaded the software on my PC and iPad for a trial on 14/01/22. I updated the software today in the hope of trying out the updated software but now I am unable to continue on my iPad as the app on my iPad is giving me only an option to purchase. Request you to look in the matter and let me continue the trial period for the remaining trial period.

**Comment by Sienna-lee** [comment]
해당 사용자에게 로그 파일을 요청하였습니다.

----

Hello, customer. Easy&Light support team.

First of all, we apologize for the inconvenience.

Accurate and quick analysis is possible if you explain the PC log and application side log and more detailed symptoms.
Even if it is troublesome, please send both PC log and application log.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

thank you.

Easy & Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

Dear Easynlight Team,

Thank you for your response. I assume Easycanvas & Easycanvas subscription model are the same except for the payment mode. Since I had a problem with Easycanvas, I have downloaded  Easycanvas subscription (3 day trial) for testing. I have Rebelle 5 painting application on my Laptop and wanted a digitiser that would allow me to paint on my iPad. I would like to bring to your attention that this version, though may have better UI, the app has become very sluggish compared to the previous version I was testing. Previous version would become sluggish when I made plenty of rapid strokes (as is required in a painting app). This version has become even more sluggish that just no rapid strokes can be made at all and the lag is experienced from the moment I put the Apple pencil to the screen. I have a laptop with i7 processor (6th Gen) with 8 GB ram, Nvidia GEFORCE GTX 960 GPU. I do not find this lag while painting directly on the laptop with a mouse, which means that the specification of the laptop is sufficient to paint in the application. Your previous version of Easycanvas was usable but the newer version is not. I would like to know if the previous version is available for purchase.

If you need any further information please let me know.

Thanking you

Yours Sincerely

Ravindra Dubhashi

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. Easy&Light support team.

First of all, we apologize for the inconvenience.

Unfortunately, the App Store does not support the ability to provide the versions below. So we can't provide an older version of the app. But PC programs may provide older versions.


Could you please send us the log file?
Our technical team will check your problem and provide you with a solution.

Even if it is troublesome, please send both PC log and application log.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

If it is difficult to attach the log, the log file is automatically attached by using "Inquiry" of the PC program.


thank you.

Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

-----
Dear Easy&Light Team

I commend you on your prompt response. I have sent the log file through inquire panel of the EL Hub on the Laptop. I request you to look into the issue of lag in registering a stroke in Rebelle5 and let me know if it is machine specific and can something be done about it. With the lag it is becoming almost impossible to create any meaningful artwork. As mentioned in my earlier email this lag is not there using a mouse or Wacom tablet (I had borrowed it to test).

Thanking you,

Regards

Ravindra Dubhashi

**Comment by Juilliardsong** [comment]
#480 이슈에서 계속 처리합니다.
