### ISSUE TITLE
업데이트 후 화면 깨지는 현상

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#409]
e-mail:kjm9828@naver.com<br><br>업데이트 이후에  화면이 깨지는 현상이 나옵니다<br><br>[EL_Display_01b50312-9e50-4232-844e-80ef978c60bb.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_01b50312-9e50-4232-844e-80ef978c60bb.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


안녕하세요. Easy&Light 지원팀입니다.
우선 답변이 늦어지게 되어 죄송합니다. 

더 사용하시기 편리하도록 업데이트를 진행했는데 저희 쪽에서 예상하지 못했던 문제가 발생했습니다. 꼼꼼하게 체크하지 못해 죄송합니다.

PC 프로그램(EL Display Hub)이 업데이트 되었습니다.

다시 예전 버전과 동일한 성능으로 사용하실 수 있도록 조치하였습니다.
현재 최신 버전은 v4.6.4.0입니다.

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.
Easy&Light
