### ISSUE TITLE
언어 추가 - 중국어 번체

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#413]
e-mail:victoriatseng77@gmail.com<br><br>After this update, the UI language has changed,<br>Is it possible to add options for language settings?<br>and language can add traditional Chinese.<br><br>[EL_Display_b08b5dd5-79af-4b2e-91ba-cd78c8680719.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_b08b5dd5-79af-4b2e-91ba-cd78c8680719.zip)

**Comment by Juilliardsong** [comment]
@Sienna-lee 
번체 추가는 고려해보겠다고 답변해주세요.

**Comment by Sienna-lee** [comment]
홈페이지를 통해 동일한 문의를 하여 답변하였으며 해당 이슈를 종료합니다.
