### ISSUE TITLE
세로 화면 시 터치 및 마우스 사용 불가

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#415]
e-mail:chiwuchun@nate.com<br><br>업데이트 전에는 잘 사용했는데 업데이트 이후에 화면 확장시<br>디스플레이방향이 가로는 되는데 세로로 만들면 터치도 마우스도 먹통이 됩니다.<br>빠른 문제해결 부탁드립니다<br><br>[EL_Display_86559ea8-f42c-4857-9a6b-a6d72dd399d0.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_86559ea8-f42c-4857-9a6b-a6d72dd399d0.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

윈도우 10에서 세로 모드로 동작시 오류가 발생하는 문제를 확인하였습니다.
해당 문제를 해결한 버전을 배포 진행 중이며, PC 프로그램 업데이트 부탁드립니다.

PC프로그램으로 업데이트 이후에도 동일한 오류가 발생하는 경우
아래의 로그 취득 가이드를 참조하여 어플리케이션 로그와 함께 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

Ea​​sy&Light 
```
