### ISSUE TITLE
확대/축소 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#420]
e-mail:vadekunjo@hotmail.co.uk<br><br>I would like to know if it is possible to zoom on the second display that is being mirrored, but keep the first display as it is?<br><br>[EL_Display_907a264a-c41a-4cb8-87ca-e3cac585c30a.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_907a264a-c41a-4cb8-87ca-e3cac585c30a.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello, customer. Easy&Light support team.

I'm sending this email for your inquiry.


Touch the screen with two fingers and then spread them or put them together.

Even if you use your finger to zoom in and out on the tablet, the PC screen does not move.

Please reply to us if you have more questions.


Thank you.
Easy&Light
