### ISSUE TITLE
화면 확장 시 블랙스크린 발생

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#469]
e-mail:smg0301@gmail.com<br><br>화면 확장시 블랙스크린으로 변하고 아무것도 안나옵니다.<br>화면 복제를 하면 제대로 출력이 되는 것을 보면 문제가 있습니다.<br><br>블랙스크린 상황에서도 터치를 하면 마우스 커서를 납치해가는 것을 보면 복제시에만 출력 문제가 있는 것 같습니다.<br><br>[EL_Display_acf1c916-5a2c-42f3-8995-5ce0ac9d56f6.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_acf1c916-5a2c-42f3-8995-5ce0ac9d56f6.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

현재 디스플레이 드라이버 관련 문제를 해결한 버전이 업데이트 되었습니다. 
PC 프로그램 업데이트를 부탁드립니다.

PC프로그램으로 업데이트 이후에도 동일한 오류가 발생하는 경우
아래의 로그 취득 가이드를 참조하여 어플리케이션 로그와 함께 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

Ea​​sy&Light 
```
