### ISSUE TITLE
스타일러스 입력 성능 이슈

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#480]
e-mail:dubhashiravi@gmail.com<br><br>I commend your team for the quick response. I am using Rebelle5 painting application and usinf my iPad as a mirroring device. since i cannot roll back the app on iPad to the previous version can I install the previous application of the software on my Laptop (from my previous download) and will the application still mirror. Can you solve the issue of lag while painting.<br><br>Ravindra Dubhashi<br><br>[EL_Display_e5bb6726-f925-427f-a638-1b11be02b92a.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_e5bb6726-f925-427f-a638-1b11be02b92a.zip)

**Comment by Sienna-lee** [comment]
아래 이슈와 동일한 사용자입니다.

https://github.com/edh-git/EL_Display_Hub/issues/407

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

To
Easy & Light team

I wish to inform you that the lag I had referred to in my earlier email was not on account of Easycanvas but was an issue with Rebelle software which has been solved.
I would like to know if Easycanvas supports family sharing.

Regards

Ravindra Dubhashi

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----
Hello, customer. We are an Easy & Light support team.

I'm sending this mail for your inquiry.


Please refer to the link below for the Family Sharing support function.


https://apps.apple.com/us/app/easycanvas/id1228034134

image.png
You will be able to use that function.


Thanks.

Easy&Light
