### ISSUE TITLE
오류 코드 A00300001

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#486]
- 문의 날짜 : 2022년 1월 25일 오전 10시 54분 
- 메일 주소 : zzu_limuyang@163.com

Developers,
I've been using Twomon SE for years, and it's been a good experience for me. However, after a recent update, the software on PC was updated to EL DISPLAY HUB, which I can no longer use. Error code A00300001. Your q&A site simply asked me to restart my computer, which obviously won't work. Please provide a feasible solution as soon as possible, I prefer the previous version.

![image](https://user-images.githubusercontent.com/77039816/150940095-aa7073bd-c7de-4c9c-a7c7-94c4340035b4.png)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 남겼습니다.
```
Hello, customer. Easy&Light support team.

First of all, we apologize for the inconvenience.
Currently, there are a lot of inquiries about the update, so the response is delayed.

The version that solves the current display driver related issues has been updated.
Please update your PC program.

If the same error occurs even after updating to a PC program
Please refer to the log acquisition guide below and ask again with the application log.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Easy & Light
```
