### ISSUE TITLE
要求测试

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#488]
Product:EasyCanvas<br><br>Device OS:Android<br><br>e-mail:要求测试<br><br>要求测试<br><br>[EL_Display_6b57db4a-c1b2-4b21-86fd-76677e39f851.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_6b57db4a-c1b2-4b21-86fd-76677e39f851.zip)

**Comment by kimdynne** [comment]
위와 같이 중국어가 표시되는 것을 @AnthonyJeon 와 함께 확인하였습니다.
이슈 종료 부탁드립니다.
