### ISSUE TITLE
스타일러스 성능 이슈

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#490]
e-mail:danihigh@naver.com<br><br>EL DISPLAY로 업데이트 한 후에, 탭과 컴퓨터 화면 연결은 잘 되는데 포토샵이나 클립스튜디오 같은 프로그램을 켜서 펜을 작동시키면 연결이 끊겼다 연결되었다 하고 필압도 뚝뚝 끊기고 미러링도 5초 정도 늦게 일어나며 지연현상이 계속 반복됩니다. 프로그램에선 오류 코드 D0020003이라 뜨는데 제가 어떻게 해야 할지 모르겠네요. <br>로그파일도 앱에서 다운되지 않습니다...<br><br>[EL_Display_1618bda1-c400-480a-a135-9202fc9fbe85.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_1618bda1-c400-480a-a135-9202fc9fbe85.zip)

**Comment by AdamPark0030** [comment]
아래와 같이 답변 완료 했습니다.
```
안녕하세요. Easy&Light 지원팀입니다.

이용에 불편을 끼쳐드려 정말 죄송합니다.

현재 업데이트 관련 문의로 인하여 답변이 늦어지고 있습니다.

고객님의 증상과 로그를 확인한 결과 네트워크 불안정으로 인해 연결이 끊어지는 것으로 보입니다.

네트워크 속도 문제로 발생한 것이라 다음과 같은 방법을 적용해 보시기를 바랍니다.
1. 무선 네트워크 5ghz 대역으로 연결
2. 무선 네트워크 신호 강도가 가까운 곳으로 이동
3. 노트북 유선 네트워크 연결
4. 아이패드와 유선으로 연결

위의 조치사항을 취하신 후에도 문제가 지속된다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.
http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Easy&Light
```
