### ISSUE TITLE
디스플레이간 복사 붙여 넣기 되지 않음

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#500]
e-mail:scif04@naver.com<br><br>Twomon se 사용중인데 디스플레이간에 복사하기 붙여 넣기가 안되네요 ... 기존 기능이 월레 없는건지 .. 아님 tw.. 프로그램을 써서 그런건지 궁금합니다<br><br>[EL_Display_17974ef1-48bf-43aa-9ac0-a11212541e13.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_17974ef1-48bf-43aa-9ac0-a11212541e13.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


안녕하세요. Easy&Light 지원팀입니다.
우선 답변이 늦어지게 되어 죄송합니다. 

문의하신 내용에 대한 답변을 아래 전달드립니다. 


일반 듀얼 모니터를 사용하는 것과 같이 기본적으로 PC에서 지원하는 복사 붙여넣기 기능을 사용이 가능합니다. (파일 복사하여  붙여넣기, 텍스트 복사하여 다른 창에 붙여넣기 등) 


혹시 사용하시려는 기능이 위 답변과 다르다면 참고할 수 있는 이미지와 함께 다시 한번 회신 부탁드립니다. 

감사합니다.

Easy&Light
