### ISSUE TITLE
환불해주세요

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#517]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:smkim-win11<br><br>환불해주세요 xptmxm<br><br>[EL_Display_e8f867be-7049-43b1-9f9b-13b9541d8b52.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_e8f867be-7049-43b1-9f9b-13b9541d8b52.zip)

**Comment by kimdynne** [comment]
내부테스트용 이슈입니다.
