### ISSUE TITLE
USB 케이블을 통해 디스플레이를 확장할 수 없음

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#518]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:intel-amd<br><br>USB 케이블을 통해 디스플레이를 확장할 수 없음USB 케이블을 통해 디스플레이를 확장할 수 없음USB 케이블을 통해 디스플레이를 확장할 수 없음USB 케이블을 통해 디스플레이를 확장할 수 없음USB 케이블을 통해 디스플레이를 확장할 수 없음USB 케이블을 통해 디스플레이를 확장할 수 없음USB 케이블을 통해 디스플레이를 확장할 수 없음USB 케이블을 통해 디스플레이를 확장할 수 없음<br><br>[EL_Display_95a92145-4817-4f58-9ba8-734456ecc5e7.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_95a92145-4817-4f58-9ba8-734456ecc5e7.zip)

**Comment by kimdynne** [comment]
내부테스트용 이슈입니다
