### ISSUE TITLE
Bonjour 문제

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#519]
e-mail:bonjour 서비스 문제<br><br>Twomon SE때 이상없이 잘 사용하고 있었는데요, EL DIsplay Upgrade 이후 연결이 되지 않아 확인하니 Bonjour 서비스가 계속 죽었다 살았다를 반복하고 있습니다. PID 넘버가 바뀌면서요. 몇번이나 삭제, 재설치를 해 봤는데 동일하네요. <br>환경은  Windows11 입니다. 방법이 있을까요?<br><br>[EL_Display_61152d86-cd62-4cc0-8e94-571ff127a92c.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_61152d86-cd62-4cc0-8e94-571ff127a92c.zip)

**Comment by Juilliardsong** [comment]
이메일 누락으로 답변 불가
