### ISSUE TITLE
연결이 되지 않습니다. It's not connecting. 无法接通。

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#521]
Product:EasyCanvas<br><br>Device OS:Android<br><br>e-mail:연결이 되지 않습니다. It's not connecting. 无法接通。<br><br>연결이 되지 않습니다. It's not connecting. 无法接通。<br><br>[EL_Display_ee0d6f8f-618a-4bf4-9539-8c554471c0b1.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_ee0d6f8f-618a-4bf4-9539-8c554471c0b1.zip)

**Comment by jeffrey-Devguru** [comment]
테스트용문의입니다
