### ISSUE TITLE
smkim无法在 EasyCanvas Pro 上重复显示

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#531]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:smkim无法在 EasyCanvas Pro 上重复显示<br><br>smkim无法在 EasyCanvas Pro 上重复显示<br><br>[EL_Display_791b2539-648f-4061-80dc-372a22b8b26b.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_791b2539-648f-4061-80dc-372a22b8b26b.zip)

**Comment by kimdynne** [comment]
@Juilliardsong 
테스트용 이슈이므로 close 요청 드립니다.
