### ISSUE TITLE
확장 안됨

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#532]
Product:EasyCanvas<br><br>Device OS:Android<br><br>e-mail:Android<br><br>Android<br><br>[EL_Display_083d0186-2849-4118-b200-50d4fe6aa7ea.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_083d0186-2849-4118-b200-50d4fe6aa7ea.zip)

**Comment by jeffrey-Devguru** [comment]
테스트용입니다
