### ISSUE TITLE
PC 프로그램 사용 불가 

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#533]
- 문의 날짜 : 2022년 1월 26일 오전 10시 19분
- 메일 주소 : johnmason.kim@gmail.com

제목: 최신 버전을 사용할 수 없는 환경입니다.

문의사항: 약 3주 전 앱 구매를 했고, 회사 컴퓨터를 ipad 에 확장해서 사용 하고 있었습니다.
최근 앱이 업데이트 되고 PC 프로그램고 EL Display로 통합된 후 문제가 생겼습니다.

- 웹 공지상으로 윈도우즈를 20H1 이상으로 업데이트 하라 하는데
- 문제는 제 컴퓨터가 보안상 19H2에서 추가 업데이트를 할 수 없다는 것입니다.

업데이트 전 프로그램을 실행해도 IPAD 앱이 업데이트 되어 호환이 안되고 있는 상황입니다.

엡을 최근 업데이트 이전 버전으로 받아 써야 할 것 같은데 방법이 있을 지 문의 드립니다.

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

-----


고객님, 안녕하세요. Easy&Light 지원 팀 입니다.


문의해주신 내용에 대한 답변을 메일로 전달해드립니다.



PC프로그램의 경우, 이전 버전을 제공해드릴 수 있지만 앱의 경우 앱스토어에서 버전을 낮추는 기능을 제공하지 않아 이전 버전 제공이 어렵습니다. 


번거로우시겠지만 혹시 저희 개발사로 직접 내방이 가능하실 경우, 기술팀에 요청하여 태블릿에 구 버전을 설치가 가능합니다. 회사는 서울시 금천구 가산디지털단지역 근처에 위치하고 있으며, 방문이 가능하실 경우 방문 날짜를 알려주시면 상세 주소를 전달드리도록 하겠습니다. 

사용이 어려워 환불을 원하실 경우, 애플의 경우 애플 스토어에 직접 환불을 요청해야 하나  앱스토어를 통한 환불이 어려우시다면 저희에게 요청해주시면 별도로 환불을 진행해드리도록 하겠습니다. 


이번 업데이트로 인해 제품 이용에 불편을 드려 죄송합니다. 

Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.


----

답변 감사드립니다.

혹시 직접 방문하지 않고 설치 파일을 메일로 받아볼 수 있는 방법은 없는지 확인 요청 드립니다.

저도 평일 출근하는 회사원이다 보니 방문을 쉽게 할 수가 없어서요.
(프로그램은 제게 맞아 계속 사용하고 싶습니다.)

감사합니다.

**Comment by Sienna-lee** [comment]
@Juilliardsong 

환불을 원하지 않고 계속 사용하고 싶다고 하시는데 혹시 방법이 있는지 확인 부탁드립니다.

**Comment by Juilliardsong** [comment]
@Sienna-lee 
아래와 같이 답변했습니다.

---

안녕하세요. Easy&Light 지원 팀 입니다.

죄송하게도 앱 다운그레이는 내방이 꼭 필요합니다.

대신 앱 로그를 보내주시면 고객님 환경에서 사용할 수 있는 방법이 있는지 검토해보고 연락드리겠습니다.

앱 로그는 아래 FAQ를 참조하여 보내주시면 됩니다.
http://www.easynlight.com/supporttwomon/?faq=121


현재 윈도우 버전 업데이트 없이도 사용할 수 있도록 프로그램을 수정하고 있습니다.
업데이트가 늦어져 다시 한번 죄송하다는 말씀 드립니다.

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

-----

회신 감사드립니다.

혹시 프로그램 수정 일정을 대략적으로 알 수 있을까요?

우선 로그 파일 첨부 드립니다. 확인 부탁 드립니다.

감사합니다.

[Re__[Twomon_SE_-_Windows_533]_최신_버전을_사용할_수_없는_환경입니다..zip](https://github.com/edh-git/EL_Display_Hub/files/7992554/Re__.Twomon_SE_-_Windows_533._._._._._._.zip)

**Comment by Juilliardsong** [comment]
아래와 같이 답변함
---
안녕하세요. Easy&Light 지원팀입니다.
먼저 답변이 늦어 죄송하다는 말씀 드립니다.

오늘 PC 프로그램(EL Display Hub)을 업데이트 하였습니다.
이전 버전에서 연결이 불가했던 문제는 최신 버전으로 업데이트하면 해결될 것으로 보입니다. 
현재 최신 버전은 v4.6.4.0입니다. 

최신버전으로 업데이트 했음에도 연결이 되지 않는다면 죄송하지만 다시 한번 문의 접수를 부탁드립니다.
(EL Display Hub의 [고객지원] - [문의하기]를 통해 문의 접수)

감사합니다.

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

인녕하세요?

기존 버전 삭제하고 웹에서 다시 다운받아 설치했더니 아이패드와 연결이 잘 됩니다.

감사합니다.
