### ISSUE TITLE
화면 깨짐

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#553]
- 문의 날짜 : 2022년 1월 26일 오후 9시 33분
- 메일 주소 : bubooio@naver.com

제목: [사진첨부]보라색 디지털 깨짐이 너무 심합니다.

문의사항: 디지털 깨짐현상이 너무 심하고 보라색으로 변질됩니다. 1시간 작업 중에도 몇번이나 껏다 켜야 할 정도로 심합니다. 눈이 너무 아프고 멀미가 날 지경이네요..
첨부된 사진은 변색된지 얼마 안된 걸 카메라로 촬영해서 별 것 아닌것 같아 보이지만 실제로 보면 너무 심해요. 작업이 불가능할 정도입니다. 빠른 수정 부탁 드립니다.

![KakaoTalk_20220126_212954501_01](https://user-images.githubusercontent.com/77039816/151270659-490b5ff3-698a-4a40-aa81-35a9db87a5fe.jpg)

**Comment by Sienna-lee** [comment]
@james-kim-Devguru 

해당 이슈 로그파일이 필요한지 확인 부탁드립니다.
로그파일이 필요할 경우 저에게 할당해주시면 사용자에게 요청하도록 하겠습니다.

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변하였습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

현재 디스플레이 드라이버 관련 문제를 해결한 버전이 업데이트 되었습니다. 
PC 프로그램 업데이트 후 증상 확인 부탁드립니다.

또한 성능 개선을 위해 변경된 코덱에 의해서 화질에 순간적인 문제가 발생할 수 있습니다.

유선 연결의 경우 : PC와 태블릿을 연결하는 케이블이나 포트가 손상되었을 수 있습니다. 다른 케이블이나 포트의 위치를 후면으로 변경하여 테스트 부탁드립니다.

무선 연결의 경우 : PC와 태블릿의 인터넷 연결 상태 확인 부탁드립니다.
    1) PC 측과 아이패드는 공유기를 통해 무선으로 연결되며, 아이패드나 PC가 공유기의 연결 상태가 불안정한 경우 무선 통신에 실패할 수 있습니다.
    2) 아이패드와 공유기를 가까이 위치하거나 PC를 유선 연결하여도 동일한 문제가 발생하는지 확인부탁드립니다.
    3) 원활한 통신을 위해서는 무선 네트워크는 가능한 5ghz 대역을 이용바랍니다.

위 조치 사항을 취해도 동일한 문제가 발생하는 경우에는 아래의 로그 취득 가이드를 참조하여 어플리케이션 로그와 함께 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

감사합니다.

Ea​​sy&Light 
```
