### ISSUE TITLE
필압 적용 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#569]
e-mail:Peter@secondbaystudios.com<br><br>Is pressure support for the ipad pencil supported<br>Say for example in photosop?<br><br>Thanks<br><br><br>[EL_Display_17597621-a5ec-41ba-bf77-204b432f861f.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_17597621-a5ec-41ba-bf77-204b432f861f.zip)

**Comment by Juilliardsong** [comment]
#570 이슈와 함께 처리해주세요.
