### ISSUE TITLE
키보드 입력 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#570]
e-mail:Peter@secondbaystudios.com<br><br>Magic keyboard not working on ipad.Is there a way to turn it on?<br>Thanks<br><br>Peter<br><br>[EL_Display_1cfa67b4-0af8-49e2-90b7-a4ea7d68b020.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_1cfa67b4-0af8-49e2-90b7-a4ea7d68b020.zip)

**Comment by Juilliardsong** [comment]
#570 이슈와 함께 처리해주세요.
