### ISSUE TITLE
포토샵 필압 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#571]
e-mail:peter@secondbaystudios.com<br><br>There is no PSUserConfig.txt file in Adobe Photoshop 2022 Settings directory<br><br>So how does one get pressure sensitivity?<br><br>Thanks<br><br>Peter<br><br>[EL_Display_197f630e-482e-45de-8cf6-127a38433de7.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_197f630e-482e-45de-8cf6-127a38433de7.zip)

**Comment by Juilliardsong** [comment]
#569 필압 적용 문의
#570 키보드 입력 문의
이슈와 함께 처리해주세요.

**Comment by Sienna-lee** [comment]
위 내용에 대해 가이드해주시면 다른 이슈 질문을 취합하여 답변하도록 하겠습니다.

**Comment by AdamPark0030** [comment]
1. 필압적용 문의

PSUserConfig.txt 파일이 존재하지 않을 경우 파일을 직접 생성해주시면 됩니다.

그리고 UseSystemStylus 옵션을 0 또는 1로 설정 해보시길 바랍니다. 

설정을 변경 후에는 포토샵을 재시작 해야 합니다.

2. 매직키보드 사용 문의

아이패드용 매직키보드를 통해 태블릿에서 PC로 키보드 입력을 전송하는 기능은 지원하지 않습니다.

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

-----



Hello, Customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.


1. Inquiry about pen pressure application


If the PSUserConfig.txt file does not exist, you can create it yourself.
Also, try setting the UseSystemStylus option to 0 or 1.
After changing the settings, you need to restart Photoshop.


image.png



2. Inquiries about using the Magic Keyboard


Sending keyboard input from tablet to PC via Magic Keyboard for iPad is not supported.
You can use the Magic Keyboard by connecting it to your PC.



Please reply with any additional questions
Thank you.

Easy&Light
