### ISSUE TITLE
확장 옵션 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#573]
e-mail:annie.ashina@gmail.com<br><br>where is the option to extend screen<br><br>[EL_Display_cd0b1c43-9857-4508-a03b-4105f94ef3fb.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_cd0b1c43-9857-4508-a03b-4105f94ef3fb.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

-----


Hello, customer. Easy&Light support team.

I'm sending this email for your inquiry.



Select "Extension"" in EL Display Hub [Options] - [Select Display]
(If it is already extended, the "Extension" menu is not displayed.)
EL_Extension.png




Please reply to us if you have more questions.


Thank you.
Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

Hello, what I was explain was that even when it's set to extension the screen is mirrored, not extended

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello, customer. We are an Easy & Light support team.

If you cannot use the "Extension" function after the update, please take the following actions.

1. Reboot after deleting EL Display Hub (If a third-party monitor app PC program is installed, delete it together and reboot)

2. Install the latest version of EL Display Hub (v4.6.4.0)

3. Press Win+P to select "Extend"

EL_Extend.png


4. Select "Extension"" in EL Display Hub [Options] - [Select Display]
(If it is already extended, the "Extension" menu is not displayed.)
EL_Extension.png

If the extension does not work even after following the steps above, we are sorry, but Please contact us again.
(You can inquire through [Support] - [Inquiry] of the EL Display Hub.)



We will do our best to make better products.


Easy&Light
