### ISSUE TITLE
Twomon SE not working after the EL display hub update

### ISSUE THREAD

**Issue by Juilliardsong** [edh-git/EL_Display_Hub#575]
사용자 정보
---
제품선택 :  Twomon SE
사용OS : Windows
사용기기 : iOS
이름 : Quancheng Liu
메일 : qliu18@ncsu.edu

문의 내용
---
Questions: the display just lags forever. The only time it would refresh is to change the option such as resolution or performance and it would only refresh that once. It\'s just like what happens when I update to windows 11.

[com.devguru.ntwomon-2022-01-27-14-29.log](https://github.com/edh-git/EL_Display_Hub/files/7955130/com.devguru.ntwomon-2022-01-27-14-29.log)
[log.zip](https://github.com/edh-git/EL_Display_Hub/files/7955132/log.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변하였습니다.
```
Hello, customer. Easy&Light support team.

First of all, we apologize for the inconvenience.
Currently, there are a lot of inquiries about the update, so the response is delayed.

We have confirmed that an error occurs when operating in portrait mode in Windows 10.
We are distributing a version that solves the problem, please update the PC program.

Also in Windows 11 there seems to be a problem with the functionality that Windows provides when in portrait mode.
Unless Microsoft corrects the error, it seems unlikely that the problem will be resolved.

Even if it is inconvenient for now, please use it in landscape mode in Windows 11.
If EL Display Hub or Windows is updated, please check the symptoms again.

thank you.

Easy & Light
```
