### ISSUE TITLE
bonjour오류

### ISSUE THREAD

**Issue by Juilliardsong** [edh-git/EL_Display_Hub#576]
사용자 정보
---
제품선택 : Twomon SE
사용OS : Windows
사용기기 : iOS
이름 : 권혁범
메일 : hbk0424@gmail.com

문의사항
---
업데이트 이후로 bonjour비활성화 오류가 계속 뜹니다. 삭제 후 재설치 해도 동일합니다.
연결은 정상적으로 작동되는데, 계속 떠서 너무 번거롭습니다.

코드 A0020002 입니다.

pc 프로그램 진단을 해봐도 다 정상이네요.

기기랑 연결 안한 상태여도 그렇습니다.

로그파일 첨부드립니다.
<br><br>

![1111](https://user-images.githubusercontent.com/68727895/151474737-7eebf8ba-a4d6-47b3-8a40-e8a465b7e74e.png)

[Twomon_20220128_001432.zip](https://github.com/edh-git/EL_Display_Hub/files/7955167/Twomon_20220128_001432.zip)
[Twomon_20220128_0014321.zip](https://github.com/edh-git/EL_Display_Hub/files/7955168/Twomon_20220128_0014321.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변하였습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

고객님께서 보내주신 로그를 검토한 결과 프로그램의 일부가 제대로 동작하지 않은 것으로 보입니다.

PC프로그램을 설치하며 "Bonjour Service"가 같이 설치되며 현재 고객님의 PC에서 해당 프로그램이 정상적으로 동작하지 않는 것으로 보입니다.

해당 문제의 경우 서비스의 "Bonjour Service"를 재실행 시킬 경우 해결될 것으로 보입니다.

1. 윈도우 검색 창에서 "서비스"를 검색하여 실행합니다.
2. "Bonjour Service" 항목을 찾습니다.
3. "상태"가 "실행 중", "시작 유형"이 "자동"인지 확인합니다.
4. "실행 중"이 아닐 경우 "시작"을 통해서 실행 상태로 변경하여 주십시오.
5. "시작 유형"이 "자동"이 아닐 경우, "우클릭 - 속성"을 통해서 속성 창을 연 뒤, "시작 유형"을 "자동"으로 변경하여 주십시오.
6. PC를 재부팅 합니다.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/en/supporteasycanvas/?faq=54

감사합니다.

Ea​​sy&Light 

```
