### ISSUE TITLE
Blender에서의 사용 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#580]
e-mail:sarik85@gmail.com<br><br>Rotate canvas doesn't work<br><br>Hi,<br><br>I'm using 4th generation Ipad Pro with Windows 10.  Easycanvas app version is 4.6.1R.<br><br>I purchased Easycanvas mainly to be used with Blender. Easycanvas doesn't work at all in Blender- not being able to zoom or rotate canvas using grease pencil for example. I also use Affinity Designer, and I'm able to zoom but not rotate. <br><br>Please advise what to do about the rotation problem? If there isn't a fix, could I please get a refund?<br><br>[EL_Display_3bd97e5b-3cbe-402c-aed3-be04cc86a031.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_3bd97e5b-3cbe-402c-aed3-be04cc86a031.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. We are an Easy & Light support team.
I'm sending this email for your inquiry. 
Have you already set this way?http://www.easynlight.com/en/supporteasycanvas/?faq=75


If that doesn't work, make sure the Grease pencil supports pressure and sensitivity.

The only way is to change the settings to Win Ink.

I'm sorry I couldn't resolve your problem.

If the problem persists and you can't use it, we'll send you a guide so you can get a refund.


[How to get a refund]

1. App Store for iOSWe'd like to give you a refund but we are not in charge of the refund. We'll let you know how to get the refund from the iTunes store. Please refer to the following websites.
Contact Apple Support:https://reportaproblem.apple.com/
How to get a refund from iTunes store:https://support.apple.com/en-us/HT204084

2. Google play store for AndroidPlease click the following link, fill out and submit a refund request form.https://docs.google.com/forms/d/1q0_e3fDsvldj5KLzch2OfUBKFCqcluPGNYAyT8TMt7Y/

I will try to make a better program.

Thank you.

Easy&Light
