### ISSUE TITLE
VOC::604 이슈와 중복

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#605]
e-mail:jpbdias@gmail.com<br><br>Hi,<br>After the last update of Twomon SE I'm having trouble watching videos.<br><br>After a few minutes of watching the video, small squares appear on the screen.<br><br>Attached error image.<br><br>Original video: https://www.youtube.com/watch?v=rS5st3W3DLU<br><br>Thanks,<br>JP<br><br>[EL_Display_339a2a6f-75ff-4a5a-97c9-e346a4964de5.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_339a2a6f-75ff-4a5a-97c9-e346a4964de5.zip)

**Comment by james-kim-Devguru** [comment]
https://github.com/edh-git/EL_Display_Hub/issues/605
