### ISSUE TITLE
VOC::VOC내용 이상(?표시)

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#611]
e-mail:rudah716@gmail.com<br><br>?? EL????? ??? ?? ???? ???????. ??????? ??? ????, ????? ??? ????.?????? ????? ???? ???? TWOMON SE????? ?????? ???.<br><br>[EL_Display_db2c4759-3841-4629-ac81-b3f7f824d9af.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_db2c4759-3841-4629-ac81-b3f7f824d9af.zip)

**Comment by Sienna-lee** [comment]
#612 동일 사용자
