### ISSUE TITLE
VOC::VOC내용 이상(?표시)

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#612]
e-mail:rudah716@gmail.com<br><br>?? ? ??? ??? EL????? ? ??? ??!!!!!!!!!!!!!!!!!!!<br><br>[EL_Display_d66400ca-4e45-4df6-87dc-84cc40fac179.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_d66400ca-4e45-4df6-87dc-84cc40fac179.zip)

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

-----


DL로 업데이트 하고 작동안해서 못써먹겠다.진심으로 모든걸 다해봤다 더이상 열불나게하지말고 환불이나 진행 해주라.
로그파일 보냈으니까 확인하고
구글 계정 [rudah716@gmail.com](mailto:rudah716@gmail.com) 다.

**Comment by Sienna-lee** [comment]
해당 사용자에게 환불 가이드를 전달하였습니다.

----

고객님, 안녕하세요. Easy&Light 지원 팀 입니다. 
먼저 제품 이용에 불편을 드려 죄송합니다.

[rudah716@gmail.com](mailto:rudah716@gmail.com) 해당 주소로 확인 결과 구매내역이 확인 되지 않습니다.   
앱을 구매한 계정 주소를 다시 한번 확인 부탁드립니다.
보다 정확히 확인하실 수 있도록 아래 환불 가이드를 함께 전달드립니다. 



[환불 가이드]
1. Playstore for Android하단의 링크로 접속하시어 필요한 내용을 기입 후 제출해주시면 확인하여 환불 절차를 진행해드리겠습니다.[Android] Twomon SE/TwomonAir/TwomonUSB 환불 요청서https://docs.google.com/forms/d/1wFxbQS5wg3u1QbMLG_ZQDM2ExNbDHC9xraPje5_hBbo/edit?urp=gmail_link
2. App Store for iOS애플 앱스토어에서 판매되는 앱은 모두 애플에서 관리합니다. 저희는 고객님의 구매 정보를 가지고 있지 않기 때문에 애플리케이션 환불을 진행할 권리가 없습니다. 아래 링크를 참조 부탁드립니다.Apple Support 사이트 링크 :[https://reportaproblem.apple.com/﻿](https://reportaproblem.apple.com/)
﻿iTunes store 에서 환불 받는 방법 :https://support.apple.com/ko-kr/HT204084

다시 한번 이용에 불편을 드려 죄송하다는 말씀 드립니다.
더 좋은 제품을 만들기 위해 노력하겠습니다.

Easy&Light
