### ISSUE TITLE
연결 끊김 현상 발생

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#621]
e-mail:annablaster47@gmail.com<br><br>I am using my Ipad's usb to connect because it is more reliable than the wifi. I am currently subscribed and it always keeps disconnecting me, I did what I see on the FAQ and the problem continues regardless. I deleted, reinstall and restart, but still I always get disconnected and it doesn't connect me back. This is actually really annoying paying for something and can't get proper use. Is there something else I can do to fix this problem?<br><br>[EL_Display_e980189b-82ed-400a-9847-00ecb4c79cb1.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_e980189b-82ed-400a-9847-00ecb4c79cb1.zip)

**Comment by Juilliardsong** [comment]
#623 이슈에서 처리합니다.
