### ISSUE TITLE
업데이트 후 연결 문제 발생

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#624]
e-mail:setterrr@gmail.com<br><br>I haven't been able to get Easy Canvas to work since the recent change to EL Display Hub and the corresponding ios app update.<br><br>I am using an Ipad Mini 2 with a W10 computer.  I had been using it everyday without any problems up until the recent update.<br><br>When it connects via wifi, the app just immediately crashes.<br><br>When I turn wifi off on the ipad mini and force it to use a cable connection, it works barely but not to a usable degree.  The W10 screen is shown on the ipad mini, but there is a massive 5 second delay before the screen updates on the ipad mini.<br><br>It seems like the problem might be with the ipad mini app. If I simply hit the keyboard shortcut settings button, it takes at least 10 seconds to come up.<br><br>I have updated Windows and reinstalled both apps on both devices with no luck.  The W10 app diagnostic shows no problems.<br><br>[EL_Display_bd408265-335c-49aa-ab13-207cc7711af0.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_bd408265-335c-49aa-ab13-207cc7711af0.zip)

**Comment by AdamPark0030** [comment]
아래와 같이 답변 완료 했습니다.
```
Hello, customer. We are an Easy & Light support team.

First, we apologize for the inconvenience in using it.

Currently, there are many inquiries about updates, so the answer is delayed.

Currently, a version of v4.6.4.0 with several bugs fixed in the PC program has been deployed.

Please update the PC program through the download link.
[PC Program Download Link] : http://www.easynlight.com/en/easycanvas/

If the problem does not improve even after proceeding with the above measures, please inquire again with the application log.
[Log Guide] : http://www.easynlight.com/en/supporttwomon/?faq=78

Thank you.
```
