### ISSUE TITLE
Windows 11에서 세로 모드 사용 불가

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#625]
e-mail:r0688@hanmail.net<br><br>세로모드 동작이 안됩니다.<br>( 윈도우11에서 세로모드 전화)<br><br>가로모드는 잘 됩니다.<br><br>[EL_Display_6a0fce61-e495-4cf3-b7a2-01ee1431a636.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_6a0fce61-e495-4cf3-b7a2-01ee1431a636.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

세로 모드일 때 Windows에서 제공하는 기능에 문제가 있는 것 같습니다.
Microsoft에서 오류를 수정하지 않으면 해당 문제의 해결이 어려울 것 같습니다.

현재로서는 불편하시더라도 Windows 11에서는 가로 모드로 사용해주시길 바랍니다.
Twomon SE가 업데이트 될 경우, 다시 증상을 확인 부탁드립니다.

감사합니다.

Easy&Light
