### ISSUE TITLE
PC 프로그램과 앱 호환 불가 

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#642]
- 문의 날짜 : 2022년 2월 2일 오전 4시 35분
 - 메일 주소 : stevekithinji@gmail.com

Title: First Time setup [Need Update]

Questions: How do i resolve this?
The current PC program is not compatible with the mobile app version.

I am running version 4.6.1.0 on the PC and 4.6.1 R on the tablet.

----

Hi Team,

I installed this application yesterday but I am stuck where the tablet app throws a warning that I need to update the PC program yet I am running the latest version on both PC and tablet. 

I was almost giving up, kindly but urgently assist.

Best regards,
Steve M

----

More info:

Tablet is running the latest android version and the PC is on Windows 10.

----

Hello Support,

Any response on this ?

Best regard,
Steve M.

**Comment by Sienna-lee** [comment]
해당 사용자에게 로그파일을 요청하였습니다.

----


Hello, customer. We are an Easy & Light support team.

I'm sending this mail for your inquiry.
 
To know the problem, we need log files.
Please refer to this link and send us log files.

http://www.easynlight.com/en/supporttwomon/?faq=78

If you send log files, we will analyze and give you a guide.
Sorry for the inconvenience.


Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----


Hi Support Team,

I don't have the logs, but we can have a remote session if this is okay with you we set it up together.

Best regards,
Steve M

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. Easy&Light support team.

I'm sending this email for your inquiry.


 

If the log extraction method is difficult, please contact us using 'Inquiry' in the PC program (EL Display Hub). The log file is automatically attached.

thank you.


Easy&Light

**Comment by Juilliardsong** [comment]
#650 이슈에서 함께 처리해주세요.

**Comment by AdamPark0030** [comment]
#650 이슈에 답변 했습니다.
