### ISSUE TITLE
A0030001 에러 발생

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#651]
e-mail:sdmstj@naver.com<br><br>error code A0030001<br>재부팅 해도 안됨<br><br>[EL_Display_64023d88-08ef-411c-8d48-153e433f9605.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_64023d88-08ef-411c-8d48-153e433f9605.zip)

**Comment by Juilliardsong** [comment]
#652 이슈에서 처리합니다.
