### ISSUE TITLE
display driver YB 43 on Windows 10 v1607

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#664]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:smkim<br><br>YB 43<br><br>[EL_Display_4837c79f-6c10-4cda-ad82-818354ac73e3.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_4837c79f-6c10-4cda-ad82-818354ac73e3.zip)

**Comment by kimdynne** [comment]
ELHUB display driver YB 10 (NOT YB 43)
![1607-YB10](https://user-images.githubusercontent.com/68727617/152469939-da7301c1-0586-40f7-ab06-7d681b2d0ffa.png)
