### ISSUE TITLE
Apple pen and photoshop

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#671]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:zachhessn13@gmail.com<br><br>Hello, i am trying to use my Ipad to draw in photo shop and for the most part i have everything set up. The problem that im having is that when i actually go to draw I can't actually draw wirh the pen, i can mess with pretty much anything else switch over to using a different tool or even close out of the application if I want but it wont draw. I tried going to the FQA but it seems out dated.<br><br>[EL_Display_fde1fc69-68d6-4a4a-884f-59db46c6a886.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_fde1fc69-68d6-4a4a-884f-59db46c6a886.zip)

**Comment by AdamPark0030** [comment]
![image](https://user-images.githubusercontent.com/73160679/153171886-ce82e366-463e-4630-aaf3-c2767b56741e.png)

**Comment by AdamPark0030** [comment]
아래와 같이 답변 완료 했습니다.
```
Hello, customer. We are an Easy & Light support team.

First, we apologize for the inconvenience in using it.
Currently, there are many inquiries about updates, so the answer is delayed.

Please check the "Photoshop" item in the link below.
[The pen pressure input of Apple Pencil does not work in drawing programs] : http://www.easynlight.com/en/supporteasycanvas/?faq=75

If the PSUserConfig.txt file does not exist, you can create the file yourself.

And please set the UseSystemStylus option to 0 or 1.

If the problem does not improve even after proceeding with the above measures, please inquire again.

Thank you.

Easy&Light

```
한글원문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.
현재 업데이트 관련 문의가 많아 답변이 늦어지고 있습니다.

아래의 링크에서 "Photoshop" 항목을 확인해주세요.
[The pen pressure input of Apple Pencil does not work in drawing programs] : http://www.easynlight.com/en/supporteasycanvas/?faq=75

PSUserConfig.txt 파일이 존재하지 않을 경우 파일을 직접 생성해주시면 됩니다.

그리고 UseSystemStylus 옵션을 0 또는 1로 설정 해보시길 바랍니다.

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면 재문의 부탁드립니다.

감사합니다.

Ea​​sy&Light 
```

[참고 이미지]
![image](https://user-images.githubusercontent.com/73160679/153172448-acefbf78-2027-43b4-88e5-c3cec851581d.png)
