### ISSUE TITLE
듀얼연결은 되는데 창

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#688]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:bompulbyun@gmail.com<br><br>듀얼 연결 후에 창을 옆으로 넘기려고 하면 정지 상태로 머물러 있습니다. 창이 나 화살표가 안넘어 가요<br><br>[EL_Display_35e2725a-9514-476c-8f9e-46dba09ddf6b.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_35e2725a-9514-476c-8f9e-46dba09ddf6b.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변하였습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

세로 모드일 때 Windows에서 제공하는 기능에 문제가 있는 것 같습니다. 
Microsoft에서 오류를 수정하지 않으면 해당 문제의 해결이 어려울 것 같습니다.

현재로서는 불편하시더라도 Windows 11에서는 가로 모드로 사용해주시길 바랍니다.
Twomon SE가 업데이트 될 경우, 다시 증상을 확인 부탁드립니다.

감사합니다.

Ea​​sy&Light 
```
