### ISSUE TITLE
윈도우 10 프로 아이패드 연결이 안되요

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#690]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:gseung98@kepco.co.kr<br><br>PC로 프로그램 설치했고 USB 연결해서 아이패드도 앱 켰는데 연결이 안되요<br><br>[EL_Display_f186c046-6548-4091-b043-46b3929a3eab.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_f186c046-6548-4091-b043-46b3929a3eab.zip)

**Comment by AdamPark0030** [comment]
아래와 같이 답변했습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

보내주신 로그와 증상을 검토한결과 IOS 앱을 업데이트 후 다시 연결에 시도해주시길 바랍니다.

현재 보내주신 문의사항에 앱 로그가 누락되어 정확한 증상 파악이 어렵습니다. 

IOS 앱 업데이트 이후 문제가 지속된다면 아래의 로그 취득 가이드를 통해 앱로그와 함께 첨부해주세요.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light 
```
