### ISSUE TITLE
자동결재 해지 요청

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#701]
Product:EasyCanvas<br><br>Device OS:Android<br><br>e-mail:kp0625@hanmail.net<br><br>카드 자동결제 해지 요청합니다 01071926753<br><br>[EL_Display_a1f38067-9bd1-4493-a9f3-aa12c5a65123.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_a1f38067-9bd1-4493-a9f3-aa12c5a65123.zip)

**Comment by Juilliardsong** [comment]
아래와 같이 답변함 - 환불 및 구독 해지 링크 전달
---
안녕하세요. Easy&Light 지원팀입니다.

애플 앱스토어에서 판매되는 앱은 모두 애플에서 관리합니다.
저희는 고객 정보를 가지고 있지 않기 때문에 환불이나 구독 해지를 진행할 권리가 없습니다.

대신 환불 및 구독 해지 가이드 링크를 전달해 드리겠습니다.

* 결제 취소 방법 : https://support.apple.com/ko-kr/HT204084
* 구독 해지 방법 : https://support.apple.com/ko-kr/HT202039

감사합니다.
