### ISSUE TITLE
i want to unsubscribe the aplication on the ipad but i cant find a way to do that on the app or in the app store

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#702]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:mithunkagalkar@icloud.com<br><br>i want to cancel my subscription im still in my free trial period , i cant scroll down on my ipad and its not very helpful for writing on onenote , i cant find the option to unsubscribe on my ipad before im charged for the subscription<br><br>[EL_Display_a9c6b4fa-15cd-4cf1-ab8e-440808f173a8.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_a9c6b4fa-15cd-4cf1-ab8e-440808f173a8.zip)

**Comment by Juilliardsong** [comment]
아래와 같이 답변함 - 구독 취소 가이드 안내
---
Hello, customer. We are an Easy & Light support team.

If you are using the "[EasyCanvas-Subscription](https://apps.apple.com/us/app/easycanvas-pro/id1499946999)" app, you can unsubscribe by referring to the guide below.
https://support.apple.com/en-us/HT202039

If you are using the "[EasyCanvas-GraphictableApp](https://apps.apple.com/us/app/id1228034134)" app, it will not be automatically paid after the free period expires.

Thank you.
