### ISSUE TITLE
무선 연결 문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#704]
e-mail:jappiejaabir@gmail.com<br><br>Not connecting wirelessly after following every step in the e-mail by letting both devices register via USB, then unplugging them.<br><br>[EL_Display_6bd2fab4-26f4-4879-a924-c58d39121a61.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_6bd2fab4-26f4-4879-a924-c58d39121a61.zip)

**Comment by Juilliardsong** [comment]
#378 이슈의 추가 문의입니다.

**Comment by AdamPark0030** [comment]
아래와 같이 답변 완료 했습니다.

```
Hello, customer. We are an Easy & Light support team.

First, we apologize for the inconvenience in using it.

I'm sorry, but the Twomon SE app does not support wireless connection.

If you want to use wireless connection, please use Easy Canvas or Easy Canvas Sub products.

Thank you.
```
한글원문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

죄송하지만 Twomon SE 앱은 무선 연결을 지원하지 않습니다.

무선연결을 이용하고 싶다면 EasyCanvas 또는 EasyCanvas Sub 제품을 이용해주세요.

감사합니다.
```
