### ISSUE TITLE
이지캔버스 사용 오류

### ISSUE THREAD

**Issue by Juilliardsong** [edh-git/EL_Display_Hub#706]
메일 접수 VOC

제품선택 : EasyCanvas
사용OS : Windows
사용기기 : iOS
이름 : 이상현
Email : bluestory13@naver.com
<br>
---
문의사항 : 
안녕하세요.
부팅 시 마다 \"AMDS 서비스가 활성화되지 않았습니다.\" 라는 에러 메시지가 나오는데 재부팅해도 같은 상황입니다.
프로그램이 바뀌고나서는 정상적으로 사용을 해보지 못하고 있는 상황입니다.
확실한 해결책(재부팅은 확실한 해결책이 아닙니다)을 제시해 주세요.

첨부파일 : 
![오류-화면](https://user-images.githubusercontent.com/68727895/153319334-18a32daf-b6d2-4886-a637-48462d2a0b2b.png)

**Comment by AdamPark0030** [comment]
아래와 같이 답변 완료 했습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

현재 문의해주신 내용만으로 정확한 원인 파악이 어렵습니다.

아래의 로그 취득 가이드를 통해 로그를 첨부하여 다시 문의해주세요.

[FAQ] 로그 취득 가이드 : 
http://www.easynlight.com/supporttwomon/?faq=121

감사합니다.

Ea​​sy&Light 
```
