### ISSUE TITLE
도와주세용

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#708]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:cjswoalfm@naver.com<br><br>자꾸 에러가 떠용...ㅠㅠ도와주세요 매니저님<br><br>[EL_Display_d66418bc-d36d-4592-bd1f-fe59e4aab741.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_d66418bc-d36d-4592-bd1f-fe59e4aab741.zip)

**Comment by Juilliardsong** [comment]
중복 문의로 해당 이슈 종료합니다.
