### ISSUE TITLE
업데이트 이후 구동 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#729]
- 문의 날짜 : 2022년 2월 13일 오후 3시 36분
- 메일 주소 : deerdeer0216@naver.com

1. 업데이트 이후에 전혀 구동이 안됩니다. 

2. 현재 문제에 대한 화면캡쳐를 첨부합니다.

3. 해결방법을 메일로 보내주세요.

4. 업데이트 전이 훨씬 좋습니다. 

5. 사용자들은 유료구매를 한것입니다.

그런데, 서비스 이용에 불편이 생깁니다.

업데이트 이후, 앱 사용불가로 

업무에 차질이 생깁니다.

 

수고하세요. 

[업데이트_이후에_ㄱ구동이_전혀_안되는_문제로_문의메일_보냅니다..zip](https://github.com/edh-git/EL_Display_Hub/files/8057096/_._._._._._._.zip)

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 추가로 메일을 보내왔습니다.

----

기존에는 간편한 접근성으로 인해 사용한것입니다. 

일부로 USB로만 가능한 제품이며 무선연결이 필요없는 usb로 가능한 유료앱을 샀던 것입니다.

그런데 접근성이 아예 가동이 안되니 정말 불편합니다.



업데이트 이후 앱은 예전 버전 그대로고 

피씨 버전만 업데이트 된것으로밖엔 안보입니다. 



바로 연결하자마자 되야 사용가능한데

이런식이면 환불을 원합니다.



포토샵같은 프로그램도 버전별로 가격이 상이하고 버전별로 업데이트 없이 기존버전을 사용하게끔 되있는데

업데이트 전 프로그램을 원합니다. 



전 USB 연결 및 Wifi 연결이 되지않는 이유로 SE 투몬을 구매한 것인데

그 역할을 다하지 못한다면 환불을 원합니다.

**Comment by Sienna-lee** [comment]
에러 코드 등을 확인할 수 있는 첨부된 이미지로 문제 해결이 가능한지 확인 부탁드립니다. 로그파일이 필요할 시 저에게 할당하여 주시면 사용자에게 로그파일을 요청하도록 하겠습니다.

**Comment by AdamPark0030** [comment]
@Sienna-lee 로그파일 요청 부탁드립니다.

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 로그파일을 요청하였습니다.

----


고객님, 안녕하세요. Easy&Light 지원 팀 입니다.


EasyCanvas와 Twomon SE의 성능 개선 및 사용 편의를 위해 통합 PC 프로그램(EL Display Hub)으로 업데이트하였으나 이로인해 불편을 드려 죄송합니다. 



 

 문제를 상세히 확인할 수 있도록 로그파일을 함께 첨부하여 문의주시면 기술팀에서 확인하여  해결 방안을 전달드리도록 하겠습니다.





- 로그 추출 가이드 : http://www.easynlight.com/supporttwomon/?faq=121




혹시 위 방법이 너무 어려우실 경우, EL Display Hub(PC 프로그램)의 고객지원 -> 문의하기를 이용하여 다시 한번 문의를 부탁드립니다.





image.png



위 방법으로 문의하시면 별도의 로그 추출을 하지 않아도 자동으로 로그가 함께 전달됩니다. 

현재 문의주신 메일 주소와 동일하게 문의주시면 해당 메일주소로 답변을 드릴 예정입니다. 



감사합니다.


Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

-----


제목: 왜 답변을 안해주십니까 ?

문의사항: 유료제품이고 메일로 문의드렸는데 왜 문의답변을 주지 않으십니까 ?
일할때 필수로 사용하면서 진행하고 했는데 업데이트 이후 활용을 못하고 있습니다.
로그 추출해서 메일로도 보냈는데 연락이 아예 없네요.

메일 수신확인은 하셨는데 왜 답변을 안해주시나요.
연락처도 없고 답답하고 이 기업은 신뢰할 수가 없습니다
환불문의를 했지만 답변도 없습니까 ?

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

제품 이용에 불편을 드려 죄송합니다. 

지난 2월 14일에 로그파일을 요청드리는 회신을 하였는데 현재 문의주신 이메일 주소로 접수된 로그파일이 확인되지 않습니다. 
혹시 PC 프로그램을 통해 접수해주셨다면 접수해주신 이메일 주소 확인을 부탁드립니다.만약 메일 확인이 어려울 시 번거로우시겠지만 다시 한번 PC 프로그램을 통한 문의 부탁드립니다. (EL Display Hub의 고객지원 -> 문의하기)

현재 제품 특성상 유선을 통한 고객지원 서비스가 어려워 이메일을 통한 고객지원만 되는 점 양해 부탁드립니다. 환불을 원하실 경우 참고하실 수 있도록 아래 환불 가이드도 함께 전달드립니다. 

[환불 가이드]
1. Playstore for Android하단의 링크로 접속하시어 필요한 내용을 기입 후 제출해주시면 확인하여 환불 절차를 진행해드리겠습니다.[Android] Twomon SE/TwomonAir/TwomonUSB 환불 요청서https://docs.google.com/forms/d/1wFxbQS5wg3u1QbMLG_ZQDM2ExNbDHC9xraPje5_hBbo/edit?urp=gmail_link
2. App Store for iOS애플 앱스토어에서 판매되는 앱은 모두 애플에서 관리합니다. 저희는 고객님의 구매 정보를 가지고 있지 않기 때문에 애플리케이션 환불을 진행할 권리가 없습니다. 아래 링크를 참조 부탁드립니다.Apple Support 사이트 링크 :[https://reportaproblem.apple.com/﻿](https://reportaproblem.apple.com/)
﻿iTunes store 에서 환불 받는 방법 :https://support.apple.com/ko-kr/HT204084



다시 한번 제품 이용에 불편을 드려 죄송합니다.
Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

다른 화면에 표시 확장에 디버깅에 그러한 기본적 시도는 당연히 하였습니다.

하지만, 프로그램 업데이트 이후 전혀 사용을 하지 못하였습니다.

 

물론, 업데이트 되지 않았던, http://www.easynlight.com/supporttwomon/?mod=list&faq=123


이 해결방법을 따라하며, 시스템에 들어가 이것저거 문제해결을 도모했지만 전혀 해결에 단 0.1%의 도움도 받지 못하였습니다.

이유는 이엘디스플레이 호환문제에 대한 어떤것도 쓰여있지 않고, 도움도 되지 않았습니다.

 

앱을 업데이트 해도, 보통 이런식으로 완전히 180도 다른 프로그램화하진 않는데

새로운 어플을 만드실려는 시도보다 ,기존의 접근성이 좋던 프로그램을 업데이트 화 해버리고,

그로 인해 많은 문제가 있음에도 로그파일보내도, 그 이엘프로그램이 문제인지, 회신도 잘안되는것 같습니다.

 

저는 deerdeer216@naver.com 로 로그 파일을 보냈습니다.

그러나 어떠한 답변도 받지 못했습니다. 회신이 안되걸로 사료되는 상황입니다.

 

기존의 프로그램은 모니터에서 끝났습니다.

지금 시도하시는게 < 웹툰이나 드로잉 > 관련해서 펜인식까지 잡아가는 좀 더 업데이트된 프로그램로 업데이트를 생각하셨다면

전 소비자로써 그러한 걸 원한적이 1도 없습니다.

 

저는 아주 간편하고 접근성이 편리한 보조모니터 기능을 매우 빠른시간내 수행할 수 있는 프로그램을 원했습니다.

이렇게, 불편하고 업데이트 후 전혀 다른 프로그램화되있고, 안정성이 매우 없는 상태에서 오랫동안 소비자가 불편을 감수하는 상황은

매우 2022년 시스템 답지 않습니다. 

차라리, "새로운 드로잉 및 보조모니트 어플"을 개발하시고, 여러번 테스트과정을 한후에 판매를 하고, SE를 종료하는 과정에서

 SE 이용자에게 공지를 하여 "그 어플로" 넘어오게끔 시스템을 하는 어드벤티지 시스템을 하면되는데,

기존의 소비자들을 테스터로 가져가는 건 매우 불편함을 소비자에게 감수하라는 행동이고 이는 매우 신뢰성을 잃게 만드는 행동입니다.

우리는 그러한 목적을 위해 돈을 지불할 이유가 없기 때문입니다. 

 

소비자는 완성작을 사고 싶어하지, 미완성작 제품/ 어플 을 전혀 사고싶은 맘이 없습니다.

업데이트 하는 과정에서 문제가 아주 많이 동일한 모습이 연출되도 , 그저 소비자로써 감내만 하라는 행동은 공감을 1도 없을 수 없습니다.

 

기존의 프로그램처럼 간단하고 편리한걸 <보조모니터 > 개념을 원한거지

드로잉 펜인식, 뭐 이런 고급화되고 복잡한 프로그램을 원한적이 0.1%도 없습니다.

 

기존 프로그램을 매우 잘 만드셨는데, 왜 급진적이고 불안정한 프로그램으로 업데이트 과정에서의 불편감을 오롯이

고객들에게 넘기는 상황을 만드셨는지 아쉽습니다.  기존 프로그램은 다른 비슷한 프로그램에 비해 매우 안정적이고 괜찮았고 최상의 프로그램이였으나,

현재의 "이엘" 업데이트된 프로그램은 매우... 싫습니다. 

 

다운그레이드가 안될바엔 환불을 원합니다.

포토샵이나 그런 프로그램들도 한글이나, 프로그램 구매시 <소비자의 허락없이> 업데이트로 인한 불편감을 주는경우가 없습니다.

 그리고 업데이트도 안합니다. 소비자는 업데이트로 인해 오히려 굉장히 불편해하고 싫어합니다.

그런데, 업데이트 후에 구동도 안하는 프로그램되었고 ,말그대로 고장나고 , 해결방법도 올드한서식 그대로 있고, 이메일 회신과정도 느리고,

로그파일 보내도 연락안되고 이런 상황에서 소비자가 선택할 수 있는건, 아쉽게도 환불밖에 없습니다.

 

나중에 차후 완전히 안정화 된 후면 몰라도 현재는 환불을 요청하는 바입니다.

 

당장 회사에서 자주 필요한데 이렇게 사용이 불가능하면 어떻게 하라는 건지 정말 불편하고, 아쉽습니다.

 

기존 프로그램이 딱 1000000000배 좋습니다 . 투몬 SE PC 예전 버전이요. >>>>>>>>>>>>>>> 이엘 어쩌구 구동도 안되는 업데이트된 프로그램

 

환불요청합니다. 기업이지만, 소비자가 빠져나갈때 이유라도 확인해주시길 바랍니다.

개발에 수고 많으시지만, 저도 더이상 이런 저런 시간낭비를 줄이고 싶네요.

이정도로 충분합니다. 

 

감사합니다..

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

이지앤라이트 개발사측에서 통영으로 차타고 오겠다는 겁니까.

문제를 일으킨 개발자가 책임을 지는게 상식인데, 어디서 피해본 소비자보고 오라가라는겁니까 ?

이런식으로 모든 문제를 소비자한테 떠넘기면서 사십니까.

 

돈 지불한 고객한테 개발사가 어디서 오라가라 갑질을 하지.

저급한 갑질은 밖에서 하지말고, 집에서 가족한테나 하시면 되겠고.

이지앤라이트 대응하는 수준이 저~기 삼류기업에도 못미치는거 아시길 바랍니다.

 

메일로 보낸 불법적 경로 파일을 설치하고 싶은 생각 없습니다.

불법으로 태블릿에 넣어줄테니까 통합 12시간 걸리는 서울로 오라고 당당하게 말합니까.

양심이 거덜난 몰상식한 갑질 발언을 제게 하지 말길 바랍니다. 

 

소비자들은 쌩돈내고 사용도 못하고, 해결방법도 없고, 

"불따해줄테니 서울오라"고 하등한 갑질에 이딴 메일로 시간낭비에 

역지사지 피해자 입장을 생각하는건 기본입니다.

 

본인 말마따나 불법다운로드가 최선이면 

서울시 금천구 가산디지털단지지역 근처에서 당장 통영으로 버스든 차를 타고 오시고,

하루 거덜나고 차비,밥값 20만원 넘게 나오니 알아서 돈 내시면 됩니다.

불법 설치 해주고 간다는건데 피해본 소비자 보고 오러가라 갑질을 하니 우습기 짝이 없고. 

문제상황 해결도 못하고, 책임도 미루고, 개발사가 이래저래 환불 미루는거보니 돈도 없나 싶습니다.

 

수십번 얘기하게 하지맙시다.

EL 디스플레이 허브로 로그파일 보냈다고 몇번 말하면 알아듣습니까 ? 

한낱 로그파일 메일 회신도 안되는걸 제작한게 누굽니까 ? 이지앤라이트 개발자입니다. 

프로그램이 결함이 많은데 인정이나 납득이 잘안되시는것 같은데, 개발자면 부끄러운줄 아십시요.

 

1. 합법적으로 다운 그레이드를 시켜서 사용이 가능케 하거나 아니면 2. 환불 하시면 됩니다. 

이전버전 환불이 구글 플레이로 어려우면 제 계좌로 환불하십시요. 바득바득 핑계대지 마시고.

 

 김소윤 .  새마을금고 9003 2574 0908 6 

 

환불로 결론이 나있는데, 계좌찍으라 하면 되지 뭔 말을 빙빙 돌려댑니까.

사과 ,변명 '서울로 오라가라' 저열한 갑질 메일로 구질구질하게 굴지 마시고,

남한테는 환불이란 책임만 지시면 됩니다.  

 

어떤 정신나간 인간이 개발자님 제안대로

불법으로 옛날 버전 앱 설치한답니까. 그거 하러 서울간답니까.

소비자 엿먹이고 싶은 마음을 정성스럽게 적어서 메일로 함부로 보내지 마십시요.  

본인 얼굴에 침뱉는거고, 이런식으로 살면 망하는건 일순간입니다. 그렇게 살지 맙시다.  

기본 인성과 소양 좀 갖추며 살아갑시다. 이지앤라이트 개발자님.  양심에 화인맞은 행동하지 맙시다.

 

환불 후 좋은 하루 보내시고, 건강하십시길 바랍니다.

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

-----

안녕하세요 고객님. Easy&Light 개발팀입니다.

현재 문의했던 내용의 경우 연결 불가 상태이며, 해당 문제는 다양한 원인으로 발생할 수 있기 때문에 상태 확인을 위해서는 로그 파일이 필요합니다.
또한 원격 지원의 경우 로그를 바탕으로 사용자 환경과 증상이 파악되어야 진행이 가능합니다.
현재 보내신 이미지를 기반으로 원인 파악한 결과 설치과정 중 문제가 발생하여 드라이버와 일부 프로그램이 정상적으로 설치되지 않은 것으로 보이며, 아래의 설명대로 재설치 부탁드립니다.
[재설치 절차]
1. EL Display Hub를 삭제합니다.2. PC 재부팅합니다. (종료 옵션의 "다시 시작" 사용)3. 최신 EL Display Hub 인스톨러를 재설치합니다.[EL Display Hub] 설치 링크 : http://www.easynlight.com/twomonse/4. EL Display Hub를 재설치합니다.5. 증상을 확인합니다.

현재 PC 프로그램의 문의하기와 이메일의 첨부 파일에는 로그파일들이 접수되지 않았습니다.
PC 측 프로그램의 문제로 보이니 문제 해결을 위해서 아래의 방법대로 수동으로 PC의 로그와 태블릿 측의 어플리케이션 로그를 추출해서 이메일 회신시 첨부하여 보내주시길 바랍니다.

[로그 수동 수집 절차]
1. Windows키 입력 > "실행" > "msinfo32" 입력 > 파일 > 저장2. C:\ProgramData\devguru 경로에 존재하는 파일3. C:\Users\{사용자명}\AppData\Local\Devguru 경로에 존재하는 파일 ( %localappdata%\Devguru 로 경로에 접근 가능)

[앱 로그 추출 방법]
1. 로그를 추출할 기기에서 App을 재실행 합니다.2. 메인 화면 하단 오른쪽에 표시되어 있는 앱 버전을 약 10번 터치하여 TwomonSE.log.archived.yyyymmddhhmmss.zip이 Download 폴더에 생성됩니다.3. 안드로이드 기기의 Download 포더에 생성된 압축파일을 첨부하여 주십시오.

또한 환불의 경우 Google Play Store를 통해 환불을 진행하게 되는데 구매일로부터 일정 기간 이상 지난 제품의 경우 저희에게 권한이 없어 환불이 진행에 도움 드릴 수 있는 부분이 없습니다. 이 경우 사용자가 직접 구글 측에 문의하셔야 합니다. 

감사합니다.
Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 로그파일을 전달하였습니다.

----

연결안되요

로그파일 보냅니다

[Devguru.zip](https://github.com/edh-git/EL_Display_Hub/files/8093115/Devguru.zip)



----

한 번 더 시도 하고 로그파일 다시 수집해서 보냈는데

문제 원인을 아셨는지 모르겠지만 

 

재설치 방법대로 해도 똑같이 안됩니다
[Devguru (1).zip](https://github.com/edh-git/EL_Display_Hub/files/8093120/Devguru.1.zip)


-----

제목: 로그파일 수집해서 보내는데, 삭제하고 재시작재설치해도 문제상황은 똑같습니다

문의사항: 로그파일 수집해서 보내는데,
삭제하고 재시작재설치해도 문제상황은 똑같습니다

피씨랑 앱 로그를 보냅니다 - > 해결방법 or 환불

감사합니다.

[[TwomonUSB_-_Windows]_로그파일_수집해서_보내는데,_삭제하고_재시작재설치해도_문제상황은_똑같습니다.zip](https://github.com/edh-git/EL_Display_Hub/files/8093124/TwomonUSB_-_Windows._._._._._._._.zip)



----



PC 로그  + APP 로그 파일 두개이고요 ! 

해결방법 or 환불 감사요 

 

재설치 방법대로 정석으로 해도 안되요


[PC_로그__+_APP_로그_파일_두개이고요_!_해결방법_or_환불이요.zip](https://github.com/edh-git/EL_Display_Hub/files/8093125/PC_.__%2B_APP_._._._._._or_.zip)

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 메일을 보내왔습니다.

----- 

왜 답변 안보내시나요, 문제 해결 방법 아직도 못찾으셨나요 

[왜_답변_안보내시나요,_문제_해결_방법_아직도_못찾으셨나요.zip](https://github.com/edh-git/EL_Display_Hub/files/8106455/_._._._._._._.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 부탁드립니다.
```
안녕하세요 고객님. Easy&Light 개발팀입니다.

새롭게 보내주신 로그를 확인한 결과 요청 드린 로그 파일 전체가 제대로 포함되지 않았으며, 확인된 로그 상에서는 설치 과정 중 드라이버가 제대로 설치되지 않은 문제가 확인되었습니다.

우선, 수동 로그 수집을 위한 방안을 좀 더 상세하게 안내해드리겠습니다.

[로그 수동 수집 절차]
1. 바탕 화면에 "EL수동로그파일" 폴더 생성
2. Windows 검색 > "시스템 정보" 검색 및 실행 > 좌측 상단의 메뉴의 "파일" 클릭 > "저장" 클릭 > 바탕 화면의 "EL수동로그파일" 폴더에 "시스템 정보 파일"로 이름을 설정하여 저장
3. C:\ProgramData\devguru 폴더 복사 > 바탕 화면의 "EL수동로그파일" 폴더에 붙여넣기 > 해당 폴더를 "ProgramData"로 폴더명 변경
4. C:\Users\{사용자명}\AppData\Local\Devguru 폴더 복사 ( 윈도우에서 %localappdata% 를 검색해서 경로에 접근 가능) > 바탕화면의 "EL수동로그파일" 폴더에 붙여넣기 > 해당 폴더를 "LocalAppdata"로 폴더명 변경
5. "C:\Windows\INF\setupapi.app.log"에 해당 하는 파일을 복사 > 바탕화면의 "EL수동로그파일" 폴더에 붙여넣기 (드라이버 관련 로그를 추가로 수집합니다.)
6. 바탕화면의 "EL수동로그파일" 폴더를 압축합니다.
7. 이메일로 "EL수동로그파일" 압축 파일을 회신하여 주십시오.


추가적으로, 현재 로그 상으로 파악된 문제를 설명드리겠습니다.

Twomon SE가 동시에 설치된 적이 있어 보입니다. 기존 PC 프로그램인 "Twomon SE" PC프로그램과 통합 PC 프로그램인 "EL Display Hub"가 동시에 설치된 경우 충돌이 발생할 수 있습니다. 기존의 "Twomon SE" PC프로그램을 제거하여 주십시오.

또한 드라이버의 경우 윈도우즈 업데이트 도중 손상되거나 충돌이 발생할 수 있습니다. Windows를 최신 버전으로 업데이트하여 주십시오.


위 두 가지 문제를 해결하신 뒤 정상적으로 설치하기 위해 저번에 안내해드린 방법대로 재설치 부탁드립니다.

[재설치 절차]
1. EL Display Hub를 삭제합니다.
2. PC 재부팅합니다. (종료 옵션의 "다시 시작" 사용)
3. 최신 EL Display Hub 인스톨러를 재설치합니다.
[EL Display Hub] 설치 링크 : http://www.easynlight.com/easycanvas/
4. EL Display Hub를 재설치합니다.
5. 증상을 확인합니다.


또한, 환불 문의의 경우 다시 안내해드리면 Google Play Store를 통해 환불을 진행합니다.
구매일로 30일이 지난 제품의 경우 저희에게 권한이 없어 환불이 진행에 도움드릴 부분이 없습니다.
관련 사항은 Google Play Store 측에 문의 바랍니다.

감사합니다.

Easy&Light
```

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


안녕하세요 고객님. Easy&Light 개발팀입니다.

새롭게 보내주신 로그를 확인한 결과 요청 드린 로그 파일 전체가 제대로 포함되지 않았으며, 확인된 로그 상에서는 설치 과정 중 드라이버가 제대로 설치되지 않은 문제가 확인되었습니다.

우선, 수동 로그 수집을 위한 방안을 좀 더 상세하게 안내해드리겠습니다.


[로그 수동 수집 절차]
1. 바탕 화면에 "EL수동로그파일" 폴더 생성
2. Windows 검색 > "시스템 정보" 검색 및 실행 > 좌측 상단의 메뉴의 "파일" 클릭 > "저장" 클릭 > 바탕 화면의 "EL수동로그파일" 폴더에 "시스템 정보 파일"로 이름을 설정하여 저장
3. C:\ProgramData\devguru 폴더 복사 > 바탕 화면의 "EL수동로그파일" 폴더에 붙여넣기 > 해당 폴더를 "ProgramData"로 폴더명 변경
4. C:\Users\{사용자명}\AppData\Local\Devguru 폴더 복사 ( 윈도우에서 %localappdata% 를 검색해서 경로에 접근 가능) > 바탕화면의 "EL수동로그파일" 폴더에 붙여넣기 > 해당 폴더를 "LocalAppdata"로 폴더명 변경
5. "C:\Windows\INF\setupapi.app.log"에 해당 하는 파일을 복사 > 바탕화면의 "EL수동로그파일" 폴더에 붙여넣기 (드라이버 관련 로그를 추가로 수집합니다.)
6. 바탕화면의 "EL수동로그파일" 폴더를 압축합니다.
7. 이메일로 "EL수동로그파일" 압축 파일을 회신하여 주십시오.



추가적으로, 현재 로그 상으로 파악된 문제를 설명드리겠습니다.

Twomon SE가 동시에 설치된 적이 있어 보입니다. 기존 PC 프로그램인 "Twomon SE" PC프로그램과 통합 PC 프로그램인 "EL Display Hub"가 동시에 설치된 경우 충돌이 발생할 수 있습니다. 기존의 "Twomon SE" PC프로그램을 제거하여 주십시오.

또한 드라이버의 경우 윈도우즈 업데이트 도중 손상되거나 충돌이 발생할 수 있습니다. Windows를 최신 버전으로 업데이트하여 주십시오.


위 두 가지 문제를 해결하신 뒤 정상적으로 설치하기 위해 저번에 안내해드린 방법대로 재설치 부탁드립니다.



[재설치 절차]
1. EL Display Hub를 삭제합니다.
2. PC 재부팅합니다. (종료 옵션의 "다시 시작" 사용)
3. 최신 EL Display Hub 인스톨러를 재설치합니다.[EL Display Hub] 설치 링크 : http://www.easynlight.com/easycanvas/
4. EL Display Hub를 재설치합니다.
5. 증상을 확인합니다.

또한, 환불 문의의 경우 다시 안내해드리면 Google Play Store를 통해 환불을 진행합니다.
구매일로부터 오랜기간 지난 제품의 경우 저희에게 권한이 없어 환불 진행에 도움 드릴 수 있는 부분이 없습니다. 관련 사항은 Google Play Store 측에 문의 바랍니다.

감사합니다.

Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

시스템 정보 보내는건 해킹하겠다는 뜻이잖아요 

왜계속 시스템 정보 로그를 달라고 하나요

 

로그 보냈잖아요 댁이 달라는걸로

프로그램 로그만 보고 해결을 해야지

 

왜 제 컴퓨터 시스템 정보를 보내라고 난리예요

 

장난하세요 ?

**Comment by Sienna-lee** [comment]
해당 이슈는 추후 분석이 가능한 로그파일이 올 경우 처리하는 것으로 정리하도록 하겠습니다.

**Comment by Sienna-lee** [comment]
해당 사용자가 로그파일을 보내왔습니다.

----
[EL수동로그파일.zip](https://github.com/edh-git/EL_Display_Hub/files/8121151/EL.zip)

**Comment by Sienna-lee** [comment]
해당 사용자가 로그파일을 보내왔습니다.
----
[EL수동로그파일 (1).zip](https://github.com/edh-git/EL_Display_Hub/files/8121154/EL.1.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변부탁드립니다.
```
안녕하세요 고객님. Easy&Light 개발팀입니다.

보내주신 로그와 증상을 검토한 결과, 타 프로그램과의 충돌 문제 및 드라이버 설치 실패 문제를 발견하였습니다.

EL Display Hub의 경우 화면 공유 프로그램이나 화면 캡처 혹은 녹화 기능이 있는 프로그램과 함께 사용할 경우 충돌이 발생할 수 있습니다.

현재 설치된 프로그램 중 몇 가지 충돌하는 프로그램을 확인하였습니다. (추가로 비슷한 동작이나 위의 기능을 사용하는 프로그램이 있을 수 있습니다.)
"Duet Display", "Spacedesk", "Superdisplay", "XDisplay" 등은 비슷한 동작을하며 OS와 하드웨어에서 EL Display Hub와 충돌이 발생할 수 있습니다.
또한 "Duet Display"와 "Superdisplay"의 경우 안드로이드 기기의 연결 시 자체 프로토콜을 사용하여 타 프로그램이 안드로이드 기기가 연결 시도조차 하지 않는 문제가 발생합니다.

우선 해당하는 프로그램들과 "EL Display Hub"를 삭제하신 뒤 PC를 재부팅하신 뒤 "EL Display Hub"의 새로운 인스톨러를 다운로드 받아 재설치하여 주신 뒤 연결 상태를 확인 부탁드립니다.

[EL Display Hub] 설치 페이지 : http://www.easynlight.com/twomonse/


또한 추가적으로 드라이버의 설치 시 다양한 원인으로 오류가 발생할 수 있습니다. 기존의 타 드라이버(위의 충돌 발생을 유발하는 프로그램일 확률이 높습니다.)와 충돌이 발생하거나, OS 측의 오류로 설치가 실패할 수 있습니다.

재설치하는 경우 대부분 문제가 해결되며, 재설치 이후에도 동일한 문제가 발생하는 경우에는 윈도우를 최신 윈도우로 업데이트 진행 후 재설치 부탁드립니다.

위와 같은 조치사항들을 진행하시고도 문제 사항이 개선되지 않으신다면 조치사항이 적용된 뒤의 로그를 확인하기 위하여 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

추가적으로 드라이버 설치 시 로그를 확인하기 위하여 "C:\Windows\INF" 경로의 "setupapi"로 시작하는 파일들을 함께 보내주시길 바랍니다.


감사합니다.

Ea​​sy&Light 
```

**Comment by Sienna-lee** [comment]
해당 사용자에게 위와 같이 회신하였습니다.

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

"Duet Display", "Spacedesk"는 설치자체가 안되있는 프로그램입니다. 
설치가 안되있는데 프로토콜을 사용한다는게 이해가 안되는군요.
"Superdisplay"는 삭제를 하였고

"XDisplay" 는 투몬이 안되서 설치한 임시로 사용하는 프로그램입니다.
그리고 얘는 나중에 이메일 주고받은 후 한참나중에 설치한거고 
투몬이랑 충돌이 안되고 잘만되던데 
투몬은 먼저설치한건데도 아예 안되네요

그리고 윈도우업뎃은 그저께인가 새로 싹다 했고요

일단 현재 문제해결을 도모해보고 안되면 바로 연락하겠습니다

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

이보세요

 

그 방법으로 다 해봐도 뭐 삭제할것도 없지만

해봐도 프로토콜에 잡히지도 않고

작업관리자창이나 서비스에 떠있는 프로그램들도 없고

 

충돌거리는데

EL 프로그램자체가 설치를 하고 폰을 연결을 안해도 

바로 뜨는게 에러창 2개인데 뭔소리를 하는거예요

 

구글플레이에 다 그렇게 별점 1개에

안된다고 하는데 해결방법으로도 안되거든요 

 

쓰레기같은 프로그램 환불이나 하세요 진짜 스트레스받게

몇십번을 설치하게 만드는건지

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 추가로 메일을 보냈습니다.

----

오랜만이네요
​
밝은 오늘을내일을 살아가고 계신건지
아나면 그런 희망을 못본채 계신지
따스한 봄은 왔습니다 매화꽃이 풍년이지요
​
이틀전 테스트해봤는데
투몬은 아직도 마치 전기가 차단된
녹슬었지만 간판만은 건재한 발전소마냥
그 기능을 잃어버린채 존재하고 있습니다
​
역시나도
여차부차 예전에
보내신 메일로도
단 0.01%의 문제해결도 이뤄내지 못했습니다
​
투몬이 안되서 이멜을 주고받고
잡다한 시간낭비 감정소모 후에 깐 또다른 미러링 앱은
10분간 무료로 쓸수있어
가뭄속 단비역할을 해냅니다
​
투몬과 다른앱 충돌로 합리화하고 싶으신
개발자 맘은 이해하지만
그것 또한 거짓에 해당합니다
​
예전 문제는 녹슨채 그대로 변함이없고
폰연결 하던 말던 허구한날 
같은 에러문구가 뻔히 뜨는건
새벽 황혼에 뜨는 아침해마냥 늘 똑같은 일입니다
​
귀하도 컴터를 좀 다루지만
말도 안되는 핑계는 사실 통하지 않습니다
애플 봉쥬르 항상 핑계는 대자면
언제든 그럴듯한 영어가 필수지요
​
사람이라 인간된 도리로써
예의란 기준을 가지고
이지앤라이트 개발자를 대하는데
​
문제해결에 대한 묵묵부답도
그대는 어차피 현재에 속한일일뿐
시간이 지나고 나면 다 잊혀지겠지싶어
얼렁뚱땅 유야무야 넘어가고 싶은 맘은
이해하나
​
허나 그럴수록
양심에 멍이드니
양심의 기능이 어떨지 잠시 생각해보시죠
​
양심
현대인들이 잊고 살기 쉽지만
실상 잊어선 안될 단어
​
이지앤 라이트 개발자님
금전적 여유가 된다면 저를비롯한
피해자분들에게 환불 요청하는 바요
​
남의 한두만원
아무것도 아닌것 갖지만
​
양심
책망
죄책감
책임
신뢰
​
안보면그만
넘기면그만
환불걍안해
​
현재는 2022년
지금이 기록되고 기억되고 있다면 그냥 넘기시겠나요?
 
귀하와 나의 위치는 사람입니다.
양심도 있고
잘못하면
뒤바꿀 기회란게 존재합니다
​
​
만원쪼가리를 낸 피해자들
마음과 물질적 피해
그냥 사라지는 한낱 티끌로 생각치마십시요
​
그 티끌도
양심에겐 큰 것입니다
​
양심에 쌓인먼지 훌훌 털며 살아가면
매부좋고 누이좋고 너도좋고 나도좋고지만
​
남한테 손해라는거
쉽게 끼치며 살아가도
별거 아닌것 같지만
​
만원 한장이 우스워
가해자도 피해자고
그래서 단순히들 살아가지만
​
양심을 저버린다는게
티끌을 가벼히 여기며 길고짧은
인생 100년을 살아가는게
좋은게 아니란 말밖엔 드릴 말씀이 없군요.
​
사람의 수명은 고작해야 100년
​
정직하면 보상을 받습니다.
​
결론은 정직하자.
양심적으로 살면된다.
​
​
​
양심과 정직.
​
​
이 두단어는 사람을 사람답게 만드는 단어입니다
​
​
그럼 씁쓸한 밤
양심과 정직은 새겨보시며
​
행복한 잠을 주무시고
밝은 하루를 내일도 보내시길 바랍니다.
​
​
​
​
​
​
​
-티끌의 마음-
​

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


안녕하세요. Easy&Light 지원팀입니다.

앱 업데이트로 인해 제품 이용에 불편을 드려 죄송합니다.

구글을 통한 환불이 불가하여 계좌를 통해 환불해드리고자 하오니 환불 받으실 계좌번호를 남겨주시면 해당 계좌로 앱 구매금액을 입금해드리도록 하겠습니다. 

해당 환불은 계좌를 통해 이루어지므로 기존에 구매한 앱은 환불처리가 되지 않아  사용이 가능합니다. 이후 다른 환경에서 다시 한번 사용해보시기 바랍니다. 

다시 한번 제품 이용에 불편을 드려 죄송합니다.

Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자의 금융 계좌로 제품 비용을 환불하였습니다. 해당 이슈를 종료합니다.
