### ISSUE TITLE
AMDS 경고창 표시

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#731]
- 문의 날짜 : 2022년 2월 13일 오후 5시 23분
- 메일 주소 : fanyingjiyun@foxmail.com

开发者你好：
   在使用你们软件的过程中我遇到了一个问题，每次我在电脑上启动ELDisplay的时候都会弹出来一个提示，amds服务有问题，虽然分屏仍然能够运行，但是很让我很烦，希望可以修复一下这个问题。我的ipad是ipad2018，PC是Windows，ipad和PC的软件都是最新版本。日志文件没有找到
hello developer:
  I meet a problem when I use your application,everytime I boot ELDisplay,he alaways display a warning,some problem happens to amds service.Although the application runs normally,the warning makes me annoyed,I hope you can fix this problem.My ipad is ipad2018,pc is windows,ipad and pc's software is lastest version.I can't find the log file.(maybe it is in the ipad?)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


Hello, customer. We are an Easy & Light support team.

I'm sending this email for your inquiry.


Could you please send me the log file so the tech team can check your problem?

Receives inquiries through EL Display Hub's [Support] - [Inquiry]



If it is impossible, extract the log file and send it to us by the method below.



[Manual log collection procedure]


1. Windows Key > "Run" > Type "msinfo32" > File > Save

2. Files existing in the path C:\ProgramData\devguru

3. A file existing in the path C:\Users\{username}\AppData\Local\Devguru (you can access the path with %localappdata%\Devguru)


Please zip the above three files and attach them.


If you send us the log file, our technical team will check the problem and send you a solution.

Thank you.

Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----


好的，这是我的电脑信息
OK,this is my computer information

[feedback.zip](https://github.com/edh-git/EL_Display_Hub/files/8064706/feedback.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변하였습니다.
```
Hello, customer. Easy&Light support team.

First of all, we apologize for the inconvenience.

After reviewing the logs and symptoms you sent us, it appears that there is a conflict with iTunes.

For AMDS, it is a module required to connect iPad and PC.
It was installed together with the existing iTunes for Windows and operated independently, but in the case of iTunes from the MS Store, it is included and works.
Because of this, normal operation may fail.

Please install iTunes for Windows to solve this problem.
1. Delete iTunes and EL Display Hub from MS Store.
2. Please reinstall EL Display Hub.
3. Please use iTunes for Windows.
[Apple] Downloading and using iTunes for Windows: https://support.apple.com/en-us/HT210384


If the problem does not improve even after taking the above measures,
Please refer to the log acquisition guide below and ask again with the application log.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Easy & Light
```

#### 한글 원문
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

고객님께서 보내주신 로그와 증상을 검토한 결과 iTunes와 충돌이 발생하는 것으로 보입니다.

AMDS의 경우 ipad와 PC를 연결하기 위해 필요한 모듈입니다. 
기존의 Windows용 iTunes와 함께 설치되어 독립적으로 동작했지만,  MS Store의 iTunes의 경우 내부에 포함되어서 동작합니다. 
때문에 정상 동작에 실패할 수 있습니다.

해당 문제를 해결하기 위해 Windows용 iTunes를 설치하여 주시길 바랍니다.
1. MS Store의 iTunes와 EL Display Hub를 삭제하여 주십시오.
2. EL Display Hub를 재설치하여 주십시오.
3. Windows용 iTunes를 사용하여 주시길 바랍니다.
[Apple] Windows용 iTunes 다운로드 및 사용하기 : https://support.apple.com/ko-kr/HT210384


위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면,
아래의 로그 취득 가이드를 참조하여 어플리케이션 로그와 함께 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/en/supporteasycanvas/?faq=54

감사합니다.

Ea​​sy&Light 
```
