### ISSUE TITLE
[QA, TEST용 메일]

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#743]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:[QA, TEST용 메일]<br><br>확장 화면 버튼이 없음<br><br>[EL_Display_bdd456c3-67a8-4c70-8c3b-a650e2b05a83.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_bdd456c3-67a8-4c70-8c3b-a650e2b05a83.zip)

**Comment by jeffrey-Devguru** [comment]
테스트용 이슈입니다. 종료합니다.
