### ISSUE TITLE
TEST-LOG-TEST

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#744]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:smkim<br><br>TEST<br><br>[EL_Display_7907f475-b813-434f-b6ab-906deb27a901.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_7907f475-b813-434f-b6ab-906deb27a901.zip)

**Comment by kimdynne** [comment]
테스트용 이슈로 종료합니다.
