### ISSUE TITLE
Apple Pencil Tilt

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#751]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:spacegamerfury@gmail.com<br><br>Is possible to use apple pencil tilt function with easy canvas and if not it will be available some time?<br><br>[EL_Display_dcc94e6f-6030-4611-8403-006e7511be80.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_dcc94e6f-6030-4611-8403-006e7511be80.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. Easy&Light support team.

We will reply to your inquiry by e-mail.

EasyCanvas supports not only Apple Pencil tilt, but also pen pressure and palm rejection.
It supports the pressure and tilt functions using the "Windows Ink" API. 
Therefore, the values of the pressure and tilt are only applied successfully with graphical tools that support the Windows Ink API.


Thank you.
Easy & Light
