### ISSUE TITLE
연결 시 latency 문제

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#766]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:songmh0503@gmail.com<br><br>이전에 비해 레이턴시가 심하게 생기는데(와이파이 연결의 경우) 혹시 이 부분 추후 개선될 여지가 있을까요?<br><br>[EL_Display_64895901-2aec-4701-8875-1b806fe44cb7.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_64895901-2aec-4701-8875-1b806fe44cb7.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변하였습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

문의 해주신 무선 환경에서의 레이턴시의 경우 아래와 같이 네트워크 환경을 체크해주시길 바랍니다.

[인터넷 연결 상태 확인]
    1) 아이패드나 PC가 공유기의 연결 상태가 불안정한 경우 무선 통신에 실패하거나 불안정할 수 있습니다.
    2) 아이패드와 공유기를 가까이 위치하여도 동일한 문제가 발생하는지 확인부탁드립니다.
    3) 원활한 통신을 위해서는 무선 네트워크는 가능한 5ghz 대역을 이용바랍니다.
    4) PC 측의 네트워크를 유선 네트워크(이더넷)으로 연결하여 이용합니다.

위와 같은 조치사항을 진행하시고 동작을 확인하여 주시길 바랍니다. 

감사합니다.

Easy&Light
```
