### ISSUE TITLE
권장 해상도 문의

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#769]
- 문의 날짜 : 2022년 2월 18일 오전 10시 14분
- 메일 주소 : jangwookim@icloud.com

Title: 권장 화면 해상도 값, 선명도

Questions: 투몬SE 윈도우 11, 아이패드 3세대 12.9인치 사용자 입니다.

권장 해상도로 사용시 보조 모니터 (아이패드) 상 글자가 뭉개져 보입니다. 여러 세팅을 시도해 봤는데, 선명하게 글자를 볼 수 있는 세팅 못 찾았습니다.

화면상 글자를 좀 더 또렷하게 볼 수 있는 세팅값이나 별도 유틸리티가 있으면 안내 부탁합니다.

별도로, 권장 세팅이 아닌 더 큰 화면 값으로 세팅헤서 사용하던 중 (예: 2390*1792, 200%) 잠자기에서 깨우면 특정앱 (크롬 등) 의 200% 배율이 깨지는 경우가 있었습니다.

고맙습니다.

![IMG_20220218_091130](https://user-images.githubusercontent.com/77039816/154599019-a526b9ac-1844-469e-8d71-4b4ddabff66d.jpg)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변하였습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

EL Display Hub PC프로그램의 권장 해상도의 경우 기기 성능과 실시간 연결을 위한 반응성 등을 종합적으로 고려하여 타협한 설정입니다.

해상도 옵션의 최대 크기가 실제 연결된 태블릿의 해상도이며, 해당 해상도 이하에서는 실제 표시되는 태블릿의 해상도보다 캡쳐된 이미지의 해상도가 낮아서 화면 및 글자가 뿌옇게 보이는 증상이 보일 수 있는 한계점이 존재합니다.
따라서, 화면의 시인성은 태블릿의 실제 해상도인 최대 해상도로 사용하시는 것이 가장 좋습니다.

화면상의 글자를 좀 더 또렷하게 볼 수 있는 방법으로는 윈도우의 기능인 ClearType을 사용하시는 것을 추천드립니다.
ClearType은 "Windows 검색 - ClearType - ClearType 텍스트 조정"을 통해 실행될 수 있으며, 프로그램 안내에 따라서 설정하시는 것을 추천드립니다.

추가적으로 문의하신 화면 배율을 200%로 설정하는 경우 특정앱(크롬 등)의 배율이 깨지는 경우는 Windows OS의 화면 확장 과정 중의 앱과의 충돌로 의심됩니다. 
해당 문제는 개별 앱과 Windows의 설정을 확인해보셔야 할 것으로 보입니다.

추가적인 문의사항이 있으신 경우 재문의 해주시길 바랍니다.
감사합니다.

Ea​​sy&Light 
```

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.
----

답변 감사합니다, 확실한 효과 있었습니다.

FAQ에 포함해 주시면 좋겠습니다.
