### ISSUE TITLE
Mac 사용 권한 관련 문의 

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#770]
- 문의 날짜 : 2022년 2월 18일 오후 1시 43분
- 메일 주소 : gaeaearth@gmail.com

제목: 맥에서 사용시 권한을 안 물어봅니다.

문의사항: 맥에서 갤탭을 이용하여 이지캔버스를 사용하고 있는 사용자입니다.
1. 다른 맥에 이지캔버스 프로그램을 설치하고 갤탭과 연결하려는데 안되어서 살펴보니 맥쪽의 이지캔버스 프로그램이 권한 요구 메세지를 띄우지 않아서였습니다. 각기 다른 맥북 두대에 설치해보았는데 둘 다 물어보지 않는걸 봐서는 프로그램 자체의 버그로 보입니다. 제어권한에 대한 것인 손쉬운 사용의 경우 사용자 임의 추가가 가능하지만 화면기록은 프로그램에서 요구하지 않으면 일반적인 방법으로는 추가가 안됩니다... 맥쪽에도 내주면 고맙긴한데 출시 후 제대로 작동하는 지 정도는 좀 제대로 체크를 해주시면 좋을 것 같네요. 아니면 FAQ에라도 권한 추가 방법을 넣어주시던가요.
참고로 손쉬운사용에 수동으로 이지캔버스를 추가하고 연결을 하니 화면기록에 대한 권한 요구가 떠서 추가하는 방식으로 해결하였습니다.
2. 그리고 contact us에 사용기기에 안드로이드 기기도 추가 좀 해주세요...
3. 맥용 이지캔버스 프로그램에서 로그생성 버튼 누르고서 브라우져 띄우는 것 좀 없애주세요...쓸데없이 왜 띄우나요. 아니면 최소한 띄울 지 물어보던가요.

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 부탁드립니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

[Easycanvas] 소개 페이지 : http://www.easynlight.com/easycanvas/

Easycanvas 소개 페이지의 "Easycanvas 제약사항"의 3번항목과 같이
현재 MacOS 환경에서는 "iOS - 1회 구매" 앱만 사용이 가능하며, 
Easycanvas 안드로이드의 경우 공식적으로 지원하고 있지 않습니다.


현재 문의해주신 사항 중 Easycanvas 설치 과정 중 "손쉬운 사용"과 "화면 기록"에 대해서 등록을 시도합니다. 
하지만 해당 동작이 제대로 동작하지 않았다고 하셔서 원인을 파악 중이며, 수정하도록 노력하겠습니다.

또한 Contact Us의 "Android" 추가 및 로그 생성 이후 웹 브라우저를 통한 
Contact us 페이지로 이동하는 사항에 대해서는 기획팀으로 의견을 전달하다록 하겠습니다.


현재 공식적으로 지원되지 않는 버전이며, 환불을 원하시면 아래 내용을 참고해주세요.

[환불 가이드]
1. Playstore for Android
하단의 링크로 접속하시어 필요한 내용을 기입 후 제출해주시면 확인하여 환불 절차를 진행해드리겠습니다.
[Android] Twomon SE/TwomonAir/TwomonUSB 환불 요청서 : 
https://docs.google.com/forms/d/1wFxbQS5wg3u1QbMLG_ZQDM2ExNbDHC9xraPje5_hBbo/edit?urp=gmail_link

2. App Store for iOS
애플 앱스토어에서 판매되는 앱은 모두 애플에서 관리합니다. 
저희는 고객님의 구매 정보를 가지고 있지 않기 때문에 애플리케이션 환불을 진행할 권리가 없습니다. 
아래 링크를 참조 부탁드립니다.

Apple Support 사이트 링크 :
https://reportaproblem.apple.com/﻿

﻿iTunes store 에서 환불 받는 방법 :
https://support.apple.com/ko-kr/HT204084

감사합니다.

Ea​​sy&Light 
```

**Comment by Sienna-lee** [comment]
해당 사용자에게 위와 같이 답변완료하였으며, 아래 참조사항은 @Juilliardsong 에게 전달하도록 하겠습니다.
