### ISSUE TITLE
업데이트 버전에서의 보조 모니터 사용법

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#772]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:lifezone90@gmail.com<br><br>투몬을 구입해서 잘 쓰고 있었는데 업데이트 된 이후로 화면분할이 되지 않습니다. 아이패드에 노트북 화면이 미러링이 될 뿐 불할된 보조 모니터로 활용이 어렵게 되었습니다. 이리저리 앱을 조작해봐도 화면 분할이 되지 않는데 사용법을 좀 알려주시면 좋겠습니다.<br><br>[EL_Display_8bbb2418-cf06-495f-bcbb-a2c1e7b86fd8.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_8bbb2418-cf06-495f-bcbb-a2c1e7b86fd8.zip)

**Comment by Sienna-lee** [comment]
화면 확장이 안되는 것인지 단순 방법문의인지 확인 어려워 로그파일 확인 후 문제가 없을 경우 PC 프로그램 사용 가이드를 전달하도록 하겠습니다.

**Comment by AdamPark0030** [comment]
아래와 같이 답변 완료 했습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

아래의 방법을 통해 확장 화면을 활성화 해보시길 바랍니다.

1. Windows + P 키를 통해 프로젝트 설정을 확장 또는 extend로 변경
[Twomon SE 확장/복제 화면을 사용하려면 어떻게 해야하나요?] : http://www.easynlight.com/supporttwomon/?faq=129

2. EL Display Hub PC 프로그램에서 가상 디스플레이를 선택 
[PC 프로그램 사용가이드] : https://blog.naver.com/easynlight/222626582372

조치를 취한 후에도 문제가 지속된다면 아래의 로그 취득 가이드를 참조하여 어플리케이션 로그와 함께 EL Display Hub의 문의하기 기능을 통해서 재문의 부탁드립니다.
[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

Ea​​sy&Light 
``
