### ISSUE TITLE
Screen extension not working

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#773]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:jacek.mitsch@gmail.com<br><br>Hi, so im trying out your app as the screen extension got me a bit excited. Unfortunately i cant get it to extend; only replicate. When my ipad (ipad pro 2021) first connects, i do get an &quot;extend&quot; option, but when i click on it nothing happens, and the option disapears after. Could you help?<br><br>[EL_Display_9e250747-1f50-4dbe-8359-ae60b05db296.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_9e250747-1f50-4dbe-8359-ae60b05db296.zip)

**Comment by AdamPark0030** [comment]
아래와 같이 답변 완료 했습니다.

```
Hello, customer. We are an Easy & Light support team.

First, we apologize for the inconvenience in using it.

Please activate the extended screen through the method below.
1. Change project settings to extend via Windows + P key.

2.  Select "Extend" on Select Screen option

3. If "Extend" option is not exist, retry windows + P key and select extend

If the problem persists after taking action, please refer to the log acquisition guide below and inquire again through the EL Display Hub's inquiry function along with the application log.

[FAQ] Log acquisition guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Easy&Light
```
