### ISSUE TITLE
디스플레이 확장이 안됨

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#775]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:aeternuslsi@gmail.com<br><br>디스플레이 설정에서 1. 디스플레이1, 2. 확장 을 선택할 수 있고, 확장을 선택하면 되는듯하더니 확장 메뉴가 사라지고, 화면 복제밖에 안됩니다 ㅠ<br><br>[EL_Display_6b779794-4615-4b84-bfa0-fd4416ea39a8.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_6b779794-4615-4b84-bfa0-fd4416ea39a8.zip)

**Comment by AdamPark0030** [comment]
아래와 같이 답변 완료 했습니다.

```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

아래의 조치사항을 취해주세요.

1. Twomon SE와 EL Display Hub PC 프로그램 연결
2. EL Display Hub에서 확장 디스플레이 선택
3. Windows + P 키 입력하여 프로젝트 옵션을 확장으로 선택

이후에도 문제가 지속된다면 새로운 PC로그와 어플리케이션 로그를 첨부하여 재문의 해주시길 바랍니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

Ea​​sy&Light 
```
