### ISSUE TITLE
궁금합니다

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#778]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:junny6868@gmail.com<br><br>패드와 이용중인데 소리가 패드에서 나오게 할수는 없나요?? 급하게 이용해야해서 구매했는데...<br><br>[EL_Display_e7c450ab-dc4d-4373-afc6-507102918709.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_e7c450ab-dc4d-4373-afc6-507102918709.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----



고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

문의해주신 내용에 대한 답변을 메일로 전달해드립니다. 

아쉽게도 Twomon SE는 사운드 기능을 제공하지 않고 있습니다.

Easy&Light 제품 중 TwomonAir만 사운드 기능을 제공하고 있습니다. 


제품에 대해 추가로 궁금한 점은 언제든지 회신하여 주시기 바랍니다. 

감사합니다.


Easy&Light
