### ISSUE TITLE
PSUserConfig.txt 파일 찾을 수 없음

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#781]
- 문의 날짜 : 2022년 2월 21일 오후 2시 11분
- 메일 주소 : musigraphy@naver.com

제목: 이지캔버스 필압

문의사항: 포토샵 2022를 사용중인데, 안내한 폴더에 PSUserConfig.txt 파일이 존재하지 않습니다.
다른 방법이 없나요?

**Comment by Sienna-lee** [comment]
현 상황에서 가이드가 가능한지 로그파일이 필요한지 확인 부탁드립니다. 
로그파일 필요 시 해당 사용자에게 요청하도록 하겠습니다.

**Comment by AdamPark0030** [comment]
![image](https://user-images.githubusercontent.com/73160679/154872615-2ba7c00b-f65c-4a47-86e3-6033f551591a.png)
![image](https://user-images.githubusercontent.com/73160679/154872629-31e5126e-41ea-4837-996a-fd5192ad1c08.png)

**Comment by AdamPark0030** [comment]
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

PSUserConfig.txt 파일이 존재하지 않을 경우 직접 파일을 생성해주시면 됩니다.

아래의 이미지를 참고하여 파일을 생성 후 포토샵을 실행해주세요.

![image](https://user-images.githubusercontent.com/73160679/154872643-ced6a6db-e7f3-4d80-8468-3d60c12f5bcd.png)

![image](https://user-images.githubusercontent.com/73160679/154872629-31e5126e-41ea-4837-996a-fd5192ad1c08.png)



감사합니다.

Ea​​sy&Light
