### ISSUE TITLE
디스플레이 문제

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#784]
- 문의 날짜 : 2022년 2월 19일 오후 11시 31분
- 메일 주소 : tommaso.sansone91@virgilio.it

Name: Tommaso Sansone

Title: Twomon SE triggerts Udemy screenshot protection so turning the video player black

Questions: I Have bought twomon SE app to use it with Udemy.
I am extending the screen of my Windows10 pc on my android tablet and keeping the Udemy window on my tablet screen.
This because on my computer screen I want to have the IDE that I use code, and on the tablet screen the video tutorial showing how to code.
However, it looks like for some reason the app is triggering udemy screenshot protection, which turns black the screen of their video player as soon as one uses an update Take picture or video of the screen.
Can you please introduce a fix that allows one to see video tutorial on the tablet on which It\'s running Twomon Se?
Thanks

[[Twomon_SE_-_Windows]_Re__[Twomon_SE_-_Windows_450]_Twomon_SE_triggerts_Udemy_screenshot_protection_so_turning_the_video_player_black.zip](https://github.com/edh-git/EL_Display_Hub/files/8105423/Twomon_SE_-_Windows._Re__.Twomon_SE_-_Windows_450._Twomon_SE_triggerts_Udemy_screenshot_protection_so_turning_the_video_player_black.zip)

**Comment by Sienna-lee** [comment]
아래 이슈와 동일한 사용자입니다.

----

https://github.com/devguru-co-ltd/ntwomon/issues/450

**Comment by AdamPark0030** [comment]
아래와 같이 답변 완료 했습니다.
```
Hello, customer. We are an Easy & Light support team.

First, we apologize for the inconvenience in using it.

In the case of "Twomon SE", if the screen copy or captured is not allowed on the program or site,
Screen replication may fail or screen image acquisition may fail.

Please refer to the use.

Also, I would appreciate it if you could answer some questions.

1. If Udemy of "Twomon SE" is not executed, is it displayed normally?

2. As a result of testing with Udemy's free video, it was possible to run normally. Is the screen displayed different from when it was executed as a free video and when it was executed as a paid video?

3. If Udemy runs and the screen is not displayed, can you send me a screenshot of the tablet screen showing "Twomon SE"?

Thank you.

Easy&Light
```

**Comment by AdamPark0030** [comment]
아래와 같이 답변 완료 했습니다.
```
Hello, customer. We are an Easy & Light support team.

First, we apologize for the inconvenience in using it.

In the case of "Twomon SE", if the screen copy or captured is not allowed on the program or site,
Screen replication may fail or screen image acquisition may fail.

Please refer to the use.

Also, I would appreciate it if you could answer some questions.

1. If Udemy of "Twomon SE" is not executed, is it displayed normally?

2. As a result of testing with Udemy's free video, it was possible to run normally. Is the screen displayed different from when it was executed as a free video and when it was executed as a paid video?

3. If Udemy runs and the screen is not displayed, can you send me a screenshot of the tablet screen showing "Twomon SE"?

in addition, the log you sent doesn't seem to be the latest version of the log. Please update the latest version of Twomon SE.

If the problem persists, please inquire again with a new log acquisition guide.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/supporttwomon/?faq=121

Thank you.

Easy&Light
```
