### ISSUE TITLE
입력 문제

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#785]
- 문의 날짜 : 2022년 2월 20일 오후 10시 45분
- 메일 주소 : 1242787902@qq.com

重装软件很多次也不好用，apple二代笔，笔尖位置在显示器上飘逸，同时ps中无法绘制线条，只能断断续续的触到点。有什么办法吗，不然帮我办理退款，谢谢

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. Easy&Light support team.

Could you please send us the log file to fix the problem?
Please contact us through 'Inquiry' in the PC program customer support.
Our technical team will solve your problem.

image.png

Thank you.

Easy & Light

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

-----
点击inquiry后程序卡住无响应，:(

![14796B4A@EA93D720 36EE1262 png](https://user-images.githubusercontent.com/77039816/154878890-04d3af73-c1b7-4a75-99ed-10fd3a117efe.jpg)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

-----

Hello, customer. Easy&Light support team.


Please refer to the manual log acquisition guide below and ask again with the application log.

[Manual log collection procedure]

1. Enter Windows key > "Run" > Enter "msinfo32" > File > Save

2. Files existing in the path C:\ProgramData\devguru

3. A file existing in the path C:\Users\{username}\AppData\Local\Devguru (you can access the path with %localappdata%\Devguru)

Please zip the three files and attach them.

Thank you.

Easy&Light

**Comment by Sienna-lee** [comment]
해당 사용자가 로그파일을 첨부하였습니다.

----

file attached。谢谢技术人员:)
[log.zip](https://github.com/edh-git/EL_Display_Hub/files/8106468/log.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변하였습니다.
```
Hello, customer. Easy&Light support team.

First of all, we apologize for the inconvenience.

With this update, the defaults for "Resolution" and "Performance Mode" in User Settings have been changed so that High Quality is selected.
Performance may be slightly slower depending on the specifications of PC and tablet due to changes in settings,
Please refer to the FAQ below and change the settings of "Resolution" and "Performance Mode".

[FAQ] Screen update or response speed is slow. : http://www.easynlight.com/supporteasycanvas/?faq=112

Or, it could be a problem with Photoshop options. It is an integrated PC program and has been changed to use hardware acceleration to improve performance during the update process.

In that case, it can be seen that there is a conflict between Photoshop and the graphics acceleration feature.
 
Symptoms may be alleviated by disabling GPU acceleration in the Photoshop side of the graphics card-related troubleshooting article below.
[Adobe FAQ] Troubleshoot Photoshop graphics processor (GPU) and graphics driver issues: https://helpx.adobe.com/photoshop/kb/troubleshoot-gpu-graphics-card.html#multiple-gpus


If the problem does not improve even after taking the above measures,
Please refer to the log acquisition guide below and ask again with the application log.

[FAQ] Log Acquisition Guide: http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Easy & Light
```
