### ISSUE TITLE
딜레이가 엄청나네요.

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#788]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:wlcjsqo2002@naver.com<br><br>아이패드 에어1세대를 쓰고있는 사람인데 프로그램 사서 잘 쓰고 있었는데 업그레이드 이후 전혀 쓸 수 가 없네요. 블로그에 글 남겼더니 이렇게 하라고 해서 했는데 아직 전혀 피드백이 없네요. 이정도면 전 버전이 더 나은것 아닌가요? 도대체 뭐가 더 좋아진지 모르겠네요. 그쪽이 대응 안하면 제가 대응 하겠습니다.<br><br>[EL_Display_47e77b00-2209-4235-aa3c-99595be4d73d.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_47e77b00-2209-4235-aa3c-99595be4d73d.zip)

**Comment by james-kim-Devguru** [comment]
## 다음과 같이 답변 하였습니다.
```
안녕하세요 고객님. Easy&Light 지원팀입니다.

먼저, 이용에 불편을 드려 죄송합니다.

이번 업데이트로 사용자 설정의 "해상도"와 "성능 모드"의 기본값이 높은 품질이 선택되도록 변경되었습니다.
설정이 변경되어 PC 및 태블릿의 사양에 따라서 성능이 다소 느려질 수 있으며,
아래의 FAQ를 참조하셔서 "해상도"와 "성능 모드"의 설정을 변경하여 주시길 바랍니다.

[FAQ] 화면 갱신이나 반응속도가 느려요. : http://www.easynlight.com/supporteasycanvas/?faq=112

위와 같은 조치사항을 진행하시고도 문제 사항이 개선되지 않으신다면,
아래의 로그 취득 가이드를 참조하여 어플리케이션 로그와 함께 재문의 부탁드립니다.

[FAQ] 로그 취득 가이드 : http://www.easynlight.com/supporteasycanvas/?faq=97

감사합니다.

Ea​​sy&Light 
```
