### ISSUE TITLE
세로모드가 되면 먹통이 됩니다

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#791]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:mhs0722@nate.com<br><br>가로모드로는 잘 동작하는데 세로모드로 넘기면 화면이 멈춥니다<br><br>[EL_Display_1424bd65-ff1a-466c-adf0-36ebe6b48047.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_1424bd65-ff1a-466c-adf0-36ebe6b48047.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


안녕하세요 고객님. Easy&Light 지원팀입니다.

문의하신 내용에 대한 답변을 아래 전달드립니다. 

현재 윈도우11의 경우 세로 모드일 때 Windows에서 제공하는 기능에 문제가 있는 것으로 판단됩니다. Microsoft에서 오류를 수정하지 않으면 해당 문제는 해결이 어려울 것으로 보이며, 현재로서는 불편하시더라도 Windows 11에서는 가로 모드로 사용해주시길 바랍니다.

감사합니다.

Easy&Light
