### ISSUE TITLE
Screen extension not working

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#792]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:tim.cooremans@hotmail.com<br><br>The option to extend the screen doesn't work and sometimes the option isn't even given. When selecting 'extension' it still is just a duplicate screen<br><br>[EL_Display_c3246dab-66c9-43ed-94f5-89052eddc244.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_c3246dab-66c9-43ed-94f5-89052eddc244.zip)

**Comment by AdamPark0030** [comment]
아래와 같이 답변완료 했습니다.
```
Hello, customer. We are an Easy & Light support team.

First, we apologize for the inconvenience in using it.

Please take the measures below.

1. Connect EL Display Hub and Twomon SE.
2. Enter the Window + P key.
3. Select the project option as Extension.

If the problem persists, please re-examine the new PC log and application log.

[FAQ] Log acquisition guide: http://www.easynlight.com/en/supporttwomon/?faq=78

Thank you.

Easy&Light
```
