### ISSUE TITLE
특정 환경에서 연결 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#797]
- 문의 날짜 : 2022년 2월 22일 오전 5시 58분
- 메일 주소 : rafadexter@hotmail.com

Title: Easycanvas only connect on pc if have a external monitor on pc

Questions: I was not able to get Easycanvas to connect to my laptop, but after I connected an external monitor through the hdmi input, Easycanvas started to connect normally to my laptop. Was this supposed to happen? I just want Easycanvas on the laptop without needing another external monitor. Can you help me please? I\'ve reinstalled El Display several times and the problem continues.

[[EasyCanvas_-_Windows]_Easycanvas_only_connect_on_pc_if_have_a_external_monitor_on_pc.zip](https://github.com/edh-git/EL_Display_Hub/files/8112791/EasyCanvas_-_Windows._Easycanvas_only_connect_on_pc_if_have_a_external_monitor_on_pc.zip)

**Comment by AdamPark0030** [comment]
아래와 같이 답변완료 했습니다.
```
Hello, customer. We are an Easy & Light support team.

First, we apologize for the inconvenience in using it.

It is difficult to identify symptoms only with the app log you attached.

Please contact us again through the log acquisition guide below.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/en/supporteasycanvas/?faq=54

Thank you.

Easy&Light
```
