### ISSUE TITLE
화면 캡쳐 실패

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#801]
- 문의 날짜 : 2022년 2월 22일 2시 29분 
- 메일 주소 : dasasdhba@outlook.com

Title: Failed to screen capture D0010101

Questions: Hello, I need some help. I got an error \"Failed to screen capture\" When I tried to connect.
There are two log files in \\AppData\\Local\\Devguru\\ELDisplayHub., so I merged them to one file.

[[Twomon_SE_-_Windows]_Failed_to_screen_capture_D0010101.zip](https://github.com/edh-git/EL_Display_Hub/files/8113898/Twomon_SE_-_Windows._Failed_to_screen_capture_D0010101.zip)

**Comment by AdamPark0030** [comment]
아래와 같이 답변 완료 했습니다.
```
Hello, customer. We are an Easy & Light support team.

First, we apologize for the inconvenience in using it.

It is difficult to identify symptoms only with the logs you attached.

I would appreciate it if you could attach the log through the log acquisition guide below.

[FAQ] Log Acquisition Guide:
http://www.easynlight.com/supporttwomon/?faq=121

Thank you.

Easy&Light
```
