### ISSUE TITLE
실행안됨

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#802]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:jeawon7653@naver.com<br><br>투몬 se 버젼을 삿는데 왜 pc사이트에서 pc다운로드를 누루면 el display만 다운이 되고 투몬 se는 다운이 안되나요<br><br>[EL_Display_f0eda560-91df-4b9c-8ba3-8a5a565a5231.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_f0eda560-91df-4b9c-8ba3-8a5a565a5231.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

고객님, 안녕하세요. Easy&Light 지원 팀 입니다.


문의해주신 내용에 대한 답변을 메일로 전달해드립니다.





Easy&Light 제품군의 성능 개선 및 사용 편의를 위해 통합 PC 프로그램(EL Display Hub)으로 업데이트 되었습니다.



EL Display Hub를 다운로드 받아 설치하시면 Twomon SE를 사용하실 수 있습니다. 





만약 연결이 되지 않을 경우, 로그파일과 함께 문의주시면 기술팀에서 문제를 확인하여 해결 방안을 전달드리도록 하겠습니다.





- 로그 추출 가이드 : http://www.easynlight.com/supporttwomon/?faq=121




혹시 위 방법이 너무 어려우실 경우, EL Display Hub(PC 프로그램)의 고객지원 -> 문의하기를 이용하여 다시 한번 문의를 부탁드립니다.






감사합니다.


Easy&Light
