### ISSUE TITLE
문의

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#803]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:jeawon7653@naver.com<br><br>twomon se는 컴퓨터 pc로는 이용이 안되나요? 아이패드랑 hdmi선으로 연결을했고 컴퓨터 실행을 먼저했는데 자꾸 아이패드에서는 연결이 안됫다고 뜨네요<br><br>[EL_Display_3294d22c-ebb7-4826-b40a-0d6a3ef4e3f7.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_3294d22c-ebb7-4826-b40a-0d6a3ef4e3f7.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


고객님, 안녕하세요. Easy&Light 지원 팀 입니다.


문의해주신 내용에 대한 답변을 메일로 전달해드립니다.







일반 데스크탑 PC와 연결하여 사용할 수 있습니다.

하지만 HDMI 연결은 지원하지 않습니다.

사용하기 위해서는 태블릿과 PC를 USB케이블로 연결하셔야 합니다.

USB케이블로 연결 후 다시 확인 부탁드립니다.


감사합니다.

Easy&Light
