### ISSUE TITLE
Confusion on offerings

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#804]
Product:EasyCanvas<br><br>Device OS:Android<br><br>e-mail:tosinfakunle@yahoo.com<br><br>I am confused about your offerings on google play for easy canvas. There is a subcription option and a &quot;Graphics Tablet&quot; option with a higher price. What is the difference between the two? Is one a one-time payment and the other is not?<br><br>[EL_Display_a47f31e0-5c39-455b-9ca4-7cbf1ca2baef.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_a47f31e0-5c39-455b-9ca4-7cbf1ca2baef.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. We are an Easy & Light support team.


The features of both products are identical.
The difference is in the way you buy.


If you want to use the product for a long time, you can purchase it '[in-app](https://play.google.com/store/apps/details?id=com.devguru.bypd)'.
If you want to use it for a short period of time, you can purchase it as a '[subscription](https://play.google.com/store/apps/details?id=com.devguru.bypdpro)'.

If you have more questions about our products, please reply to us.
Thank you.

Easy&Light
