### ISSUE TITLE
딜레이 해상도 이미 낮은성능으로 되어있음.

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#814]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:wlcjsqo2002@naver.com<br><br>일전에 투몬se 확장에 딜레이 문의를 했었는데 메일로 낮은성능으로 해보라고 이야기 해서 해봤는데 다를바가 없네요.<br><br>[EL_Display_558c5aeb-0f72-4902-861a-e00f45250120.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_558c5aeb-0f72-4902-861a-e00f45250120.zip)

**Comment by Sienna-lee** [comment]
#788 와 동일사용자 입니다
#816 에서 처리 요청드립니다.
