### ISSUE TITLE
라이선스 인증 실패 오류

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#823]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:audgjs772@gmail.com<br><br>안녕하세요, 오늘 투몬SE를 갤럭시 탭 s8+에 구매 및 설치 후 실행했는데 &quot;구글 플레이 라이선스 인증에 실패했습니다. 구매 시 사용한 계정이 로그인 되어 있는지 확인해주세요.&quot; 라는 문구가 뜨면서 확인 버튼을 누르니 강제종료 돼더라고요. 이에 대해 도와주실 수 있으면 감사하겠습니다.<br><br>[EL_Display_312ed133-4561-456b-8403-8bbd0a380d4c.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_312ed133-4561-456b-8403-8bbd0a380d4c.zip)

**Comment by Juilliardsong** [comment]
아래와 같이 답변
---
안녕하세요. Easy&Light 지원팀 입니다.
라이선스 인증 문제라면 아래 사항을 참조해주세요.

1. 인터넷이 연결되어 있는지 확인

2. 앱을 구매한 계정으로 로그인이 되어 있는지 확인

3. 광고 차단 앱이 설치되어 있는 경우, 해당 앱을 실행 중지하거나 앱 내 예외 리스트를 설정할 수 있다면 Twomon SE를 예외 리스트로 선택

4. 위 내용을 참고해도 해결이 되지 않는다면, 구매하신 구글 계정 외에 다른 계정을 삭제한 후 다시 한번 연결해주세요.

추가 지원이 필요하신 경우 언제든 연락 부탁드립니다.
감사합니다.
