### ISSUE TITLE
라이센스 인증 오류

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#825]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:audgjs772@gmail.com<br><br>안녕하세요 어제 라이센스 오류에 대해 문의를 했고 답장을 받았는데 답장에서 받은 방법들을 모두 해봤지만 안되네요.. 다른 방법이 없을까요? 감사합니다.<br><br>[EL_Display_2677b8bb-e236-40a6-8f0b-5577a28212e2.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_2677b8bb-e236-40a6-8f0b-5577a28212e2.zip)

**Comment by Juilliardsong** [comment]
#823 이슈 참조

**Comment by Juilliardsong** [comment]
아래와 같이 추가 답변함
---
안녕하세요. Easy&Light 지원팀입니다.


PC에서 앱을 설치하는 법을 알려드리겠습니다.

1. PC에서 구글 플레이스토어에 접속하여 Twomon SE를 구입한 계정으로 로그인합니다. (https://play.google.com/)

2. 검색창에 "twomon se"를 검색합니다.

3. "다른 기기에 설치" 버튼을 눌러 사용할 기기를 선택합니다.
기기 모델명은 기기의 [설정] - [태블릿 정보] - "모델번호"에서 확인하실 수 있습니다.

잠시 후 모바일 기기에 Twomon SE가 설치됩니다.


이 방법으로 꼭 해결되었으면 좋겠네요.

감사합니다.

**Comment by Juilliardsong** [comment]
추가 답변 옴 - 환불 요청
---
내용 : 
안녕하세요, PC로 앱을 설치했지만 여전히 오류가 해결이 안되네요... 제가 뭘 잘못한건지... 태블렛 계정들 다 삭제하고 구글만 로그인도 해보고 플레이스토어에서 환불 후 삭제 및 재설치도 시도 해봤는데 정말 아쉽지만 안되네요... ㅠㅠ 죄송하지만 다른 방법이 더 없다면 환불이 가능할까요...? 감사합니다. 나중에 오류가 고쳐지면 꼭 사용해보고 싶습니다 ㅠㅠ

**Comment by Juilliardsong** [comment]
아래와 같이 답변함 - 환불 가이드 전달
---
안녕하세요. Easy&Light 지원팀입니다.

구글 라이선스 문제의 경우 저희가 알려드린 방법대로 되지 않는다면 구글측에 해당 계정으로 문의를 해보셔야 할 것 같습니다.

구매일이 30일이 지나지 않았다면, 하단의 링크를 통해 환불을 접수해 주시면 확인 후 진행해드리겠습니다.
https://docs.google.com/forms/d/1wFxbQS5wg3u1QbMLG_ZQDM2ExNbDHC9xraPje5_hBbo/edit?urp=gmail_link

감사합니다.

**Comment by Sienna-lee** [comment]
해당 사용자가 아래와 같이 회신하였습니다.

----

아 이메일 답변으로 문의를 하면 안되는줄 알고 따로 문의를 드렸는데 해당 문의는 무시해주실 수 있을까요? 아까운 시간 쓰게해서 죄송합니다.
