### ISSUE TITLE
화웨이 앱 업데이트 불가

### ISSUE THREAD

**Issue by Sienna-lee** [edh-git/EL_Display_Hub#836]
- 문의 날짜 : 2022년 2월 28일 오후 8시 44분
- 메일 주소 : xujiaxiang.2002@163.com

你好，我年初在华为商城上下载并购买了twomon se这个软件，现在电脑上的程序可以更新，但是我的华为matepad pro上的app无法从华为商城更新，twomon se 这个软件也从华为商城下架，请问应该怎么办？

**Comment by Sienna-lee** [comment]
@Juilliardsong 

화웨이 앱 업데이트 불가 내용 확인 부탁드립니다.

**Comment by Juilliardsong** [comment]
@Sienna-lee 
화웨이 앱갤러리에 4.6.1버전 정상적으로 배포되어 있음.
업데이트 및 다운로드 문의는 앱갤러리를 통해 문의하라고 답변해주세요.

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. We are an Easy & Light support team.

We will answer your inquiry below.


The Twomon SE app is registered in the Huawei App Gallery, and we have confirmed that it is downloaded and updated normally.

If the problem persists, please contact the Huawei App Gallery.

Thank you.
