### ISSUE TITLE
향후 업데이트때 사운드 미러링도 부탁드립니다

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#841]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:ygh9311@gmail.com<br><br>서브모니터로 쓰면서 편해서 좋긴합니다만 아이패드 쿼드스피커를 못쓰는게 좀 아쉽네요 향후 업데이트때 추가부탁드립니다<br><br>[EL_Display_7515a8f5-6511-45a7-ac7a-e65a495d581a.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_7515a8f5-6511-45a7-ac7a-e65a495d581a.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


고객님, 안녕하세요. Easy&Light 지원 팀 입니다.


문의해주신 내용에 대한 답변을 메일로 전달해드립니다.





현재 Twomon 제품 중 TwomonAir만 사운드 기능을 제공하고 있으며, Twomon SE는  사운드 기능을 제공하고 있지 않습니다.



의견 주신 내용을 이후 업데이트 시 검토해볼 수 있도록 담당자에게 전달하도록 하겠습니다.



제품 사용 중 궁금하거나 불편한 사항은 언제든지 문의하여 주시기 바랍니다.



감사합니다.





Easy&Light
