### ISSUE TITLE
세로형  안되나요

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#845]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:agidolly@hanmail.net<br><br>아이패드 프로 쓰는데, A4용지 세로형(폭 좁고 위아래 넓은) 쓰고싶은데 그 건 방법 어떻게 하나요?<br><br>[EL_Display_30108615-5322-46ff-84af-7a957dd372f3.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_30108615-5322-46ff-84af-7a957dd372f3.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----



고객님, 안녕하세요. Easy&Light 지원 팀 입니다.


문의해주신 내용에 대한 답변을 메일로 전달해드립니다.






아이패드의 화면을 세로로 사용하시길 원하시면, 디스플레이 설정에서 가능합니다.

바탕화면에서 우클릭 - 디스플레이 설정으로 가신 후,

아이패드에 해당하는 화면을 선택 후 아래의 디스플레이 방향을 "세로"로 선택해주시면 됩니다.


현재 Windows 11의 경우 세로 모드일 때 Windows에서 제공하는 기능에 문제가 있어 화면 멈춤 현상 등이 발생할 수 있습니다.

Microsoft에서 오류를 수정하지 않으면 해당 문제는 해결이 어려울 것으로 보이며, 현재로서는 불편하시더라도 Windows 11에서는 가로 모드로 사용해주시길 바랍니다.

감사합니다.



Easy&Light
