### ISSUE TITLE
아이패드에 화면 세로로 될 수 있도록 해주세요

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#875]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:kty2637@naver.com<br><br>세로로 설정해놓으면 마치 렉이 걸린 것처럼 터치도 안 되고 프로그램을 아이패드로 넘겨도 변하질 않습니다. 다른 앱을 켰다가 들어오면 화면이 바뀌어 있지만 또 화면이 먹통입니다. 한마디로 나갔다 들어오면 한 장면씩 볼 수 있다는 것입니다.<br><br>[EL_Display_c87ad3df-147d-415c-8dcd-62d20cd35ddb.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_c87ad3df-147d-415c-8dcd-62d20cd35ddb.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

고객님, 안녕하세요. Easy&Light 지원 팀 입니다.


문의해주신 내용에 대한 답변을 메일로 전달해드립니다.





현재 Windows 11의 경우 세로 모드일 때 Windows에서 제공하는 기능에 문제가 있어 화면 멈춤 현상 등이 발생할 수 있습니다.

Microsoft에서 오류를 수정하지 않으면 해당 문제는 해결이 어려울 것으로 보이며, 현재로서는 불편하시더라도 Windows 11에서는 가로 모드로 사용해주시길 바랍니다.






감사합니다.

Easy&Light
