### ISSUE TITLE
무선 연결을 끊고 유선 연결만 가능하게 설정할 방법은 없나요

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#905]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:gg0602@naver.com<br><br>노트북(윈도우)-아이패드를 사용하고 있습니다. 미묘하게 딜레이가 느껴져서 유선 연결은 좀 괜찮지 않을까 시도해보고 싶은데 이지캔버스를 실행하면 서로 정보가 저장된 두 기기들이 자동으로 무선 연결이 됩니다. 이 설정을 끊고 유선으로만 사용할 수 있는 방법이 없나요?<br><br>[EL_Display_53849376-f4de-4e94-9f75-d14817c9494d.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_53849376-f4de-4e94-9f75-d14817c9494d.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


고객님, 안녕하세요. Easy&Light 지원 팀 입니다.


문의해주신 내용에 대한 답변을 메일로 전달해드립니다.





EasyCanvas의 연결 방식은 유선과 무선을 동시에 연결 시 유선 연결로 우선 동작하도록 구성되어 있습니다. 만약 동시 연결 시에 무선으로 연결이 될 때에는 PC와 태블릿을 서로 다른 네트워크로 연결하거나 태블릿의 네트워크 연결을 해제하여 유선 연결으로 사용하실 수 있습니다.





제품에 대해 추가로 궁금한 점은 회신하여 주시기 바랍니다.





감사합니다. 



Easy&Light
