### ISSUE TITLE
笔刷没有压感，怎么设置

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#909]
Product:EasyCanvas<br><br>Device OS:Android<br><br>e-mail:1657100652@qq.com<br><br>没有压感，怎么设置<br><br>[EL_Display_30fa897f-7d24-4d07-89db-eb6d953294ad.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_30fa897f-7d24-4d07-89db-eb6d953294ad.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----



Hello, customer. We are an Easy & Light support team.

We will answer your inquiry below.



Please refer to the link below to set the pen pressure.

- Pen pressure setting:http://www.easynlight.com/en/supporteasycanvas/?mod=list&faq=75



Please reply to us with any further questions.


Thank you.

Easy&Light
