### ISSUE TITLE
Compability.

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#927]
Product:EasyCanvas<br><br>Device OS:iOS<br><br>e-mail:arpelibol.00@gmail.com<br><br>My iPad says it's on version 4.6.8 yet the latest PC version  I can find it's the 4.6.6; which apparently isn't compatible. Is there a way to fix this?<br><br>[EL_Display_8660fe92-6c7d-4819-9e5f-2548714458f3.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_8660fe92-6c7d-4819-9e5f-2548714458f3.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----



Hello, customer. We are an Easy & Light support team.

We will answer your inquiry below.


The PC version and iPad version are not always the same.
The iPad version and PC version you are currently using are up-to-date.
If you want to check the latest version of the PC program, you can check it in "Support" -> "Check Update" of the PC program.

If you have any additional questions about the product, please reply.


Thank you.

Easy&Light
