### ISSUE TITLE
Twomon gives Need update message

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#933]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:beleckis2005@yahoo.com<br><br>but when I go to update the program it says latest version is installed. I'm running Twomon on a tablet attached to my pc to monitor my computer temps. I'm using AIDA 64 to create a sensor panel. Everything worked fine until the most recent update.<br><br>[EL_Display_1b6e6f61-decb-4def-a9c3-1199d9a25662.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_1b6e6f61-decb-4def-a9c3-1199d9a25662.zip)

**Comment by Sienna-lee** [comment]
#937 사용자와 동일한 사용자입니다
