### ISSUE TITLE
Problem Fixed for Need Updating

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#937]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:beleckis2005@yahoo.com<br><br>Yesterday I sent a request to help fix a problem with updating my Twomon software. This problem has been fixed. It was a corrupted Daemon Tools Lite virtual drive. I deleted the Virtual device and noticed that Twomon would not start. I then deleted EL Display Hub and reinstalled it. Problem fixed.<br><br>[EL_Display_44691dbf-ddc1-4561-bfd7-bd7212147f41.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_44691dbf-ddc1-4561-bfd7-bd7212147f41.zip)

**Comment by Sienna-lee** [comment]
#933 사용자와 동일한 사용자입니다

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----

Hello, customer. Easy&Light support team.

I'm glad the issue has been resolved.

If you have any questions, please contact us.

We will try our best to provide you with a better program.

thank you.


Easy&Light
