### ISSUE TITLE
세로로설정하는법

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#940]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:youth51244@naver.com<br><br>아이패드를 모니터 확장모드로 사용중인데 아이패드에 가로로 고정되서 나와서 이거 세로로 바꿀수있는기능은 없나요<br><br>[EL_Display_2c451366-da7a-4684-b97c-f9dddbc51686.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_2c451366-da7a-4684-b97c-f9dddbc51686.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.


----

고객님, 안녕하세요. Easy&Light 지원 팀 입니다.    

Twomon SE의 경우는 틸트기능을 지원하지 않고 있습니다.

따라서 세로모드로 사용하고 싶으시다면, 

디스플레이 설정 - 디스플레이에서 아이패드 모니터를 선택 후  디스플레이 방향에서 세로로 변경하시면 세로모드로 사용이 가능합니다.

PC프로그램에 별도의 옵션은 없는 점 참고 부탁드립니다.

추가로 현재 Windows 11의 경우 세로 모드일 때 Windows에서 제공하는 기능에 문제가 있어 세로모드에서 사용이 어렵습니다. 불편하시더라도 Windows 11에서는 가로 모드로 사용해주시길 바랍니다.


궁금하신 점이 있으면 언제든 문의 주시기 바랍니다.

감사합니다.


Easy&Light
