### ISSUE TITLE
세로화면시 윈도우 창이 넘어가지 않음

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#949]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:ezra92@hanmail.net<br><br>세로화면시 윈도우 창이 넘어가지 않는 오류가 발생합니다. 가로일 때는 잘 넘어갑니다. 해결방안을 알려주세요<br><br>[EL_Display_cde4378d-6417-4402-93f4-6df2a569c671.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_cde4378d-6417-4402-93f4-6df2a569c671.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


고객님, 안녕하세요. Easy&Light 지원 팀 입니다.


문의해주신 내용에 대한 답변을 메일로 전달해드립니다.





혹시 사용하시는 환경이 Windows 11 인지요? 



현재 Windows 11의 경우 세로 모드일 때 Windows에서 제공하는 기능에 문제가 있어 화면 멈춤 현상 등이 발생할 수 있습니다.

Microsoft에서 오류를 수정하지 않으면 해당 문제는 해결이 어려울 것으로 보이며, 현재로서는 불편하시더라도 Windows 11에서는 가로 모드로 사용해주시길 바랍니다.




추가로 제품에 대해 궁금하거나 불편한 점은 언제든지 문의하여 주시기 바랍니다.



감사합니다.

Easy&Light
