### ISSUE TITLE
태블릿에서 APP 엡에이트 했더니 해결됨.

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#950]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:southkoreaseoul@gmail.com<br><br>PC도 하고 태블릿도 업데이트 했더니 됨.<br><br>[EL_Display_fe88bb6b-9ad3-4ab5-8168-2b2a7aab2c0a.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_fe88bb6b-9ad3-4ab5-8168-2b2a7aab2c0a.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

앱 업데이트를 통해 문제가 해결 되셨다니 다행입니다.

사용 중 궁금한점이 있으시면 언제든 문의주시기 바랍니다.

더 나은 프로그램을 제공해드리기 위해 노력하겠습니다.

감사합니다.


Easy&Light
