### ISSUE TITLE
아놔 안된다구요 짜증나네...

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#952]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:novoetvorenie@gmail.com<br><br>진짜.. 업데이트만 되면 뭐가 문제가 발생하냐구요... 정말 화가나네요..<br><br>[EL_Display_ffbc6f9f-d364-4bdf-8d95-950abe248d21.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_ffbc6f9f-d364-4bdf-8d95-950abe248d21.zip)

**Comment by Sienna-lee** [comment]
#943 이슈와 동일 사용자입니다.
