### ISSUE TITLE
TWOMON SE not working

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#960]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:howhun@hotmail.com<br><br>My pc software was automatically updated from TWOMON SE to EL DISPLAY HUB so now it doesn't work on my Samsung Tablet that still runs on TWOMON SE. I am trying to update the software on my tablet but can't find EL DISPLAY HUB on Google Playstore.<br><br>[EL_Display_703aaadb-3b87-495d-b053-c9d3b91bbda2.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_703aaadb-3b87-495d-b053-c9d3b91bbda2.zip)

**Comment by Sienna-lee** [comment]
#966 와 동일사용자입니다.
