### ISSUE TITLE
Black Screen and reloading

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#974]
Product:Twomon SE<br><br>Device OS:Android<br><br>e-mail:khan.contact.pro@gmail.com<br><br>Hi ! I probably messed up with some services from windows for El Display. My secondary screen run in black screen.. I followed the instructions about errors and turned on some services that i turned off (Like Bonjour and AMDS).. But still my other screen juste turns black when it's connected. How could i fix that. And btw sorry for my english.. i'm French one.<br><br>[EL_Display_9f6f3d62-b98b-46ab-a391-c5e2d9b54adb.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_9f6f3d62-b98b-46ab-a391-c5e2d9b54adb.zip)

**Comment by Sienna-lee** [comment]
해당 사용자가 서비스를 활성화했더니 프로그램이 동작한다고 다시 한번 연락이 왔습니다.

#975

해당 이슈를 종료합니다.
