### ISSUE TITLE
아이패드 2대를 동시에 연결해서 쓰려면 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by edh-git** [edh-git/EL_Display_Hub#998]
Product:Twomon SE<br><br>Device OS:iOS<br><br>e-mail:daeyong.lee@wooricpa.co.kr<br><br>동시에 연결하니 하나는 제거해야 한다고 합니다.<br><br>[EL_Display_32dac6a8-af03-41a4-974c-298d0b1c4ec1.zip](https://github.com/edh-git/EL_Display_Hub/blob/main/EL_Display_32dac6a8-af03-41a4-974c-298d0b1c4ec1.zip)

**Comment by Sienna-lee** [comment]
해당 사용자에게 아래와 같이 회신하였습니다.

----


고객님, 안녕하세요. Easy&Light 지원 팀 입니다.

문의해주신 내용에 대한 답변을 메일로 전달해드립니다.

아쉽게도, 고객님이 말씀하신 태블릿 2대 연결은 불가능합니다.

Twomon SE가 설치된 태블릿 1대와의 연결만 가능합니다.

원하시는 답변을 드리지 못해 죄송합니다.

또 궁금한 점이 있으시면 언제든 문의주시기 바랍니다.

감사합니다.



Easy&Light
